src/core/arm/dyncom/arm_dyncom.cpp, src/core/arm/dyncom/arm_dyncom_trans.cpp, src/core/arm/skyeye_common/armsupp.cpp
Just removes a few unnecessary header dependencies. Now these files won't need to be recompiled if the headers are changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3231)
=> dyncom: Remove unnecessary includes

src/citra_qt/main.cpp, src/citra_qt/main.h
Fixes the bug described [here](https://github.com/citra-emu/citra/pull/3001#issuecomment-338401048). (Could also fix https://github.com/citra-emu/citra/issues/3040 but I don´t have a Ubuntu VM set up to test it.)
Therefore, the contents of ToggleFullscreen() have been refactored into ShowFullscreen() and HideFullscreen() (feel free to suggest better names for them) to make it easier to fix the bug. 
Also tracking of the window geometry before it was fullscreened has been added.
Thanks @CDAGaming for helping me with clang format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3159)
=> citra-qt : Fix a bug in our fullscreen implementation

src/core/hle/svc.cpp
This return value is meant to be used as a simple conversion between linear heap PAddr<->VAddr, thus it only very depends on where the entire FCRAM is mapped in VAddr (can be only 0x30000000 / 0x14000000). It shouldn't use `GetLinearHeapBase` which is for the APPLICATION/SYSTEM/BASE region base address.
Fixes new version swkbd not rendering issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3241)
=> svc: correct GetProcessInfo(20)

src/citra_qt/main.cpp
The telemetry_session of the System is null when loading fails, resulting in a crash when trying to add telemetry fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3247)
=> Fix crash when loading an unsupported file

src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_extsavedata.h
The FS module overrides whatever value was in the saveid high dword with 0x48000 when trying to open the archive.
This fixes the problem where the Home Menu would create a few SharedExtData archives with 0x48000 as the saveid high, but then try to open them with 0 as the high value and fail.
Cue '*how did anything even work at all?*' moment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3242)
=> HLE/FS: Always use 0x48000 as the high dword when opening the SharedExtData archive

src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_ncch.h, src/core/file_sys/archive_other_savedata.cpp, src/core/file_sys/archive_savedata.cpp, src/core/file_sys/ivfc_archive.cpp, src/core/file_sys/ivfc_archive.h
Just avoids some unnecessary atomic inc/dec and copies. A fairly trivial change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3254)
=> file_sys: std::move data argumnets in the constructor where applicable

externals/cryptopp/CMakeLists.txt
Instead of globbing all .cpp files that ship with CryptoPP, use an
explicit list of files to compile. This cuts out compilation of a lot of
stuff we don't use (reducing build times) and also works around
https://github.com/weidai11/cryptopp/issues/527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3255)
=> cryptopp: Build only required files

src/core/hle/service/ac/ac.cpp
The parent class constructor will always run before the class' initializers for member variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3259)
=> ac: Correct constructor initialization order

src/core/CMakeLists.txt, src/core/hle/service/pxi/dev.cpp, src/core/hle/service/pxi/dev.h, src/core/hle/service/pxi/pxi.cpp, src/core/hle/service/pxi/pxi.h, src/core/hle/service/service.cpp
Adds a simple pxi:dev stub so that apps that use it (e.g. FBI) won't error when trying to retrieve a handle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3246)
=> HLE: Add pxi:dev stub.

src/core/hle/kernel/server_session.cpp
In a real 3DS, threads that call svcSyncRequest are put to sleep until the server responds via svcReplyAndReceive. Our HLE services don't implement this mechanism and are effectively immediate from the 3DS's point of view. This commit makes it so that we at least simulate the IPC delay.
Specific HLE handlers might need to put their callers to sleep for a longer period of time to simulate IO timings. This is their responsibility but doing so is currently not implemented.
See https://gist.github.com/ds84182/4a7690c5376e045cab9129ca4185bbeb for a test that was not passing before this commit.
Thanks @ds84182 for pointing this out!
Closes #2794 #1105 #3054 #2647 #2802 #2608 #2749 #2118 #2526 #2749 
--- …
=> Kernel/IPC: Add a small delay after each SyncRequest to prevent thread starvation.

src/core/hle/service/news/news_s.cpp
This prevents an invalid read loop on games that call it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3250)
=> HLE/News: Stubbed GetTotalNotifications to always return 0 notifications.

src/core/hle/service/fs/fs_user.cpp
We don't yet implement the SEEDDB store.
This number is supposed to be modified by the AddSeed function (0x087A0180) but there's too little info about it on 3dbrew.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3251)
=> HLE/FS: Stubbed GetNumSeeds to always return 0 seeds.

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/swrasterizer/rasterizer.cpp
Also includes a fix for logic ops not being enabled in OpenGL (depending on circumstances).
Also ports the hack from the hardware renderer to software rasterizer where null texture addresses are ignored. (Otherwise the software rasterizer will crash doing a null deref).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3097)
=> Round primary color in swrast

src/core/core.cpp
This causes crashes such as [this one](https://www.reddit.com/r/Citra/comments/7j3sbn/automatic_crash/).
Init is called [a few lines down](https://github.com/citra-emu/citra/pull/3275/files#diff-5db0ca19c12b31af1e97555eeadc9eeaR101).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3275)
=> core: Don't Shutdown before we've even Init-ed

src/core/hle/ipc_helpers.h
Alleviates the need to static_cast to an enum type at the call sites of the Push and Pop calls.
We only allow strongly typed enums, as they have a defined type of int by default if an underlying type isn't explicitly specified, whereas with regular enums, if an underlying type isn't specified, an implementation-defined  type is used that can fit all the enumeration values. So this opts for a "do the default consistent thing" approach.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3268)
=> ipc_helpers: Add member functions for pushing and popping strongly typed enums

src/core/hle/kernel/hle_ipc.h, src/core/hle/service/am/am.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp
The File class now holds a list of connected sessions along with data unique to each session.
A subfile is a window into an existing file. They have a few limitations compared to normal files:
* They can't be written to.
* They can't be flushed.
* Their size can not be changed.
* New subfiles can't be created from another subfile.
This function is used by the DLP module to open the DLPChild CIA from the game's RomFS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3235)
=> HLE/FS: Implemented FSFile::OpenSubFile.

src/video_core/shader/shader_jit_x64_compiler.cpp
ICC emits this instead for its __sec_reduce_add intrinsic when supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3261)
=> shader_jit_x64_compiler: Use haddps for horizontal summation

src/core/hle/service/ir/ir.cpp, src/core/hle/service/ir/ir.h, src/core/hle/service/ir/ir_rst.cpp, src/core/hle/service/ir/ir_rst.h, src/core/hle/service/ir/ir_u.cpp, src/core/hle/service/ir/ir_u.h, src/core/hle/service/ir/ir_user.cpp, src/core/hle/service/ir/ir_user.h, src/core/hle/service/service.cpp
Besides moving around code, there are three small changes made:
- Fixed request parser header code for `IR_RST::Shutdown`
- `IR_USER::receive_buffer` is changed from a `boost::optional` to `std::unique_ptr`, to avoid moving around the definition of `BufferManager` because `boost::optional` doesn't support forward declaration.
- ir.cpp keeps weak references to `IR_RST` and `IR_USER` in order to inform them about input device reloading. I need more opinion on this to see if there is a better way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3248)
=> ir: convert to ServiceFramework

src/citra_qt/configuration/configure_input.cpp
This PR replaces the [non-keyboard] placeholders for gamepads in the input configuration dialog by labels actually telling you the mappings. Here's how it looks now:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3240)
=> Add button labels for sdl joystick mappings

src/input_common/CMakeLists.txt
This is a leftover that I stupidly left in. The generator expression above it already conditionally adds it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3294)
=> input_common: Remove redundant target_sources in CMakeLists

src/video_core/pica_types.h
Converting infinities or NaNs into float24 would previously result in normal numbers between +/-1.84467441e19 and +/-3.68932067e19. rcp(infinity) == 0 works now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3292)
=> video_core: fix infinity and NaN conversions

src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/apt_s.cpp, src/core/hle/service/apt/apt_u.cpp
Calling this function for AppletId::Application is not yet implemented because we don't support launching applications from APT.
The HLE applet machinery is showing its age, it's getting awkward to still support it alongside LLE applets. I want to rewrite it one day to make it use an interface more similar to real applets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3265)
=> HLE/APT: Implement GetAppletInfo for LLE applets.

src/citra_qt/CMakeLists.txt
We don't support Qt 4 anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3295)
=> citra_qt: CMakeLists: Drop leftover handling code for Qt 4 UI files

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/service.h
Some services can have multiple clients at the same time, and they identify the different clients using the server session as a key.
This parameter (if present) should be a structure that contains the per-session data for each service.
The data can be retrieved using ServiceFramework::GetSessionData(session)
cc @wwylele
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3284)
=>  HLE/Services: Allow specifying a SessionData template parameter to ServiceFramework.

src/citra_qt/bootmanager.cpp, src/citra_qt/debugger/graphics/graphics_cmdlists.cpp
We don't support Qt 4.x anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3306)
=> citra_qt: Drop Qt 5 version checks in code

src/core/hle/service/ldr_ro/ldr_ro.cpp, src/core/hle/service/ldr_ro/ldr_ro.h
Make use of #3284. This is closer to the real RO service as it use session handle as key to the slot, not the process handle/ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3309)
=> ldr_ro: use ServiceFramework's session slot for client slot

src/citra_qt/bootmanager.cpp, src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/debugger/graphics/graphics.cpp, src/citra_qt/debugger/graphics/graphics_breakpoint_observer.cpp, src/citra_qt/debugger/graphics/graphics_breakpoints.cpp, src/citra_qt/debugger/graphics/graphics_cmdlists.cpp, src/citra_qt/debugger/graphics/graphics_surface.cpp, src/citra_qt/debugger/graphics/graphics_tracing.cpp, src/citra_qt/debugger/graphics/graphics_vertex_shader.cpp, src/citra_qt/debugger/profiler.cpp, src/citra_qt/game_list.cpp, src/citra_qt/main.cpp, src/citra_qt/util/spinbox.cpp
This is more type-safe than the string-based signal/slot syntax that was being used. It also makes the connections throughout the UI code consistent.
Unfortunately, since we don't have Qt 5.7 as a requirement, we can't leverage [qOverload](https://doc.qt.io/qt-5/qtglobal.html#qOverload) to make this a little neater in terms of the `static_cast`s currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3312)
=> citra_qt: Migrate to Qt 5 signal/slot connection syntax where applicable

src/core/gdbstub/gdbstub.cpp
Constructing and destructing a Core::System instance for the GetInstance() call isn't the smartest thing to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3318)
=> gdbstub: Correct typo

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp
Terminating processes with ready threads is not currently implemented and will assert. It is currently unknown how the 3DS kernel stops ready threads or threads running in another core.
Please note that this is still not enough to allow applets to exit. Some APT functions still need to be implemented, and the GSP module needs to be changed to account for multiple clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3301)
=> Kernel/SVC: Partially implemented svcExitProcess.

src/core/hle/kernel/svc.cpp
The one in `GetResourceLimitCurrentValues` is correct.
Are we going to make `VAddr` a strong type?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3338)
=> Kernel/SVC: fix typo in GetResourceLimitLimitValues

src/citra_qt/configuration/configure.ui
Hello there! This is my first pull request. I thought I could do some work on the front-end so I decided to resize the default configuration layout width. It looks too wide and It looks much nicer when it's not so stretched out. Let me know if this is all good. :)
Original
Fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3336)
=> citra_qt: Resized main config window

src/video_core/command_processor.cpp, src/video_core/regs_rasterizer.h, src/video_core/shader/shader.cpp, src/video_core/shader/shader.h
First I unrolled the inner loop, then I pushed semantics validation
outside of the hotloop.
I also added overflow slots to avoid conditional branches.
Super Mario 3D Land's intro runs at almost full speed when compiled with
Clang, and theres a noticible speed increase in MSVC. GCC hasn't been
tested but I'm confident in its ability to optimize this code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3283)
=> Optimize AttributeBuffer to OutputVertex conversion

.appveyor/UtilityFunctions.ps1, appveyor.yml
This is done by recursively calling bindump to determine the dependencies
of each binary that is required from each of the executables. Doing this
allows us to avoid hard-coding a list of required DLL files to copy into
the release archives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3043)
=> appveyor: Determine dlls to include in package programmatically

src/citra_qt/bootmanager.cpp, src/citra_qt/main.cpp
Just a small commit to pause the emulation thread on CoreError because some games will spam the dialog boxes when the users are missing system files or shared fonts #3331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3333)
=> citra_qt: Pause emulation on CoreError

src/core/hle/kernel/hle_ipc.h, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/gsp/gsp_gpu.h
Only signal the GSP interrupts for the currently active thread (set by GSP_GPU::AcquireRight).
This PR makes it so that applets won't mess up the GSP state for the running application via UnregisterInterruptRelayQueue after they're closed.
Full disclosure: I don't know if this will break any games that use the GSP in funny ways (acquiring the gsp right multiple times without releasing it, other weird but probably valid behaviors). I don't have a way to verify this since my IDB for the GSP module was recently corrupted resulting in a total data loss.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3324)
=> Services: Keep track of per-session data in GSPGPU

.travis.yml
This PR fixes several Travis-Related Warnings/Errors/Deprecation's in MacOS (Now running on Sierra instead of El Capitan, as 7.x Versions of XCode have now been marked obsolete by Travis CI). These Warnings included Path Not Set Warnings, shell_session warnings, and a few other types.
This Commit also Updates the following Submodules:
- enet (Includes Minor CMakeList Changes for cleaner Solutions) ([Changelog](https://github.com/lsalzman/enet/compare/a84c120eff13d2fa3eadb41ef7afe0f7819f4d6c...39a72ab1990014eb399cee9d538fd529df99c6a0))
- Nihstro (Includes a bugfix on compiling with Boost v1.63) ([Changelog](https://github.com/neobrain/nihstro/compare/7e24743af21a7c2e3cef21ef174ae4269d0cfdac...28ac07a5273b6250cfafb4630bee8da820ad33d7))
Both the MINGW and MSVC Builds have been tested for …
=> [External] Travis CI Quick Fix + Minor Submodule Updates

src/citra_qt/debugger/graphics/graphics_surface.cpp
I don't see a reason why they should be translated. So to avoid unnecessary work for translators, I removed "tr" from those Strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3399)
=> Remove "tr" from image formats in graphics_surface.cpp

src/common/CMakeLists.txt
**its -> it's**
(This is a straight port of https://github.com/yuzu-emu/yuzu/pull/124)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3404)
=> Fix minor spelling error in CMakeLists 

src/core/hle/service/ptm/ptm.cpp, src/core/hle/service/ptm/ptm.h, src/core/hle/service/ptm/ptm_gets.cpp, src/core/hle/service/ptm/ptm_gets.h, src/core/hle/service/ptm/ptm_play.cpp, src/core/hle/service/ptm/ptm_play.h, src/core/hle/service/ptm/ptm_sets.cpp, src/core/hle/service/ptm/ptm_sets.h, src/core/hle/service/ptm/ptm_sysm.cpp, src/core/hle/service/ptm/ptm_sysm.h, src/core/hle/service/ptm/ptm_u.cpp, src/core/hle/service/ptm/ptm_u.h, src/core/hle/service/service.cpp
Functional change:
- the maximum session for each port is RE-ed from PTM code. All are 26, except for the one for `ptm:sets`, which is 1.
- Push mapped buffer in response in `GetStepHistory`.
- Fixed response header in `CheckNew3DS`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3361)
=> Service/PTM: convert to ServiceFramework

src/citra/citra.cpp, src/common/logging/backend.cpp, src/common/logging/log.h, src/core/CMakeLists.txt, src/core/core.cpp, src/core/hle/service/hid/hid.cpp, src/core/hle/service/ir/extra_hid.cpp, src/core/hle/service/ir/extra_hid.h, src/core/hle/service/ir/ir_rst.cpp, src/core/hle/service/ir/ir_rst.h, src/core/movie.cpp, src/core/movie.h, src/core/settings.h
Heavily inspired by the [Dolphin implementation](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/Movie.h).
Adds command lines to the SDL2 exe to control playback and recording. We should add something to the QT UI to match in the future.
(Is there somewhere these should be documented other than just in the `--help` response?)
Every time the hardware reads an input device (buttons, touch screen, accelerometer, gyroscope, c-stick) we copy (when recording) or replace (when playing) the values.
Once playback has finished, we release control of inputs so that the user can take control.
It is possible (likely even) that replays will desync between versions of Citra as behaviours change. This is expected.
File format will need documenting in the wiki. I've hopefully left …
=> Movie (Game Inputs) recording and playback

src/core/hle/kernel/ipc.cpp, src/core/hle/kernel/ipc.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Right now only MappedBuffers that only span a single page and are not aligned are implemented.
MappedBuffers are unmapped during the reply part of ReplyAndReceive. Only unmapping of ReadOnly buffers is currently implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3090)
=> Kernel/IPC: Partially implement  LLE MappedBuffer translation.

src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/tests/CMakeLists.txt, src/tests/core/memory/vm_manager.cpp
This function will be useful when implementing memory aliasing operations, see https://github.com/citra-emu/citra/commit/e55583d4f9f89b2e60da5fdda710e447ab7dabe9 for a draft of what's to come.
The function will enforce that the permissions and memory state of each block in the range match the input parameters before carving and updating the VMA.
Also added some VMManager tests, more to come.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3136)
=> Kernel/Memory: Added a function to change the memory state of an address range

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/citra_qt/main.cpp, src/core/perf_stats.cpp, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/video_core.cpp, src/video_core/video_core.h
Allows the user to customize the speed limit instead of a binary off/on frame limiter. 
Things to know:
* Adjusts the max frametime lag to 250ms instead to allow lower frame limits. If the max lag is too small, the clamp will prevent limiting to smaller values. In practice: at the original 25ms value, the limiter could clamp around values of 60%, so half speed play wasn't possible. 250ms was selected as it allows clamps around 6%. This can be changed if someone thinks that limiting to such values would be pointless.
* Adds a hotkey (+ / - by default) to adjust the speed limit by +- 5%
* Status bar changed to display the limit
* Using a spinbox lets the user choose a precise limit as its adjustable by +- 1%
--- …
=> citra-qt: Add customizable speed limit target

src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h
- Allows installed games to display in the game list
- Allows installed (executable) system applications to display in the game list
- Replaces the game icon with the icon from an installed update if available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3402)
=> Allow Installed Apps to Display in the Game List

src/core/hle/service/service.cpp, src/core/hle/service/y2r_u.cpp, src/core/hle/service/y2r_u.h
Functional changes:
Type of `temporal_dithering_enabled`, `transfer_end_interrupt_enabled` and `spacial_dithering_enabled` is changed from `u32` to `bool`, and their corresponding functions use standard `Push/Pop<bool>`. It is confirmed from the y2r code that they follows the standard ARM ABI and IPC convention where `bool` type stores as one byte.
I only moved existing function documentation from the cpp to the header file. Should I complete the documentation for those that don't have yet?
----
Also about whether to use pImpl here (this talk derives from [here](https://github.com/citra-emu/citra/pull/3253#discussion_r155930667) in mic_u migration):
I personally don't like it for the following reasons:
- the header only has two file depending on it: y2r_u.cpp and service.cpp. Only two …
=> Service/Y2R: convert to ServiceFramework

src/core/CMakeLists.txt, src/core/hle/applets/applet.cpp, src/core/hle/applets/applet.h, src/core/hle/applets/erreula.cpp, src/core/hle/applets/erreula.h, src/core/hle/applets/mii_selector.cpp, src/core/hle/applets/mii_selector.h, src/core/hle/applets/mint.cpp, src/core/hle/applets/mint.h, src/core/hle/applets/swkbd.cpp, src/core/hle/applets/swkbd.h, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/apt/applet_manager.h, src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/errors.h, src/core/hle/service/ns/ns.h
This is a preparation for converting APT service into `ServiceFramework`. APT service consists of many components and functionality. Direct conversion would make it expose too much implementation detail and everything would entangle together (well, it already is...). This PR refactor out a main component of APT, the applets manager, into its own class, and move the implementation detail of related service functions into the class. Moved functions are
- `Send/Receive/Glance/CancelParameter`
- `Initialize`, `Enable`, `IsRegistered`, `GetAppletInfo`
- `PrepareToStart/Preload/FinishPreloading/StartLibraryApplet`
There are more applet related functions that are not moved yet. They are all currently stubbed and I leave the work to who implements it.
Some other changes are also made:
- Use enum …
=> APT/Applet: move applet management into its own class

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/main.cpp, src/citra_qt/main.h
Turns OnGameListOpenSaveFolder into a general purpose function to open a location based on on which enum value is passed to it and adds options to the GameList context menu for it
Follow-up to request made by @LogPod in #3402 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3411)
=> Add Context Menu Options to Open Application and Update Location

src/citra_qt/debugger/wait_tree.cpp, src/core/arm/arm_interface.h, src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/dyncom/arm_dyncom.cpp, src/core/arm/dyncom/arm_dyncom.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
~~WIP as dynarmic side changes are in flux.~~
Advantage is this avoids needing to invalidate cache-like structures on the CPU emulator like the Return Stack Buffer when doing a context-switch. This also avoids the cost of seralizing and deseralizing the CPSR and FPSCR when the CPU backend has a non-canonical representation of these things.
On dynarmic's side we also have the following changes for speed:
* Split CPSR for slightly faster GE flags access and slightly faster runtime location-hash calculation.
* Added prediction for where the next basic block would be when exiting due to exhaustion of time slice to avoid an expensive std::unordered_map lookup on re-entry.
* Turn RSB back into a stack since it offers better predictions with the context changes.
--- …
=> core/arm: Backend-specific context implementations

.travis/linux-frozen/build.sh, .travis/linux-frozen/docker.sh, .travis/linux-frozen/install_package.py, .travis/linux/build.sh, .travis/linux/deps.sh, .travis/linux/docker.sh, .travis/macos/build.sh, CMakeLists.txt, externals/cryptopp/CMakeLists.txt
This also updates the docker machines we use on our build servers to Ubuntu 18.04.
Note: Upstream CMake file can be found at: https://github.com/noloader/cryptopp-cmake/blob/7ef1dbe0db095ea480500dd8e10c9ece8975974f/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3430)
=> Bump to C++17

src/core/hle/service/fs/fs_user.cpp
Stubbing these functions results in saves loading correctly in games which require a secure value.
An example is shown here with Animal Crossing: New Leaf:
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3429)
=> Service/FS_User: Stub Secure Value Functions

src/core/hle/service/apt/apt.cpp
This is a abuse of `Skip` which conflicts with the new hle_ipc framework and which is revealed by #3421 . Currently if the shared font fails to load, hle_ipc will ASSERT on the handle because it is skipped and their is no corresponding objects being send (even though it is just a null object). The object should be send by calling PushCopy/MoveObjects regardless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3448)
=> APT: don't skip translation parameters

src/audio_core/codec.cpp
Signal range is -32767 to 32768, not -127 to 128.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3459)
=> decode: Fix PCM8 decoding

src/core/file_sys/archive_backend.cpp, src/core/file_sys/archive_backend.h, src/core/hle/ipc_helpers.h, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/fs/fs_user.h, src/core/hle/service/service.cpp
See commit description for some details.
There are some global state in fs/archive which should be encapsulate in the FS_USER object (or a general FS object), but I didn't touch them in this PR because FS module is depended by many others including PTM, CFG and loader etc, which requires a major refactor. I leave them to a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3441)
=> Service/FS: convert to ServiceFramework

src/core/hle/kernel/hle_ipc.h, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/gsp/gsp_gpu.h
This was HW tested behavior
To enabled service specific behavior on closing the session the according SessionRequestHandler::ClientDisconnected had to be virtual.
Since SessionRequestHandler is just an interface and out of consistency I decided to make the ClientConnected virtual too. It isn't needed atm, but we might reach a point where it is useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3461)
=> GSP_GPU: Release the GPU right if the active session closes the gpu session

externals/CMakeLists.txt, src/common/swap.h, src/core/hle/service/service.cpp, src/core/hle/service/soc_u.cpp, src/web_service/announce_room_json.cpp, src/web_service/json.h, src/web_service/telemetry_json.h, src/web_service/verify_login.cpp
Refer to the commit messages for details.
The first (fix swap functions on Bitrig and OpenBSD) and last (use std::experimental::string_view in json) changes are particularly hacky, but unless the project is willing to rename the entire Common::swap* function family, I can't think of a better way to do the former. The latter can just be dropped if it's viewed as too hacky; it's understandable if the project doesn't want to cater to incomplete c++17 stdlib implementations.
With these changes, citra compiles on OpenBSD with the following commands:
```
mkdir build && cd build
export Qt5_DIR=/usr/local/lib/qt5/cmake/Qt5
cmake \
-DCMAKE_CXX_FLAGS='-I/usr/local/include -O2' \
-DCMAKE_EXE_LINKER_FLAGS=-zwxneeded \
-DUSE_SYSTEM_CURL=1 ..
make
```
As an aside, I noticed that compiling with …
=> Fix build on OpenBSD

src/core/hle/ipc_helpers.h, src/core/hle/service/nim/nim.cpp, src/core/hle/service/nim/nim.h, src/core/hle/service/nim/nim_aoc.cpp, src/core/hle/service/nim/nim_aoc.h, src/core/hle/service/nim/nim_s.cpp, src/core/hle/service/nim/nim_s.h, src/core/hle/service/nim/nim_u.cpp, src/core/hle/service/nim/nim_u.h, src/core/hle/service/service.cpp
This is the last user of deprecated PushHandles.
NIM services don't have shared functions exposed for each port, so it makes more sense to move the function implementation into their own port file. I moved the only two stubbed/implemented function from nim.cpp to nim_u.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3468)
=> Service/NIM: convert to ServiceFramework

src/core/hle/service/nwm/nwm.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/shared_page.cpp, src/core/hle/shared_page.h
Apparently several games check the shared page mac address and wifi
link level values, and will refuse to start UDS if they are not correct.
This change gives a default value (in case you aren't connected to a
network) and will read the value from Room if you are connected.
This pr is known to fix Tri Force Heroes multiplayer. Please test other games that used to have the "Cannot connect" issue when starting a lobby, and report success here. Some games that I know are on that list are:  Mario Party Star Rush, The Legend of Zelda: TriForce Heroes, Monster Hunter Generations, Monster Hunter X, Monster Hunter XX, Dragon Quest Monsters: Terry, PokemonXY, and VirtualConsole games (such as pokemon red/blue/gold/silver)
clang format will likely bark at me.
--- …
=> UDS: Add non zero mac address to the shared page

src/core/CMakeLists.txt, src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_ncch.h, src/core/file_sys/archive_sdmc.cpp, src/core/file_sys/archive_selfncch.cpp, src/core/file_sys/delay_generator.h, src/core/file_sys/disk_archive.cpp, src/core/file_sys/disk_archive.h, src/core/file_sys/file_backend.h, src/core/file_sys/ivfc_archive.cpp, src/core/file_sys/ivfc_archive.h, src/core/file_sys/savedata_archive.cpp, src/core/hle/service/fs/archive.cpp
File IOs on a 3DS take much longer then our currently emulated 39000 ns for each SVC call. Without the additional delay added by that PR the thread reading a file is executed much faster then it should, leading e.g. to deadlocks.
Also the emulated timing is a lot more precise with that PR. The testing homebrew https://gist.github.com/B3n30/9c08a8103880f661fd9eee284044eff4 took on a 3ds about 10 min while in citra without that PR it was finished in 30 sec (with framelimiter enabled). With that PR the timings were about the same.
The time it took for the reads were tested with that homebrew and the average for each file size was determined. The values were then extracted from that averages. For now RomFS, ExeFS, and reading savefiles were tested. For all other values for now the RomFS/ExeFS …
=> File_Sys: Add a size dependent delay for each file read

src/common/assert.h
This really serves no purpose but pure annoyance:
- it doesn't crash in release build so no-op in user's perspective
- it is very common (unimplemented texture type in video_core, unimplemented pipe in audio_core etc.). By writing the code `UNIMPLEMENTED();`, devs already well acknowledged that this code _will_ be hit in some cases (as opposite to `UNREACHABLE()`), and will look for the log when they need regardless whether the emulator crashes or not
- it prevents debugging other problems in debug build because it crashes before the debug point, essentially stop devs from debugging in debug build, which is exactly the opposite of the purpose this code was supposed to have.
--- …
=> assert: do not crash on unimplemented code in debug build

CMakeLists.txt, src/video_core/CMakeLists.txt, src/video_core/debug_utils/debug_utils.cpp, src/video_core/debug_utils/debug_utils.h, src/video_core/swrasterizer/rasterizer.cpp
Backport from LibRetro.
Libpng is only currently used in [one place in Citra](https://github.com/citra-emu/citra/blob/443bb3d522916f9be2d27fc8b3d7b5cc942213df/src/video_core/debug_utils/debug_utils.cpp#L322), which is [never reached by code ordinarily](https://github.com/citra-emu/citra/blob/ae7240a2cb6ebcf703df52f086d57a26551e4761/src/video_core/swrasterizer/rasterizer.cpp#L397) as PICA_DUMP_TEXTURES is [disabled](https://github.com/citra-emu/citra/blob/0cb52ee74a8255eb0320c882bc9e70700317d16a/src/video_core/debug_utils/debug_utils.h#L184). It is a dependency which is generally hard to bring around and literally doesn't add any functionality to regular, release Citra builds at all.
This PR disables libpng integration by default, and gates it behind a CMake option. It should be trivial …
=> Remove PICA image dumping, burn libpng

src/core/memory.cpp, src/core/memory.h
This page type is not used, and is not expected to be used at any time. Rasterizer only caches on linear heap and VRAM, which has no overlap with I/O region.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3487)
=> Memory: remove RasterizerCachedSpecial page type

src/citra_qt/bootmanager.cpp
This fixes #2092, a long-standing bug where on macOS resizing the window results in a garbled display.
It seems the seemingly optional `child()->makeCurrent` call is actually required on macOS. Enabling it in all cases fixes the resize issue.
I couldn't observe any effect on performances. However it should be possible to perform this call only if the buffer was resized since last swap (at the cost of added complexity).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3505)
=> Fix QGLWidget viewport resize on macOS

src/network/room.cpp, src/network/room.h
Currently, we are leaking memory from our HandleWifiPacket() implementation. This PR adds some sanity checks that will log a error and free that memory if a situation like this is hit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3503)
=> Handle ENet packet destruction if the packet is not sent anywhere

src/network/room.cpp, src/network/room.h
stringstream interpreted u8 as char and thus stopped printing on a 0 byte. 
Also the width of each octal was just 1 if a leading 0 was required.
Blame me, since I suggested stringstream in the first place.
Thx for @wwylele for finding that error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3515)
=> Fix formatting of mac address in error log

.gitignore, src/citra_qt/main.cpp
Fixes that the menu layout option is not updated after changing layout with F10
-----------------------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3513)
=> .gitignore: Add CMakeLists.txt.user to Project/editor files, citra_qt: Sync menu UI settings after changing the layout with F10

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h
Use ARB_buffer_storage with persistent mappings to stream the vertex data to the GPU.
Update:
I've picked the helper classes from #3499. This code uses GL_sync to block if the buffer is full instead of orphaning. The performance however should be close to identical. Too big draw call, which won't fit in the buffer, will be splitted in small chucks (tested with a tiny buffer).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3504)
=> Vertex streaming

src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.h, src/core/hle/ipc_helpers.h, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/apt/apt.cpp, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h, src/core/hle/service/cfg/cfg_i.cpp, src/core/hle/service/cfg/cfg_i.h, src/core/hle/service/cfg/cfg_nor.cpp, src/core/hle/service/cfg/cfg_nor.h, src/core/hle/service/cfg/cfg_s.cpp, src/core/hle/service/cfg/cfg_s.h, src/core/hle/service/cfg/cfg_u.cpp, src/core/hle/service/cfg/cfg_u.h, src/core/hle/service/service.cpp, src/core/loader/ncch.cpp
This is a relatively large one and have several inter-module dependencies, so please take time to do careful review, thanks!
CFG module have some functions that have multiple IDs. I checked the module code and confirmed that these functions with different IDs indeed contains identical content. To implement this in `ServiceFramework`, I had to make a dispatcher template `D` to assign different IDs to the same function.
This is also the last user that uses IPC helpers with command buffer directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3498)
=>  Service/CFG: convert to ServiceFramework 

src/video_core/renderer_opengl/gl_resource_manager.h
Leave the object moved from in a state where resources aren't accessable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3506)
=> gl_resource_manager: Use std::exchange in move assignment operators and constructors

src/citra/citra.cpp, src/citra_qt/main.cpp
https://stackoverflow.com/a/39047129
basically copied this^
I held off on AMD because I have no way to test that, and AMD GPUs sometimes have more issues than Intel integrated graphics in the current PICA->GLSL implementation.
(this can of course be overridden by custom control panel profiles)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3528)
=> use nvidia graphics automatically on laptops with optimus

src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/swrasterizer/lighting.cpp
Fixes #3482
I hwtested the two side diffuse and highlights clamping behaviour and there is a summary table
|           |                           |       |         |       |         | 
|-----------|---------------------------|-------|---------|-------|---------| 
| \         | Two side diffuse          | FALSE | TRUE    | FALSE | TRUE    | 
|           | Clamp highlights          | FALSE | FALSE   | TRUE  | TRUE    | 
| L * N > 0 | dot product =             | L * N | L * N   | L * N | L * N   | 
|           | clamp highlights factor = | 1     | 1       | 1     | 1       | 
| L * N = 0 | dot product =             | 0     | 0       | 0     | 0       | 
|           | clamp highlights factor = | 1     | 1       | 0     | 0       | 
| L * N < 0 | dot product =             | 0     | - L * N | …
=> pica/lighting: compute highlight clamp after one-/two-sided diffuse pass

CMakeLists.txt
Hehe, my first time contributing code, do I deserve a cookie ? :smile: 
More seriously, thank you the team for this amazing work. This only puts the Boost requirement to version 1.66.0. This will avoid people reporting bugs for this because of the Boost < 1.66 / GCC incompatibility.
Let me know if there is any problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3564)
=> Build fixes

src/input_common/sdl/sdl.cpp
Follow-up of #3533
Replace logging to use NGLOG instead of LOG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3578)
=> input_common: Migrate logging macros

src/web_service/announce_room_json.cpp, src/web_service/web_backend.cpp
Follow-up of #3533
Replace prefix of all logging macros from LOG to NGLOG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3577)
=> web_service: Migrate logging macros

src/citra_qt/game_list.h
This is a straightforward port of https://github.com/yuzu-emu/yuzu/pull/87.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3582)
=> Implement Pull #87 from yuzu: game_list: Add missing override specifier for KeyReleaseEater's eventFilter function

src/citra_qt/compatdb.cpp, src/citra_qt/game_list.cpp, src/citra_qt/main.cpp, src/citra_qt/updater/updater.cpp
Follow-up of #3533
Replace prefix of all logging macros from LOG to NGLOG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3574)
=> citra_qt: Migrate logging macros

src/core/hle/service/nwm/nwm_uds.cpp, src/network/room.h, src/network/room_member.h
This checks the flags in SendTo and tries to sand the packets according to the flags. 
This wasn't HW-Tested by me, but just taken from 3dbrew
~~Some variants are currently unimplemented and will assert. I didn't observe any game using that mode yet. If we find such games I'll implement them.~~
I want this PR to stay in canary some time to see if some games (especially games with more then 2 players) get fixed by that, ~~or if the hit the unimplemented scenarios.~~
Note: Since this PR also touches libnetwork I increased the libnetwork version. This makes future builds incompatible with old builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3481)
=> NWM_UDS:: Check flags in SendTo

src/core/hle/service/err_f.cpp
Introduced by 691f069743bd0cf06cb070ee14c8e4ef51977550
If we hit a prefetch abort, the DFSR and DFAR contents aren't really going to be that useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3599)
=> err_f: Add missing break in ThrowFatalError()

src/core/hle/service/boss/boss.cpp
This was previously overwriting data in the same index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3598)
=> boss: Correct ReceiveProperty()'s response data payload

src/core/file_sys/ncch_container.cpp
These kinds of casts invoke undefined behavior, due to both the aliasing rule, and from an alignment point-of-view. Use the way that's guaranteed to always work instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3597)
=> ncch_container: Get rid of pointer casts in LZSS_GetDecompressedSize() and LZSS_Decompress()

src/video_core/renderer_opengl/gl_rasterizer.cpp
This should actually be comparing the validity of the destination surface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3601)
=> gl_rasterizer: Fix incorrect comparison against src_surface in AccelerateTextureCopy()

src/core/file_sys/archive_systemsavedata.cpp
These kinds of casts invoke undefined behavior due to alignment rules.
Use memcpy instead which always does the right thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3604)
=> archive_systemsavedata: Remove pointer cast from GetSystemSaveDataPath()

src/dedicated_room/citra-room.cpp
If the variable we're checking is a u16, then there can never be values outside of the 0-65535 range. This is bad because an arbitrary larger value can be truncated down into a valid value (as we use strtoul, which operates on unsigned longs), making otherwise malformed argument well-formed.
Change it to use u32 to allow the check to function properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3603)
=> citra-room: Fix always false case in main() related to port range

src/core/loader/3dsx.cpp, src/core/loader/elf.cpp, src/core/loader/loader.cpp, src/core/loader/ncch.cpp
Replace logging to use `NGLOG` instead of `LOG`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3593)
=> core/loader: Migrate logging macros

src/citra_qt/main.cpp, src/citra_qt/main.h
adds a signal to tell widgets to update icons to match the current theme
also moves UpdateUITheme() before widget initialization so widgets properly inherit the icon theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3610)
=> QT: add themed icon update signal

src/video_core/regs_framebuffer.h, src/video_core/regs_lighting.h, src/video_core/regs_texturing.h, src/video_core/swrasterizer/framebuffer.cpp, src/video_core/swrasterizer/framebuffer.h, src/video_core/swrasterizer/lighting.cpp, src/video_core/swrasterizer/rasterizer.cpp
Credit to @fincs for [the documentation regarding to shadow mapping](https://gist.github.com/fincs/543f7e1375815f495f10020a053f14e9)
PICA's shadow mapping mode consists of three relatively independent parts (corresponding to the three commits)
This is an additional factor applied to diffuse/specular/alpha terms (and is the last unimplemented term in the lighting engine). It is pretty straight-forward, as it takes the sampled colors from textures and directly multiplies the colors as factors to the shadow-enabled terms. The diffuse/specular color attenuation term is applied in per-light basis, while the alpha term is applied globally, after the Fresnel term. The alpha selector shares the same register as the Fresnel selector, so you can view the selector register as general "enable alpha …
=> SwRasterizer: Implement shadow mapping 

src/web_service/verify_login.cpp
This function can be simplified by attempting to find the username within the JSON object and then only accessing it if it does. There's no need to blindly access the data itself.
This also eliminates the need to copy the string to a local as well, since we already have the element itself, we can just compare against it. For the failure case, it's the same if we were checking that the provided username string is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3602)
=> verify_login: Make VerifyLogin exceptionless

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
This is a question come up from #3499 (["`// TODO: why is this here ???`"](https://github.com/citra-emu/citra/pull/3499/files#diff-d1b91c65951bd9733c0e7d924161e57dR1742)), and it hinders further refactor for preparing vertex/geometry shader. All the SyncXXX functions called here share the following patterns:
- Their implementation all follows this form:
```
some_value = Pica::g_state.regs.some_register
if (some_value != uniform_block_data.data.some_value) {
uniform_block_data.data.some_value = some_value;
uniform_block_data.dirty = true;
}
```
- They are all called in exactly two places: `SetShader` (here) and `NotifyPicaRegisterChanged`
It can be seen that only when the register value and uniform value mismatch, these function can do something instead of no-op. The only possibilities of …
=> gl_rasterizer: move shader uniform sync from SetShader() to ctor

src/common/hash.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h
This is to avoid misuse of hash functions & memcpy without noticing padding problem like the ones in #3499. The usage of this template would be like:
```
struct XState{
// state member variables
};
struct XConfig : HashableStruct<XState> {
// useful member functions, constructors and creators
};
namespace std {
template <>
struct hash<XConfig> {
size_t operator()(const XConfig& k) const {
return k.Hash();
}
};
} // namespace std
...
XConfig config;
config.state.member = ...; // use "state" to access state member variables
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3518)
=> Common/Hash: abstract HashableStruct from GLShader::PicaShaderConfig

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h
This is the core part of #3499. I extracted out so that it can be reviewed first. In this PR, I only added the source file, without adding any users, so that we can focus on the implementation first. Other parts in #3499 still have some unclear issue including AMD problems, which will be investigated after this.
Here is a doc about the design
----
A subroutine is a collection of code. Each subroutine is identified by two code addresses: the entry point (named "begin" in the code) and the return point (named "end" in the code). The code execution starts from the entry point. When the execution reaches the return point, the subroutine exits and the execution goes back to the caller. However, the entry point is not necessarily the lower boundary of the code belonging to the subroutine; the …
=> renderer_opengl: add PICA->GLSL shader decompiler

src/core/hle/service/nwm/nwm_uds.cpp
This updates the connection_status and the node_info of already connected clients
On a 3ds a special packet is send for that purpose, but thats not necessary for us. We can just use the eapol packet that is sent to the new client
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3489)
=> NWM_ UDS:Let connected clients handle the eapol packet

src/common/logging/backend.cpp, src/common/logging/log.h
Additionally, when updating fmtlib, there was a change in fmtlib broke
how the old logging macro was overloaded, so this works around that by
just naming the fmtlib macro impl something different
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3629)
=> Update fmtlib to fix msvc warnings

src/audio_core/hle/mixers.cpp, src/citra_qt/debugger/graphics/graphics_surface.cpp, src/common/assert.h, src/common/chunk_file.h, src/common/file_util.cpp, src/common/logging/filter.cpp, src/common/memory_util.cpp, src/common/param_package.cpp, src/common/string_util.cpp, src/core/core_timing.cpp, src/core/hle/applets/applet.cpp, src/core/hle/ipc_helpers.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/ipc.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/apt/apt.cpp, src/core/hle/service/dsp_dsp.cpp, src/core/hle/service/sm/srv.cpp, src/core/memory.cpp, src/video_core/regs_framebuffer.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/shader/shader.cpp
Follow-up of #3533
Replace logging to use `NGLOG` instead of `LOG`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3580)
=> common: Migrate logging macros

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h
hardware renderer's counterpart of #2721. The test program there can be also used for this.
This is an unoptimized implementation because I want to avoid penetrating the cache system before I fully understand it. There is a single cubemap texture object owned by the rasterizer (not the cache), and bound to a dedicated texture unit. When texture cube enabled, on each vertex batch, the 6 texture surfaces were pulled from texture cache and blit to the cubemap texture object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3497)
=> gl_rasterizer: implement TextureCube

src/video_core/regs_lighting.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/swrasterizer/lighting.cpp
The hw renderer counterpart of **the first commit** of #3516. The other two are still unimplemented. 
----
I am still not sure how to implement the rest of shadow mapping stuff, specifically the third part _Shadow map rendering in the output merger stage_. To support soft shadow, PICA has a pretty complicated output merger stage algorithm, which is hard to emulate using the standard depth/stencil test & blending in OpenGL. So far the only feasible way I know is to use [Image load store](https://www.khronos.org/opengl/wiki/Image_Load_Store). Another option is to not support soft shadow (no game using this known to me), and to only implement hard shadow, which makes it a trivial depth test.
--- …
=>  gl_rasterizer/lighting: implement shadow attenuation

.travis.yml, .travis/transifex/build.sh, .travis/transifex/deps.sh, .travis/transifex/docker.sh, .travis/transifex/upload.sh
This PR will attempt to fix the Transifex upload failure in Travis CI build.
This should fix #3472 .
Please do note the **Travis CI will still fail in this PR**, since according to [Travis CI documentation](https://docs.travis-ci.com/user/encryption-keys/), the secured variables will not be exposed to PRs for safety concerns. So it will show something like:
```
tx INFO: Pushing resource citra.emulator
[?] Enter your api token: tx ERROR: EOF when reading a line
```
But I'd expect it to behave correctly after being merged.
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3647)
=> travis: fix Transifex upload

src/citra_qt/main.cpp
Fix the stuck in fullscreen bug (split from #3576).
Open a game, go fullscreen, hit alt+f4 & close Citra. Reopen, and you get stuck.
To fix, remove geometry data from qt-config.ini.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3611)
=> citra-qt: Fix the stuck in fullscreen bug.

src/dedicated_room/CMakeLists.txt, src/dedicated_room/citra-room.cpp
Fixes #3538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3634)
=> citra-room: Use the default OpenGL loader instead of SDL_GL_GetProcAddress

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
Game can feed the texture address register an invalid value and doesn't use the texture in the rendering pipeline. In this case we should just ignore the invalid texture. We already do this for normal texture units, and it should also be done fore the texture cube.
The texture cube is also changed such that it is not bound to the texture unit from the rasterizer initialization, but only bound when in use, just in the same way as normal textures. It will not be bound when texture cube is not used or when the address is invalid.
Aim to fix #3635.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3639)
=> gl_rasterizer_cache: exit FillTextureCube when address is invalid

src/video_core/renderer_opengl/gl_shader_gen.cpp
Adds a function to the generated GLSL called byteround for floats and vec2-vec4.
Fixes water effect in SM3DL.
Closes #2791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3638)
=> Round TEV outputs and the final fragment output in GLSL

src/core/core.cpp, src/core/core.h, src/core/hle/service/service.cpp, src/core/hle/service/service.h, src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
Rather than have it live as a global variable, place it into the System class and make it instance-based.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3656)
=> sm: Relocate the service manager to the System class

src/citra_qt/main.cpp
The keys F9 and F10 were marked for translation in the Qt GUI, this shouldn't be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3660)
=> Don't translate function keys in Qt GUI

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_shader_util.cpp, src/video_core/renderer_opengl/gl_shader_util.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/renderer_opengl.h
We currently have an ambiguous concept in our code: a "shader" (`OGLShader` class) represents a OpenGL program object, not a shader object. This works fine till now because we either use completely fixed program (hard-coded GLSL), or program where only the fragment shader is configurable. In this case there is a well-defined 1:1 mapping between shader source code and program objects. However with #3499 pending, we are going to decompile PICA vertex & geometry shaders to GLSL as well, which means the vertex shader and the geometry shader are also configurable, breaking the 1:1 mapping between program objects and shader source code.
This PR is extracted from the bulk change in #3499. It intends to redefine program resource and shader resource to match what they are in OpenGL, and to add a …
=> renderer_opengl: refactor shader & program objects and add shader manager for rasterizer

src/video_core/command_processor.cpp, src/video_core/shader/shader.h, src/video_core/shader/shader_jit_x64.cpp, src/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/shader/shader_jit_x64_compiler.h
A small optimization isolated from #3499 which is essentially unrelated to shader decompilation. Difference from the phantom's version: avoid using `offsetof` and private members in the same class ([not guaranteed supported in C++](http://en.cppreference.com/w/cpp/types/offsetof) and generates warnings in GCC)
Some statistics: the cache hit/miss rate is about 1:1 in games I tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3662)
=>  shader: avoid recomputing hash for the same program 

src/citra_qt/game_list_p.h
#3663 regression. Not sure how the header is bootlegged on Travis CI but...
```
$ pkg info -x qt5
qt5-buildtools-5.9.4_1
qt5-concurrent-5.9.4_1
qt5-core-5.9.4_2
qt5-dbus-5.9.4_1
qt5-gui-5.9.4_4
qt5-network-5.9.4_3
qt5-opengl-5.9.4_1
qt5-qmake-5.9.4_1
qt5-widgets-5.9.4_1
$ rg QCoreApplication::translate /usr/local/include
/usr/local/include/qt5/QtCore/qcoreapplication.h
244:        { return QCoreApplication::translate(#context, sourceText, disambiguation, n); }
250:        { return QCoreApplication::translate(#context, sourceText, disambiguation, n); } \
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3670)
=> Unbreak build with Qt 5.9.4 (at least on FreeBSD)

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h
This is a followup to #3504 .
The idea of this rewrite is to orphan the buffer when it is full instead of syncing. This allows the driver to allocate many buffer objects and so to increase/decrease the size of the ring buffer. This however needs a glMapBufferRange call on orphaning, which likely synchronize the drivers worker thread once a frame.
On rewriting the implementation, I've also updated the API to flush the used buffer space on unmapping. This allows to generate the vertex data in-place and to flush the generated data afterwards. The new API also returns if the old allocations are still valid. This might allow us to use this kind of buffer for uniforms and texture buffers. In this way, we just need to reupload all of them on orphaning.
--- …
=> renderer_opengl: Rewrite stream buffer.

src/citra_qt/multiplayer/message.cpp
Fixes this 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3689)
=> Frontend: Add missing translation for network error messages

src/citra/citra.cpp, src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_debug.cpp, src/citra_qt/configuration/configure_debug.ui, src/citra_qt/debugger/console.cpp, src/citra_qt/debugger/console.h, src/citra_qt/main.cpp, src/citra_qt/ui_settings.h, src/common/common_paths.h, src/common/file_util.cpp, src/common/file_util.h, src/common/logging/backend.cpp, src/common/logging/backend.h, src/common/string_util.cpp, src/core/settings.cpp, src/core/settings.h
This is part 2 of #3449 , also a follow-up of #3533
The main goal of this is to change the logging backend to support multiple sinks (console, color console, file, etc) through the Backend interface, with the following changes:
* Separate logging into its own thread
* Add support for adding and removing backends on runtime
* Change logging filter on runtime
* Button to open log location
As a side effect, on Windows, Citra has to be compiled as a GUI application to make the console hidden by default.
The current way of dealing with large log files is to set a limit of 50MB for logging to file. This should work fine when the log level is not Debug.
On Discord, we discussed about truncating repeated logs. For the aim of reducing the number of lines (spam on console, and also the number of …
=> Logging: Add customizable backends

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/pica_to_gl.h
This is a follow-up PR of #3567, and is a part extracted from #3499. While gl_shader_decompiler generates the core code segment of the shaders, this PR generates everything around the core code, including input/output handling, and generates complete shader source code and shader object. Three new types of shaders are introduced to gl_shader_gen and gl_shader_manager:
- programmable vertex shaders, which is translated from PICA vertex shader
- fixed geometry shaders, used when no PICA geometry shader is used. This shader only does the following work
- Map shader output to semantic slots (originally done in OutputVertex::FromAttributeBuffer)
- "Quaternion fix" (originally done in gl_rasterizer). This is the main reason a geometry shader is needed.
- Clipping distance calculation …
=> gl_shader_gen: generate programmable vs/gs and fixed gs

src/citra_qt/multiplayer/lobby.cpp
This would be quite a quick fix.
Old (canary):
Default
Entered something
PR:
Default
Entered something
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3705)
=> citra_qt: multiplayer password dialog fix

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
This is to reduce the performance impact of texture cube. Previously the texture cube is copied from texture surfaces on every draw batch, and for example in some area in Monster Hunter XX this is about 36 texture copies per frame.
Now with the cached texture cube, the texture copy only happens when the content of texture is changed, which in theory means: 6 copy on first draw and 0 copy per frame for static cubemap (= games load the cube from binary. The 0 copy per frame statistics is tested in MHXX), and 6 copies per frame for dynamic cubemap (= games renders environment to cube then do shading using the cube)
The cache is implemented such that, for each cached texture cube object, it has six watchers linked with the six referenced surfaces. When the texture cube is used, it checks if …
=> gl_rasterizer_cache: cache texture cube

src/video_core/regs_pipeline.h
These utility functions for loaders have common issues:
- `inline` is unnecessary as it is already defined in-class (implicitly inline)
- input parameter are used as array index, which should be size_t
- output are converted from u32 to int. Their only user is video_core/vertex_loader, where they are then converted back to unsigned values, making the type `int` meaningless
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3719)
=> regs_pipeline: use proper unsigned type where applicable

dist/languages/de.ts, dist/languages/es_ES.ts, dist/languages/fr.ts, dist/languages/hu_HU.ts, dist/languages/id.ts, dist/languages/it.ts, dist/languages/ja_JP.ts, dist/languages/ko_KR.ts, dist/languages/lt_LT.ts, dist/languages/nl.ts, dist/languages/pt_BR.ts, dist/languages/ru_RU.ts, dist/languages/zh_CN.ts
This PR adds the current translations (2018-04-25) to the main Citra repo from the Transifex project. I accepted translations that were at least 50% translated and reviewed with some exceptions.
Language list: German, Spanish, French, Hungarian, Indonesian, Italian, Japanese, Korean, Lithuanian, Dutch, Brazillian, Russian, Chinese.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3688)
=> Added current translations from Transifex

CMakeLists.txt, src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/game_list_p.h, src/citra_qt/main.cpp, src/citra_qt/main.h
I made this PR, because @chris062689 wanted to make some changes to the API endpoint used for the compatibility list.
The only functional change in this PR should be the introduction of a new context menu option when you right-click a game. It is called "Navigate to GameDB entry" and opens the game wiki page of the game in your browser. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3730)
=> citra_qt: Refactor game list compatibility system

.travis/transifex/docker.sh
The Qt multimedia dependency was added in #3566, but didn't added to the transfex push job. Although it really doesn't have anything to do translation, the CI on master still errored anyway: https://travis-ci.org/citra-emu/citra/jobs/377846806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3734)
=> travis: add missing dependency for transifex push job

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/core/settings.cpp, src/core/settings.h, src/video_core/command_processor.cpp, src/video_core/primitive_assembly.cpp, src/video_core/primitive_assembly.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/video_core.cpp, src/video_core/video_core.h
This is the last backend piece for #3499, which includes the following jobs
- setup GL vertex arrays from PICA vertex loader
- Vertex attributes specification is translated from PICA attribute registers as they map pretty well. Note that, however, GL VAO also handles the "PICA input attributes => input registers" transformation (See transformation [2] in #3686), so be aware that the attribute index in GL represents the VS inout register index in PICA.
- For non-indexed draw, vertex attributes data are directly streamed into the GL vertex buffer
- for indexed draw, the index list is first scanned to find the minimal and maximal indices. Then vertex data in this min/max range is streamed into the GL vertex buffer, and the index data is streamed into the GL index buffer.
- AMD GPU has a …
=>  gl_rasterizer: implement AccelerateDrawBatch to emulate PICA shader on hardware

src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/core/settings.h
This is the frontend part of #3499. I am not very happy with the UI design (either the original one or current one), but I am running out of idea. Currently the core problem we have is
Our shader emulation implementation is not good enough yet to eliminate the need of manual configuration from users, so we have to expose multiple options in the UI. 
My excuse is that the default settings should be good for most games and users, so users don't need to go over these options. These are here for debug purpose when an issue is found and dev asks the user to try different settings and report.
The layout is rearranged to incorporate with the new options. Some of them is put into a hierarchy, where disabling the top level option would also disable all sub-options. The hierarchy is indicated by …
=>  citra-qt: add gpu shader emulation related configurations 

src/citra_qt/camera/qt_camera_factory.cpp, src/citra_qt/camera/still_image_camera.cpp, src/citra_qt/configuration/configure_camera.ui
Correct the translation of some things in the camera module I found while translating.
When the config in ``QtCameraFactory::CreatePreview()`` couldn't be loaded the translation would sound very messed up in some languages (like German) where the wording does not correspond to "Couldn't load" and "the camera".
Also there is a missing "s" in the ``.ui`` file (come -> comes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3747)
=> Camera translation

src/common/logging/text_formatter.h
The text formatter doesn't include std::string by itself, erroneously relying on the includes from parent files.
This PR adds this.
... describing one line of changes isn't easy, is it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3758)
=> Add missing std::string import in text_formatter

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
There is no need to disable this state after the draw call, gl_state will handle this for us if needed. This kind of redundant state changes are bad for the driver overhead, as flipping bits will invalidate the driver state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3724)
=> gl_rasterizer: Remove redundant scissor state change.

src/video_core/renderer_opengl/gl_rasterizer.cpp
The state object isn't used anywhere else, so there is no need to revert the state.
And the comment is just wrong: It doesn't matter which textures are bound on framebuffer binding, it only matters at draw time. And we reset all bindings before the draw call. So let's use gl_state as it is designed to avoid flipping states.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3789)
=> gl_rasterizer: Don't flip the texture bindings.

.gitmodules, CMakeLists.txt, externals/CMakeLists.txt, src/audio_core/CMakeLists.txt, src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h, src/audio_core/sink_details.cpp
This PR implements a [cubeb](https://github.com/kinetiknz/cubeb) audio sink, as an alternative to the existing SDL2 audio sink. Cubeb is also used by Dolphin and noted for its low latency.
The implementation here is based partially off of Dolphin's and the existing SDL2 audio sink, although the actual output buffering is new.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3776)
=> Implement a Cubeb audio sink

externals/cryptopp/CMakeLists.txt
Probably regressed by #3430. Follow up to #3732. See [error log](https://ptpb.pw/lhm8). Upstream is [not affected](https://github.com/weidai11/cryptopp/blob/CRYPTOPP_6_1_0/GNUmakefile#L391-L400).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3790)
=> cryptopp: unbreak on aarch64

CMakeLists.txt
Some preliminary work has already been done a while ago in https://github.com/citra-emu/citra/commit/bf12f270b3c74f694c789a57cc69f414753ca080.
Among other things, [`/DNOMINMAX` was defined for MSVC](https://github.com/citra-emu/citra/commit/bf12f270b3c74f694c789a57cc69f414753ca080#diff-af3b638bc2a3e6c650974192a53c7291R14) to avoid Microsoft's lowercase `min` and `max` macros. It turns out that this is *not* enough to avoid these macros. Even worse, there are a lot of unneeded macros that MSVC will still define.
Grepping through the most recent Windows headers reveals that the `min` and `max` macros are actually defined in four places:
1) ntdef.h:3280
2) minmax.h:17
3) minwindef.h:197
4) stdlib.h:1290
None of the Windows headers includes `ntdef.h` (1) or `minmax.h` (2), so let's disregard …
=> CMake: Avoid non-compliant standard library extensions in MSVC

src/citra_qt/game_list_p.h
I think Citra's game list items does not look very nice, so I made this..
I swapped the positions of the game title and file name, as I think game title is more important.
And, I think file name is incomplete without extension, so I added it.
For Installed titles & System titles, it makes no sense to display the file name (usually it's 00000000.app or something similar), so I display the program ID.
This is what Installed Titles look like (with multiple game dir PR merged)
And this is what a usual game directory looks like..
With (not latest) Canary it will look like this..
What do you think?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3757)
=> citra_qt: Improve Game List Item display

src/video_core/renderer_opengl/gl_shader_gen.cpp
See the comment in the code. The warning in question is reproducible on mesa drivers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3751)
=> gl_shader_gen: rearrange function definition to avoid suprious warnings

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
A fixup to #3700. The watcher invalidation there is only placed in `UploadGLTexture`, which is called when the game upload the texture from CPU side. However, there are more cases where a texture surface can be modified. Specifically, they are:
- when cleared (GPU accelerate surface clear)
- when copied from other texture (GPU accelerate display transfer / texture copy)
- when rendered by framebuffer 
In all this cases, the watcher should notify that the holder/cubemap should update the content.
For whoever is wondering, this would have performance impact on dynamic environment cube mapping, but wouldn't affect games with static cubemap (tested monster hunter).
--- …
=> gl_rasterizer_cache: add missing watcher invalidation

src/core/hle/service/nwm/nwm_uds.cpp
The mapped buffer descriptor consists of two words
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3803)
=> UDS: fix RecvBeaconBroadcastData response header

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
The ERET instruction (called by the kernel on return to userland) clears exclusive state.
It was a bug for exclusive state to be maintained across a SVC call.
This PR fixes both dynarmic and skyeye.
Closes #3806.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3810)
=> arm: Clear exclusive state after service call

src/citra_qt/game_list_p.h
Fixed system titles (they are stored in NAND)
Also, hide "-00000000" from the ID. (it is ugly).
Now only filename other than "00000000" will be displayed.
In the example, "AR Games" has a filename of 00000000 so it is hidden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3819)
=> game_list: fix system title display

src/core/hle/service/boss/boss.cpp
Changes output parameter 2 to buff_size as a placeholder for the actual number of read bytes, as per [3dbrew](http://3dbrew.org/wiki/BOSSU:ReceiveProperty) documentation.
Probably the most inconsequential title ever, but this at least fixes the Ambassador Certificate app. Before, it would throw a fatal error on boot with result code 0xD860F82C.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3826)
=> boss: Return buff_size in parameter 2 of ReceiveProperty.

.travis/transifex/docker.sh
This PR fixes tx push by replacing `/usr/bin/tx` with the original executable instead of the `easy_install` generated one (which can cause problems)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3828)
=> travis: fix tx push (again)

externals/CMakeLists.txt
Regressed by #3776. See [error log](https://ptpb.pw/v3YL).
```
$ cmake -DENABLE_QT=off -DCMAKE_INSTALL_PREFIX=/prefix /path/to/citra
$ gmake
$ gmake install
[...]
[100%] Built target citra
[100%] Built target citra-room
Install the project...
-- Install configuration: "Release"
-- Installing: /prefix/share/man/man6/citra.6
CMake Error at externals/cubeb/cmake_install.cmake:44 (file):
file INSTALL cannot find "/path/to/citra/include".
Call Stack (most recent call first):
externals/cmake_install.cmake:46 (include)
cmake_install.cmake:49 (include)
gmake: *** [Makefile:74: install] Error 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3805)
=> Unbreak install

src/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/shader/shader_jit_x64_compiler.h
I implemented this in JIT first instead of the interpreter because I plan to do a interpreter accuracy enhancement based on flacs' work, after which BREAKC can be implemented in a clean way. Our JIT, on the other hand, doesn't aim for flow control accuracy (it doesn't even support nested looping). Just to make common shaders working, I put a simple implementation of BREAKC in the JIT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3788)
=> shader/jit: implement breakc

src/video_core/shader/shader_jit_x64_compiler.cpp
It is already known that, at least for geometry shaders, normal registers are preserved across invocation, and it is already implemented. It turns out that the integer registers and condition registers also follow the same rule, and a subdivision test in ctraging relies on this. This is already implemented in the interpreter. However, shader JIT stores these registers in the host registers directly, so we need to load and store them before and after the shader execution.
Note that the mentioned ctraging test still won't render properly after this, because it also uses the unimplemented command BREAKC. This will come in the next PR.
--- …
=> shader/jit: preserve integer & condition register across invocation

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/core/frontend/emu_window.cpp, src/core/hle/shared_page.cpp, src/core/hle/shared_page.h, src/core/settings.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h
So this is pretty much a very dirty hack, but I couldn't figure out a better way to do it, so here it is.
Maybe some of y'all know how to make it better.
This PR adds the Following:
- Two new Options, "toggle_3d" and "factor_3d". "Toggle" obviously toggles usage of 3D, "Factor" represents the 3D Slider (0-100). ~~Factor is then used in the nwm service (Someone please check if this is the correct way to do it)~~ Factor is now set in shared page out of lack of i2c emulation. Both are added to the "Graphics" tab on citra_qt, in the Layout Section
- Changes to the OpenGL renderer: The Renderer now correctly seperates Left and Right eye, and displays 3D when toggle_3d is set (However, when factor_3d is 0, you wont see any 3d effect). Additionally, The Renderer now halves the Layout and …
=> Add Support for Stereoscopic 3D

src/citra_qt/aboutdialog.cpp, src/citra_qt/aboutdialog.ui
This is just some random PR.. If you don't think it necessary I will close.
But.. It's nice to let the users know how old their builds are, isn't it?
It's not good to put this in the titlebar, as that way the title bar text will be too long when game is running. (#3804)
Note: I did not include full date string in the dialog as it is not user-friendly (contains `T` and `Z` like `2018-06-18T12:39:22Z`), and has problems with time zones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3837)
=> citra-qt: Add build date in about dialog

src/core/hle/service/cecd/cecd.cpp
Not much to say for this one. Just some "(Stubbed) called" warnings migrated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3842)
=> service/cecd: Migrate logging macros

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h
This is the other alternative to implement shadow map, mentioned in #3729. 
The downside of this method so-far:
- requires extension ARB_shader_image_load_store (and some other trivial extension). Many modern GPUs have this implemented tho. The overall support rate is 70% reported by @jroweboy 
-  has more potentially overhead due to atomic read/write in the fragment shader. The largest performance impact I have been reported is from nightly 110%+ speed -> this branch 105% speed, running monster hunter gen/x/xx on Nvidia GPU.
The advantage of this method:
- Accurate soft shadow emulation
- No texture reinterpretation between RGBA8 and D24S8. The format reinterpretation and decoding is done natively by image load/store and shader program.
- In #3729 the reinterpretation caused huge …
=> gl_rasterizer: implement shadow map 2D/Cube - Image load/store version

src/citra_qt/main.cpp
A bug introduced in #3804, citra would crash on any invalid ROM.
This also affect the shortcut created by the installer, which forwards the filename from command line. When no file specified, it would forward an empty filename (= invalid ROM), causing guaranteed crash from opening citra from the shortcut.  
cc @zhaowenlan1779
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3880)
=> citra_qt: only update title from game after ensuring loaded successfully

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/pica_to_gl.h
This PR rewrites all of the TBO usage of the main draw calls:
Instead of having one binding per LUT with is updated by glBufferSubData, upload all TBO data within one buffer. To address in this big buffer, one offset per LUT is stored within the UBO.
The indirect addressing adds a small overhead for the GPU per pixel, but UBO access is usually very fast.
However skipping the glBufferSubData call decrease both the CPU and GPU overhead.
So for high upscaling factors, this PR makes the GPU performance slower. For low upscaling factors, this PR should make the emulation faster.
As a small dicussion about how to upload our LUTs:
The big part of our LUTs are our 24 lighting LUTs with each 2kB. I don't want to reupload all of them if one has changed to save memory bandwidth, and we can't use one …
=> Rewrite texture_buffer_object handling.

src/video_core/renderer_opengl/gl_shader_gen.cpp
This log turns out to be usually a false positive and can be annoying. An example of this is Monster Hunter X/XX/Gen. The game always has tev stage 0 source 2 set to texture 3 (proctex), but only actually use it for some specific models. For other models, proctex is disabled, and the tev stage 0 operation is configured to one that doesn't use source 2 (anything other than lerp or multiply-and-add). Our shader generator would still go through source 2 in this case and generate dead code for it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3851)
=> gl_shader_gen: lower log level of using disabled proctex

src/core/hle/service/dsp_dsp.cpp
The formatting of the hashes took a little tweaking to reproduce correctly. I used the old LOG_ and the new NGLOG_ macros together until it was identical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3863)
=> service/dsp: Migrate logging macros

src/citra_qt/configuration/configure_camera.cpp
Previously becasue of a bug filter will not be applied (matif reported on Discord)
With this PR filters are properly applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3889)
=> citra_qt: Fix image file selection dialog

src/video_core/command_processor.cpp, src/video_core/debug_utils/debug_utils.cpp, src/video_core/gpu_debugger.h, src/video_core/primitive_assembly.cpp, src/video_core/regs_framebuffer.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/shader/shader.cpp, src/video_core/shader/shader_interpreter.cpp, src/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/swrasterizer/clipper.cpp, src/video_core/swrasterizer/framebuffer.cpp, src/video_core/swrasterizer/lighting.cpp, src/video_core/swrasterizer/proctex.cpp, src/video_core/swrasterizer/rasterizer.cpp, src/video_core/swrasterizer/texturing.cpp, src/video_core/texture/texture_decode.cpp, src/video_core/vertex_loader.cpp, src/video_core/video_core.cpp
There is still one `LOG_GENERIC` left in renderer_opengl.cpp. I can do that after `NGLOG_GENERIC` is added in my hle/kernel pr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3878)
=> video-core: Migrate logging macros

src/core/CMakeLists.txt, src/core/hle/service/qtm/qtm.cpp, src/core/hle/service/qtm/qtm_c.cpp, src/core/hle/service/qtm/qtm_c.h, src/core/hle/service/qtm/qtm_s.cpp, src/core/hle/service/qtm/qtm_s.h, src/core/hle/service/qtm/qtm_sp.cpp, src/core/hle/service/qtm/qtm_sp.h, src/core/hle/service/qtm/qtm_u.cpp, src/core/hle/service/qtm/qtm_u.h, src/core/hle/service/service.cpp
While checking 3dbrew for max sessions, I noticed there was a little information on qtm:c, so I added boilerplate code for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3892)
=> service/qtm: Migrate to ServiceFramework

src/citra_qt/main.cpp
As of Qt 5 Qt::AA_X11InitThreads no longer does anything.
See http://doc.qt.io/qt-5/qt.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3913)
=> citra_qt: Remove obsolete application attribute

src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/configuration/configure_camera.cpp, src/citra_qt/configuration/configure_debug.cpp, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_web.cpp, src/citra_qt/main.cpp
In an attempt to relieve issue #3049, I profiled the time between closing the configuration dialog and the end of `GMainWindow::OnConfigure`. I unfortunately could not recreate the freeze on command, but I noticed that, even while a game was running, a large percentage of CPU time was spent applying the theme, regardless of whether the theme was changed:
With this change, the theme is only applied if changed.
I also removed redundant calls to `Settings::Apply` as it only needs to be called once for the entire configuration dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3911)
=> citra-qt: optimize settings application

src/citra_qt/main.cpp
fixes two instances of:
`Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3912)
=> fix conversion warnings

src/core/hle/service/nwm/nwm.cpp, src/core/hle/service/nwm/nwm.h, src/core/hle/service/nwm/nwm_cec.cpp, src/core/hle/service/nwm/nwm_cec.h, src/core/hle/service/nwm/nwm_ext.cpp, src/core/hle/service/nwm/nwm_ext.h, src/core/hle/service/nwm/nwm_inf.cpp, src/core/hle/service/nwm/nwm_inf.h, src/core/hle/service/nwm/nwm_sap.cpp, src/core/hle/service/nwm/nwm_sap.h, src/core/hle/service/nwm/nwm_soc.cpp, src/core/hle/service/nwm/nwm_soc.h, src/core/hle/service/nwm/nwm_tst.cpp, src/core/hle/service/nwm/nwm_tst.h, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/service.cpp
Also moved the MAC initialization from `NWM::Init()` to `NWM_UDS::NWM_UDS()`. A better place for this would be a central NWM module shared by all service. But for now UDS is the only functioning service which acts like a single-service module, so I put it there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3873)
=> Service/NWM: convert to ServiceFramwework

src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/swrasterizer/rasterizer.cpp
Similar to #3851, games only use this texture type when they actually disable it. This texture type can be referenced during the shader generation but would typically end up in dead code, so it is harmless to silently return a 0. ~~Furthermore, it indeed returns 0 on real 3DS.~~
The behavior on 3DS is that Disabled texture would return the last texel color it fetched when it was not disabled. This is not possible to emulate in our current code.
All known texture type are handled so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3898)
=> swrasterizer, gl_shader_gen: return 0.0 for Disabled texture unit 0

src/citra_qt/debugger/console.cpp
There was a bug that on linux/macOS, opening and closing configuration window would duplicate all the following log. This is due to `ToggleConsole` being called and `Log::AddBackend` being called twice. This PR prevents log backend changing if the setting value hasn't been changed.
cc @jroweboy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3899)
=> citra_qt: only toggle console if the setting has been changed

.travis.yml
I don't know why this fixed it.
It seems that the gpg key is only added in this way.
Anyway, it is simpler and fixes the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3923)
=> Fix clang-format CI

CMakeModules/CopyCitraQt5Deps.cmake, appveyor.yml
This adds a lot of extra supported formats to qt.
MSVC:
Mingw:
The above pictures come from Appveyor builds of my repo.
pinging #3706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3891)
=> CI: add imageformats plugins

src/core/hle/service/apt/apt.cpp
3dbrew says it's capped to 0x300, so silently set it to 0x300 and let the code continue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3921)
=> Fix parameter_size in APT::GetStartupArgument

.travis.yml, .travis/common/post-upload.sh, .travis/linux-mingw/build.sh, .travis/linux-mingw/deps.sh, .travis/linux-mingw/docker.sh, .travis/linux-mingw/scan_dll.py, .travis/linux-mingw/upload.sh, CMakeModules/MinGWCross.cmake, appveyor.yml
As it was said before, this is precedent to the PR #3649 
This one maybe controversial, so I expect it will take time to be reviewed and merged.
There's a workaround in the build script, the reason it was here was that `libressl` module wasn't up-to-date in `citra` main repository.
Libraries used in this build:
Lib|Version
-----|-----
Qt 5 |5.9.6
SDL2 | 2.0.7
libsamplerate | 0.1.9
Test build download link is shown here: https://travis-ci.org/liushuyu/citra/jobs/373341674#L4134
The download speed maybe very slow, and it will be expired after 14 days (2018-05-13)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3706)
=> Use Travis CI to build MinGW packages

src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h, src/audio_core/dsp_interface.cpp, src/audio_core/dsp_interface.h, src/audio_core/null_sink.h, src/audio_core/sdl2_sink.cpp, src/audio_core/sdl2_sink.h, src/audio_core/sink.h, src/audio_core/sink_details.cpp, src/audio_core/sink_details.h, src/citra_qt/configuration/configure_audio.cpp, src/core/core.cpp, src/core/settings.cpp
1. Remove dead code.
1. We shouldn't have to construct a sink to get a device list.
1. Remove all references to `Settings`.
We also fix changing audio device at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3909)
=> sink_details: Tidy-up device listing code

CMakeLists.txt
Reverts citra-emu/citra#3773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3935)
=> Revert "CMake: Avoid non-compliant standard library extensions in MSVC"

src/citra_qt/configuration/configure_system.cpp
The "Console ID: " text is untranslated once you regenerate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3952)
=> configure_system: fix an untranslated text

src/audio_core/dsp_interface.cpp, src/audio_core/dsp_interface.h, src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/configuration/configure_audio.ui, src/core/hle/service/hid/hid.cpp, src/core/settings.h
This PR adds a volume slider to Citra, which uses a logarithmic scale. 
It also implements Hid:GetSoundVolume.
UI Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3831)
=> citra_qt: Add a volume slider

src/citra_qt/multiplayer/direct_connect.cpp, src/citra_qt/multiplayer/host_room.cpp, src/citra_qt/multiplayer/lobby.cpp
fix #3945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3947)
=> citra_qt: use Citra Web Service username as default multiplayer nickname

src/citra/config.cpp, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp
Also show an warning when turning it on.
This is because I've seen several issues/forum topics where users enabled hw shader on macos (or just used default settings) and got black screen.
AFAIK the option was left there for test/development purposes, but I think at least we can disable it by default and provide a warning when users turn it on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3946)
=> citra_qt: disable hw shader by default for macos

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h
This doesn't depend on class state at all, so this can be made internal. While we're at it, amend the function to take its arguments by const reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3958)
=> game_list: Make containsAllWords() a non-member function

src/citra_qt/game_list.cpp
QString initializes to an empty string by default, so this does nothing meaningful. While we're at it, use a constructor initializer list for initializing the gamelist member variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3957)
=> game_list: Remove unnecessary QString initialization in KeyReleaseEater

src/video_core/regs_texturing.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/swrasterizer/proctex.cpp
Parallel to #3910, this is the special mipmap mechanism for procedural texture. The mipmap look up happens at the last step of proctex: sampling the color map LUT. The color map works like a 1D texture with mipmap. Games uploads all mipmap levels to the LUT buffer and specifies the offsets for each level. However the last four offsets seem to be hardcoded, and the first four are also always 0, 0x80, 0xC0, and 0xE0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3916)
=> gl_rasterizer: implement mipmap for procedural texture

src/core/frontend/applets/swkbd.cpp, src/core/hle/applets/swkbd.cpp
While testing the latest revision, I encountered some problems with the software keyboard implementation (#3850).
Precisely, two problems :
- the input box show invalid characters 
- after validating input box, citra crash randomly ("double free or corruption")
For the first case, I don't understand why the Qt function fromStdString() would not do the job. I changed it for fromUtf8() since our labels are converted using Common::UTF16ToUTF8().
The second case, I could find it thanks to a warning coming from the compiler. Effectively, function SoftwareKeyboard::Finalize() was not returning a value in non-error path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3964)
=> Small fixes on software keyboard implementation

src/common/threadsafe_queue.h
This removes an issue where when you would cast MPSCQueue* to SPSCQueue* the multiple write thread safety isn't granted anymore.
Thx to @yuriks for catching the mistake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3973)
=> remove polymorphism issue

src/core/loader/loader.cpp
Previously for installed titles, the file type would be NCCH (assumed as CXI) and the extension would be ".app". This would trigger a warning of the file "having a different type than its extension", which is actually not true here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3978)
=> core/loader: avoid "different type" warning for .app

src/common/string_util.cpp
Being a wannabe Lioncash.
Note: according to cppreference it is necessary to convert char to unsigned char when using std::tolower and std::toupper, otherwise the behaviour would be undefined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3997)
=> common/string_utils: replace boost::transform with std counterpart

src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h, src/core/hle/service/service.cpp
This is a team effort by @Subv and me.
Our goal is to get a fully working implementation of the http service including ssl with all the certificates. At the moment we are planning to use httplib and [libressl](https://www.libressl.org/) (which is already in citra) for the communication. 
We decided to make small PRs for easy review. 
So this one implements:
- Initialize
- CreateContext
- CloseContext
- AddRequestHeader
There is still a lot of research left so for all parts where we currently don't know how it behaves we added asserts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3981)
=> Migrate HTTP_C to the ServiceFramework and implement functions

src/core/CMakeLists.txt, src/core/hle/service/ps/ps_ps.cpp, src/core/hle/service/ps/ps_ps.h, src/core/hle/service/service.cpp
While I was messing with the BOSS sysmodule, I needed to stub the PS service to get past the crash from there not currently being a PS service registered. I also needed to comment out the line in service.cpp, then it booted and was stable.
Not sure if this is needed. If it isn't, by all means, go ahead and close this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3999)
=> service/ps: Boilerplate to register service, no functions implemented

src/core/hle/service/apt/applet_manager.cpp
Currently LLE applets cannot exit properly in Citra and causes Citra to hang. We are already providing HLE for applets, and the LLE applets are preventing users who dumped their system files from using the applets correctly. Before the further fix is done, I think we should temporaily disable loading LLE applets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3991)
=> applet_manager: disable loading LLE applets

src/common/timer.cpp, src/common/timer.h
A part of fixing #3934 
This took advantage of the new `<chrono>` standard library. I have removed all platform dependent code and replaced some of them with platform independent ones. The signature changes do not really matter - it seems that no code has used this so far (at least that's what my IDE tell me..)
I also cleaned up the code a bit, replacing C-style type casts with static_cast.
This is my first time using the std::chrono library. Please check if there are any issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3972)
=> common/timer: use std::chrono, avoid platform-dependent code

src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/multiplayer/state.cpp, src/citra_qt/multiplayer/state.h, src/network/room_member.h
As the status bar does not have an UI file, it has to be manually retranslated by setting the text again.
I had to add a `Network::RoomMember::State` to provide the same behaviour ("Not Connected. Click here to find a room" by default, and "Not Connected" once you join a room and quit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3989)
=> citra_qt: retranslate status bar

src/core/hle/romfs.cpp, src/core/hle/romfs.h, src/core/hle/service/apt/apt.cpp
Since RomFS::GetFilePointer only returns a pointer to the start address of the file but not the size but this might be necessary I added that function and a class for storing both informations. 
We could probably drop GetFilePointer() and replace it with GetFile() but for now I left both versions in the code. Also if it gets necessary to add more information to the file it's trivial to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4007)
=> RomFS: add RomFSFile and RomFS::GetFile

src/citra_qt/main.cpp
Logging was inited after GMainWindow inits, but really we only need to do it after the config is created, so moving it after the first line of the constructor should get us the QT init logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4013)
=> citra-qt: Init logging sooner so we dont miss some logs on startup

src/citra_qt/main.cpp
When you change the language when a game is running, the "Continue" action in the "Emulation" menu would become "Start". This PR fixes the issue by checking and setting it if it should be "Continue". It seems that this is the only place with this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3990)
=> citra_qt: minor retranslation fix

src/citra_qt/configuration/configure_input.cpp
Previously, once you change language, the texts in the buttons in the Input tab will disappear. It is because the default text in the buttons are empty, and we did not update the text after translations are reloaded, aka texts are reset. This PR fixed the issue.
Again, one line diff took 4 lines of description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3986)
=> citra_qt/configuration: fix input configuration disappearing after changing languages

src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.h, src/citra_qt/configuration/configure_system.ui, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h
This adds country selection to the System tab.
Tested in Pokemon (UM). This indeed changed the country.
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3951)
=> service/cfg, citra_qt: add country code configuration

src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/chat_room.h
@adityaruplaha says such feature is needed, and @wwylele suggested it
This is an example GIF
Note that the GIF was recorded on a earlier version of the code and now I have added a question to explain what a Block is and confirm they want to block the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3988)
=> citra_qt/multiplayer: allow blocking other players in chat room

src/core/hle/ipc.h, src/core/hle/service/frd/frd.h, src/core/hle/service/service.cpp, src/core/hle/service/service.h
Just deletes unused stuff. Closes #2531.
`GetCommandBuffer` is not removed because it is still used by svc and HLE command buffer translation, and removing it requires some large refactor there. This is put to later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4014)
=> service: remove deprecated service interface

src/citra_qt/configuration/configure_dialog.cpp
It was really a stupid mistake..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4046)
=> citra_qt/configuration: retranslate camera tab

src/citra_qt/CMakeLists.txt
This got rid of a warning of CMake Policy CMP0071 not set. In fact, setting it to either OLD or NEW is same for Citra (I tested on MSVC and MinGW), and the OLD option is deprecated, so I am using NEW here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4011)
=> citra_qt/CMakeLists: get rid of a warning

src/video_core/swrasterizer/lighting.cpp
Software rasterizer version of #3904
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4040)
=> swrasterizer/lighting: remove newline in logging macro

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h
This intends to workaround #3962 by introducing vender-specific configuration. The vendor string is got from [dolphin source code](https://github.com/dolphin-emu/dolphin/blob/cddc2d52c22b42773bbb65a9255cceb90982f531/Source/Core/VideoBackends/OGL/Render.cpp#L183) and verified against citra telemetry data (though there is no "Advanced Micro Devices, Inc." observed)
@greasythemattis could you test if this fixes your issue?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4042)
=> gl_rasterizer: apply AMD hack only when the vendor is AMD

src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.h, src/citra_qt/configuration/configure_graphics.ui
This is actually very easy to do. I added a label and a push button for it, and used the Qt standard dialog QColorDialog for picking colors.
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4047)
=> citra_qt/configuration: Add background color config

src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.ui, src/citra_qt/hotkeys.cpp, src/citra_qt/hotkeys.h
The hotkey widget has a separate class defined for it, and qt cannot automatically retranslate it when retranslateUi is called. This commit explicitly calls the function to retranslate the hotkey dialog.
Side note: the name for the hotkey dialog widget: "widget" is too bad, so I changed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3987)
=> citra_qt/configuration: retranslate hotkey widget on language change

src/citra_qt/main.cpp, src/citra_qt/main.ui
Hotkey is F5
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3902)
=> citra_qt: add restart hotkey & menu option

src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/config.h
This is to fix #3531.
Design:
1. When a setting does not has a default value, it is stored in the same way as before. (Simple QSettings  entry)
1. When a setting has a default value, it is separated into two entries: `xxxxx\default` and `xxxxx`. If `xxxxx\default` = true, it means that the setting is using its default value, and when the configuration is loaded, the setting will be automatically replaced with the new default value (if any). The `xxxxx` entry stores the setting value, however it is only used when `xxxxx\default` = false. See the `ReadSetting` and `WriteSetting` functions for more detail.
1. In this way the new config file will be compatible with the old file.
1. I did not make any changes to the core/settings part. It remained as-is.
Advantages:
1. We can tell if a user is …
=> citra_qt: Settings (configuration) default value fix

src/citra/default_ini.h
I discovered this while making changing background color.. Just a minor nit.
Do not look at the branch name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4051)
=> citra: default_ini bg color default value fix

CMakeLists.txt, src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/core/settings.h, src/input_common/CMakeLists.txt, src/input_common/main.cpp, src/input_common/sdl/sdl.cpp, src/input_common/sdl/sdl.h, src/input_common/udp/client.cpp, src/input_common/udp/client.h, src/input_common/udp/protocol.cpp, src/input_common/udp/protocol.h, src/input_common/udp/udp.cpp, src/input_common/udp/udp.h
An implementation of the cemuhook motion/touch protocol, this adds the ability for users to connect several different devices to citra to send direct motion and touch data to citra. For more information on the available motion servers see https://cemuhook.sshnuke.net/padudpserver.html
As seen in issues like #4048, the current motion controls are rather unwieldy to use, often being to hard to figure out exactly where to move the cursor to get the kind of tilt you want. Using a real device for motion controls is simply much more intuitive and will be an all around better experience for users.
I chose to use this protocol because there really isn't many other options. It already has good device support, and since it uses UDP, it works on just about anything with a network stack and allows …
=> Input: UDP Client to provide motion and touch controls

src/citra_qt/main.cpp, src/citra_qt/main.h
I had to edit a bit of the Restart action so that it does not go wrong because recent files are cleared.
Screenshot:
Fix #4055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4056)
=> citra_qt: add Clear Recent Files menu action

src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h
Use the session data to store information about the HTTP session state.
This is based on reverse engineering of the HTTP module.
~~The AddRequestHeader function is still mostly incorrect, this will be fixed in follow up PRs~~
AddRequestHeader's behavior has been corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4001)
=> Services/HTTP: Corrected some error codes and added a few new ones.

src/core/CMakeLists.txt, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_selfncch.cpp, src/core/file_sys/archive_selfncch.h, src/core/file_sys/ivfc_archive.cpp, src/core/file_sys/ivfc_archive.h, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/file_sys/romfs_reader.cpp, src/core/file_sys/romfs_reader.h, src/core/hw/aes/key.cpp, src/core/hw/aes/key.h, src/core/loader/3dsx.cpp, src/core/loader/3dsx.h, src/core/loader/loader.h, src/core/loader/ncch.cpp, src/core/loader/ncch.h
We originally wanted to have VFS first before implementing this. I now have a different idea about it, and currently agree more on the "abstract only when needed" philosophy: if we build up VFS class hierarchy before implementing real features, we might end up with a bunch of over-abstracted useless structure that we don't need for the finite problem we want to resolve, which might have been grown to simpler code if we only abstract on the need. So I want to start from implementing real thing, and start abstraction from where it needs change.
`RomFSReader` is introduced to represent a RomFS file that can be either encrypted or decrypted, which replaces the original `IOFile + offset + size` parameter passing.
----
The keys should be provided by user via `sysdata/aes_keys.txt`, as it is in …
=> ncch_container: support encrypted games

src/core/hle/service/am/am.cpp
Instead of falling back on content ID 0, an empty path should be returned so the file fails to open and proper error codes are returned. The bounds of ListDLCContentInfos have also been fixed so that it won't attempt to go past the end of the list when start_index is non-zero.
This may help with https://github.com/citra-emu/citra/issues/4029 based on the log output, but I haven't tested it myself as I don't own the game in question.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4053)
=> am: Corrections to handling of non-existent content indices.

src/common/file_util.h
Please refer to yuzu-emu/yuzu#967 for details.
**Caution! This PR had cherry-pick conflicts while being generated.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4061)
=> Port "file_util: Avoid sign-conversions in WriteArray() and ReadArray()" from yuzu

src/citra_qt/main.cpp
Manually ported - blame the folder name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4066)
=> Port "qt/main: Collapse if statement in UpdateRecentFiles()" from yuzu

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/config.cpp, src/citra_qt/debugger/lle_service_modules.cpp, src/citra_qt/debugger/lle_service_modules.h, src/citra_qt/main.cpp, src/citra_qt/main.h, src/core/hle/service/service.cpp, src/core/hle/service/service.h, src/core/settings.h
Allows developers to easily toggle low level emulation of installed service modules.
As requested by @Subv 
```[Debugging]
use_gdbstub=false
gdbstub_port=24689
LLE\SSL=false
LLE\AC=false
LLE\AM=false
LLE\CDC=true
LLE\ACT=false
LLE\CAM=false
etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3967)
=> citra-qt: service: add convenient LLE service module configuration

src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_ncch.h, src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h, src/core/hw/aes/key.h
This will decrypt the ClCartA romfs to provide the default Client Cert and Private Key for the http_c module. This happens in the ctor of HTTP_C to only decrypt once and then provide it every time OpenDefaultClientCertContext is called.
For now the certs aren't used since OpenDefaultClientCertContext isn't implemented yet. This will happen in a follow up PR. 
For citra to make use of that and to allow to connect to some Nintendo URLs those client certs are necessary. They needed to get dumped from title id 0004001b00010002 and the normalkey in keyslot 0x0D (The SSLkey) must be provided in the aes_keys.txt: `slot0x0DKeyN=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF `
(replacing the FFFFs with the actually key)
--- …
=> Service::HTTP_C: Add decryption of the ClCertA

src/core/core_timing.cpp, src/core/core_timing.h
Please refer to yuzu-emu/yuzu#932 for details.
**Caution! This PR had cherry-pick conflicts while being generated.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4079)
=> Port "core_timing: Use transparent functors where applicable" from yuzu

src/citra_qt/main.cpp
ported manually - blame the folder name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4076)
=> qt/main: Better file-existence checking within OnMenuRecentFile() and UpdateUITheme()

src/core/core_timing.cpp, src/core/core_timing.h, src/core/perf_stats.cpp, src/core/perf_stats.h
Please refer to yuzu-emu/yuzu#934 for details.
**Caution! This PR had cherry-pick conflicts while being generated.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4078)
=> Port " core_timing: Make GetGlobalTimeUs() return std::chrono::microseconds" from yuzu

src/input_common/udp/protocol.cpp
If Citra is used without a UDP server running, Citra will receive invalid packets, and an error will be logged. This PR changes this log message to *Debug*, because if a UDP server really isn't being used, then it isn't an error.
Fixes  #4095.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4096)
=> udp: Change invalid packet message to Debug

src/citra_qt/main.cpp, src/citra_qt/main.h
Changed a few texts that are not so good in the UI according to @neobrain.
This should just be a Part 1.
1. Users do not read long text, so text should be as simple and short as possible
1. Title should be in title case, and should not be sentences
1. Provide some help/action for the users. For example I guided users to redump their games when the ROM is invalid, instead of just displaying the error message.
1. Text too long.
1. Not actionable.
1. opt-out, not opt-in. 
although 2 and 3 seems to be @bunnei's design
1. Text too long.
1. Icon not proper.
1. Text too long.
1. Icon not proper.
1. No guidance on how to solve the problem.
1. Title is not in title case.
1. Users would not know what is "system mode"
1. No guidance on how to solve the problem
1. Title is not in title case.
Similar …
=> citra_qt: UI text improvements

src/citra_qt/debugger/lle_service_modules.cpp
Gets rid of a qt error similar to `QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x55c3d1c98b00 'Toggle LLE Service Modules;` that occurs when Citra is closed.
introduced by #3967
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4099)
=> citra_qt: set object name for LLEServiceModulesWidget

src/citra_qt/configuration/config.cpp
Reverts citra-emu/citra#4109
@B3n30 requesting permission to revert this.
Discussion: on the matter  https://i.imgur.com/K8MGdDD.png and https://i.imgur.com/mH4Ctir.png
(also good job creating the branch on this repo instead of my fork, github...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4110)
=> Revert "Set Discord Rich Presence "OFF" by default"

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/loader/3dsx.cpp, src/core/loader/elf.cpp, src/core/loader/ncch.cpp
See yuzu-emu/yuzu#914 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4123)
=> Port #914 from yuzu: "kernel/process: Use accessors instead of class members for referencing segment array"

src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_dialog.h, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.h, src/citra_qt/hotkeys.cpp, src/citra_qt/hotkeys.h, src/citra_qt/main.cpp, src/citra_qt/main.h
See yuzu-emu/yuzu#950 for more details.
To make things easier, it would be nice to get this merged before #3786. Otherwise rebasing this PR and porting Adits to yuzu will be a huge PITA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4137)
=> Port #950 from yuzu: "qt/hotkey: Get rid of global hotkey map instance"

src/citra/citra.cpp, src/citra_qt/configuration/config.cpp, src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/main.ui, src/citra_qt/ui_settings.h, src/core/core.cpp, src/core/movie.cpp, src/core/movie.h, src/core/settings.h
This got rid of the settings abuse, and I have kinda refactored the core/movie module, now it more looks like a separate module instead of a submodule of System. I also added some validation and message boxes.
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3922)
=> movie: Add Qt Movie feature

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.h, src/citra_qt/configuration/configure_system.ui, src/core/core.cpp, src/core/core.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/memory.cpp, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/shared_page.cpp, src/core/hle/shared_page.h, src/core/settings.h, src/tests/core/memory/memory.cpp
This is take two based on #3507. I hope I addressed all the comments 
This adds the possibility to set a fixed time for the emulated GetSystemTime.
It also synchronises the advance of the clock with the executed ticks like mentioned in #1963
Options are provided for SDL and for qt the settings are added to the config dialog.
I didn't add new screenshots since the one from the old PR are still how it looks like.
Minor design change: I had to add a SharedPage handler class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4043)
=> Add system time configuration

src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.ui, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/configuration/configure_motion_touch.h, src/citra_qt/configuration/configure_motion_touch.ui, src/common/thread.h, src/input_common/main.cpp, src/input_common/main.h, src/input_common/udp/client.cpp, src/input_common/udp/client.h, src/input_common/udp/udp.cpp, src/input_common/udp/udp.h
These functions include reloading udp client, testing communication and configuring calibration. I also added a function to common/thread.h to use WaitFor.
Implemented a Motion/Touch... configuration dialog. Users can open this dialog by clicking a button on the Input tab. The dialog also includes CemuhookUDP server config and communication testing, and the touchpad calibration config.
I had no time to provide a screenshot now, but I will add one soon
UPD: Screenshot
Note: Touchpad calibration configuration is not easy to finish according to @jroweboy. I do not have a better idea for this currently though. Probably add a dialog about the process?
--- …
=>  citra_qt: add motion/touch config

src/citra/citra.cpp, src/citra_qt/main.cpp, src/core/core.cpp, src/core/core.h, src/core/settings.cpp, src/video_core/renderer_base.cpp, src/video_core/renderer_base.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/video_core.cpp, src/video_core/video_core.h
See yuzu-emu/yuzu#892 for more details.
Please note I needed to add an additional` GetRenderWindow()` function in order for `GetResolutionScaleFactor()` to still work correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4126)
=> Port #892 from yuzu: "Make global EmuWindow instance part of the base renderer class"

src/core/telemetry_session.cpp
See yuzu-emu/yuzu#1126 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4162)
=> Port yuzu-emu/yuzu#1126 from yuzu: "Don't allocate std::string instances for program lifetime in GetTelemetryId() and RegenerateTelemetryId()"

src/common/logging/backend.cpp
See yuzu-emu/yuzu#1060 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4156)
=> Port #1060 from yuzu: "logging/backend: Use const reference to refer to log filter"

src/core/file_sys/ncch_container.cpp
We currently receive a lot of reports from users with the log just showing
`[   0.806359] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   0.806604] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
[   0.806612] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:275: Failed to decrypt
[   0.806636] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   0.806643] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
[   0.806652] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:275: Failed to decrypt
[   0.808210] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing`
To help debug this I added a line that logs the …
=> NCCH_Container: Add file_path log to Load()

src/video_core/renderer_opengl/gl_shader_gen.cpp
This change to floor() was made in 2927c88 (#3916) (from https://github.com/citra-emu/citra/pull/3916/files#diff-21b620fbb9c59667998f26b07834ff81L1183 to https://github.com/citra-emu/citra/pull/3916/files#diff-21b620fbb9c59667998f26b07834ff81R1160) , which was a result of doing some hwtest. It turned out that it was buggy edge cases in PICA, and for most cases round() still applies. Revert back to round to make it work for most common cases.
Fixes #4150. @suppaflie could you test to see if this also fixes #4103 ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4174)
=> gl_rasiterzer/proctex: revert back to round() for Nearest sampling

src/core/hle/service/sm/srv.cpp, src/core/hle/service/sm/srv.h
This wasn't necessary for HLE services but the run multiple LLE services it is.
There is no timeout for the wait, similar to a real 3ds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4069)
=> Service::SM: Wait till client is registered

src/citra_qt/main.cpp, src/core/core.h, src/core/hle/service/apt/apt.cpp
Shared fonts is no different from any other system archives, and there is not really any point to make a separate status for it. This also fixes the incorrect error message that was introduced when I made the UI text improvements.
The incorrect error message:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4143)
=> core, citra_qt: unify status of system archives and shared fonts

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/core/announce_multiplayer_session.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/dedicated_room/citra-room.cpp, src/web_service/web_backend.cpp
This PR aims to unify the links for web service endpoints into one. 
All links for the respective features like telemetry, rooms, etc. are then directly hardcoded in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4138)
=> web_service: Unify links for web service endpoints

src/citra_qt/configuration/configure.ui, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_dialog.h
Screenshot:
The specific grouping might still be suboptimal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4187)
=> Qt/Configure: Use sidebar to divide tabs into smaller groups

src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h, src/audio_core/dsp_interface.cpp, src/audio_core/dsp_interface.h, src/audio_core/null_sink.h, src/audio_core/sdl2_sink.cpp, src/audio_core/sdl2_sink.h, src/audio_core/sink.h, src/audio_core/time_stretch.cpp, src/audio_core/time_stretch.h, src/common/CMakeLists.txt, src/common/ring_buffer.h
We simplify the sink interface so it's just a callback now. We also do now do all audio processing in one place instead of duplicating code between the sinks.
Changes made:
* Added a proper lock-free audio FIFO.
* Simplify audio-stretching related code.
* Audio-stretching now occurs on the audio thread and not the emulation thread.
* Reduced popping upon underflow.
* Perform volume adjustment on audio thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4194)
=> audio_core: Simplify sink interface

CMakeLists.txt
Set citra-qt project as default StartUp Project in Visual Studio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4214)
=> Set citra-qt project as default StartUp Project in Visual Studio

src/core/hle/service/soc_u.cpp
RecvFrom currently crash immediately when App call `recv` method ( buffsize < 0x2000 )
Because of `HLERequestContext::WriteToOutgoingCommandBuffer` -> `StaticBuffer` failed on
`ASSERT_MSG(target_descriptor.size >= data.size(), "Static buffer data is too big");`
so i resize `addr_buff` to 0 when recvfrom return error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4113)
=> fix soc service - RecvFrom - SendTo

src/audio_core/cubeb_sink.cpp
See yuzu-emu/yuzu#1321 for more details.
Original description: `The parameter of the lambda was shadowing the variable that was being assigned to.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4248)
=> Port yuzu-emu/yuzu#1321: "cubeb_sink: Get rid of variable shadowing within CubebSink's constructor"

src/audio_core/time_stretch.cpp
See yuzu-emu/yuzu#1314: for more details.
Original description: `The SoundTouch API only accepts uint amount of samples.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4247)
=> Port yuzu-emu/yuzu#1314: "audio_core/time_stretch: Silence truncation warnings in Process()"

dist/scripting/citra.py
Just a small style change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4226)
=> citra.py: use IntEnum for request types

.gitattributes
Github Linguist will read this file when calculating language stats for
the repository. We can use this to exclude any vendored dependencies in
externals and dist
This should keep github from thinking the project is 50% C code (thanks to the shared_font.h)
see https://github.com/github/linguist#overrides for more information
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4258)
=> Meta: Add gitattributes file

src/core/hle/function_wrappers.h
See yuzu-emu/yuzu#1346 for more details.
Original description: `This can just be a regular function, getting rid of the need to also
explicitly undef the define at the end of the file. Given FuncReturn()
was already converted into a function, it's #undef can also be removed.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4246)
=> Port yuzu-emu/yuzu#1346: "svc_wrap: Convert the PARAM macro into a function"

.travis/linux/upload.sh, .travis/macos/upload.sh, CMakeLists.txt
Much cleaner than having executables in ``$BUILD_DIR/src/foo/foo``.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4263)
=> cmake: Output binaries to bin on every platform

src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.h, src/citra_qt/configuration/configure_system.ui, src/core/hle/service/ptm/ptm.cpp, src/core/hle/service/ptm/ptm.h
Screenshot:
This allows setting play coins when game is running. It is a potential race condition, but should rarely be an issue, and I've left a TODO there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4209)
=> service/ptm, citra_qt: Add Play Coins setting

src/core/hle/kernel/object.h, src/core/hle/kernel/wait_object.h
See yuzu-emu/yuzu#1412 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4280)
=> Port yuzu-emu/yuzu#1412: "kernel/object: Remove unnecessary std::move from DynamicObjectCast()"

src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h
Implements:
- HTTP_C::OpenClientCertContext
- HTTP_C::OpenDefaultClientCertContext
- HTTP_C::CloseClientCertContext
Behavior and error codes from testing with hombrew and dissasembly 
This also adds a session_id to SessionData, Context, RootCertChain, RootCACert, and ClientCert
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4072)
=> Service::HTTP_C: Implement Client Cert opening and closing

src/citra/citra.cpp, src/citra_qt/configuration/configure_web.cpp, src/citra_qt/configuration/configure_web.h, src/citra_qt/main.cpp, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/lobby.h, src/common/CMakeLists.txt, src/common/announce_multiplayer_room.h, src/common/detached_tasks.cpp, src/common/detached_tasks.h, src/core/announce_multiplayer_session.cpp, src/core/announce_multiplayer_session.h, src/core/telemetry_session.cpp, src/core/telemetry_session.h, src/dedicated_room/citra-room.cpp, src/web_service/announce_room_json.cpp, src/web_service/announce_room_json.h, src/web_service/telemetry_json.cpp, src/web_service/telemetry_json.h, src/web_service/verify_login.cpp, src/web_service/verify_login.h, src/web_service/web_backend.cpp, src/web_service/web_backend.h
This is a rework of web_backend and all related service (telemetry, login verification and lobby). The old code has the following issue:
- std::future + callback abuse. This was historically introduced to incorporate cpr's API style, but since we changed the library to httplib, this is unnecessary and only leave a bunch of problems:
- abuse callback for side effect such as UI prompt. The typical view of std::future is a deferred maybe / monad, and the design of cpr's callback API is only a compensation for missing `std::future::then()`, meaning that the callback is intended to be a pure function to do result transformation. Although std::future does guarantee when the task is executed to some degree, by specifying the `policy` bit in `std::async` in the implementation, this is not …
=> web_service: stop using std::future + callback style async

.travis/macos/build.sh
OSX doesn't ship updates for the stdlibc++ for older OSX versions. So as we start to use features in new libs those builds won't work anymore on older systems. Our CI runs on osx 10.13 with XCode 10 so any system that doesn't have the recent updates won't work with citra.
The first time we introduced such issue was with #4194. The usage of alignas there isn't supported by systems below 10.13. 
For now the easiest fix is to don't support those old systems. Systems not supported anymore are:
- iMac manufactured late 2009 or later
- MacBook manufactured late 2009 or later
- MacBook Pro manufactured mid 2010 or later
- MacBook Air manufactured late 2010 or later
- Mac Mini manufactured mid 2010 or later
- Mac Pro manufactured mid 2010 or later
Other solutions to that issue:
2. Don't use such …
=> OSX: Set MACOSX_DEPLOYMENT_TARGET to 10.13

src/core/arm/dynarmic/arm_dynarmic.cpp
Allow gdbstub to handle execution breakpoints when JIT is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4276)
=> arm_dynarmic: Pass breakpoints to gdbstub

src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h, src/citra_qt/configuration/configure_input.ui, src/common/param_package.cpp, src/common/param_package.h
Ref: #3953
Implemented some of the features mentioned in that issue.
* Added a context menu on the buttons including Clear & Restore Default
* Allow clearing (unsetting) inputs. Added a Clear All button
* Allow restoring a single input to default (instead of all)
* Bind all: not implemented. It's harder than it sounds and I do not know if that's really useful.
* Highlight input conflicts: #3786 already prevents binding keys to multiple inputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4140)
=> citra_qt/configuration: misc input tab improvements

src/citra_qt/configuration/configure_system.cpp, src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_extsavedata.h, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h, src/core/hle/service/fs/archive.cpp, src/core/hle/service/ptm/ptm.cpp
Similar to #4277
I put these two together because they can decouple the FS dependency in Qt configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4278)
=>  cfg, ptm: access FS via backend directly 

src/citra/citra.cpp
More grammatically correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4291)
=> Slightly changed wording of LOG_ERROR statements.

src/core/hle/service/am/am.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h
FS subfiles are created with File::OpenSubFile, they have a start offset that must be added to all read/write operations.
The implementation in this commit is done using a new FileBackend that wraps the FS::File along with the start offset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4287)
=> Services/AM: Support using FS subfiles with the CIA-related service functions.

src/core/hle/kernel/client_port.h, src/core/hle/kernel/server_port.h, src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
This allows frontends to access hle service interfaces e.g to change their state. ATM NFC is waiting for that change, but there might be other parts, too.
the usage (e.g. for NFC) would be: 
```
auto sm = system.ServiceManager(); 
if (sm != nullptr) { 
std::shared_ptr<Service::NFC::Module::Interface> nfc = sm->GetService("NFC");
if(nfc != nullptr) { 
...
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4296)
=> Give frontend access to the hle service interfaces

src/common/swap.h, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_selfncch.cpp, src/core/hle/applets/swkbd.cpp, src/core/hle/applets/swkbd.h, src/core/hle/service/ldr_ro/cro_helper.h, src/core/hle/service/nwm/uds_connection.cpp, src/core/hle/service/nwm/uds_connection.h, src/core/hle/service/nwm/uds_data.cpp, src/core/hle/service/nwm/uds_data.h
There has been an issue that `enum` types cannot be specified with endianness like other integer types. This PR fixes the problem by providing `enum_le`/`enum_be` template types. The expected usage is as follows:
```
enum class TypeA : u32 {
...
};
...
struct StructInGuestMemory {
u32_le some_member;
enum_le<TypeA> enum_member;
...
};
TypeA GetA() {
StructInGuestMemory s;
std::memcpy(&s, <guest memory>)
return s.enum_member;
}
```
This template is only used where the underlying memory is copied from/to guest memory using `std::memcpy` or its equivalent (the same rule as other `u32_le`-like type)
I also ensured that the `_be` version can be compiled in different cases by swapping the definition of `enum_le` and `enum_be` in the code.
--- …
=> common/swap: add swap template for enum

src/citra_qt/game_list.cpp
Reverts citra-emu/citra#4241
> So eh... I looked into the current transifex push failure
> which is related to the plurals
> I think the introduction of plurals broke the current transifex+qt update model a little bit...
> The problem is like this
> To fully support plurals, Qt requires loading the "translation" of the source language (english) as well, which should contains man-made translations, say, "result" and "results" (no, qt doesn't automatically generates them)
> The current model assumes that the english translation is a no-op and the en.qm file doesn't need to be loaded (and shouldn't, as qt has a bug/feature that loading an empty qm file return failure https://bugreports.qt.io/browse/QTBUG-31031 (fixed in alpha version))(edited)
> and transifex probably does not accept a …
=> Revert "Port yuzu/#1367 from yuzu: "game_list: Handle plurals within setFilterResult() better""

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/game_list_p.h, src/citra_qt/main.cpp, src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_extsavedata.h, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/loader/loader.h, src/core/loader/ncch.cpp, src/core/loader/ncch.h
* "Open Save Data Location" is now hidden when the folder does not exist.
* "Open Application Location" is now only shown when the item is the Installed game. (If you have both the Installed and the file version of a game, the action is only shown for the Installed one)
* "Open Update Data Location" is now hidden when the folder does not exist.
* "Open Extra Data Location" is added. It is not shown for system titles. It is hidden when the folder does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4229)
=> citra_qt, core: game list "Open XXX Location" improvements

src/citra/citra.cpp, src/citra_qt/main.cpp, src/core/hle/shared_page.cpp, src/core/movie.cpp, src/core/movie.h
This adds a clock init time field to the CTM header. The clock settings would be overridden when playing a movie. And when recording a movie, if the clock is set to System Time, it would be set to fixed init time at the current moment as well. In this way this keeps consistency with the RNG even if the user does just no setting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4267)
=> movie: Add clock init time to CTM header

CONTRIBUTING.md
Apparently it's not true: https://github.com/citra-emu/citra/pull/4310#discussion_r223174725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4313)
=> CONTRIBUTING.md - remove note about casting numeric types

src/audio_core/time_stretch.cpp
See yuzu-emu/yuzu#1376 for more details.
`This function is called too many times and makes the debug logging basically unusable due to the spam.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4317)
=> Port yuzu-emu/yuzu#1376: "Logging: Change the TimeStretch::Process log from debug to trace level."

src/common/logging/text_formatter.cpp
See yuzu-emu/yuzu#1442 for more details.
`operator+ for std::string creates an entirely new string, which is kind
of unnecessary here if we just want to append a null terminator to the
existing one.
Reduces the total amount of potential allocations that need to be done
in the logging path.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4316)
=> Port yuzu-emu/yuzu#1442: "Avoid unnecessary string temporary creation in PrintMessage()"

src/citra_qt/configuration/configure_general.cpp, src/citra_qt/ui_settings.cpp, src/citra_qt/ui_settings.h
See yuzu-emu/yuzu#1440 for more details.
Original description: 
`Placing the array wholesale into the header places a copy of the whole
array into every translation unit that uses the data, which is wasteful.
Particularly given that this array is referenced from three different
translation units.
This also changes the array to contain pairs of const char*, rather than
QString instances. This way, the string data is able to be fixed into
the read-only segment of the program, as well as eliminate static
constructors/heap allocation immediately on program start.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4314)
=> Port yuzu-emu/yuzu#1440: "ui_settings: Place definition of the theme array within the cpp file"

src/citra_qt/camera/qt_multimedia_camera.cpp
Forces camera pixel format to RGB565
Before:
After:
Fixes #4200 & #4148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4242)
=> Fix camera on Linux

src/core/CMakeLists.txt, src/core/file_sys/ncch_container.cpp, src/core/file_sys/seed_db.cpp, src/core/file_sys/seed_db.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/fs/fs_user.h
This PR implements SeedDB, Seed Crypto and FS AddSeed & GetNumSeeds functions.
SeedDB.
Format:
- Number of seeds in the SeedDB (u32)
- Padding (12 bytes)
- Seeds (format below)
- Title ID (u64)
- Seed data (16 bytes)
- Reserved data (8 bytes)
Nightly:
This PR:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4283)
=> Implement SeedDB & Seed Crypto

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/main.cpp
fixes several errors while installing multiple CIAs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4284)
=> citra-qt: disable directory watcher during CIA installation

src/citra/emu_window/emu_window_sdl2.cpp, src/citra/emu_window/emu_window_sdl2.h, src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h
Fixes #1437.
In both SDL and Qt, this will fix how Citra behaves when it's interacted with using a touchscreen.
In Qt only, using multiple fingers (multi-touch) will make the average position of them be sent to the emulation, making it behave exactly like a real 3DS. In SDL, this is trickier to implement, so what happens instead is that the last finger to move is detected. This doesn't really matter, because users shouldn't be using multi-touch in the first place.
In the process, it improves some mouse input code (DRY), and fixes a minor bug where dragging the mouse from the touchscreen to the left of the emulator window or above it would make the touch be registered at the right or bottom of the touchscreen.
I've tested on a Windows 10 laptop with a built-in touchscreen.
This is my first …
=> Handle touch input

src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/chat_room.h, src/citra_qt/multiplayer/client_room.cpp, src/citra_qt/multiplayer/client_room.h, src/citra_qt/multiplayer/direct_connect.cpp, src/citra_qt/multiplayer/direct_connect.h, src/citra_qt/multiplayer/host_room.cpp, src/citra_qt/multiplayer/host_room.h, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/lobby.h, src/citra_qt/multiplayer/state.cpp
These dialogs are only hidden when closed and currently will not be retranslated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4326)
=> citra_qt/multiplayer: retranslate multiplayer dialogs

src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/main.ui, src/core/hle/service/nfc/nfc.cpp, src/core/hle/service/nfc/nfc.h, src/core/hle/service/nfc/nfc_m.cpp, src/core/hle/service/nfc/nfc_u.cpp
This PR adds the ability to use "virtual Amiibo" files to emulate the scanning of them. 
Currently no keys are needed cause the encrypted sections are not accessed.
UI screenshot:
Example:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4333)
=> nfc: Add Amiibo support

src/citra_qt/main.cpp
See yuzu-emu/yuzu#1487 for more details.
`Depending on whether or not USE_DISCORD_PRESENCE is defined, the "state"
parameter can be used or unused. If USE_DISCORD_PRESENCE is not defined,
the parameter will be considered unused, which can lead to compiler
warnings. So, we can explicitly mark it with [[maybe_unused]] to inform
the compiler that this is intentional.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4343)
=> Port yuzu-emu/yuzu#1487: "Apply the [[maybe_unused]] attribute to the parameter of SetDiscordEnabled()"

src/input_common/sdl/sdl_impl.cpp
This adds two features to the joystick code:
1. Events from joysticks will now get registered even if citra isn't in focus
2. Analog axis can have a deadzone. There is no gui for setting it yet. Adding a deadzone can be done via the config inis, e.g.:
`circle_pad="port:0,guid:050000005769696d6f74652028303000,axis_x:0,axis_y:1,engine:sdl,deadzone:0.5"`
the deadzone needs to be: `0.0 <= deadzone < 1.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4193)
=> Joystick: Allow for background events; Add deadzone to SDLAnalog

src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure.ui, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.h, src/citra_qt/configuration/configure_general.ui, src/citra_qt/configuration/configure_ui.cpp, src/citra_qt/configuration/configure_ui.h, src/citra_qt/configuration/configure_ui.ui, src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/game_list_p.h, src/citra_qt/main.cpp, src/citra_qt/ui_settings.h
This adds a Game List configuration group box which is similar to yuzu's, with features including icon size setting, row 1/2 text, and ability to hide invalid titles (those without a valid SMDH). I also added a UI tab and moved the language and theme settings there.
Screenshot:
(Icon size set to Small, row 1 set to Title Name and row 2 set to Title ID)
(The new UI tab)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4259)
=> citra_qt: Add Game List configuration

src/citra_qt/configuration/configure_system.cpp, src/core/frontend/applets/swkbd.cpp, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/apt/apt.cpp, src/core/hle/service/cam/cam.cpp, src/core/hle/service/cam/cam.h, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/hle/service/ir/ir.cpp, src/core/hle/service/ir/ir.h, src/core/loader/ncch.cpp, src/core/settings.cpp
This removes some global weak_ptr<Module> in CFG, CAM, HID, and IR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4328)
=> remove GetCurrentModule() functions in HLE Services

src/common/logging/backend.cpp, src/common/logging/backend.h, src/common/threadsafe_queue.h, src/core/rpc/rpc_server.cpp, src/core/rpc/rpc_server.h, src/core/rpc/server.cpp, src/core/rpc/zmq_server.cpp
This adds a way to wait until the SPSCQueue / MPSCQueue isn't empty anymore. I didn't add a WaitFor and WaitUntil yet, but this can be easily added if necessary.
For now there is only one instance where this gets used (logging) but scripting (#4016) should also use it. This also assures that Wait isn't ended spuriously.
@jroweboy @EverOddish : What's your opinions on that?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4197)
=> threadsafe_queue: Add PopWait and use it where possible

src/citra_qt/main.cpp
See yuzu-emu/yuzu#1490 for more details.
```
We can utilize QStringList's join() function to perform all of the
appending in a single function call.
While we're at it, make the extension list a single translatable string
and add a disambiguation comment to explain to translators what %1
actually is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4338)
=> Port yuzu-emu/yuzu#1490: "citra_qt/main: Simplify OnMenuLoadFile()"

src/citra_qt/CMakeLists.txt
See yuzu-emu/yuzu#1543.
`Keeps the definition constrained to the citra_qt target and prevents
polluting anything else in the same directory (should that ever happen).
It also keeps it consistent with how the USE_DISCORD_PRESENCE definition
is introduced below it.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4360)
=> Port yuzu-emu/yuzu#1543: "CMakeLists: Use target_compile_definitions instead of add_definitions to define CITRA_ENABLE_COMPATIBILITY_REPORTING"

src/audio_core/cubeb_sink.cpp
We already ignore them on listing devices. We should do the same when selecting devices. This fix a crash when opening a specific device while there is a null device in the list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4367)
=> cubeb_sink: ignore null-name device when selecting

src/core/core.cpp, src/core/core.h, src/core/file_sys/archive_savedata.cpp, src/core/file_sys/archive_selfncch.cpp, src/core/hle/kernel/handle_table.cpp, src/core/hle/kernel/handle_table.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/ipc.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/shared_memory.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/timer.cpp, src/core/hle/kernel/timer.h, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/cecd/cecd.cpp, src/core/hle/service/cecd/cecd.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/service.cpp, src/core/memory.cpp, src/tests/core/arm/arm_test_common.cpp, src/tests/core/arm/arm_test_common.h, src/tests/core/hle/kernel/hle_ipc.cpp
Global state elimination for kernel: part 2. 
Functional change: make handle table per-process (as it is in real 3DS), plus a minor fix in `Thread::Stop()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4358)
=>  kernel: Eliminate global state in process and handle_table

CMakeLists.txt, src/citra_qt/CMakeLists.txt, src/web_service/CMakeLists.txt
See yuzu-emu/yuzu#1542.
This is more localized to what we want to enforce directory-wise with
the project. CMAKE_SOURCE_DIR indicates the root of the source tree, but
this would cause the wrong behavior if someone included yuzu as part of
a larger buildsystem (for whatever reason). Instead, we want to use the
directory where the "project(yuzu)" command was declared as the root
path reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4375)
=> Port yuzu-emu/yuzu#1542: "CMakeLists: Use PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR"

dist/scripting/citra.py
Removed unused import `binascii`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4368)
=> scripting/citra: Removed unused import binascii

src/citra_qt/main.cpp
Variable in tr() won't trigger linguist to generate translation entry. Instead it needs a string literal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4364)
=> citra_qt: fix translation for opengl version error

src/citra_qt/debugger/graphics/graphics_breakpoints.cpp, src/citra_qt/debugger/graphics/graphics_breakpoints_p.h
See yuzu-emu/yuzu#1571.
tr() will not function properly on static/global data like this, as the
object is only ever constructed once, so the strings won't translate if
the language is changed without restarting the program, which is
undesirable. Instead we can just turn the map into a plain old function
that maps the values to their equivalent strings. This is also lessens
the memory allocated, since it's only allocating memory for the strings
themselves, and not an encompassing map as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4376)
=> Port yuzu-emu/yuzu#1571: "graphic_breakpoints: Correct translation of strings in BreakpointModel's data() function"

src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.h, src/citra_qt/configuration/configure_general.ui
I think this change is fairly self-explanatory.
When the button is clicked, the settings file gets deleted and Citra gets closed.
Screenshots:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4382)
=> configure_general: Add an option to reset defaults

src/citra_qt/compatdb.cpp, src/citra_qt/compatdb.h, src/citra_qt/main.ui, src/common/telemetry.h, src/core/telemetry_session.cpp, src/core/telemetry_session.h, src/web_service/telemetry_json.cpp, src/web_service/telemetry_json.h
This PR switches the endpoint for testcases to `api.citra-emu.org/gamedb/testcase` instead of sending them as part of Telemetry. It also adds basic error handling to the compatdb wizard and shows the user a popup in case submission failed.
It also moves the `Report compatibility` button to the emulation tab. This was done to get more users to submit testcase cause it's way more likely a user will visit this tab, than the help tab. If you've got any opinions on this change, don't hesitate to voice them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4369)
=>  compatdb: Use a seperate endpoint for testcase submission

src/core/hle/kernel/process.h
Fix a warning where class definition and forward declaration mismatch. CodeSet is a kernel object and have ctor/dtor/private members like others, so in convention it should be a class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4386)
=> Kernel/CodeSet: change struct to class

src/citra_qt/debugger/wait_tree.cpp, src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/skyeye_common/armstate.cpp, src/core/core.cpp, src/core/gdbstub/gdbstub.cpp, src/core/hle/ipc.h, src/core/hle/kernel/handle_table.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/mutex.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/timer.cpp, src/core/hle/kernel/timer.h, src/core/hle/service/fs/file.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/service.cpp, src/core/hle/service/sm/srv.cpp
Global state elimination for kernel part 3.
Also removed the deprecated `IPC::GetCommandBuffer` as I touched it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4371)
=> Kernel: eliminate global state for threads and timers

src/core/hle/kernel/kernel.h
Fixup of #4399, see comments in the code. Fixes #4402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4403)
=> Kernel: thread manager still has to be destructed first

src/core/file_sys/ncch_container.cpp
I start to like sanitizer now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4425)
=> filesys/ncch: prevent buffer overflow on calculating SHA256

src/core/hle/kernel/thread.cpp
A simple hardware test of `svcQueryMemory(&meminfo,&pageinfo,(u32)getThreadLocalStorage())` confirmed this this.
I also notice that on real hardware the TLS page allocation seems not starting from `0x1FF82000` but somewhere in the middle. My test program got TLS at `0x1FFAE000` or `0x1FFAF000` randomly. Not sure what this actually means.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4415)
=> Kernel: correct MemoryState for TLS

src/core/hle/kernel/shared_memory.cpp, src/core/hle/service/apt/apt.cpp, src/core/memory.cpp, src/core/memory.h
Hardware test shows that the shared font memory location always uses the old linear heap region, regardless of system version / old/new 3DS. Fixing the memory location fixed an issue for me where loading new version swkbd from an old game couldn't display the text.
While I am on it, I replaced the global `PhysicalToVirtualAddress` and replace it with a dedicated one for rasterizer, and make it independent to kernel version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4413)
=> Fix shared font addres; Remove global PhysicalToVirtualAddress

src/core/memory.h
The virtual address range of IO region is 0x1EC00000 to 0x1F000000. It can't go beyond because 0x1F000000 is the start of VRAM. 3dbrew doesn't document any more IO region after the GPU IO region, which starts at VAddr=0x1EF00000, PAddr=0x10400000, whose length is no more that 0x2000 bytes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4429)
=> Memory: IO area is at most 4MB

src/common/bit_field.h
Storing signed type causes the following behaviour: `ExtractValue` can do overflow/negative left shift. Now it only relies on two implementation-defined behaviours (which are almost always defined as we want): unsigned->signed conversion (as two's complement equivalence), and signed right shift (arithmetic shift).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4426)
=> Common/Bitfield: store value as unsigned type

src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/main.ui
See yuzu-emu/yuzu#1639 for more details.
Opens a windows explorer/file manager window at the user's yuzu folder (%APPDATA%/yuzu on windows).
Meant to make following guide or making configuration changes easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4419)
=> Port yuzu-emu/yuzu#1639: "qt: Add help option to open yuzu folder"

src/citra_qt/configuration/configure_audio.h, src/citra_qt/configuration/configure_debug.h, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_dialog.h, src/citra_qt/configuration/configure_general.h, src/citra_qt/configuration/configure_graphics.h, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_ui.h, src/citra_qt/configuration/configure_ui.ui, src/citra_qt/configuration/configure_web.h
Fixes #4372.
Changing languages will now apply the settings - and load them back to the UI afterwards. Also fixed a bug introduced in the tabbed config PR caused by using translated strings in the data.
@FearlessTobi Can you verify that language configuration works properly now?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4398)
=> citra_qt/configuration: fix language configuration issues

src/core/cheats/gateway_cheat.cpp
Fix a small typo in the 16bit comparison operations of cheats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4447)
=> Fix 16bit comparison operations

.travis/linux-mingw/docker.sh, appveyor.yml
See yuzu-emu/yuzu#1705 for more details.
Problem:
Game icons do not show in mingw builds
Cause:
Missing libjpeg dll
Solution:
This PR (hopefully). I don't currently have a Linux environment set up to fully test this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4440)
=> Port yuzu-emu/yuzu#1705: "Include QT imageformat dependencies with releases"

src/core/memory.cpp
Also note that the four regions to check (VRAM, DSP, FCRAM, N3DS_EXTRA) are all isolated in the physical address space, so there is no collision on checking the boundary address. The returned pointer of boundary is also safe, as C++ permits one-past-the-end pointer for pointer arithmetic. It is just not dereferencable.
This is used in GPU for memory range check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4436)
=> Memory: GetPhysicalPointer should accept right open bound address

src/core/hle/kernel/svc.cpp
Hardware test shows that svcQueryMemory reports a merged memory block for the same state & permission, regardless whether the internal mapping is continuous. The test included:
- consecutive heap pages that are allocated in random order (so their physical memory should be in random order)
- two consecutive memory alias block mapped from different source.
- two consecutive shared memory block mapped from different service.
In all this cases QueryMemory reported a merged block.
Our VMManager merges blocks only when the physical mapping is continuous (and has the same state & permission), so we need to merge similar blocks on fly when svcQueryMemory is called.
--- …
=> SVC: QueryMemory merges similar VMA

src/core/hle/service/service.cpp
See yuzu-emu/yuzu#1688 for more details.
When yuzu is compiled in release mode this function is unused, however,
when compiled in debug mode, it's used within a LOG_TRACE statement.
This prevents erroneous compilation warnings about an unused function
(that isn't actually totally unused).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4441)
=> Port yuzu-emu/yuzu#1688: "service: Mark MakeFunctionString with the [[maybe_unused]] attribute."

src/common/math_util.h
See yuzu-emu/yuzu#1758 for more details.
Mostly just cleaning out old code. It also allows Rectangle to be constexpr constructible, which allows other data structures containing Rectangle instances to also be constexpr constructible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4454)
=> Port yuzu-emu/yuzu#1758: "common/math_util: Minor cleanup"

src/core/hle/kernel/shared_memory.h
This avoids a potential reallocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4465)
=> kernel/shared_memory: std::move the string parameter in SetName()

README.md
Copied from https://app.bitrise.io/app/4ccd8e5720f0d13b#/builds
Btw, this is a debug build CI, which is a good thing given we only had release build CI previously. @BreadFish64 Is this intended though?  How would we handle release build in the future?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4461)
=> README: add bitrise badge

.travis/linux-flatpak/generate-data.sh
So that the flatpak build has discord rpc and scripting support as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4474)
=> travis: Add missing flags for flatpak build

.travis/linux-flatpak/generate-data.sh
Reverts citra-emu/citra#4474
It is believed that these flags were actually dropped intentionally, as scripting (libzmq) won't build properly, and discord-rpc likely won't work inside a sandbox.
Sorry, I did not test it before adding the flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4475)
=> Revert "travis: Add missing flags for flatpak build"

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/citra_qt/configuration/config.cpp, src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/main.ui, src/citra_qt/ui_settings.h, src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/video_core.cpp, src/video_core/video_core.h
Closes #3121
Allows capturing screenshot at the current internal resolution (native for software renderer), but a setting is available to capture it in other resolutions (the internal resolution won't be changed, instead the image captured is upscaled/downscaled). The screenshot is saved to a single PNG in the current layout.
Examples of captured images can be found in the #screenshots-videos channel in Citra discord (they were captured with an older version of the code, but I have confirmed the result is the same). This is [one](https://cdn.discordapp.com/attachments/472575481179537418/484372018179997706/screenshot2.zip) of them.
A menu action is added to the Movie menu (I believe this is the most suitable place) as well as a hotkey. The hotkey is bound to Ctrl+S by default.
I have just …
=> citra_qt, video_core: Screenshot functionality

.travis/linux-mingw/docker.sh
Remove the `pip install` statement.
Currently blocked by citra-emu/build-environments#11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4478)
=> travis: MinGW: minor changes

src/audio_core/hle/source.cpp
Fixes #3313 and #3393, and probably also #3378 and #3392.
The physical audio buffer addresses that Luigi's Mansion Dark Moon gives to the DSP have the least-significant bit set for no obvious reason. Citra took it at its word, resulting in garbled audio. Masking the addresses with `0xFFFFFFFE` is enough to fix the issue, but hardware testing (thanks to @Dragios and @jroweboy) indicated that `0xFFFFFFFC` is actually the correct mask for all audio formats (mono and stereo PCM8, mono and stereo PCM16, and ADPCM). This fixes the audio on Dark Moon, The Amazing Spiderman, Metroid Prime Federation Force, and probably also some other games that haven't been re-tested yet (see the issues I linked above).
A few extra notes:
- Luigi's Mansion Dark Moon, Metroid Prime Federation Force, The Amazing …
=> DSP: Add address mask for physical pointers to audio data buffers

src/citra/citra.cpp, src/citra_qt/main.cpp, src/common/logging/backend.cpp, src/common/logging/backend.h
See yuzu-emu/yuzu#1441 for more details.
This shows the log in the Output window in Visual Studio, or whatever other debugger you use on Windows, like it does in Dolphin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4418)
=> Port yuzu-emu/yuzu#1441: "logging: Add DebuggerBackend for logging to Visual Studio"

src/video_core/renderer_opengl/renderer_opengl.cpp
This PR fixes a bad string comparison (comparing pointer values instead of string content) in the opengl renderer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4484)
=> renderer_opengl: Fix string comparison

src/core/hle/service/service.cpp, src/core/hle/service/sm/sm.cpp
See yuzu-emu/yuzu#1874 for more details.
Tidies up the pre-C++17 code to use structured bindings where applicable and cleans up a few other minor things along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4494)
=> Port yuzu-emu/yuzu#1874: "hle/service, hle/sm: Minor cleanup"

src/citra_qt/debugger/wait_tree.cpp, src/citra_qt/debugger/wait_tree.h
See yuzu-emu/yuzu#1871 for more details.
Just a trivial modernization that potentially avoids copying strings in certain scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4511)
=>  Port yuzu-emu/yuzu#1871: "yuzu/wait_tree: Pass QString by value and std::move in the initializer list for WaitTreeText"

src/citra_qt/multiplayer/chat_room.cpp
The mega PR is #4468.
* Made the font black for pinged messages so that they can be seen more clearly in dark themes.
* Added a `View Profile` action that opens the member's Citra Community Profile if they are authenticated. (requested by @chris062689)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4516)
=> multiplayer: minor UI fixes

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This is a workaround to the recurring problem #2110. The game tries to load a texture part of which goes beyond VRAM region. On real hardware this would results in garbage data being read. However this is safe because the game then only use the first valid part of the texture to do following rendering operations.
#2799 "Fixed" the crash on citra by adding boundary check during address conversion for rasterizer cache. However, it leaves the out-of-bound read in texture loading there, and the texture would copy garbage data from host memory.
Recent memory module change in #4480 moves VRAM from global to heap, resulting in runtime adding unmapped/guard pages around the VRAM memory, and now causing the out-of-bound read crash. This PR prevents the out-of-bound read when detecting invalid …
=> gl_rasterizer_cache/MortonCopy: avoid read/write to invalid address

src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h, src/audio_core/dsp_interface.cpp, src/audio_core/null_sink.h, src/audio_core/sink_details.cpp, src/audio_core/sink_details.h, src/citra_qt/configuration/configure_audio.cpp
See yuzu-emu/yuzu#1902 for more details.
We can hide the direct array from external view and instead provide functions to retrieve the necessary info. This has the benefit of completely hiding the makeup of the SinkDetails structure from the rest of the code.
Given that this makes the array hidden, we can also make the array constexpr by altering the members slightly. This gets rid of several static constructor calls related to std::vector and std::function.
Now we don't have heap allocations here that need to occur before the program can even enter main(). It also has the benefit of saving a little bit of heap space, but this doesn't matter too much, since the savings in that regard are pretty tiny.
--- …
=> Port yuzu-emu/yuzu#1902: "audio_core: Make g_sink_details internally linked"

.gitmodules, externals/CMakeLists.txt, src/audio_core/CMakeLists.txt, src/audio_core/dsp_interface.cpp, src/audio_core/dsp_interface.h, src/audio_core/hle/hle.cpp, src/audio_core/hle/hle.h, src/audio_core/lle/lle.cpp, src/audio_core/lle/lle.h, src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/configuration/configure_audio.ui, src/common/thread.h, src/core/core.cpp, src/core/hle/kernel/wait_object.cpp, src/core/hle/kernel/wait_object.h, src/core/hle/service/dsp/dsp_dsp.cpp, src/core/hle/service/dsp/dsp_dsp.h, src/core/settings.cpp, src/core/settings.h
This adds one of my project as submodule: [teakra](https://github.com/wwylele/teakra), which is a functioning but unoptimized interpreter of the DSP core, with necessary peripherals implemented as well. Comments, reviews and PRs to the teakra repo are welcome.
On the citra side, this is implement as a new `DspInterface` named `DspLle`. Some functions originally implemented in `DSP_DSP` service now are pushed to `DspInterface`, due to the implementation difference between `DspHle` and `DspLle`. Please see each commit for added and moved functions.
The state of this code is that the feature-implementing stage is basically finished, and the optimization stage has just started, hence "WIP". I open this early, instead of when it is fully finished, because I want to gain opinions and ideas in …
=> audio: implement DSP LLE

src/citra_qt/multiplayer/state.cpp
This keeps config from crashing when the chat room is not open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4576)
=> Frontend: Only reload icons in chat when the chat room is open

src/audio_core/time_stretch.cpp, src/citra_qt/game_list.cpp
This PR ports yuzu-emu/yuzu#1848 and yuzu-emu/yuzu#2020. 
I grouped them together cause they are both so minor and it's basically impossible for them to cause regressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4582)
=> Port two minor changes from yuzu (# 1848 and # 2020)

src/citra/config.cpp, src/citra/default_ini.h, src/citra/emu_window/emu_window_sdl2.cpp, src/citra_qt/bootmanager.cpp, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp
The V-Sync option is fundamentally broken in Citra, so let's do the same as yuzu and remove it entirely for SDL2 and at least from the frontend for QT.
(It was also only used by 7.3% of users)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4457)
=> citra_qt: Remove V-Sync option

src/citra_qt/configuration/configure_web.cpp
See yuzu-emu/yuzu#2032 for more details.
**Original desc:**
It's general practice to use an ellipsis to indicate an ongoing action within a UI. While we're at it, this also removes an unused lambda capture in the same function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4591)
=> Port yuzu-emu/yuzu#2032: "yuzu/configuration/configure_web: Amend verification string"

src/core/arm/skyeye_common/vfp/vfp_helper.h
Makes the lines of code slightly nicer to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4594)
=> vfp_helper: Remove odd use of the comma operator in vfp_single_unpack()

src/audio_core/hle/shared_memory.h, src/common/bit_field.h, src/common/swap.h, src/core/file_sys/ncch_container.h, src/core/hle/service/ir/extra_hid.h, src/core/hle/service/ir/ir_rst.h, src/core/hle/service/ldr_ro/cro_helper.h, src/core/movie.cpp, src/input_common/udp/protocol.h, src/tests/CMakeLists.txt, src/tests/common/bit_field.cpp
With this `BitField` now has storage specification on byte order just like `u32_le`/`u32_be`. The original `BitField` is default to little endian, while the big-endian counterpart is aliased to `BitFieldBE`. This resolves the problem of `BitField<*, *, u32_le>` not compilable on BE machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4599)
=> Common: make BitField endianness-aware

src/core/gdbstub/gdbstub.cpp
Back in August last year, commit bd658a88014152551c2c833205b implemented logic for code breakpoints to be hit via a `bkpt 0` opcode that temporarily overwrites the targeted instruction (by the `CommitBreakpoint` / `RemoveBreakpoint` functions). However, this is also done inadvertently for watchpoints (Read-, Write-, or Access-type breakpoint types), which can corrupt data used by the software (#4502). This PR adds a simple check to both functions.
**Note to users/testers:** Currently, CPU JIT isn't designed around memory watchpoints, so make sure it's off.
Speaking of which, although my MS2017 debugger reveals that watchpoints are being hit internally (i.e. calls [`CheckMemoryBreakpoint(VAddr, type)`](https://github.com/citra-emu/citra/blob/8b047a49ae2dcf972560567b7146554f74ac4ad6/src/core …
=> gdbstub: only let Execute breakpoints write/restore BKPT opcodes into memory

src/citra_qt/main.cpp
By default, Qt doesn't add an extension to files if none is explicitly typed by the user.
As such, screenshots would silently fail to save if a user did not type an extension.
This fix creates a full QFileDialog instead of using the getSaveFileName shortcut so a default suffix can be added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4583)
=> citra_qt: Fix saving screenshot when no file extension is provided

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.h
Games can frequently change this register. Using it as shader config var would generates a lot of shaders, causing slowdown on shader compilation and lookup.
Fixes #4293. Huge thanks to @tywald for tracing down the issue :heart:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4619)
=> gl_rasterizer: change shadow_texture_bias from shader config to shader uniform

src/citra_qt/game_list_worker.cpp
Previously, the game list wouldn't show demos if they were installed. This fixes that, and shows them under the "Installed Titles" category.
Please let me know if I did anything wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4631)
=> citra_qt: show demos on game list

src/video_core/renderer_opengl/gl_rasterizer_cache.h
The current method constructs two additional boost interval_sets which is somewhat expensive. This accomplishes the same thing (checking that `interval` is fully contained in `invalid_regions`) with a smaller impact. Speed difference ranges from none to 2x in certain areas of pilotwings.
Frame time data from the games tested can be found here:
https://docs.google.com/spreadsheets/d/1lMMQN_52nURA5OsU1JMNER5Y_FnQrEhHRNBoAJ-x-EQ/edit?usp=sharing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4633)
=> video_core: improve efficiency of CachedSurface::IsSurfaceFullyInvalid

src/citra_qt/configuration/config.cpp
Fixes the issue where all input profiles had the name "default" after restarting Citra.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4648)
=> citra_qt/config: actually save name of input profile

src/audio_core/codec.cpp, src/audio_core/codec.h, src/audio_core/dsp_interface.h, src/audio_core/hle/common.h, src/audio_core/hle/filter.cpp, src/audio_core/hle/filter.h, src/audio_core/hle/mixers.cpp, src/audio_core/hle/mixers.h, src/audio_core/hle/shared_memory.h, src/audio_core/hle/source.cpp, src/audio_core/hle/source.h, src/audio_core/interpolate.cpp, src/audio_core/interpolate.h
Some files already used nested namespaces, however some didn't. No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4652)
=> audio_core: use nested namespaces

src/video_core/command_processor.cpp, src/video_core/command_processor.h, src/video_core/rasterizer_interface.h, src/video_core/shader/debug_data.h, src/video_core/shader/shader.cpp, src/video_core/shader/shader.h, src/video_core/shader/shader_interpreter.cpp, src/video_core/shader/shader_interpreter.h, src/video_core/shader/shader_jit_x64.cpp, src/video_core/shader/shader_jit_x64.h, src/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/shader/shader_jit_x64_compiler.h, src/video_core/swrasterizer/clipper.cpp, src/video_core/swrasterizer/framebuffer.cpp, src/video_core/swrasterizer/framebuffer.h, src/video_core/swrasterizer/proctex.cpp, src/video_core/swrasterizer/proctex.h, src/video_core/swrasterizer/rasterizer.cpp, src/video_core/swrasterizer/rasterizer.h, src/video_core/swrasterizer/swrasterizer.h, src/video_core/swrasterizer/texturing.cpp, src/video_core/swrasterizer/texturing.h, src/video_core/texture/etc1.cpp, src/video_core/texture/etc1.h, src/video_core/texture/texture_decode.cpp, src/video_core/texture/texture_decode.h
Some files already used nested namespaces, however some didn't. No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4654)
=> video_core: use nested namespaces

src/audio_core/hle/shared_memory.h, src/common/bit_field.h, src/common/swap.h, src/core/hle/service/ldr_ro/cro_helper.h
Citra can't be compiled using GCC <7 because of required C++17 support, so these version checks don't need to exist anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4655)
=> Remove GCC version checks

src/citra_qt/main.cpp
MSVC does not seem to like using constexpr values in a lambda that were declared outside of it.
Previously on MSVC build the hotkeys to inc-/decrease the speed limit were not working correctly because in the lambda the SPEED_LIMIT_STEP had garbage values.
After googling around a bit I found: https://github.com/codeplaysoftware/computecpp-sdk/issues/95 which seems to be a similar issue.
Trying the suggested fix to make the variable static constexpr also fixes the bug here.
If you have any better solution, don't hesitate to tell me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4647)
=> citra_qt/main: make SPEED_LIMIT_STEP static constexpr

src/common/bit_field.h
This ports https://github.com/yuzu-emu/yuzu/commit/0315fe8c3dc8cb267284b061a20b85c09cd5d98b#diff-08ca154e611eee771a3dc2d7e929d0a9 and https://github.com/yuzu-emu/yuzu/commit/e59126809c9c092d0913e6c1446f6d0ecf20bca2#diff-08ca154e611eee771a3dc2d7e929d0a9.
I only saw them now cause bunnei put them in two mega PRs which hid the changes from me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4629)
=> Port minor changes for BitField from yuzu

src/core/hle/service/soc_u.cpp, src/core/hle/service/soc_u.h
Implements two additional functions in soc:U, getaddrinfo and getnameinfo, using the corresponding host socket functions.
I only tested this with a few (self-written) homebrews and things seem to work fine so far... more testing and reviews would be appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4632)
=> service/soc_u: Implement getaddrinfo and getnameinfo

src/core/memory.cpp
The comment already invalidates itself: neither MMIO nor rasterizer cache belongs to HLE kernel state. This mutex has a too large scope if MMIO or cache is included, which is prone to dead lock when multiple thread acquires these resource at the same time. If necessary, each MMIO component or rasterizer should have their own lock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4630)
=> Memory: don't lock hle mutex in memory read/write

src/common/threadsafe_queue.h, src/core/core_timing.h
See yuzu-emu/yuzu#2116 for more details.
The necessity of this parameter is dubious at best (even if enabled, it would still include the size data member as part of the class instead of removing it with template shenanigans), and in 2019 probably offers completely negligible savings as opposed to just leaving this enabled. This removes it and simplifies the overall interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4645)
=> Port yuzu-emu/yuzu#2116: "threadsafe_queue: Remove NeedSize template parameter"

src/core/hle/kernel/process.cpp, src/core/hle/kernel/shared_memory.h
To break a circular reference formed by process->handle_table->shared_memory->process. Since SharedMemory uses its owner process in the destructor, which is not kept alive by SharedMemory any more, we need to make sure that the lifetime of process is longer than the shared memory. To partially resolve this, Process now explicitly releases shared memory first in its destructor. This is with the assumtion that there is no inter-process reference to shared memory on exit, which is not true when we introduce more multi-process emulation. A TODO is left there for this, as more RE needs to be done on how 3DS handles this situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra …
=> Kernel/SharedMemory: make owner_process a raw pointer

src/core/file_sys/archive_backend.h, src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_extsavedata.h, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_ncch.h, src/core/file_sys/archive_other_savedata.cpp, src/core/file_sys/archive_other_savedata.h, src/core/file_sys/archive_savedata.cpp, src/core/file_sys/archive_savedata.h, src/core/file_sys/archive_sdmc.cpp, src/core/file_sys/archive_sdmc.h, src/core/file_sys/archive_sdmcwriteonly.cpp, src/core/file_sys/archive_sdmcwriteonly.h, src/core/file_sys/archive_selfncch.cpp, src/core/file_sys/archive_selfncch.h, src/core/file_sys/archive_systemsavedata.cpp, src/core/file_sys/archive_systemsavedata.h, src/core/hle/service/cecd/cecd.cpp, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/fs/fs_user.h, src/core/hle/service/ptm/ptm.cpp
To eliminate System::GetInstance usage. Archive type like SelfNCCH and SaveData changes the actual reference path for different client, so archive backend interface should accept client information from the service interface. Currently we only pass the program ID as the client information.
FS usage in cfg, ptm and cecd stubs 0 to the parameter `program_id`. Technically they should use their respective system module ID for these place, but since they don't use ID-dependent archives at all, I don't bother adding magic numbers there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4618)
=> FS: pass down program ID for archive operation (cleanup System::GetInstance part 3)

src/audio_core/codec.cpp, src/citra_qt/compatdb.cpp, src/core/frontend/emu_window.cpp, src/core/frontend/emu_window.h
This PR ports https://github.com/yuzu-emu/yuzu/pull/2173, https://github.com/yuzu-emu/yuzu/pull/2170, https://github.com/yuzu-emu/yuzu/pull/2160 (partially) ~~and https://github.com/yuzu-emu/yuzu/pull/2141~~.
~~Now that I'm writing this, I've realized that I might should have factored out the memory commit in a seperate PR, so I guess if any problems come up related to it, I can just drop it for now... At least I wasn't able to observe any regressions.~~
Please review this PR commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4665)
=> Port various minor PRs from yuzu

src/citra_qt/cheats.cpp, src/citra_qt/cheats.h, src/citra_qt/cheats.ui, src/core/cheats/cheat_base.h, src/core/cheats/cheats.cpp, src/core/cheats/cheats.h, src/core/cheats/gateway_cheat.cpp, src/core/cheats/gateway_cheat.h
Screenshot:
More description can be found in the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4610)
=> Implement UI for adding/editing/deleting cheats

src/core/frontend/applets/swkbd.cpp
Also removed a TODO as it is verified that max_text_length is inclusive (allows size = max_text_length)
Should fixes #4667 and #4547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4668)
=> applet/swkbd: use UTF-16 string to test string size

src/core/rpc/server.cpp, src/core/rpc/udp_server.cpp
udp_server might not be created due to error (occupied port etc.), in which case its destructor and thread-ending call chain will not be excuted in Server::Stop. However, the ending packet still need to be send no matter udp is on or not, so move it to Server::Stop
Fixes #4662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4669)
=> rpc: send ending packet in Server instead of UDPServer

src/citra_qt/main.cpp, src/citra_qt/main.h
When dragging a CIA onto Citra, or just opening it by double-clicking in the Windows explorer, Citra tells you that the ROM format is unsupported.
This is
- a) 100% wrong
- b) a hassle for even the people who know that CIA is supported and just want to install it
With this PR, this popup appears when trying to boot a CIA file and asks the user if they want to install the CIA:
~~**PS**: I only made this PR cause I really got annoyed by this when frequently installing CIAs for my FileOpen delay tests.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4627)
=> citra_qt: when opening a cia file directly, make Citra ask to install it

src/core/hle/service/nfc/nfc.cpp
When making the initial implementation, I forgot to add the series variable to the AmiiboConfig struct.
With this PR it is added and many of the AmiiboConfig fields get their proper values now.
The loading of the Amiibo data that is added here has been hwtested.
This fixes Amiibos in Yoshis Woolly World, Smash (partially) and probably other games too.
(I'm planning to further improve the Amiibo implementation and add a way of Amiibo AppData loading sometime in the future.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4688)
=> nfc: Improve implementation of GetAmiiboConfig

src/.clang-format, src/android/app/src/main/cpp/CMakeLists.txt, src/android/app/src/main/cpp/dummy.cpp, src/android/app/src/main/cpp/logging/log.cpp, src/android/app/src/main/cpp/logging/logcat_backend.cpp, src/android/app/src/main/cpp/logging/logcat_backend.h, src/android/app/src/main/cpp/native_interface.cpp, src/android/app/src/main/cpp/native_interface.h, src/android/app/src/main/cpp/ui/main/main_activity.cpp, src/android/app/src/main/java/org/citra_emu/citra/CitraApplication.java, src/android/app/src/main/java/org/citra_emu/citra/LOG.java, src/android/app/src/main/java/org/citra_emu/citra/ui/main/MainActivity.java, src/android/app/src/main/java/org/citra_emu/citra/utils/FileUtil.java, src/android/app/src/main/java/org/citra_emu/citra/utils/PermissionUtil.java, src/common/file_util.cpp, src/common/logging/backend.cpp, src/common/string_util.cpp, src/common/string_util.h
sends logs over logcat ~~using the color backend~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4575)
=> android: add logging

src/citra_qt/bootmanager.cpp
This PR will (hopefully) fix the case where Citra could end up locking up.
To reproduce the hang, you need a pretty specific setup.
In my case, the conditions are:
1. Using Plasma KDE 5 as the Desktop Environment
2. Using the default settings where the single click is the selection (instead of double-click)
3. Click pretty fast on any entry in the game list multiple times
If the conditions above are met, Citra will freeze 100% of the time.
The fix introduces a `QMutex` which will do a lock acquire each time `BootGame` is called to mitigate the issue. In my case, this can resolve the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4684)
=> frontend: qt: fix a freeze issue

.travis/macos/deps.sh, .travis/macos/upload.sh
Originally proposed by @al3xtjames. The reason I brought this up again is mostly for the extra ffmpeg dependencies to be added in #4602.
This appears to properly handle the ffmpeg libraries that dylibbundler failed to patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4686)
=> travis/macos: Use macpack to bundle dependencies

src/video_core/renderer_opengl/gl_shader_util.cpp
Some GLES drivers complain about the GLES version string not being on the first line. With how it was defined, technically it's not wrong as the first line is an empty newline. This puts the version declaration on the first line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4698)
=> Fix GLES version header on picky drivers

src/citra/citra.cpp, src/dedicated_room/citra-room.cpp
getopt_long returns a signed integer, and the parsing loop expects it to return -1 when an option specified doesn't exist (e.g. a filename).
The char type is not only the wrong return type for getopt_long, it is not guaranteed to be signed on all systems (e.g. ARM).
Obviously that wouldn't work, so this branch addresses the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4697)
=> Fix getopt return type on systems where char is unsigned by default

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This PR attempt to fix the inverted color when rendered using OpenGL ES renderer. The issue is caused by OpenGL ES lacks `GL_BGR` and `GL_BGRA` formats. This PR fixes this issue by manually doing the byte-swap on the pixels.
Not sure about the performance for now and the PR is highly unoptimized, so comments and suggestions are highly welcomed.
Thanks for @wwylele and @jroweboy for their great help on how to approach the solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4691)
=> video_core: renderer_opengl: gles color fix

src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/nwm/nwm_uds.h
TODO:
This is reverse-engineered by comparing the two versions of functions (deprecated vs. current). So far it turned out that NWM module parses IPC different params and then forward them to the same base functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4690)
=> UDS: implement deprecated functions

src/common/CMakeLists.txt, src/common/thread_queue_list.h
See yuzu-emu/yuzu#2247 for more details.
We really don't need to pull in several headers of boost related
machinery just to perform the erase-remove idiom (particularly with
C++20 around the corner, which adds universal container std::erase and
std::erase_if, which we can just use instead).
With this, we don't need to link in anything boost-related into common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4709)
=> Port yuzu-emu/yuzu#2247: "common/thread_queue_list: Remove unnecessary dependency on boost"

src/core/file_sys/archive_backend.h, src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_sdmc.cpp, src/core/file_sys/archive_sdmc.h, src/core/file_sys/archive_sdmcwriteonly.cpp, src/core/file_sys/archive_sdmcwriteonly.h, src/core/file_sys/delay_generator.cpp, src/core/file_sys/delay_generator.h, src/core/file_sys/file_backend.h, src/core/file_sys/ivfc_archive.cpp, src/core/file_sys/ivfc_archive.h, src/core/file_sys/savedata_archive.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/file.cpp, src/core/hle/service/fs/fs_user.cpp
File IOs on a 3DS take much longer then our currently emulated 39000 ns for each SVC call. Without the additional delay added by that PR the thread opening a file is executed much faster then it should, leading e.g. to deadlocks.
The time it took for the opening of files were tested with homebrews (links to their source code can be found in the code). The delay values were taken from the averages of all FileOpen operations for the specified archive type.
For now RomFS, ExeFS, and reading savefiles were tested. For all other values for now the RomFS/ExeFS delay was assumed until they get measured to. Adding that delay instead of the 39000 ns seems to be at least a bit more precise.
The final goal is still to measure all delays for File IOs (Read, FileCreate, FileDelete, DirCreate, …
=> fs_user: Add a delay for each file open

src/core/core.cpp, src/core/hle/service/service.cpp, src/core/hle/service/service.h
... to solve a memory leak caused by reference cycle. The bug leaked all services and their owned objects (including... many stuff) upon stopping the game.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4689)
=>  ServiceFrameworkBase: remove ownership to ServerPort 

src/core/hle/service/cam/cam.h
Previously, these variables are only initialized when the game calls `DriverInitialize`. This could cause problem if any of them are read before `DriverInitialize`. Particularly, in the destructor `Module::~Module`, which calls `CancelReceiving`, which has the following code
```
if (!ports[port_id].is_receiving)
return;
```
which would read the uninitialized `is_receiving` on exit if the game never uses camera.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4715)
=> CAM: initialize states

CMakeLists.txt
should be pretty self-explanatory. i had the citra repo cloned to a path with spaces, so the clang-format target wouldn't work. this pull request fixes that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4718)
=> Fix clang-format target when using a path with spaces on Windows

src/citra_qt/configuration/configure_input.cpp
Fixes a bug where users can't bind anything to the B key.
Arises because this was not changed in #4537.
Tested with no issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4722)
=> ConfigureInput::GetUsedKeyboardKeys(): Change index of home button to use NativeButton instead of magic number.

src/audio_core/cubeb_sink.cpp
`impl->cb` is used in the cubeb stream callback, so setting it to `nullptr` while the stream is still running could cause a race condition. When setting `impl->cb` to `nullptr`, this calls the destructor for the `std::function` object, but the cubeb callback thread is still running and it could be using data inside the `std::function` at this point, causing a crash.
Note: i've managed to replicate this a few times now by having a game running while time stretching is enabled and then force closing citra with the task manager. Since this patch, I haven't been able to replicate the crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4723)
=> Destroy the callback after the stream is destroyed to prevent crashes on close

src/citra_qt/CMakeLists.txt, src/citra_qt/applets/mii_selector.cpp, src/citra_qt/applets/mii_selector.h, src/citra_qt/applets/swkbd.cpp, src/citra_qt/applets/swkbd.h, src/citra_qt/main.cpp, src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/file_sys/archive_backend.h, src/core/frontend/applets/default_applets.cpp, src/core/frontend/applets/mii_selector.cpp, src/core/frontend/applets/mii_selector.h, src/core/frontend/applets/swkbd.cpp, src/core/frontend/applets/swkbd.h, src/core/hle/applets/mii_selector.cpp, src/core/hle/applets/mii_selector.h, src/core/hle/applets/swkbd.cpp, src/core/hle/service/ptm/ptm.cpp, src/core/hle/service/ptm/ptm.h
First, a big thanks to @valentinvanelslande for providing https://github.com/citra-emu/citra/pull/4345 as base for this. I've tried to clean it up and address most of the review comments on it.
This PR aims to add a basic HLE replacement for the LLE Mii selector.
When a game requests you to chose a Mii, this dialog appears:
In case you don't have any Miis, it shows this dialog, asking you if you want to use the Citra standard Mii:
As always, this implementation is QT only and for SDL the behavior stays the same.
This HLE implementation is also affected by https://github.com/citra-emu/citra/issues/4634.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4635)
=> citra-qt: Implement Mii selector applet 

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/common/detached_tasks.cpp, src/common/logging/backend.cpp, src/common/thread.h, src/common/threadsafe_queue.h, src/core/announce_multiplayer_session.cpp, src/core/frontend/emu_window.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/perf_stats.cpp, src/input_common/keyboard.cpp, src/input_common/motion_emu.cpp, src/input_common/sdl/sdl_impl.cpp, src/input_common/udp/client.cpp, src/input_common/udp/udp.cpp, src/network/room.cpp, src/network/room_member.cpp, src/video_core/debug_utils/debug_utils.cpp, src/video_core/debug_utils/debug_utils.h, src/web_service/web_backend.cpp
See yuzu-emu/yuzu#2312 for more details.
Since C++17, the introduction of deduction guides for locking facilities means that we no longer need to hardcode the mutex type into the locks and guards themselves, making it easier to switch mutex types, should it ever be necessary in the future (and also makes for less reading).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4726)
=> Port yuzu-emu/yuzu#2312: "general: Use deducation guides for std::lock_guard and std::unique_lock"

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/server_session.cpp, src/core/hle/service/fs/file.cpp, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/sm/srv.cpp, src/tests/core/hle/kernel/hle_ipc.cpp
This reduces the boilerplate that services have to write out the current thread explicitly. Using current thread instead of client thread is also semantically incorrect, and will be a problem when we implement multicore (at which time there will be multiple current threads)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4716)
=> HLE/IPC: HLEContext can memorize the client thread and use it for SleepClientThread

src/core/hle/kernel/address_arbiter.h, src/core/hle/kernel/client_port.h, src/core/hle/kernel/client_session.h, src/core/hle/kernel/event.h, src/core/hle/kernel/mutex.h, src/core/hle/kernel/process.h, src/core/hle/kernel/resource_limit.h, src/core/hle/kernel/semaphore.h, src/core/hle/kernel/server_port.h, src/core/hle/kernel/server_session.h, src/core/hle/kernel/shared_memory.h, src/core/hle/kernel/thread.h, src/core/hle/kernel/timer.h
See yuzu-emu/yuzu#2388 for more details.
Some objects declare their handle type as const, while others declare it as constexpr. This makes the const ones constexpr for consistency, and prevents unexpected compilation errors if these happen to be attempted to be used within a constexpr context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4735)
=> Port yuzu-emu/yuzu#2388: "kernel: Make handle type declarations constexpr"

src/video_core/regs_texturing.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/pica_to_gl.h
Basic knowledge: mipmaps are uploaded by games. The pixel data of mipmaps always immediately follows the base image data, and are stored next to each other. Each mipmap level reduces the width and height by 2 from the previous level. The basic configuration and calculation of LOD in PICA basically matches the one in OpenGL.
Design idea: the code aims to minimize the change to the texture cache system. Now each `Surface` is allowed to have multiple mipmap level "attached", instead of always being single-level textures. The attached levels are only used in texture sampling in GLSL, and are not used anywhere else in the cache system. Individual `Surface` for each mipmap level still persists in the cache. When the game request a texture with mipmaps for drawing, the corresponding `Surface` …
=> gl_rasterizer: implement mipmap by forwarding PICA mipmap configuration

src/citra_qt/applets/mii_selector.cpp, src/citra_qt/applets/swkbd.cpp, src/citra_qt/applets/swkbd.h, src/common/string_util.h, src/core/frontend/applets/swkbd.cpp, src/core/frontend/applets/swkbd.h, src/core/hle/applets/mii_selector.cpp, src/core/hle/applets/swkbd.cpp, src/core/hle/applets/swkbd.h
Implements callbacks in the HLE swkbd applet by sending the config (containing text offset and length) as a parameter of signal type `Message`. The application should then send the callback result parameter, also using signal type `Message`.
If the result is `Close`, an error dialog will be shown and then the applet will exit with code `BannedInput`. If the result is `Continue`, an error dialog will be shown and the user will be asked for input again.
Slight cleanups are also done to the code like replacing pointers with references.
Fix #4568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4700)
=> applets/swkbd: Add callback support

.travis/macos/upload.sh
This is no longer needed for logging because logs are written to disk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4748)
=> Launch directly in Mac without terminal

src/core/hle/kernel/wait_object.cpp, src/core/hle/kernel/wait_object.h
See yuzu-emu/yuzu#2415 for more details.
This doesn't actually modify internal state of a wait object, so it can
be const qualified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4752)
=> Port yuzu-emu/yuzu#2415: "kernel/wait_object: Make GetHighestPriorityReadyThread() a const member function"

src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h
- SetClientCertContext: Nothing to say about it
- GetSSLError: Since the httplib::Client will only get created when we actually send a request, GetSSLError is just stubbed
- BeginRequest: Making the request will be part of the next PR to make it easier to review
-BeginRequestAsync: Dito.
Note that research showed that BeginRequest and BeginRequestAsync on real 3DS add the request to a worker queue (BeginRequestAsync async and BeginRequest not async). The request itself is always async. The plan is to skip the worker queue and just make the request async. This means both functions will be identical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4753)
=> HTTP_C: Implement SetClientCertContext, GetSSLError, BeginRequest, BeginRequestAsync

src/core/hle/service/cecd/cecd.cpp, src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h
CFG: write the max value of 0x7F7F to the default cfg savegame and auto update on init
CECD: Actually read the EULA version from CFG instad of magic numbers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4728)
=> Set accepted EULA version to max value

.travis/linux-flatpak/docker.sh
I accidentally squashed a commit containing `[erase me]` in #4731 and thus the changes weren't erased. 
This removes those changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4755)
=> linux-flatpak: revert use precompiled cache

src/citra/emu_window/emu_window_sdl2.h, src/citra_qt/bootmanager.h, src/core/core.cpp, src/core/core.h, src/core/frontend/emu_window.cpp, src/core/frontend/emu_window.h, src/video_core/renderer_base.cpp, src/video_core/renderer_base.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/video_core.cpp, src/video_core/video_core.h
See yuzu-emu/yuzu#1020 for more details.
Gets the class out of the global namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4738)
=> Port yuzu-emu/yuzu#1020: "core: Namespace EmuWindow"

src/core/hle/kernel/client_port.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/server_port.cpp, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/service/fs/file.cpp, src/core/hle/service/fs/fs_user.cpp, src/tests/core/hle/kernel/hle_ipc.cpp
See yuzu-emu/yuzu#2356 for more details.
Keeps the returned type consistent with the function name (and potentially considerably less template work depending on tuple implementations). While we're at it, we can also simplify handling of session pairs with the use of structured bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4736)
=> Port yuzu-emu/yuzu#2356: "kernel/{server_port, server_session}: Return pairs instead of tuples from pair creation functions"

src/common/logging/backend.cpp, src/common/logging/log.h, src/core/hle/service/ps/ps_ps.cpp, src/core/hle/service/service.cpp, src/core/hw/aes/arithmetic128.cpp, src/core/hw/aes/arithmetic128.h, src/core/hw/aes/key.h
Implements the service function PS:EncryptDecryptAES. This is used by the (LLE) SSL service and maybe some others.
The implementation should be rather straightforward and documented; an overload of `Add128` is added to allow adding a u128 and a u64 together, for calculating the new CTR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4733)
=> service/ps: Implement PS:EncryptDecryptAes

src/audio_core/hle/ffmpeg_decoder.cpp, src/audio_core/hle/wmf_decoder.cpp
This PR uses a better resampling algorithm when converting `f32` to `s16` data type in the audio decoders.
**TL;DR** This will resolve the pops and clicks in the game audio like Fire Emblem, Pokemon X/Y 
and other games where HLE AAC decoder is used.
The pops and clicks are caused by the signal clipping, by clamping in the calculation, the peaks are smoothed out so the hard clipping will be avoided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4763)
=> audio_core: dsp_hle: use better f32 to s16 algorithm

src/core/file_sys/cia_container.cpp
When the CIAContainer is loaded it also needs to load the ticket to ensure the correct encryption is applied when a CIA is installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4759)
=> FileSys: Load the ticket when the CIAContainer is loaded

src/core/hle/kernel/ipc.cpp, src/core/memory.cpp, src/core/memory.h
* Reorder arguments to `CopyBlock` to a more sensible order (`memcpy` order) to prevent this from happening in the future.
* Implement one version of `CopyBlock` in terms of the other, because that is silly code duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4747)
=> memory: Re-order CopyBlock arguments to match other overload

src/citra_qt/CMakeLists.txt, src/citra_qt/game_list_p.h
See yuzu-emu/yuzu#2405 for more details.
This is a compile definition introduced in Qt 4.8 for reducing the total
potential number of strings created when performing string
concatenation. This allows for less memory churn.
This can be read about here:
https://blog.qt.io/blog/2011/06/13/string-concatenation-with-qstringbuilder/
For a change that isn't source-compatible, we only had one occurrence
that actually need to have its type clarified, which is pretty good, as
far as transitioning goes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4743)
=> Port yuzu-emu/yuzu#2405: "CMakeLists: Define QT_USE_QSTRINGBUILDER for the Qt target"

src/citra_qt/compatdb.cpp, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/hotkeys.h
This ports yuzu-emu/yuzu#2456, yuzu-emu/yuzu#2458 and yuzu-emu/yuzu#2459.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4768)
=> Port multiple minor yuzu PRs

src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_hotkeys.cpp, src/citra_qt/configuration/configure_hotkeys.h
See yuzu-emu/yuzu#2376 for more details.
Minor clean-up related changes to the hotkey configuration dialog. This also notably prevents the logging window from stealing the initial focus of the hotkey dialog window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4744)
=> Port yuzu-emu/yuzu#2376: "yuzu/configure_hotkey: Minor changes"

src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h
Closes #4611
Perhaps I could shove the condition into a separate function instead of copypasting it? I would certainly do that in C#, but I'm not particularly familiar with C++ codebases and coding styles, so let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4779)
=> Check input profile name for duplicates in New/Rename

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
the constructed rectangle from GetSubRect already has the right info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4789)
=> video_core: change "left + width" to "right" in CanSubRect

src/core/core.cpp, src/core/telemetry_session.cpp, src/core/telemetry_session.h
See yuzu-emu/yuzu#2526 for more details.
A case where the use of global variables in the past is coming up to bite us, previously the initial telemetry data would always be bogus for the bits that relied on the app loader. At initialization time, the app loader will never have any useful information in it, because a game isn't considered to be loading them. Only at load time is that a thing.
Coincidentally, Init() is called in Load(), which prevents any issues from occurring, but if they were ever separated in the future, this would cause issues (and even crash the emulator). By making the dependency part of the interface, we strongly enforce it on the caller, making them call the necessary functions when the objects are known to exist.
While we're at it, we can …
=> Port yuzu-emu/yuzu#2526: "core/telemetry_session: Remove usages of the global system accessor"

src/citra_qt/configuration/configure_graphics.cpp
See yuzu-emu/yuzu#2515 for more details.
A checkbox is able to be tri-state, giving it three possible activity types, so in the connect call here, it would actually be truncating an int into a bool, when calling QSpinbox::setEnabled
Instead, we can just listen on the toggled() signal, which passes along a bool, not an int.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4792)
=> Port yuzu-emu/yuzu#2515: "yuzu/configuration/configure_graphics: Eliminate type narrowing in a connect call"

src/core/hle/kernel/hle_ipc.h, src/core/hle/service/gsp/gsp.cpp, src/core/hle/service/gsp/gsp.h, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/gsp/gsp_gpu.h, src/core/hle/service/service.h
...and remove an unused function while we are on it.
With the change, `GSP::SessionData` essentially depends on a `GSP_GPU` to construct, and therefore a pointer needs to be passed in to the constructor, and the `MakeSessionData` function is override. The default constructor is still provided to make the default implementation compilable, but it is marked unreachable at runtime. The `const` specifier is also removed from `MakeSessionData` because, as seen in GSP_GPU, constructing a session can surely alter the state of the service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4801)
=>  GSP_GPU: move used_thread_ids into the class 

src/CMakeLists.txt
See yuzu-emu/yuzu#2450 for more details.
Ensures that -Wall is always active as a compilation flag regardless of build type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4806)
=> Port yuzu-emu/yuzu#2450: "CMakeLists: Explicitly specify -Wall for the non-MSVC case"

src/core/hle/kernel/vm_manager.cpp
See yuzu-emu/yuzu#2580 for more details.
This is performing more work than would otherwise be necessary during VMManager's destruction. All we actually want to occur in this scenario is for any allocated memory to be freed, which will happen automatically as the VMManager instance goes out of scope. Anything else being done is unnecessary work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4803)
=> Port yuzu-emu/yuzu#2580: "kernel/vm_manager: Remove redundant Reset call in destructor "

src/core/file_sys/ncch_container.cpp
Currently, having a replacement code.bin causes Citra to crash as it is
trying to load icon data from code.bin because of a typo. This commit
fixes that typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4812)
=> ncch_container: Fix code.bin replacement

src/core/hle/service/csnd/csnd_snd.cpp, src/core/hle/service/csnd/csnd_snd.h
I am not sure if I am going to finish this to the end (=perfect sound output), but at least we should have a good foundation to work on. I would take off the [WIP] whenever I (and anyone) don't feel like working on it, and the code can be merged as a partial progress.
CSND is a sound engine in 3DS that seems highly parallel to the DSP. It is used by applets (to avoid conflict with games using DSP) and old homebrew apps (before people figured out how to use DSP). It supports up to 32 channels sound output of PCM/ADPCM/PSG sqaure wave/noise, and two sound capture units. Its functions are very similar to the DS sound engine, but has different MMIO layout and some other different stuff. It is theorized that CSND is DS sound 2.0, which has compatible interface in DS mode, while having new …
=> Foundation for CSND

src/video_core/renderer_opengl/gl_rasterizer.cpp
The previous version would break when the state changes from (cube=true,mipmap=false) -> (cube=true,mipmap=true)
Meant to fix #4821 but I didn't test. @tom-overton could you help?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4822)
=> gl_rasterizer: correct supress_mipmap_for_cube logic

src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/lobby.cpp
See yuzu-emu/yuzu#2550 for more details.
Passes three defines that Qt doesn't enable by default that make it harder to introduce bugs in Qt frontend code. Mainly makes it so written code is required to be more explicit in expressing its intent. e.g. if narrowing is desirable, it should be explicitly handled so it's made evident the writer intended that behavior to happen, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4807)
=> Port yuzu-emu/yuzu#2550: "yuzu/CMakeLists: Pass compilation flags that make it more difficult to cause bugs in Qt code"

src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/configuration/configure_audio.h, src/citra_qt/configuration/configure_camera.cpp, src/citra_qt/configuration/configure_camera.h, src/citra_qt/configuration/configure_debug.cpp, src/citra_qt/configuration/configure_debug.h, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_dialog.h, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.h, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.h, src/citra_qt/configuration/configure_hotkeys.cpp, src/citra_qt/configuration/configure_hotkeys.h, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/configuration/configure_motion_touch.h, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.h, src/citra_qt/configuration/configure_ui.cpp, src/citra_qt/configuration/configure_ui.h, src/citra_qt/configuration/configure_web.cpp, src/citra_qt/configuration/configure_web.h, src/citra_qt/main.cpp
See yuzu-emu/yuzu#2521 for more details.
Makes the naming of functions match our project style (CamelCase), unless a Qt function is being overridden. Figured I'd get this out of the way before performing future work on making the configuration dialog itself more friendly when it comes to future handling translations (handling LanguageChanged events, which only one dialog tab handles properly right now; the game list tab)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4823)
=> Port yuzu-emu/yuzu#2521: "yuzu/configuration: Make function naming consistent"

src/core/core.cpp, src/core/core.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/thread.cpp, src/core/memory.cpp, src/core/memory.h, src/tests/core/arm/arm_test_common.cpp
This removes cpu_core instance from memory.cpp making cpu_core and memory being completely independent components inside the system, having a simpler and more understandable initialization process
The thread which casues page table changes in memory will be responsible of notifying the cpu_core too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4799)
=> kernel: handle all page table changes internally when switching processes

src/CMakeLists.txt, src/citra/citra.cpp, src/dedicated_room/citra-room.cpp
See yuzu-emu/yuzu#2404.
Previously we were building with MBCS, which is pretty undesirable. We want the application to be Unicode-aware in general.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4804)
=> Port yuzu-emu/yuzu#2404: "CMakeLists: Ensure we specify Unicode as the codepage on Windows"

src/network/room_member.h
Otherwise produces multpile definition in translation units and generates unused warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4833)
=> network/room_member: in-header function should be inline

src/citra_qt/debugger/profiler.cpp
This is indeed confusing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4835)
=> citra_qt/profiler: add parenthesis to silent warning

src/citra_qt/cheats.cpp, src/citra_qt/multiplayer/chat_room.cpp
🖕Qt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4836)
=> citra_qt: silent sign comparison warning

src/core/hle/ipc_helpers.h
index is only used as positive index in arrays. The warning is in DEBUG_ASSERT_MSG(index == TotalSize() ...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4839)
=> ipc_helpers: silent signed comparison warning

src/citra_qt/configuration/configure_motion_touch.ui
Fixes #4840, hopefully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4841)
=> citra_qt/configure_motion_touch: fix slot name

src/citra_qt/main.cpp, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_ncch.h, src/core/hle/service/am/am.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp
Some unused variables are still kept in services, as they are parameters passed from the command buffer and might be used in the future
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4832)
=> Remove unused stuff

src/citra_qt/cheats.cpp, src/citra_qt/configuration/configure_debug.cpp, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/client_room.cpp, src/citra_qt/multiplayer/direct_connect.cpp, src/citra_qt/multiplayer/host_room.cpp, src/citra_qt/multiplayer/lobby.cpp
This PR fixes a few UI buttons reacting to incorrect signals. Previously, a few buttons did not follow the standard UI behaviour and instead of reacting to button **click** (press & release), they executed their actions on **press**. This led to a bit inconsistent experience.
Affected dialogs:
- Cheats
- Configure/Debug
- Configure/Input
- Chat Room
- Direct Connect
- Host
- Lobby List
While this may look like a mass Find & Replace, each case has been analyzed separately and tested for regressions.
To observe the changes easiest, do the following:
1. Navigate to `Emulation -> Configure -> Controls -> Input`
2. Press the mouse button when hovered over `New`. Do **NOT** release it.
3. Move the mouse cursor outside the button, **without** releasing left mouse button.
"New Profile" dialog …
=> Fixed behaviour of some buttons by connecting functors to correct signals

src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/dyncom/arm_dyncom.h
Fixing a couple of compiler warnings on clang complaining about some forward declarations that didn't match the signature of the `System` class.
if this is not useful please feel free to close!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4851)
=> Fixing some compiler warnings in core/arm/

src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/loader/ncch.cpp
This allows an IPS patch to edit .bss. This is useful for game patches
that need to add code, as putting things in .bss allows adding new code
*without* editing .code and thus without having to relocate everything.
(Thanks for @wwylele for the suggestion!)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4817)
=> ncch_container: Apply IPS patch after allocating .bss

src/network/room_member.h
Fixes some compiler warnings from clang. 
I think the `"Unknown'` return statement would never be reached without using `default`.
if this is not useful please feel free to close!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4852)
=> Added default case for GetErrorStr, removed useless const declaration in header

src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/config.h
See yuzu-emu/yuzu#2504 for more details.
Allows the configuration code to build successfully with implicit string conversions disabled. I got a little ahead of myself in the previous conversion-related PR. The following PR after this one, will be the one that addresses main.cpp and disables implicit conversions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4858)
=> Port yuzu-emu/yuzu#2504: "yuzu/configuration/config: Specify string conversions explicitly"

src/citra_qt/configuration/configure_audio.cpp, src/citra_qt/configuration/configure_camera.cpp, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_ui.cpp, src/citra_qt/configuration/configure_web.cpp
See yuzu-emu/yuzu#2499 for more details.
Like the previous changes in the same vein, this moves the UI code a step closer to disabling implicit string conversions. This makes the configuration window compatible with disabled implicit QString conversions. After this, all that's left is to deal with some of the top-level source files in the project directory and the conversions can be disabled.
This also uncovered some strings that weren't marked as translatable but should have been. These are also corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4860)
=> Port yuzu-emu/yuzu#2499: "yuzu/configuration: Specify string conversions explicitly"

src/citra_qt/debugger/graphics/graphics.cpp, src/citra_qt/debugger/graphics/graphics_breakpoints.cpp, src/citra_qt/debugger/graphics/graphics_cmdlists.cpp, src/citra_qt/debugger/graphics/graphics_surface.cpp, src/citra_qt/debugger/graphics/graphics_tracing.cpp, src/citra_qt/debugger/graphics/graphics_vertex_shader.cpp, src/citra_qt/debugger/lle_service_modules.cpp, src/citra_qt/debugger/profiler.cpp, src/citra_qt/debugger/registers.cpp, src/citra_qt/debugger/wait_tree.cpp
See yuzu-emu/yuzu#2492 for more details.
Another set of changes that brings us slightly closer to disabling implicit string conversions in Qt code. This makes all of the string conversions explicit in the debugger, which is relatively lower traffic in terms of changes compared to the rest of the UI code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4856)
=> Port yuzu-emu/yuzu#2492: "yuzu/debugger: Specify string conversions explicitly"

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp
fix some type cast in shader.
`GL_TEXTURE_LOD_BIAS` doesn't support in opengl es.
`GetTexImageOES` use wrong width and height for scaled texture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4859)
=> minor fix for opengles

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.h, src/citra_qt/configuration/configure_graphics.ui, src/common/common_paths.h, src/common/file_util.cpp, src/common/file_util.h, src/core/frontend/emu_window.cpp, src/core/hle/kernel/shared_page.cpp, src/core/hle/kernel/shared_page.h, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_shader_util.cpp, src/video_core/renderer_opengl/post_processing_opengl.cpp, src/video_core/renderer_opengl/post_processing_opengl.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/video_core.cpp, src/video_core/video_core.h
Adds support for the majority of Dolphin's glsl post-processing shaders.
Primarily done to add support for different types of Anaglyph 3D, which effectively required adding custom shader support.
For convenience when setting up Anaglyph 3D, the 3D slider can now be adjusted via the configuration menu while the game is running.
A red-cyan Anaglyph Dubois shader is built-in so Anaglyph 3D can be used without further configuration.
Custom shaders can be added in the new shaders folder in the Citra data directory, and
other flavors of Anaglyph can be added in the new shaders/anaglyph directory.
I wasn't quite sure how to structure this, and it's mostly based on my interpretation of the structure of similar components.
Screenshots of the new settings layout:
Stereoscopy modes:
Default shader …
=> renderer_opengl: Add support for custom shaders

src/video_core/renderer_opengl/gl_rasterizer.h
We recently had increased reports about flickering issue in pokemon games on Nvidia graphics. This issue has been known since day 1 of hardware shader + vertex buffer streaming. The root cause has never been found. However, it was found that whether it flickers or not depends on vertex buffer size, or video memory usage in general. Originally we adjusted this size in the hardware shader PR to reduce the flickering. Recently, we merged some seemingly unrelated PR to video core (like screenshot, video capture etc.), which might affect this due to more video memory usage. I want people to test if reducing the size helps anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citr …
=> [EXPERIMENT] gl_rasterizer: decrease vertex buffer size

src/citra_qt/main.cpp
if you start a bundle(binary) on osx from without the terminal to working directory is /
But since we require to working directory to be the executable path for the location of the user folder in the Qt Frontend we should cd into that working directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4877)
=> citra_qt: on osx chdir to bundle dir to allow detection of user folder

src/citra_qt/game_list_p.h, src/core/loader/smdh.cpp, src/core/loader/smdh.h
This supersedes #4846.
The perfect solution would be to display images of flags. But this can come in a later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4878)
=> Citra_qt: Display all valid regions in game_list

src/core/loader/smdh.cpp
Adds a simple hack to fix China-compatible Taiwan-region games from displaying incorrectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4846)
=> Fix incorrect display of some Taiwan region games

src/citra_qt/main.cpp
Fix compile error on Windows caused by #4877 
Weird, I thought I saw this guard during the code review...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4884)
=> Guard unistd.h with MacOS only macro

appveyor.yml
The following is just a copy of commit messages.
The original purpose of freezing CMake is to use a **higher** version than supplied in order to fix a certain issue. Now that a very long time has passed and mingw's CMake has been updated, there's really no reason to still freeze it any more. What's more, trying to use a certain version is unreliable by pacman's design and will probably cause issues for using older versions of dependencies. The current (and previous) mingw errors may come from this...
Cyclical dependencies will result in errors. Redirecting err to null doesn't help. I removed the redirection so that errors and warnings would show up (they might be useful for us). 
As FFmpeg is added, even more cyclical dependencies are present now. I do not want to figure out what to …
=> Fix appveyor mingw (partially)

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/core/core.cpp, src/core/core.h, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/hid/hid.cpp, src/core/perf_stats.cpp, src/core/perf_stats.h, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp
Supersedes - https://github.com/citra-emu/citra/pull/4636
After addressing many of the concerns in #4636, and running into places where this would be really handy, I want to re-open frametime logging for review. 
When discussing changes to citra that affect performance, we don't have any framework in place for logging performance changes between builds. This has caused, at worst, several "I recall" situations where people try to remember what impact a change had on performance, and at best, other situations where people pull up speed% numbers that they tried their best to sample at the right time in between tests. This change should give better insight into real performance differences between builds allowing us to make more informed decisions when changing the code base.
* No longer an …
=> Frametime logging for tracking performance over time

src/core/core.cpp, src/core/core.h, src/core/telemetry_session.cpp
Fixes an error where it causes citra to crash on second game launch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4891)
=> Fixup! Prevent issue deleting PerfStats

.travis/linux-mingw/docker.sh, CMakeLists.txt, src/CMakeLists.txt
Also, I disabled it for the Linux MinGW build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4885)
=> Add MinGW CMake option to disable DWARF debugging information

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/command_processor.cpp, src/video_core/video_core.cpp, src/video_core/video_core.h
This setting is currently set to be enabled by default and when disabled causes performance loss in games that use GS and can cause graphical glitches. There should be no instance where turning it off is beneficial so let's just remove the option to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4879)
=> Remove 'Accurate Geometry Shader' setting

src/network/room_member.h
This causes lots of warnings. Adding the Uninitialized case solves this
Fixes 24 of all 100 -Wswitch warnings :sunglasses:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4898)
=> network/room_member: Silence -Wswitch warning

src/core/hle/service/apt/applet_manager.cpp
LLE Applets are enabled again in #4500, but @wwylele didn't remove these comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4907)
=> applet_manager: remove the "we are going to disable loading LLE applets before further fixes are done" comments

src/citra_qt/configuration/configure_input.cpp
When a user clicks the "Set Analog Stick" button, Citra will pop up an information window with instructions for setting it up. 
The message reads "After pressing OK, first move your joystick horizontally, and then vertically."
There's a small incongruence between what the message says and the actual behavior, as Citra will try to accept an input even if the user closes the information window by pressing 'Esc' or by clicking the 'x' (not sure how to properly call it).
This PR proposes the addition of a 'Cancel' button and a check for the button clicked by the user. 
According to the Qt documentation, this will also assign 'Cancel' as the Escape Button, triggering it when the user presses 'Esc'.
--- …
=> Add a cancel option to analog stick configuration

src/citra_qt/main.cpp
The stuck in fullscreen mode bug happens if the emulated program exits, is fixed by adding [this](https://github.com/citra-emu/citra/compare/master...vvanelslande:hotkey-and-fullscreen-fixes?expand=1#diff-5e8bf22f5c3b3579c402308dd96b7563R888-R894), steps to reproduce:
- Start [FBI](https://github.com/Steveice10/FBI)
- Press START
The fixed hotkeys (I changed them to use [connect](https://doc.qt.io/qt-5/qobject.html#connect) instead of [setShortcut](https://doc.qt.io/qt-5/qaction.html#shortcut-prop) + [setShortcutContext](https://doc.qt.io/qt-5/qaction.html#shortcutContext-prop)) are:
- Load File (was not working in windowed mode), fixed by removing the [setShortcut](https://doc.qt.io/qt-5/qaction.html#shortcut-prop) + [setShortcutContext](https://doc.qt.io/qt-5/qaction.html#shortcutContext …
=> citra_qt: fix the stuck in fullscreen mode and hotkey bugs

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h
Continuation of #4879, removing dead code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4894)
=> opengl: remove hw geometry shader related stuff

src/core/core_timing.h
This is causing a lot of warnings all over the place.
Fixes 986 of the 1,053 -Wsign-compare warnings 😎
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4897)
=> core_timing: Silence sign comparison warnings

src/citra_qt/main.cpp, src/citra_qt/main.h
Fixes #4870 , uses the provided [SetThreadExecutionState](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate) function to keep display and system awake while a game is being played.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4914)
=> Fix to Windows sleep issues

src/core/hle/service/gsp/gsp_gpu.h, src/core/hle/service/ptm/ptm.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp
Silences some warnings (C4099, C4101, C4834) related to a mismatched declaration and unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4918)
=> Silence warnings from unused code and mismatched declaration

src/core/perf_stats.cpp
See citra-emu/citra#2818 for more details.
Should fix https://github.com/citra-emu/citra/issues/4766.
This is required for yuzu to build on Linux.
Credit to @Cleverking2003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4915)
=> Port citra-emu/citra#2818: "externals: update fmt to 6.0.0"

src/core/hle/service/nfc/nfc.cpp, src/core/hle/service/nfc/nfc.h
Because I don't like changing UX for fixing a core bug like in #4890, I decided to PR my proposed alternative. Still, huge thank to @vvanelslande for discovering the bug and provideing research info. I haven't tested my code. Could you help me test it?
----
Added a new state amiibo_in_range. This state is akin to the real world
physical relationship between a 3DS machine and an amiibo, which is
independent from the service state (or even the machine is powered on or
not). The service state nfc_tag_state is then synchronized with this
physical state on every potential point when the state changes. This
solves the issue where user might load an amiibo before NFC service
initializes, or remove an amiibo after NFC service shutdown, which
previously causes inconsistent state change.
Also …
=> NFC: extract frontend-facing tag state

src/citra_qt/configuration/config.cpp
Changes the code to use the defined enums instead of magic numbers.
Shouldn't change functionality or UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4925)
=> Change the coding style of GameListIconSize bounds check to use the enum

src/core/hle/kernel/wait_object.h
`intrusive_ptr` isn't used in the code anymore, so this shouldn't be needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4933)
=> Remove unused boost header

src/video_core/command_processor.cpp, src/video_core/regs.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
the compiler bug appears to be fixed so there's no reason to keep this around
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4936)
=> remove ugly msvc hack

src/citra_qt/game_list_worker.cpp, src/core/loader/loader.h, src/core/loader/ncch.cpp, src/core/loader/ncch.h
Currently, installing game CIAs will add a bunch of unusable entries for extra NCCH files like manual data. This change checks the executable bit in the NCCH header and filters non-executable entries out of the game list.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4922)
=> Filter non-executable files out of the game list.

src/core/hle/kernel/mutex.cpp, src/core/hle/kernel/thread.h, src/video_core/swrasterizer/clipper.cpp
Other boost headers that may not be needed anymore.
I checked flat_map manually, was added on commit 17b29d8865ea4d96c18f7e1671bd6d0f01eab95f and removed on commit fd95b6ee2606da4cd47c5f2916ad3b4f86c0e0f4 . (~~Is there a better way to refer to them?~~ nvm, github links them properly)
vector seems to be there since before github tracking, so I don't know.
erase doesn't look like it was ever needed (the code uses the flat_set erase public method), was introduced in commit 4e84df8be30c5bac65e4c4e9faf07bf0fc3fb33a
(This can be saved for a rainy day)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4934)
=> Remove boost headers not currently used

src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_ui.ui, src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h, src/citra_qt/uisettings.h, src/core/loader/smdh.cpp, src/core/loader/smdh.h
I noticed that sometimes, the game name is shortened even though there was enough space for it. Investigating the code, I discovered Citra uses the short_title provided by the game, and it would be possible to use the long_title without much trouble.
Adds the option to display the full title of the game to the configurations. 
Changes the search to use the long_title instead of the short_title.
As some long titles contain newlines, strips them before displaying.
Fixes part of the motivation for #4593 
> many games don't show the full name, or sometimes it just shows the initials of the game so it's better to show the file name
I'm still trying to figure out the quirks of how the sorting of the titles is done, so it's not a full fix yet.
--- …
=> Allow displaying the long_title of the game

src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_general.ui, src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/uisettings.h
Addresses and should close #4481. 
Creates the option for Citra to pause when it's in the background or minimized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4930)
=> Pause when in background

src/citra_qt/CMakeLists.txt, src/citra_qt/debugger/ipc/record_dialog.cpp, src/citra_qt/debugger/ipc/record_dialog.h, src/citra_qt/debugger/ipc/record_dialog.ui, src/citra_qt/debugger/ipc/recorder.cpp, src/citra_qt/debugger/ipc/recorder.h, src/citra_qt/debugger/ipc/recorder.ui, src/citra_qt/main.cpp, src/citra_qt/main.h, src/core/CMakeLists.txt, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/ipc.cpp, src/core/hle/kernel/ipc.h, src/core/hle/kernel/ipc_debugger/recorder.cpp, src/core/hle/kernel/ipc_debugger/recorder.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/svc.cpp, src/core/hle/service/service.cpp, src/core/hle/service/service.h, src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
This is based on @Subv's request on Discord (in a private channel) about half a month ago. I posted the chat [here](https://pastebin.com/vk2dRyNK) for anyone interested.
This implementation here basically satisfies all the needs, but the filter is built in the frontend instead of the core. The IPC requests are very frequent (actually a lot over 100 per second), which means that it is not feasible to keep this recorder on for a long time, as both time and memory costs can be high. However it should be okay for debugging purposes. My not-so-powerful laptop can have Pokemon UM run at 3x at near 150% speed while also recording all the 30000+ requests (gdb unattached), but the Qt widget does seem a bit unresponsive while browsing, and there was a substantial input delay of over a second for …
=> core, citra_qt: IPC Recorder

src/citra/citra.cpp, src/citra/emu_window/emu_window_sdl2.cpp, src/citra/emu_window/emu_window_sdl2.h
Also fix a small issue with incorrect shutdown ordering in SDL.
Previously the system would still be running so the telemetry task
didn't launch and detached_tasks would assert(count == 0)
I'm adding this so that we can visually have people test to see if theres a performance difference between SDL and Qt. We techincally could have them turn on frametime logging, but thats still *slightly* unreliable since we learned about how SwapBuffers() isn't included in frametime calculations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4950)
=> Add FPS to SDL title bar

src/citra_qt/debugger/ipc/record_dialog.cpp
The OK button didn't do anything before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4946)
=> citra_qt/RecordDialog: close when OK is clicked

src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h, src/citra_qt/game_list_worker.cpp, src/citra_qt/game_list_worker.h
See yuzu-emu/yuzu#2942 for more details.
Silence miscellaneous warnings. Description in individual commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4985)
=> Port yuzu-emu/yuzu#2942: "Silence miscellaneous warnings"

src/citra_qt/configuration/configure_web.cpp, src/citra_qt/configuration/configure_web.ui, src/dedicated_room/CMakeLists.txt, src/dedicated_room/citra-room.cpp
citra_qt: configure_web: Use Base64 encoded token for simplifying user experience.
This is a change we are making for both citra and yuzu across all clients. It's purely a user-facing/UI change, to make the experience of adding your credential simpler - it's just a simply copy+paste of one string.
Obligatory UX changes:
@chris062689 @jroweboy as FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4993)
=> citra_qt: configure_web: Use Base64 encoded token

src/citra_qt/main.ui
Self-explanatory. No UI changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4953)
=> citra_qt/main.ui: remove unused actions "Load Symbol Map..." and "Select Game Directory..."

src/dedicated_room/citra-room.cpp
Instead of adding a `detached_tasks.WaitForAllTasks();` to the `if (in.size() > 0)`, this PR changes the `if (in.size() > 0)` body to a `break;` because when the `while (room->GetState() == Network::Room::State::Open)` ends, all the current code in the `if (in.size() > 0)` and the `detached_tasks.WaitForAllTasks();` runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4998)
=> dedicated_room: fix crash (count != 0) when closing the room

src/video_core/renderer_opengl/gl_shader_gen.h
This comment is no longer applicable. TexStageConfigRaw remains unchanged to avoid hashing const_color.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5004)
=> video_core: remove MSVC hack comment on TevStageConfigRaw

src/dedicated_room/citra-room.cpp
Username passed to `room->Create` was always empty if using the new token format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5002)
=> Fix moderation by room host in dedicated rooms

src/common/logging/backend.cpp
See yuzu-emu/yuzu#3123 for more details.
Silence no return value warnings with asserts enabled and disabled on common logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5006)
=> Port yuzu-emu/yuzu#3123: "common/logging: Silence no return value warnings"

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/game_list_p.h, src/citra_qt/game_list_worker.cpp, src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/lobby_p.h, src/citra_qt/multiplayer/state.cpp, src/citra_qt/multiplayer/validation.h, src/citra_qt/updater/updater_p.h
Also see https://github.com/yuzu-emu/yuzu/pull/2503.
Makes all top-level source files compilable with implicit Qt string conversions disabled. Now all that's left is to address main.cpp, which I'll do in a follow-up PR, as it's quite a large file, and would like to have those changes reviewed separately. The follow up change will also finally pass compilation flags that disable implicit Qt string conversions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4992)
=> yuzu/game_list&multiplayer: Specify string conversions explicitly

src/common/assert.h
We relies on UNREACHABLE's noreturn attribute to eliminate parent's "no return value" warning. However, this was wrapped in a `if(!false)` block, which compilers may not unfold to recognize the noreturn nature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4964)
=> unfold UNREACHABLE implementation for dumb compilers

src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h
Should fix #4593.
As the issue might not be entirely clear, I'll offer a short explanation from what I understood from it and found from experimentation.
Currently Citra offers the user the option do change the text that's displayed in the "Name" column in the game list. Generally, it is expected that the items are sorted based on the displayed text, but Citra would sort them by title instead.
Made it so that an access to SortRole returns the same as DisplayRole.
There shouldn't be any UI changes, only change in behaviour.
Also fixes a bug with directory sorting, where having the directories out of order would enable you to try to "move up" to the addDirectory button, which would crash the emulator.
~~(There's still one thing I'd like to investigate and try to include in this PR, which is …
=> Fixes to game list sorting

src/core/hle/applets/swkbd.cpp
The text shared memory wasn't supposed to be cleared according to my comparison with the LLE swkbd. This can cause issues in certain games such as Harvest Moon.
A null terminator is added to the text copied to mark the end of the string.
Fixes #4178.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5016)
=> applets/swkbd: Remove text memory clearing

src/video_core/regs_pipeline.h
The index_array can't possible be 31 bits long as that would index
out of bounds memory. According to 3dbrew, this should be 28
Fixes https://github.com/citra-emu/citra/issues/3984 and maybe a few other crashes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5023)
=> Use the correct register length for index_array

src/audio_core/CMakeLists.txt, src/audio_core/hle/decoder.h, src/audio_core/hle/ffmpeg_decoder.cpp, src/audio_core/hle/ffmpeg_decoder.h, src/audio_core/hle/hle.cpp, src/audio_core/hle/wmf_decoder.cpp, src/audio_core/hle/wmf_decoder.h, src/audio_core/hle/wmf_decoder_utils.cpp, src/audio_core/hle/wmf_decoder_utils.h
This should resolve issues people have with mf.dll missing errors by changing mf.dll from loadtime loading to runtime loading. If the user doesn't have Media Foundation it will try FFMpeg (if the compilation option for that was turned on) and lastly it'll fall back to the null decoder option if all else fails. I haven't throughly tested the MF -> FFMPEG fallback but it should be *good enough* i hope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5020)
=> Runtime Load MediaFoundation dlls on Windows

src/core/telemetry_session.cpp
Was removed as part of #4940 but readded again. Brings it back with the same name as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5028)
=> Add missing vsync telemetry field

src/audio_core/hle/ffmpeg_decoder.cpp
Simple cut/paste issue where initialized is only set to true when the
emulation attempts to init the Binary Pipe, but we used it to test if
the FFMPEG decoder was valid and disabled it if it wasn't. Just return
the value of have_ffmpeg_dl instead so when dynamic loading is added
it'll still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5027)
=> Reenable AAC FFMPEG decoding

src/common/logging/backend.cpp, src/common/logging/log.h
The regex here is run on the emulation thread, and can cause slowdowns when there is excessive logging. Now the source file path trimming should be done at compile time.
https://godbolt.org/z/3vqPvB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5039)
=> common/logging: don't use regex for path trimming

.travis/macos/deps.sh
Dunno why brew errored out so hard with python already installed but this seemed to fix it for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5056)
=> Attempt to fix macOS build

src/citra_qt/game_list_worker.cpp
If the game has an update but the update does not have a valid SMDH, it will now default to the original application's SMDH. 
This should fix some problems where games do not appear on the list that should.
Possibly related to #4117 or #3658 however those both seem to be present before this filtering was implemented.
**Before (Hide Titles without Icon off):**
**After:**
*graphical glitches unrelated*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5033)
=> qt: do not use an invalid update smdh

src/core/CMakeLists.txt, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/file_sys/patch.cpp, src/core/file_sys/patch.h, src/core/loader/ncch.cpp
The BPS format allows distributing patches that are smaller and that do
not contain copyrighted content if data is relocated
(unlike non-trivial IPS patches).
This is essential for games such as *Majora's Mask 3D* that have three barely
different code revisions. Supporting all three versions would
demand an unreasonable amount of work; with BPS patches only one
version has to be supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5036)
=> file_sys: Add support for BPS patching

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/configure_enhancements.cpp, src/citra_qt/configuration/configure_enhancements.h, src/citra_qt/configuration/configure_enhancements.ui, src/core/settings.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h
This adds support for interlaced 3d (common in passive 3d supported monitors and tv screens).
Images:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5018)
=> Interlaced stereo 3d option

src/citra_qt/main.ui
See yuzu-emu/yuzu#3316 for more details.
Fixes yuzu-emu/yuzu#1898.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5061)
=> Port yuzu-emu/yuzu#3316: "Add headbar icon on Linux"

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_enhancements.cpp, src/citra_qt/configuration/configure_enhancements.ui, src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/main.ui, src/core/frontend/emu_window.cpp, src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h, src/core/settings.cpp, src/core/settings.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h
Some games use this orientation for some or all of the gameplay. Closes #1534.
example (game doesn't use the orientation, but I don't have one that does):
Open to suggestions for the naming of the layouts.
Changes to configuration:
Changes to the menu:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5043)
=> Implement Upright/Book-style layout

src/audio_core/hle/source.cpp
This is a HACK, but we also shouldn't freeze the users computer by allocating more RAM than they could possibly have, so I am opening this with full intention to merge anyway. I've researched this issue fairly extensively so far without any proper fix for it yet, so I will open an issue about fixing this hack.
Details:
In Luigi's Mansion Dark Moon in HLE audio, the game mysteriously passes in an extremely large value for length, which without any checks, causing HLE audio to allocate an extremely large buffer.
This value seemingly is caused by some other missing or incomplete HLE audio feature. The game seemingly reads a value from the DSP and subtracts to get a length, without checking for underflow first. This appears to be caused by an incorrect HLE audio emulation something-or-other, …
=> Prevent out of memory errors when the game passes in an improper length value

src/citra_qt/configuration/configure_enhancements.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Two commits here:
* Check for hw shader when loading the disk cache. This is the actual fix for the issue.
* Prevent people from selecting disk cache when hw shader is disabled. Since its on a different UI tab its a little wonky, but its probably "good enough". This is just to update the config window when disk shader cache is effectively disabled.
As this is affecting Mac users in nightly, I'd like to get this merged quickly. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5072)
=> Dont load Disk Cache when HWShader is disabled

src/citra_qt/CMakeLists.txt, src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/citra_qt/loading_screen.cpp, src/citra_qt/loading_screen.h, src/citra_qt/loading_screen.ui, src/citra_qt/main.cpp, src/citra_qt/main.h
Until we get a on screen display or async shader loading, we should at
least have some measure of progress in the meantime. This is 90% a port
from the loading screen I made for yuzu, but with a slightly different
changed detection for when to display the ETA. Now we keep track of a
rolling estimate for shader load ETA and only display a ETA if its going
to take longer than 10 seconds.
The gif might cut out, but whatever. It already works fine in yuzu and I tested it pretty well here too https://i.imgur.com/enHMyqS.gifv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5071)
=> QT Frontend: Add disk shader loading progress bar

src/core/settings.cpp
Currently the loading process of the cached shaders has a couple logs for successfully finding shaders, but logging the setting itself would help with miscellaneous and unexpected issues caused by the setting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5073)
=> Log disk shader cache setting

src/core/frontend/applets/swkbd.cpp, src/core/frontend/applets/swkbd.h
Fixes #4938.
The DIGIT filter was incorrectly implemented as preventing all digits. It actually limits the maximum digit count to max_digits, according to ctrulib and hardware testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5086)
=> swkbd: Fix digit filter

src/citra_qt/bootmanager.cpp, src/core/frontend/emu_window.cpp, src/core/frontend/emu_window.h, src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h
Currently the minimum window size is always based on the default layout, but users might want to resize the window differently depending on the current layout. 
This change also prevents sub 1x window sizes for the different layouts.
(For the large layout, the minimum size is calculated based on the top screen)
closes #2675
As discussed on discord, it might be better to wait to merge this until after the incoming changes to layout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5069)
=> Update minimum window size based on current layout

dist/qt_themes/qdarkstyle/style.qss, src/citra_qt/uisettings.cpp
See yuzu-emu/yuzu#3339 for more details.
This PR fixes few minor UI issues with dark themes also trying to mimic more "Default" ("Light") mode styling and component sizes to avoid resize on theme change. The following changes has been made:
- mimic "Default" theme list headers styling - use list background color, border omission, no extra padding - **_Screenshot 1_**
- decrease contrast of even rows on the lists to mimic "Default"  theme styling and differentiate those rows more from Status Bar or Filter Bar - **_Screenshot 1_**
- update tabs minimal size and padding to roughly match "Default" theme styling - **_Screenshot 2_**
- fix Main Menu and Context Menu (ex. game row) checkbox position and items padding - **_Screenshot 3_**
- fix ComboBox currently …
=> Port yuzu-emu/yuzu#3339: "GUI: fix minor issues with dark themes + rename and reorder themes"

src/core/hle/service/hid/hid.h, src/core/hw/gpu.cpp, src/core/hw/gpu.h
GPU_REG_INDEX_WORKAROUND is no longer necessary
ASSERT_REG_POSITION now works properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5099)
=> core: Remove outdated MSVC workarounds

externals/CMakeLists.txt, externals/android-ifaddrs/CMakeLists.txt, externals/android-ifaddrs/ifaddrs.c, externals/android-ifaddrs/ifaddrs.h, externals/httplib/README.md, externals/httplib/httplib.h, src/core/CMakeLists.txt, src/core/hle/service/http_c.cpp, src/core/hle/service/http_c.h, src/web_service/CMakeLists.txt, src/web_service/web_backend.cpp
This will send the request in HTTP_C (at least with empty body requests). 
Functions to receive any data from the response aren't implemented yet.
There are some design issues I would like to discuss, before merging this:
- libressl, httplib and lurlparser are now required for every build. Should they still be guarded by a cmake flag?
- the httpblib::Response is member of Context. This is necessary since games can access the headers and the already downloaded data while download is still in progress. Any design ideas on how to make this better?
- I had to edit httplib so we could set some SSL functions, since HTTP_C needs this. I'm not sure this is the best way to go. Note that I had to edit the url encoding. So far the only char that I tested was ":", though. Other might be problematic …
=> HTTP_C::Implement Context::MakeRequest

src/video_core/renderer_opengl/gl_rasterizer_cache.h
GCC and MSVC copy the table at runtime with the old implementation, which is wasteful and prevents inlining. Unfortunately, static constexpr variables are not legal in constexpr functions, so the table has to be external.
Also replaced non-standard assert with DEBUG_ASSERT_MSG.
[Relevant compiler output](https://godbolt.org/z/-whv8_)
Ideas for how to do this without exposing the table are welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5101)
=> videocore/renderer_opengl/gl_rasterizer_cache: Move bits per pixel table out of function

bitrise.yml, src/CMakeLists.txt
~~C++17 is already specified through cmake~~
apparently this doesn't work before CMake 10, but the below warning is still fixed by specifying /std:c++17
fixes MSVC spamming the following:
> \source\repos\citra\out\build\x64-Debug\cl : Command line warning D9025: overriding '/std:c++latest' with '/std:c++17'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5047)
=> fix c++ standard flag for msvc

src/citra_qt/debugger/ipc/recorder.cpp
Fixes a segfault when using the IPC Debugger by calling a NULL pointer.
The IPC Debugger logs all IPC calls from tracing to element X. When clearing, we save the number of element X so that we know not to repeat already cleared IPC calls and show them accordingly. This was done by using the length of the treeBox. Unfortunately, after clearing once the list, the treeBox size cannot be up to date anymore, as past elements have been cleared, and as such some calculations were off leading to non-existing objects being processed.
This was replaced by using the offset calculated by the clear function added on top of the records list size.
--- …
=> ipc_debugger: Fixing NULL ptr call on multiple clear

src/citra_qt/game_list.cpp, src/citra_qt/game_list.h, src/citra_qt/main.cpp, src/citra_qt/main.h, src/core/CMakeLists.txt, src/core/core.cpp, src/core/file_sys/layered_fs.cpp, src/core/file_sys/layered_fs.h, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/file_sys/romfs_reader.cpp, src/core/file_sys/romfs_reader.h, src/core/loader/3dsx.cpp, src/core/loader/loader.h, src/core/loader/ncch.cpp, src/core/loader/ncch.h
Closes #4488.
This PR adds LayeredFS support to Citra. The directory structure is similar to yuzu's (but without mod names currently). Inside `user/load/mods/<Title ID>` (note: for updates, the Title ID is the original one) there can be up to three folders and one file:
- romfs: Files in this folder will replace the corresponding files in the RomFS. If a file does not exist in RomFS, it will be added.
- romfs_ext: Files in this folder deletes/patches the corresponding files in the RomFS. This allows modders to delete files within the romfs if a file of the same name but the extension `.stub` is found at the same directory within `romfs_ext`. Similarly, if a file with the same name but with extension `.ips` or `.bps` is found at the same directory within `romfs_ext`, the file will be …
=> core/file_sys: LayeredFS support

src/core/file_sys/ncch_container.cpp
You can now directly place ExeFS overrides/patches inside the mod folder (instead of the exefs subfolder). This allows us to have drop-in compatibility with Luma3DS mods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5110)
=> core/file_sys: Add alternative override pathes for ExeFS files

src/video_core/renderer_opengl/gl_rasterizer_cache.h
The default is discrete_interval which has dynamic open-ness.
We only use right_open intervals anyway. In theory this could allow some compile-time optimizations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5111)
=> video_core: use explicit interval type in texture cache

src/core/core.cpp, src/core/gdbstub/gdbstub.cpp, src/core/gdbstub/gdbstub.h
This fixes https://github.com/yuzu-emu/yuzu/issues/1850, a common issue between citra and yuzu's gdbstub implementation.
Under the citra-qt codebase, during the VideoCore shader initialization, the EmuThread->RunLoop logic, used to emulate the game and, among other things, handle gdbstub packets, is frozen. This ends up making gdb send back its packet a second time and eventually sending the next packet in the list, in our case qSupported followed by vMustReplyEmpty. By this time gdb is expecting a reply to vMustReplyEmpty, qSupported having been dropped but citra just decided to unfreeze the gdbstub thread and process the packets, replying to the answer of qSupported.
To fix that, I introduced a way to defer the initialization of the gdb stub to the first handling of packets. This has …
=> gdbstub: Ensure gdbstub doesn't drop packets crucial to initialization

src/core/hle/service/cam/cam.cpp, src/core/hle/service/cam/cam.h, src/core/hle/service/cam/cam_c.cpp, src/core/hle/service/cam/cam_s.cpp, src/core/hle/service/cam/cam_u.cpp
Hopefully fixes #3739, fixes #3794, fixes #4449. 
cc @RocketRobz @SatoshiOkujun @xxx169
According to HW tests, this vsync event is signaled for activated cameras at about the same frequency as the frame rate. The last 5 vsync timings are recorded (in microseconds) and can be retrieved with the service function.
Also, corrected the default frame_rate to 15, according to HW test.
This should fix the missing camera images in certain games. Note that, SynchronizeVsyncTiming is still stubbed currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5116)
=> service/cam: Implement Vsync interrupt events

src/core/hle/service/cfg/cfg.cpp
To be consitent with the Settings CFG savegame should also report the Model based on that setting. The savegame file itself isn't altered.
Logic is:
- If in cfg savegame any model is old and Settings:is_new_3ds is false, GetSystemModel will report the content of the savegame
- If in cfg savegame any model is new and Settings:is_new_3ds is false, GetSystemModel will report NINTENDO_3DS_XL
- If in cfg savegame any model is old and Settings:is_new_3ds is true, GetSystemModel will report NEW_NINTENDO_3DS_XL
- If in cfg savegame any model is new and Settings:is_new_3ds is true, GetSystemModel will report the content of the savegame
If we create a new cfg savegame the Model type written to the savegame will be based upon Settings:is_new_3ds either NEW_NINTENDO_3DS_XL or NINTENDO_3DS_XL
---
This …
=> CFG: Let GetSystemModel report model based on  Settings:is_new_3ds

src/video_core/renderer_opengl/texture_filters/bicubic/bicubic.cpp, src/video_core/renderer_opengl/texture_filters/xbrz/xbrz_freescale.cpp
Regressed by #5017. [FreeBSD](https://github.com/freebsd/freebsd/commit/c8ed04c26b6758354853a6bed4629f71d0d01a7d) and [OpenBSD](https://github.com/openbsd/src/commit/6ecde746dea9a5d17abf3bafa06c232b9189b33b) define `NULL` via `nullptr` in C++11 mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5137)
=> Unbreak build on FreeBSD

src/core/hle/service/fs/file.cpp
Fixes #4566, fixes #3627
The file's size is stored in FileSessionSlot and retrieved when the game calls GetSize. However, it is not updated when the file is written to, which can possibly change the file size. Therefore, this can cause GetSize to return incorrect results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5120)
=> service/fs: Update file size on write

src/common/thread_queue_list.h
The CI builds are failing because the compiler can't find std::find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5147)
=> common: include algorithm in thread_queue_list.h

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
In preparation for using texture views which require immutable storage, we need to add a separate allocation path for when immutable storage is available.
Immutable storage is basically the "sane" way to allocate textures in modern GL. You need only a single call to preallocate all of the storage that the texture might need and then thats that. No need to later add on mipmap levels like you do with glTexImage. The downside is that it might not be available on all cards that we support with a minimum of GL 3.3, so we have to support the old way as well.
I plan to use texture views for two things coming up soon:
* Faster subrect - useful for games that render into a power of two framebuffer, which we then need to subrect for the final frame. Subrect can be costly since it uses …
=> Use immutable storage when available

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Reverts citra-emu/citra#5053
Now that it's in nightly we're getting reports of crashes. I'm going to revert this until I can figure out why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5151)
=> Revert "Use immutable storage when available"

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_general.ui, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.ui, src/core/core.cpp, src/core/core_timing.cpp, src/core/core_timing.h, src/core/settings.cpp, src/core/settings.h, src/tests/core/arm/arm_test_common.cpp, src/tests/core/core_timing.cpp, src/tests/core/hle/kernel/hle_ipc.cpp, src/tests/core/memory/memory.cpp
This slider affects the number of cycles that the guest cpu emulation reports that have passed since the last time slice. This option scales the result returned by a percentage that the user selects. In some games underclocking the CPU can give a major speedup. Exposing this as an option will give users something to toy with for performance, while also potentially enhancing games that experience lag on the real console
For those that have seen "Custom Tick Hacks" this is that, but now with 100% less hardcoded-per-game values 👍 
Screenshot of UI change:
https://i.imgur.com/FsNQVod.png
I don't like having it on the first page in the settings as this is an advanced configuration option. I thinking about moving it to system if people agree with me (even though technically i think it fits …
=> Add CPU Clock Frequency slider

src/audio_core/hle/source.cpp, src/audio_core/interpolate.cpp
Currently the frame position moves ahead by the number of samples
output, but thats a fixed number based on the 3ds native sample rate.
Instead, based on a homebrew by cyuubi and looking at the lle audio,
this sample position should be moved forward by the number of samples
from the input buffer that was read, based on the buffer's sample rate.
This might fix the following issues related to audio playback/sync in citra 
- https://github.com/citra-emu/citra/issues/4649 
- https://github.com/citra-emu/citra/issues/5045 
- less likely, but it might fix games with issues in HLE but not LLE (won't affect games that don't work in LLE)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/ci …
=> HLE Audio: Increase frame position by input buffer sample rate

.travis/linux-flatpak/generate-data.sh
The docker image has been updated to 5.13 but the build script here wasn't. Maybe this was the issue preventing our flatpak from building recently
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5157)
=> flatpak: Update runtime version

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_system.ui, src/core/hle/service/ptm/ptm.cpp
This change should be fairly self-explanatory.
For all users who haven't messed with this setting before, it is no enabled by default.
Also a checkbox is added to the System settings to be able to toggle it.
I will add a screenshot as soon as I get QT Automoc to run again locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5117)
=> citra_qt/system: Add N3DS mode checkbox and enable it by default

CMakeLists.txt, appveyor.yml, src/input_common/sdl/sdl_impl.cpp
The change of SDL2 from 2.0.8 to 2.0.10 broke compatibility with some controllers that reported as Switch and Xbox One controllers.
Having SDL_HINT_JOYSTICK_HIDAPI set to "0" should get us the same behavior as before the change, as all of the reported problems stem from joysticks that have a hidapi driver implementation.
From some investigation, the current drivers try to write to the controller, for setting rumble, stick calibration, LED behavior and other similar tasks. 
Most or all of the users that had this problem and identified their controllers had non-official versions of the controllers. From the available information some of these controllers don't have some of the features the driver tries to use, and the driver fails to init the joystick in those cases.
Another reported issue …
=> SDL: Disable hidapi drivers due to compatibility problems with certain controllers

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_format_reinterpreter.cpp, src/video_core/renderer_opengl/gl_format_reinterpreter.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_surface_params.h
Succeeds #4902 and #4089
Adds RGBA4 -> RGB5A1 reinterpretation commonly used by virtual console
If no matching surface can be found, ValidateSurface checks for a surface in the cache which is reinterpretable to the requested format.
If that fails, the cache is checked for any surface with a matching bit-width. If one is found, the region is flushed.
If not, the region is checked against dirty_regions to see if it was created entirely on the GPU.
If not, then the surface is flushed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5170)
=> video_core/renderer_opengl/gl_rasterizer_cache: Create Format Reinterpretation Framework

src/citra_qt/bootmanager.cpp, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/main.cpp, src/core/hle/kernel/thread.cpp, src/network/room.cpp, src/network/room_member.cpp
The warnings were reported while compiling on macOS Catalina with
```
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5190)
=> Warnings: Fixed a few warnings from various places

src/citra_qt/debugger/wait_tree.cpp
It's easier to debug LLE bugs when you can actually see which thread belongs to which process in the wait list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5201)
=> Debuggers/Qt: Show the threads process names and ids in the WaitTree widget

src/video_core/renderer_opengl/gl_rasterizer.cpp
This fixes #5067 by reverting a speculative change made in a previous PR.
From this one can conclude that, for disabled textures, black (0,0,0,1) is the correct colour and clear (0,0,0,0) is not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5186)
=> Revert one change from #4844

src/core/arm/arm_interface.h, src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/dyncom/arm_dyncom.cpp, src/core/arm/dyncom/arm_dyncom.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/thread.cpp
The page tables were not being properly maintained when switching the current process of core1 (SysCore), this change fixes that.
This should allow LLE applets and sysmodules to boot again under the JIT.
See individual commits for the relevant changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5193)
=> Kernel/Process: Fixed scheduling multiple processes in the SysCore using Dynarmic

src/citra_qt/game_list_p.h, src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/direct_connect.cpp, src/citra_qt/multiplayer/host_room.cpp, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/message.cpp, src/citra_qt/multiplayer/message.h, src/citra_qt/multiplayer/state.cpp
Hopefully fixes some warnings from the Qt linguistics tool relating to the lack of context in some tr and QT_TR_NOOP calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5112)
=> Qt Linguistic warnings

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/texture_filters/scale_force/scale_force.cpp, src/video_core/renderer_opengl/texture_filters/scale_force/scale_force.frag, src/video_core/renderer_opengl/texture_filters/scale_force/scale_force.h, src/video_core/renderer_opengl/texture_filters/texture_filterer.cpp
This one is my own invention.
https://github.com/BreadFish64/ScaleFish/tree/master/scale_force
The idea is similar to Anime4K in that it detects short gradients and pushes the color values toward one side or the other; however, ScaleForce is a single pass shader, and produces much better all-around results in my testing.
example:  https://youtu.be/njCOsH062vE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5210)
=> video_core: add ScaleForce to texture filters

externals/cmake-modules/FindSDL2.cmake
For some reason, cmake was unable to find SDL2 on my Ubuntu (20.04) Budgie machine. I also work with SDL2 and have always been able to build with it provided that the full path was part of the SDL2 search paths. Adding it to this file made it possible to build Citra on my setup. 
For reference, here's my `uname -a`.
`Linux x 5.4.0-14-generic #17-Ubuntu SMP Thu Feb 6 22:47:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`.
I also tried adding only `/usr/include` to the search path, but it won't find the directory since it's called `SDL` instead of `SDL2`. Not sure why, but installing SDL2 on this setup doesn't label the directory correctly. The other way I managed to build was to create a symlink `/usr/include/SDL2 => /usr/include/SDL`, but I figured it'd be more developer-friendly if the search …
=> Added a search path in FindSDL2 for Ubuntu (Budgie) 20.04

externals/microprofile/microprofile.h
See yuzu-emu/yuzu#3497 for more details.
This adds the ability to access tokens directly and makes flipping microprofile after a fence instead of before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5132)
=> Port yuzu-emu/yuzu#3497: "Small corrections and features to microprofile"

src/core/core.cpp, src/core/gdbstub/gdbstub.cpp
1. Ensure that register information available to gdbstub is most up-to-date.
2. There's no reason to check for `current_thread == thread` when emitting a trap packet.
Doing this results in random hangs whenever a step happens upon a thread switch.
Not sure whether (1) is actually necessary. I'm planning on a refactoring of the JIT which will eventually make it a moot point anyway (using contexts directly instead of needing to Load/Store them).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5185)
=> gdbstub: Fix some gdbstub jankiness

src/citra_qt/game_list_worker.cpp, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/file_sys/ticket.cpp, src/core/hle/service/am/am.cpp
We already show an error if the cia is encrypted but not if the cia itself isn't encrypted but it's content is.
This lead to a lot of confusion where users thought they successfully installed the cia, but then nothing appeared in the game list. Now the encryption error is also shown if the cia contained any executable that Citra isn't able to decrypt (e.g. due to missing aes keys).
In addition any executable that is encrypted and Citra can't decrypt is still shown in the game list (if executables without icons are visible). Such executables will still be shown in an ugly way (no proper title, icon, region etc), since we can't access the SMDH.
As a last change in that PR I removed a debugging line we added that showed the path of each NCCH file, since it was only added to debug an issue …
=> Show an error if CIA contend is encrypted

src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/fs/fs_user.h
Also rewritten how GetArchiveResource works so that they all use the same interface.
We should decide what to do with these at some point.
Related to #3131 and #3110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5213)
=> Services/FS: Stubbed GetSdmcArchiveResource and GetNandArchiveResource.

src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/apt_s.cpp, src/core/hle/service/apt/apt_u.cpp
This one is similar to the ReceiveCaptureBufferInfo function except it doesn't clear the capture buffer, according to 3dbrew.
This function is used by the Home Menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5194)
=> Services/APT: Implemented the GetCaptureInfo function.

src/core/core_timing.h, src/core/hle/service/mic_u.cpp, src/core/hle/service/mic_u.h
This fixes a conversion error that causes mic update events to be run far more frequently than intended, causing massive slowdowns in some games. After fixing, I experienced a 5x speedup in The Sims 3.
Prior to this PR, the speedup could be achieved by using a savestate. This was due to a bug that unscheduled the mic update event when loading, which this PR fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5223)
=> Fix MIC_U serialization and timing

src/core/memory.h
`auto i = 0` deduces to an int, which was being compared with a size_t within the loop condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5232)
=> core/memory: Resolve sign conversion in serialize()

src/core/hle/kernel/shared_page.cpp
We can use `UNREACHABLE_MSG` to indicate that this path isn't intended to be reached, as it would indicate a wrong enum value.
While we're in the same area we can make the immutability of `override_init_time` explicit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5238)
=> kernel/shared_page: Silence missing return warning in GetInitTime()

src/video_core/renderer_base.h, src/video_core/renderer_opengl/gl_rasterizer.h
ShaderProgramManager was placed within the wrong namespace. Backend simply isn't necessary, so it can be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5239)
=> video_core: Amend misplaced forward declarations

src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/apt_a.cpp, src/core/hle/service/apt/apt_s.cpp
The Home Menu uses this to determine whether it is allowed to launch an app (call StartApplication)
This is a no-op for us, we allow any and all titles to be launched. The official APT module holds a list of some forbidden titles like some versions of IronFall and Flipnote Studio 3D.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5203)
=> Services/APT: Implemented the IsTitleAllowed function.

src/video_core/primitive_assembly.cpp, src/video_core/primitive_assembly.h
Makes use of `std::array` and also makes the constructor explicit. We can also make the triangle handler so that the std::function doesn't need to be copied unnecessarily (since it's not stored anywhere).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5240)
=> primitive_assembly: Minor changes

src/video_core/renderer_opengl/gl_resource_manager.h
Several standard constructors generally check if objects can be moved in a non-throwing manner (usually via `std::move_if_noexcept`) to preserve its exception guarantees. This means that if these were used with certain containers any reallocations internally would cause resource churn, as copies would be necessary instead of moves.
This way, if they're every used in that manner, the right behavior is always performed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5242)
=> gl_resource_manager: Make use of noexcept on move assignment and move constructors

src/core/memory.h
We can simplify the overload set to be less confusing (and error-prone), while also unbreaking 32-bit builds.
Fixes #5246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5250)
=> core/memory: Fix #5246

src/video_core/renderer_opengl/post_processing_opengl.cpp, src/video_core/renderer_opengl/post_processing_opengl.h
Same behavior, but doesn't result in an allocating copy of the passed in string. Particularly given the string is only compared against other existing strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5248)
=> post_processing_opengl: Make use of std::string_view with GetPostProcessingShaderCode()

src/video_core/geometry_pipeline.cpp
`std::function` is allowed to internally allocate, so this prevents potential reallocations from occurring, should that case ever happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5243)
=> geometry_pipeline: std::move vertex handler in SetVertexHandler()

src/core/hle/ipc_helpers.h, src/core/hle/service/am/am.cpp, src/core/hle/service/apt/applet_manager.cpp, src/core/hle/service/apt/apt.cpp, src/core/hle/service/cam/cam.cpp, src/core/hle/service/dsp/dsp_dsp.cpp, src/core/hle/service/frd/frd.cpp, src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/soc_u.cpp
Allows interfaces to move the `std::vector` into the calls where applicable, avoiding any reallocations.
Many existing call sites already std::move into the parameter, expecting a move to occur. Only a few remain where this wasn't already being done, which we can convert over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5235)
=> ipc_helpers: Make PushStaticBuffer take std::vector by value

src/video_core/primitive_assembly.h
This fixes a bug introduced in #5240 by incorporating Lioncache's solution with `make_array`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5256)
=> Fix savestates compatibility

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Uses string_view for AddLine so std::strings aren't created from constant string.
Resizes the source string to add indentation rather than concatenating a new one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5261)
=> video_core: reduce string allocations in shader decompiler

src/video_core/swrasterizer/proctex.cpp, src/video_core/swrasterizer/proctex.h
Avoids unnecessarily copying 512 bytes and 3584 bytes upon every invocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5247)
=> swrasterizer/proctex: Take regs by const reference

CMakeLists.txt, appveyor.yml, src/input_common/sdl/sdl_impl.cpp
As explained in #5123, many controllers are broken by the hidapi driver implementations on SDL versions 2.0.9 and 2.0.10.
As of 2.0.12 most of these problems seem to have been fixed, so we may consider to update it (citra-emu/build-environments#23)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5179)
=> Reenable hidapi for SDL2.0.12 and up

src/video_core/renderer_opengl/texture_filters/scale_force/scale_force.frag
The newer version tweaks the color distance algorithm to reduce the "black paint brush" effect at the tips of thin objects.
Before:
After:
It's also a bit faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5270)
=> texture_filters: update ScaleForce

src/video_core/command_processor.cpp, src/video_core/pica.cpp, src/video_core/pica_state.h
Prevents any implicit array to pointer decay and also makes the interface of `WriteUniformFloatReg` always take a correctly sized array.
While we're at it we can make `Zero()` a little safer to use by checking if the to-be-zeroed type is trivially copyable. We can also resolve undefined behavior related to type punning in `WriteUniformFloatReg` as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5241)
=> pica_state: Make use of std::array where applicable

src/core/file_sys/savedata_archive.cpp
Previously, we were returning a value that was way too big, causing an integer overflow in Fractured Souls.
According to wwylele, the biggest observed save size for 3DS is 1MB, so this new value should leave plenty of room, even if games use a bigger size.
Fixes https://github.com/citra-emu/citra/issues/1320.
Thanks to xperia64, Subv, wwylele, Hamish and B3N30 for investigating this on Discord.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5282)
=> savedata_archive: Make GetFreeBytes return a more accurate value

src/common/hash.h, src/video_core/renderer_opengl/gl_shader_gen.h
Marks a reference parameter as a const reference and also marks the hash implementations as noexcept, given they shouldn't throw.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5290)
=> gl_shader_gen: Minor interface cleanup

src/video_core/renderer_opengl/renderer_opengl.cpp
Resolves numerous truncation warnings on MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5291)
=> renderer_opengl: Resolve compiler truncation warnings

src/video_core/renderer_opengl/gl_shader_manager.cpp
Resolves a few trival `-Wshadow` warnings.
While we're in the area, we can also avoid making copies of all transferable entities and eliminate an unused local variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5292)
=> gl_shader_manager: Eliminate variable shadowing

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
We can invert conditionals to completely flatten out the nested branching, making it nicer to read. While we're in the same area, we can eliminate an unnecessary reference parameter, given all usages would only be passing in their own texture info instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5296)
=> gl_rasterizer_cache: Flatten LoadCustomTexture()

src/core/hle/service/ir/ir.h
This can be removed as it's not used. Even if it were however, it would be an incorrect forward declaration, as `ServiceManager` exists within the `Service::SM` namespace, not the top-level `SM` namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5303)
=> service/ir: Remove erroneous forward declaration

src/video_core/regs_shader.h, src/video_core/renderer_base.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
Resolves truncation warnings by either amending interfaces to properly handle the type being passed in, or make said truncations explicit. This also resolves a warning related to unused private class member variables and a -Wreorder warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5298)
=> gl_rasterizer: Silence various compilation warnings

src/core/hw/aes/key.cpp, src/core/hw/rsa/rsa.cpp, src/core/hw/rsa/rsa.h
Allows calling code to completely eliminate std::vector copies/reallocations in the constructor (and amends code to make use of this).
While we're in the area we can tidy up the interface a little, such as making the `operator bool()` conversion operator explicit, and mark `GetSignature()` as a const member function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5308)
=> core/hw/rsa: Minor cleanup

src/core/file_sys/layered_fs.cpp
Makes them internally linked and prevents potential -Wmissing-declaration warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5304)
=> layered_fs: Mark functions as static where applicable

src/core/file_sys/archive_extsavedata.cpp, src/core/file_sys/archive_extsavedata.h, src/core/file_sys/archive_systemsavedata.cpp, src/core/file_sys/archive_systemsavedata.h, src/core/file_sys/path_parser.cpp, src/core/file_sys/path_parser.h, src/core/file_sys/title_metadata.cpp, src/core/file_sys/title_metadata.h
Same behavior, but allows the interfaces to be used with non-allocating string types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5306)
=> file-sys: Make use of std::string_view where applicable

src/video_core/renderer_opengl/gl_rasterizer.cpp
Previously undefined behavior was being invoked in the case that geometry shaders weren't supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5297)
=> gl_rasterizer: Amend missing return value in branch in SetupGeometryShader()

externals/CMakeLists.txt
Ensures that unused targets introduced in the `add_subdirectory` call don't show up in IDE builds if they aren't used (which is the case for `teakra_c`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5302)
=> CMakeLists: Specify EXCLUDE_FROM_ALL for teakra

src/core/hle/service/soc_u.cpp
This class is memcpy-ed and memcpy has the requirement that data passed to it must be trivially copyable, otherwise the behavior is undefined.
This is trivial to resolve as BitField was made trivially copyable a while ago, so this explicit copy assignment operator isn't necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5315)
=> soc_u: Prevent undefined behavior with CTRPollFD

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/vm_manager.cpp
Ensures the initialization order matches the actual order that the class member variables will be initialized in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5316)
=> core: Resolve -Wreorder warnings

src/citra_qt/applets/swkbd.cpp, src/citra_qt/applets/swkbd.h, src/core/frontend/applets/swkbd.cpp, src/core/frontend/applets/swkbd.h
The text is validated in `Finalize`. If the validation fails, an error is returned and the applet is not actually finalized. This can result in hangs.
This is usually not a problem as the frontend is expected to validate the text passed to `Finalize`. However, when the user clicked on `Cancel`, the text is ignored and the frontend won't do any validation. Therefore, we should skip the validation here as well.
Also fixed a potential data race. All these functions should now be called on the same thread
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5294)
=> swkbd: Fix a bug where clicking Cancel hangs the game

src/core/hle/service/cfg/cfg.cpp
This block is 0x100 if in debugMode, we just stub it to 0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5330)
=> cfg-savegame: add DebugMode block

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Allows us to avoid even more string churn by allowing the AddLine function to make use of fmt formatting so the string is formatted all at once instead of concatenating multiple strings.
This is similar to how yuzu's decompiler works, which I've made function the same way in the past.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5262)
=> gl_shader_decompiler: Make use of fmt with the decompiler

src/video_core/renderer_opengl/gl_shader_gen.cpp
Avoids string churn and makes it significantly easier to read the shader template strings that are being used as the basis for formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5264)
=> gl_shader_gen: Make use of fmt where applicable

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h
There was a bug in AddressArbiter that would break shared_from_this during deserialization, if the savestate was made while waiting on an address, depending on the exact serialization order. This fixes that, allowing saves to be made in games like Detective Pikachu. Compatibility with previous saves has been maintained as much as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5231)
=> Fix Address Arbiter serialization

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_graphics.ui, src/core/settings.cpp, src/core/settings.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/video_core.cpp, src/video_core/video_core.h
This is an OSX only change:
On OSX with Intel GPUs it seems seperable shaders are broken.
So this change enables HW shaders by default but adds a flag to disable seperable shaders. This flag only matters on OSX systems with Intel GPUs. There the option is default off, enabling it will bring a warning msgBox.
The checkbox is only visible on OSX. On all other systems this option isn't visible
Changing this option in the ini file has no effect on other systems
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5230)
=> Add flag to disable seperable shaders for osx Intel GPUs. 

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
A trivial change that allows compilers to more rigorously optimize out code blocks that will never be executed in some scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5336)
=> gl_rasterizer_cache: Make use of if constexpr in MortonCopyTile()

src/common/file_util.cpp, src/common/file_util.h
See yuzu-emu/yuzu#3672 for more details.
It's undefined behavior to pass a null pointer to `std::fread` and `std::fwrite`, even if the length passed in is zero, so we must perform the precondition checking ourselves.
A common case where this can occur is when passing in the data of an empty `std::vector` and size, as an empty `std::vector` will typically have a null internal buffer.
While we're at it, we can move the implementation out of line and add debug checks against passing in nullptr to `std::fread` and `std::fwrite`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5225)
=> Port yuzu-emu/yuzu#3672: "file_util: Early-exit in Write/ReadArray if specified lengths are zero"

src/core/core.cpp, src/core/core_timing.cpp, src/core/core_timing.h, src/core/hle/kernel/thread.cpp, src/tests/core/core_timing.cpp
We didn't calculate the global time precisely especially when dynarmic didn't execute exactly the slice length or when we reduced the slice length because a event was scheduled in the current slice
I also removed the usage of the global time in thread creation and switch context to use the cpus ticks instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5257)
=> Improve core timing accuracy

src/common/file_util.cpp
See yuzu-emu/yuzu#3630 for more details.
**Original description**: 
On Windows, network shares use paths like \\server\share\file which were being broken by FileUtil::SanitizePath() removing double slashes.
Changed the code in SanitizePath to permit a double-backslash if it occurs at the start of a filepath (on Windows only).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5224)
=> Port yuzu-emu/yuzu#3630: "common/file_util: Allow access to files on network shares"

src/audio_core/cubeb_input.cpp
Games that access the microphone can end up calling StartSampling and StopSampling many times over.
Previously, cubeb_input.cpp created the input stream every time StartSampling was called, causing it to leak as StopSampling only stopped the stream, rather than destroying and releasing it.
For now, let's destroy the stream in StopSampling until this can be improved further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5356)
=> Avoid leaking cubeb input stream

src/citra_qt/applets/swkbd.cpp, src/core/hle/applets/swkbd.cpp
Fixes #5359
If an app sends custom button texts, none of them should be empty. Leaving an empty element will mess with the index, causing the frontend to add the wrong button text. This can also be merged to [citra-android](https://github.com/citra-emu/citra-android) as the issue is related to the core, not the frontend.
[Working button text](https://i.imgur.com/kvnJfoX.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5362)
=> applets/swkbd: Fix button order received from button_text

src/core/file_sys/archive_backend.cpp, src/core/file_sys/archive_backend.h, src/core/file_sys/archive_ncch.cpp, src/core/file_sys/archive_systemsavedata.cpp, src/core/hle/service/apt/apt.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp
Allows removing some allocation churn in some locations by moving std::vectors into Path where applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5333)
=> fs_user: std::move vectors where applicable

dist/qt_themes/qdarkstyle/style.qss, src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/configuration/configure_motion_touch.h, src/citra_qt/configuration/configure_motion_touch.ui, src/citra_qt/configuration/configure_touch_from_button.cpp, src/citra_qt/configuration/configure_touch_from_button.h, src/citra_qt/configuration/configure_touch_from_button.ui, src/citra_qt/configuration/configure_touch_widget.h, src/citra_qt/main.cpp, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/settings.h, src/input_common/CMakeLists.txt, src/input_common/main.cpp, src/input_common/touch_from_button.cpp, src/input_common/touch_from_button.h
This change creates an additional TouchDevice, TouchFromButtonDevice, which uses a list of mappings between ButtonDevices and screen coordinates. If enabled, this device is polled in the HID module along with the regular one to allow both free and preset inputs.
Addresses #3494, #4261.
Mapping lists are maintained separately from input profiles to allow per-game setup. Device is configured by assigning one of the mappings to the input profile. Relevant qt-config.ini entries:
```
profiles\1\use_touch_from_button=true
profiles\1\touch_from_button_map=0
touch_from_button_maps\1\name=default
touch_from_button_maps\1\entries\1\bind="(ButtonDevice params),x:(x),y:(y)"
```
GUI screenshots:
--- …
=> input: allow mapping buttons to touchscreen

src/citra_qt/configuration/configure_input.cpp
Previously I would have to reset the input to default every single time I opened Citra if I just wanted the default keyboard binds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5376)
=> Actually save the input when clearing/resetting to default

src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/nwm/uds_beacon.cpp
While we're at it, we can also improve some of the allocations and copying that would be going on in one case by preallocating and then emplacing before modifying.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5393)
=> nwm: Eliminate signed conversion warnings

src/core/hle/service/am/am.cpp
Avoids redundant std::string constructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5398)
=> am: Remove redundant c_str() calls

src/core/hle/service/fs/file.cpp
Avoids unnecessary atomic reference count increments and decrements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5400)
=> fs/file: Make use of std::move where applicable

src/citra_qt/applets/swkbd.cpp, src/core/frontend/applets/swkbd.h, src/core/hle/applets/swkbd.cpp
I'm not sure why we decided to have a boolean here, but apparently that wasn't the correct behaviour. According to HW tests, the Software Keyboard simply displays the default text when the button text provided is empty (**not necessarily all zero**). For example, if you set a text for one of the buttons and leave others empty, the button you set will have your text, while others will have their default texts. Removed the boolean and updated frontend code to make it correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5381)
=> applets/swkbd: Properly handle button_text

src/audio_core/hle/wmf_decoder.cpp
WMF seemed buggy, and produced an unpleasant blip of static (at least in Rhythm Heaven) when AAC streams started, whereas other decoders like FDK didn't have this issue.
Loosely based on the pattern of output_status's I saw in DecodingLoop, as well as this blog post: https://alax.info/blog/1883, I replaced the return in the loop with a continue.
Effectively, if you exit and return when output_status is "OK" or "HaveMoreData", WMF seems to always return a meaningless "NeedMoreInput" during the next call to ReceiveSample regardless of whether it actually "needs more input" or not. If you continue and clear the "NeedMoreInput" state early as was happening with the "HaveMoreData" case, everything works seems to work out.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Fix WMF AAC Decoder Bug

src/audio_core/hle/hle.cpp
This pull request was created to partially address https://github.com/citra-emu/citra/issues/4562
I am not confident this is the correct solution, but it just happens to fix this issue on the HLE backend from what I can tell. In some ways this PR serves as an information dump regarding the behavior I've observed.
In Project Mirai 2, on the HLE backend, the music track of a given song runs faster than the rest of the gameplay by a significant amount by the end of a 4 minute song, making gameplay very difficult. I found that by adjusting audio_frame_ticks, the speed of the music track relative to the rest of the game could be increased or decreased. By changing it from the hardware-measured 1310252 to the theoretical 1310740 (see commit comments), I found everything seemed to match the …
=> Adjust audio_frame_ticks

src/core/hle/service/dsp/dsp_dsp.cpp
Return the number of bytes we actually read back from the pipe instead of the number of bytes available before we read the pipe.
This fixes these audio tests: https://github.com/MerryMage/3ds-audio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5401)
=> Fix ReadPipeIfPossible Size

src/audio_core/lle/lle.cpp
This PR is the equivalent of https://github.com/citra-emu/citra/pull/5266 for the LLE backend.
Previously, Teakra assumed a period of 4100. This was found to be incorrect, and was updated to 4096. While this Teakra update did correct the overall audio sync, it dropped audio entirely from time to time, resulting in large discontinuities in the audio. I found this was related to the TeakraSlice value in the LLE audio backend, and found a value that appears to prevent drop outs with the Teakra update.
This PR is a WIP because I am unsure how the TeakraSlice value should be derived, if it can be at all. It appears the drop outs are caused by Teakra getting "out-of-phase" with the rest of Citra, as if it's exiting before it finishes handing off samples, and carefully selecting a slice value …
=> Update teakra, adjust TeakraSlice for new audio frame period

src/core/cheats/cheats.cpp, src/core/dumping/ffmpeg_backend.cpp, src/core/hw/gpu.cpp, src/core/hw/gpu.h
Fixes #4169, #5265, and presumably #4527. Probably other games too.
All fixed with HLE audio only for now; LLE appears to have other bugs.
This doesn't appear to affect/break my other desync fix in #5266
Since the beginning of Citra, the screen refresh rate had a placeholder value of 60Hz. The 3DS screen refresh rate is fairly well known to be roughly 59.83Hz. This is a large enough difference that heavily affects rhythm games.
TODO List for this [WIP] PR:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5273)
=> Update FPS to roughly match the actual 3DS rate

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
Another attempt at fixing https://github.com/citra-emu/citra/issues/2066
Rather than decreasing the maximum range, interpolate the circle pad by averaging it with the previous two inputs.
I have confirmed on hardware using Luma3DS InputRedirection that Theatrhythm is bugged if you recreate the same "perfect" input conditions that Citra provides, i.e. circle pad center calibrated to 0 where the circle pad value can jump to any any other value in one step. This is generally not an issue on a real 3DS because the circle pad is sluggish, and takes longer than the roughly measured ~4ms update cycle of HID and ~2.5ms sampling rate of CODEC (the circle pad ADC).
CIRCLE_PAD_AVERAGING is set to 3, as I found Theatrhythm would still drop input when setting it lower. (CIRCLE_PAD_AVERAGING of 3 means …
=> Interpolate circle pad motion

src/video_core/renderer_opengl/renderer_opengl.cpp
When stopping video dumping, deadlock can occur if the user stopped video dumping after `GetRenderFrame` has been called, but before `TryGetPresentFrame` would've been called in `FrameDumperOpenGL::PresentLoop`.
I'm not 100% happy with this solution, but a `quit` variable and an exception were the best way I could come up with to jump out of `GetRenderFrame`.
Without `quit`, `free_cv` would only wake an continue if `free_queue` contained a new frame. Adding an invalid frame or pushing one in `FrameDumperOpenGL` seemed more hacky than just adding a `quit` flag.
An exception caught when trying to render to the frame dumper mailbox seemed like the cleanest way to jump out of `GetRenderFrame`, as otherwise a null check would need to be added to `RenderToMailbox`, which would be unnecessary if …
=> Avoid deadlock when stopping video dumping

src/video_core/renderer_opengl/gl_shader_gen.cpp
Reduces some more string churn by minimizing some allocations from being done and collapsing closely related format calls into one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5403)
=> gl_shader_gen: Minor string cleanups

src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h
Fixes #5218.
The bug(s) happened because we swapped the contents on values.game_dirs, but the pointer each item had to their respective game_dir wasn't updated. This made it so that the item had the wrong game_dir associated with it after a "move up" or "move down" operation. It can be observed by choosing "open directory location" after such operation.
Changed from raw pointer to an index because it's equivalent but a bit clearer, but the change is not essential.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5344)
=> game_list: Fix folder reordering

.github/ISSUE_TEMPLATE/bug-report-feature-request.md, .github/ISSUE_TEMPLATE/config.yml
Hopefully this will decrease the number of users using GitHub issues for tech support requests.
Adds links to the discord, forums, and android repo for users reporting android bugs. There is a hyperlink at the bottom of the template page for those who want to create an actual issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5364)
=> .github: add a new issue template

src/citra_qt/bootmanager.cpp
See yuzu-emu/yuzu#4097 for more details.
Fix OpenGL renderer framebuffer size on fractional scaling display by using devicePixelRatioF().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5435)
=> Port yuzu-emu/yuzu#4097: "Fix framebuffer size on fractional scaling display."

src/common/alignment.h
In cases where the size is not a known constant when inlining, `AlignUp<std::size_t>` currently generates two 64-bit div instructions.
This generates one div and a cmov which is significantly cheaper.
https://godbolt.org/z/S848QG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5441)
=> Common: remove a mod from AlignUp

.travis.yml, .travis/macos/build.sh, .travis/macos/deps.sh
We currently build on macOS 10.14, while targeting 10.13.
Unfortunately we still link against libraries compiled for 10.14, which can result in interesting crashes on macOS 10.13.
Since we require a more up to date compiler than provided by xcode on 10.13, we pull in a more up to date compiler while building on 10.13.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5317)
=> travis: Compile on macOS 10.13 with more up to date compiler

.travis/linux/upload.sh, .travis/macos/upload.sh, CMakeLists.txt
I believe this was an oversight to miss out `$<CONFIG>` parameter at [CMakeLists.txt](https://github.com/citra-emu/citra/blob/master/CMakeLists.txt) as `$<CONFIG>` was defined in CMakeModules for both [CopyCitraQt5Deps.cmake](https://github.com/citra-emu/citra/blob/master/CMakeModules/CopyCitraQt5Deps.cmake#L3) & [CopyCitraSDLDeps.cmake](https://github.com/citra-emu/citra/blob/master/CMakeModules/CopyCitraSDLDeps.cmake#L3) files.
This fixes the issue for executables binaries copied to the `bin` folder instead of its subfolder after local compile finish with *Microsoft Visual Studio Community 2019 Preview* (Version 16.6.0 Preview 5.0) and thus causing the executable fail to launch within debugging environment due to failing to locate the dlls.
Supersedes PR #5323
--- …
=> Correct output paths for executable binaries in CMakeLists.txt

src/core/file_sys/archive_ncch.cpp, src/core/file_sys/ncch_container.cpp, src/core/file_sys/ncch_container.h, src/core/hle/service/am/am.cpp, src/core/hle/service/fs/archive.cpp, src/core/hle/service/fs/archive.h, src/core/hle/service/fs/fs_user.cpp, src/core/hle/service/fs/fs_user.h, src/core/loader/3dsx.cpp, src/core/loader/ncch.cpp
This allows games to open other partitions than partition 0 from NCSDs (aka .3ds files).
For that the NCSD header is parsed instead of being skipped. To open another partition we need to keep track of which (3ds) file is currently open on which process. On real HW the loader does something similar by registering the process and media type with FS:Reg::Register. 
We can skip the FS:Reg module and just store the information in FS_User, since there we need it.
I also added the FS_USER::GetSpecialContentIndex changes in here since they rely on the NCSD changes. So this superseds #5329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5345)
=> [WIP] NCCHContainer: support for partitions if container is NCSD

CMakeLists.txt, CMakeModules/CopyCitraQt5Deps.cmake, src/citra_qt/CMakeLists.txt
See yuzu-emu/yuzu#4221 for more details.
Removed in yuzu-emu/yuzu#2017
<details><summary>Naive headers check</summary>
```
$ rg QtOpenGL
$ rg QGL
externals/mbedtls/tests/data_files/rsa_pkcs8_pbes2_pbkdf2_4096_des_sha384.pem
40:VeR7oKrhopTLxLwWkbAZNau3h3LoWwPatgwmPX4OBAge9xGeo5BAm23DQGLtokYj
src/core/frontend/emu_window.h
62: * (e.g. SDL, QGLWidget, GLFW, etc...).
$ pkg info -l qt5-opengl | fgrep include/
/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h
/usr/local/include/qt5/QtOpenGL/5.14.2/QtOpenGL/private/qgl2pexvertexarray_p.h
/usr/local/include/qt5/QtOpenGL/5.14.2/QtOpenGL/private/qgl_p.h
/usr/local/include/qt5/QtOpenGL/5.14.2/QtOpenGL/private/qglcustomshaderstage_p.h
/usr/local/include/qt5/QtOpenGL/5.14.2/QtOpenGL/private/qglengineshadermanager_p.h …
```
=> Port yuzu-emu/yuzu#4221: "cmake: stop linking against QGL"

src/core/settings.cpp
See yuzu-emu/yuzu#4347 for more details.
In all usages of `LogSetting()`, string literals are provided. `std::string_view` is better suited here, as we won't churn a bunch of
string allocations every time the settings are logged out.
While we're at it, we can fold `LogSetting()` into `LogSettings()`, given it's only ever used there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5464)
=> Port yuzu-emu/yuzu#4347: "settings: Make use of std::string_view over std::string for logging"

src/audio_core/hle/wmf_decoder_utils.cpp
Should fix the WMF issues encountered when building with current MinGW versions.
This was always undefined behavior and a coincidence that it ever worked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5470)
=> Actually return true if InitMFDLL succeeded

.lgtm.yml
Refer to #5494 for some example issues found. LGTM analysis for this repo can be viewed [here](https://lgtm.com/projects/g/citra-emu/citra/alerts/?mode=tree). Note: this doesn't affect existing CI routines in any way.
Added config file makes static analysis results much easier to read and also speeds up analysis process by preinstalling used packages.
Potential addition:
```YAML
queries:
include: "*"
```
This enables all warning types as opposed to default only. It might be a good idea to enable later on once default ones are addressed.
Additionally, it's worth taking a look at https://lgtm.com/projects/g/citra-emu/citra/ci/. Automatic check for new alerts introduced by PRs and alerts count/code quality badges are available.
--- …
=> Add LGTM static analyzer config file

.travis/macos/build.sh
Fixes #5481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5497)
=> Use gtimeout on Mac OS job to incrementally build up ccache 

src/citra_qt/debugger/profiler.cpp
See yuzu-emu/yuzu#4531 for more details.
Eliminates a verbose function cast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5532)
=> Port yuzu-emu/yuzu#4531: "yuzu: Make use of qOverload where applicable"

src/citra_qt/game_list.cpp, src/citra_qt/game_list_worker.cpp, src/citra_qt/uisettings.h
See yuzu-emu/yuzu#4536 for more details.
While we're in the same area, we can ensure GameDir member variables are always initialized to consistent values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5531)
=> Port yuzu-emu/yuzu#4536: "yuzu: Resolve -Wextra-semi warnings"

src/audio_core/cubeb_sink.cpp
Cubeb is the default and sometimes this log can create a lot of spam, example log from a user: [citra_log.txt](https://github.com/citra-emu/citra/files/5104830/citra_log.txt) which makes supporting users more difficult so let's change the log level for this to DEBUG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5518)
=> cubeb_sink: Change a log from INFO to DEBUG level

.travis/clang-format/script.sh, CMakeLists.txt
See yuzu-emu/yuzu#4464 and yuzu-emu/yuzu#4505 for more details.
Depends on https://github.com/citra-emu/build-environments/pull/26 and https://github.com/citra-emu/ext-windows-bin/pull/23.
10.0 plays nicer with C++ attributes compared to clang-format 6.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5500)
=> Port yuzu-emu/yuzu#4464 and yuzu-emu/yuzu#4505: Update clang format to version 10.0

src/citra_qt/bootmanager.cpp
QDragLeaveEvent does not inherit QDropEvent, and can cause a segfault when cast incorrectly.
QEvent::DragResponse appears to be an internal event that likely does not need to be handled. I wasn't able to get it to happen on my machine (Linux/X11), however since there's no QDragResponseEvent, it likely does not inherit QDropEvent either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5516)
=> Avoid incorrect casts to QDropEvent

src/citra_qt/main.cpp
Fixes an issue with duplicate configuration entries when Citra is set to a language that has save/load state translated.
As a side note, it would appear there's no way to translate shortcut action text correctly until shortcut keys/names are decoupled from their display text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5504)
=> Don't translate save/load state hotkey text for the map

src/core/arm/arm_interface.h, src/core/arm/dynarmic/arm_dynarmic.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Silences some of the loudest switch-related warnings by explicitly handling the default case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5549)
=> Silence some noisy switch case warning

src/citra_qt/game_list_p.h
See yuzu-emu/yuzu#4606 for more details.
Consistency change with how we mark constants in the rest of the
codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5550)
=> game_list_p: Mark some constants as constexpr

src/citra_qt/aboutdialog.cpp, src/citra_qt/configuration/configure_debug.cpp, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_enhancements.cpp, src/citra_qt/configuration/configure_enhancements.h, src/citra_qt/configuration/configure_general.cpp, src/citra_qt/configuration/configure_graphics.cpp, src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h, src/citra_qt/configuration/configure_system.cpp, src/citra_qt/configuration/configure_ui.cpp, src/citra_qt/debugger/registers.cpp, src/citra_qt/debugger/registers.h, src/citra_qt/main.cpp, src/citra_qt/main.h, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/lobby.h
The files citra_qt/main.h and citra_qt/debugger/registers.h were the only two instances where the Ui classes weren't forward declared.
The forward declaration may reduce the size of the resulting header.
While we're at it, change the other instances that used raw pointers, or that used new instead of make_unique even though a unique_ptr is used, to be consistent with the other instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5511)
=> Use unique_ptr on all ui objects from .ui files

src/core/frontend/applets/mii_selector.h
The serialization module was heavily changed and it now this header needs to be included as it is relied in many other parts of citra.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5565)
=> Fix compilation with boost 1.74.0

src/audio_core/hle/decoder.cpp, src/audio_core/hle/wmf_decoder.cpp, src/core/hle/kernel/memory.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp
See https://github.com/yuzu-emu/yuzu/pull/4698 for more details.
Allows some implementations to avoid completely zeroing out the internal buffer of the optional, and instead only set the validity byte within the structure.
This also makes it consistent how we return empty optionals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5570)
=> Port yuzu-emu/yuzu#4698: "General: Make use of std::nullopt where applicable"

src/citra_qt/game_list.cpp, src/citra_qt/game_list_p.h
See yuzu-emu/yuzu#4733 for more details.
This fixes a memory leak as KeyReleaseEater's destructor was never called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5574)
=> Port yuzu-emu/yuzu#4733: "qt/game_list: Give GameListSearchField::KeyReleaseEater a parent"

.ci/common/post-upload.sh, .github/workflows/ci.yml
This Pull Request will fix the issue with the Qtifw installer where the directory name is incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5607)
=> ci: fix mingw folder name

src/input_common/keyboard.cpp
This fixes a glitch where keyboard-mapped buttons would become un-pressed when loading a savestate (because the state was held in each ButtonDevice, which would get destroyed on load).
There is apparently a similar issue with SDL devices, but I'm stumped on that one as the Devices don't hold any state of their own there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5255)
=> Keep keyboard state independent of acquired buttons

src/video_core/renderer_opengl/gl_shader_manager.cpp
Fixes a known issue in which the flatpak application crashes with hardware shader enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5608)
=> Fix flatpak crash when hardware shader is enabled

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/configure_enhancements.cpp, src/citra_qt/configuration/configure_enhancements.ui, src/core/settings.h, src/video_core/renderer_opengl/renderer_opengl.cpp
Add Reverse Interlaced 3D option for users with passive 3D displays that render each eye in the reverse order from normal interlaced. (e.g. LG OLED 3DTVs)
This is a simple extension of: #5018 and adds to the interlaced options mentioned in #4255
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5580)
=> Implement Reverse Interlaced 3D

src/audio_core/cubeb_sink.cpp
When using cubeb, the volume level assigned via windows wouldn't be remembered, annoying some users who controlled volume levels solely using the mixer volumes, instead of changing the master volume or the citra provided internal volume.
The issue happens on Citra as well as Yuzu (see yuzu-emu/yuzu#2935)
A recent cubeb change (kinetiknz/cubeb#599) introduced the CUBEB_STREAM_PREF_PERSIST flag which should fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5577)
=> Update cubeb to latest and request a persistent stream session

externals/microprofile/microprofile.h
See yuzu-emu/yuzu#4887 for more details.
Silences a truncation warning by making the truncation explicit and documenting the reason for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5603)
=> Port yuzu-emu/yuzu#4887: "microprofile: Silence warning in headers"

src/core/file_sys/layered_fs.cpp, src/core/file_sys/layered_fs.h
Fixes #5467.
The deep recursion has caused issues in certain games with large numbers of files, especially with MSVC builds. (other builds are likely using techniques like tail call optimization)
Previously the recursion depth is about equal to the number of files present. With this the depth should be about equal to the maximum depth of the directory structure of the RomFS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5566)
=> layered_fs: Make LoadFile and LoadDirectory less recursive

src/audio_core/hle/source.cpp, src/audio_core/hle/source.h
Fixes https://github.com/citra-emu/citra/issues/3612 and https://github.com/citra-emu/citra/issues/4281
Detective Pikachu now runs at the correct speed and sounds mostly correct, with some minor roughness.
Tomodachi Life voices no longer cut off and sound 100% correct to me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5548)
=> Initial implementation of partial_embedded_buffer_dirty handling

src/video_core/renderer_opengl/renderer_opengl.cpp
AddField is implemented using std::move.
However, the memory backing these three `const char*` fields are local in scope to this function. When Citra (SDL2 at least) attempts to use these fields on exit, the memory may already be unmapped/invalid. To fix this, just convert them to a string.
I couldn't find a good way to discriminate between `const char[]` and `const char*` in the AddField templating system, so for now we just need to be careful and keep this in mind. I did check and as far as I can tell, all of the other `const char*`-like fields passed to AddField are globals that won't be freed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5617)
=> Fix telemetry-related exit crash from use-after-free

src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/apt_a.cpp, src/core/hle/service/apt/apt_s.cpp, src/core/hle/service/apt/apt_u.cpp, src/core/hle/service/apt/ns_s.cpp
This implements the two APT/NS functions SetWirelessRebootInfo and GetWirelessRebootInfo.
It is used to transmit informations for uds connections over reboot e.g. used for dlp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5328)
=> APT: implement Set and GetWirelessRebootInfo

src/core/hle/service/apt/apt.cpp
I'm not sure why I wrote the original code anyway but this fixes Mii Maker.
Turned out to be a typo lol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5626)
=> service/apt: Fix deliver arg hmac size

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/citra_qt/main.cpp, src/citra_qt/main.h
The feature wasn't working when the "single window mode" was off.
Changed the cursor setting to only affect the render_window and moved to a signal/slot model to trigger showing the mouse.
The previous implementation relied on the bubbling of the event from the render_window to the main window, but that does not happen when "single window mode" is off. Cursor inheritance from the main window to the render_window also doesn't happen when "single window mode" is off.
Refer to #5094 for the initial implementation.
Should fix #5413 by preventing the move QMouseEvent from bubbling up to the main window
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5476)
=> Fix "hide mouse on inactivity" for popout window

.gitmodules, externals/CMakeLists.txt, src/core/CMakeLists.txt, src/core/core.cpp
- Migrates the dynarmic submodule to a fork under citra-emu
- Includes dynarmic rebased onto the latest Citra-compatible version (e.g. https://github.com/citra-emu/citra/pull/5618)
- Reorders externals/CMakeLists.txt xbyak and dynarmic sections to closer match Yuzu (the externals/CMakeLists.txt in citra-android didn't make a whole lot of sense, as xbyak should not be required on ARM64)
- Enables dynarmic in the core on ARM64
This branch has been tested to compile and run on both an x86_64 desktop and the Jetson TX2 ARM64 board with the dynarmic enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5620)
=> Merge ARM64 Dynarmic

src/citra_qt/game_list_p.h
See yuzu-emu/yuzu#5139 for more details.
This is designated as obsolete in Qt's docs (see: https://doc.qt.io/qt-5/qvariant-obsolete.html#operator-lt), so we directly compare against the data instead of delegating the work to QVariant.
Prevents our code from breaking in the future when we update Qt versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5648)
=> Port yuzu-emu/yuzu#5139: "game_list_p: Resolve deprecated usage of QVariant operator<"

src/input_common/udp/client.cpp, src/input_common/udp/client.h
See yuzu-emu/yuzu#4798 for more details.
Avoids redundant copies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5634)
=>  Port yuzu-emu/yuzu#4798: "udp/client: Take std::function by const reference with TestCommunication()"

src/common/file_util.cpp
See yuzu-emu/yuzu#4539 for more details.
These are intentionally discarded internally, since the rest of the public API allows querying success. We want all non-internal uses of
these functions to be explicitly checked, so we can signify that we intentionally want to discard the return values here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5530)
=> Port yuzu-emu/yuzu#4539: "common: Silence two discarded result warnings"

.ci/linux-flatpak/generate-data.sh, CMakeLists.txt, src/audio_core/hle/fdk_decoder.cpp
Fixes missing audio in games that require AAC decoder. I tested it with Pokemon X and the music played correctly. Since flatpak runtimes are supposed to be consistent across different Linux distributions, it's unlikely to cause any incompatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5609)
=> Enable fdk decoder for flatpak version

src/common/file_util.cpp
There was no such warning in the first place. Yuzu has Open marked as [[nodiscard]], but Citra doesn't.
Whether a function that's only called twice with both results discarded should be marked as nodiscard is a different discussion, but the changed proposed omitted the call to the Open function. (Tested on MSVC, but should also be the cause of the failed tests on GCC)
I suppose the intention was `(void)Open();` or `static_cast<void>(Open())`, both of which work fine.
Fixes tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5664)
=> Revert #5530 "Port yuzu-emu/yuzu#4539"

src/audio_core/cubeb_input.cpp, src/audio_core/cubeb_input.h, src/core/frontend/mic.cpp, src/core/frontend/mic.h, src/core/hle/service/mic_u.cpp
Merges the generic parts of https://github.com/citra-emu/citra-android/commit/5e52853078765cbcdc48b217ceeb7658c185d37b and https://github.com/citra-emu/citra-android/commit/c6e363532b0882269810c9f7f39a19878f757006
Required for Android microphone support, changes seem fine for desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5624)
=> Merge generic microphone input changes required for Android

src/citra_qt/cheats.cpp
Fixes https://github.com/citra-emu/citra/issues/5575.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5658)
=> citra_qt/cheats: Make window resizable and remove help hint

src/citra_qt/configuration/configure_input.cpp, src/citra_qt/configuration/configure_input.h, src/citra_qt/configuration/configure_input.ui, src/input_common/main.cpp, src/input_common/main.h, src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h
If the joystick has a controller mapping in the SDL database, use it as a reference to automatically map the buttons.
Currently maps on the current profile, and doesn't do anything to buttons that don't have a binding.
To do:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5100)
=> Automatic Controller Binding

src/common/logging/backend.cpp
Particularly useful for Android as Android will immediately restart the app/Activity if it crashes, immediately overwriting the old log file before it can be read. Also could be useful for the common case of users restarting Citra and overwriting their log on Desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5666)
=> Rotate previous log file to "citra_log.txt.old"

externals/CMakeLists.txt, src/common/CMakeLists.txt
Silences a warning on newer CMake versions about CMake < 2.8.12 support.
The update may also result in a 5% increase in decompression performance, according to https://github.com/facebook/zstd/releases/tag/v1.4.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5668)
=> Update zstd to v1.4.8

src/input_common/sdl/sdl_impl.cpp
When mapping an analog trigger to a button, take two samples of an axis to determine the direction it's being moved, and override the event value to be saturated in that direction if it's been moved enough to count as an event.
Should improve https://github.com/citra-emu/citra/issues/4166 and https://github.com/citra-emu/citra/issues/5488, and possibly https://github.com/citra-emu/citra/issues/3791 by making the controller mapping process less confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5509)
=> Look at direction of analog axis travel instead of instantaneous sample

src/common/logging/backend.cpp
I think this is needed for Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5675)
=> Delete the old log file before rotating

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
At least for HID::SPVR, as in the System Settings app, the 3D slider's current value is present at offset 0x18 on the HID Shared Page.
Gets the settings app passed the "slide the 3d slider all the way up" part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5676)
=> Add 3D slider value to the HID shared page

src/core/hle/service/apt/apt.cpp, src/core/hle/service/apt/apt.h, src/core/hle/service/apt/apt_a.cpp, src/core/hle/service/apt/apt_s.cpp, src/core/hle/service/apt/apt_u.cpp
An attempt at stubbing command 0x01030000 here: https://www.3dbrew.org/wiki/NS_and_APT_Services
This allows the New3DS controls (C-Stick, ZL, ZR) to work in Smash4 when New3DS mode in Citra is set.
This is a very minimalist stub and this command has no actual name that I'm aware of.
As per the wiki, the value appears to be some sort of enum, with 1 meaning "don't use the N3DS controls" or something (which I get in a 3dsx homebrew that calls the command on both O3DS and N3DS), and according to smash, 2 and 4 mean the N3DS controls are valid. My N3DSXL provides 2 as the result in Smash4, and I have no idea what 4 is.
This command is called before Smash4 even attempts to initialize the HID services for the N3DS controls.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Implement APT command 0x0103

src/citra_qt/main.cpp, src/citra_qt/main.h
See yuzu-emu/yuzu#5217 for more details.
Saves UISettings and Settings when booting a guest. Moves updating UISettings::values from GMainWindow::closeEvent into its own function, then reuses it in GMainWindow::BootGame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5671)
=> Port yuzu-emu/yuzu#5217: "citra_qt/main: Save settings when starting guest"

src/core/core.h
See yuzu-emu/yuzu#4942 for more details.
Given this is a central class, we should flag cases where the return value of some functions not being used is likely a bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5695)
=> Port yuzu-emu/yuzu#4942: "core: Make use of [[nodiscard]] with the System class"

src/citra_qt/bootmanager.cpp, src/citra_qt/game_list.cpp
See yuzu-emu/yuzu#5342 for more details.
setMargin() has been deprecated since Qt 5, and replaced with setContentsMargins(). We can move to setContentsMargins() to stay forward compatible with Qt 6.0 whenever we update to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5693)
=> Port yuzu-emu/yuzu#5342: "yuzu: Migrate off of setMargin() to setContentsMargins()"

src/video_core/regs_framebuffer.h, src/video_core/regs_lighting.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/pica_to_gl.h, src/video_core/swrasterizer/framebuffer.cpp, src/video_core/swrasterizer/lighting.cpp, src/video_core/swrasterizer/proctex.cpp, src/video_core/swrasterizer/rasterizer.cpp
See yuzu-emu/yuzu#5158 for more details.
fmt now automatically prints the numeric value of an enum class member by default, so we don't need to use casts any more.
Reduces the line noise in our code a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5657)
=> Port yuzu-emu/yuzu#5158: "video_core: Remove unnecessary enum class casting in logging messages"

.ci/macos/deps.sh
GitHub's virtual environment provides 7zip and llvm by default, so brew may fail to install them as another version is already installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5703)
=> Fix macos build

src/citra_qt/configuration/configure_input.cpp
Should fix #5705
Actually apply and save the configurations when the modifier scale or deadzone is modified.
Also change the Restore Defaults to affect the modifier scale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5707)
=> configure_input: fix modifier scale saving

src/video_core/renderer_opengl/renderer_opengl.cpp
When a frame is presented multiple times (i.e. due to the new one not being ready yet), a new presentation fence is created even though the old one hasn't been deleted, because the deletion code only fires if a new frame is available.
On some drivers/configurations that re-present frequently, this leaks resources leading to latent crashes.
The solution is to delete the fence if it already exists before creating a new one.
While this fixes an issue only identified on Android, I'd like to see how it fares on desktop drivers just to be sure we don't hit any bugs there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5713)
=> Avoid leaking fences during re-presentation

src/common/string_util.cpp
See yuzu-emu/yuzu#5895 for more details.
This has been fixed as of Visual Studio 2019 Version 16.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5717)
=> Port yuzu-emu/yuzu#5895: "string_util: Remove MSVC workaround for converting between UTF8/UTF16"

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
Previously we only did this for fill surfaces. The surfaces were left in the cache to avoid the overhead of reallocating the texture, but certain poorly behaved games (*cough Pilotwings*) make many surfaces that are fully invalidated and never reused. The dead weight in the cache bogged down texture lookup times and other cache management functions. I introduced a map of recycled textures from destroyed surfaces to avoid the aforementioned driver overhead from allocations. Pilotwings now never drops below 60fps average on my machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5710)
=> gl_rasterizer_cache: Remove all fully invalid surfaces from the cache

src/video_core/renderer_opengl/gl_rasterizer_cache.h
This was causing crashes on Android
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5725)
=> Fix destructor order in rasterizer cache

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h
This Pull Request should fix #5523.
After analyzing the memory leaks report generated by the address sanitizer, it seems like the memory leaks were originated from https://github.com/citra-emu/citra/blob/3f13e1cc2419fac837952c44d7be9db78b054a2f/src/citra_qt/bootmanager.cpp#L449-L451.
The fix is simply to add a destructor to the `GLContext` in the `bootmanager`.
After the fix, the memory leaks report no longer shows this particular memory leak anymore.
Note that, during testing, the `citra-qt` crashed once for reasons unknown. I wasn't able to reproduce this crash despite ~20 more attempts. I suggest when testing this change, try to abuse the save state system as much as possible to see if you can reproduce the crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> bootmanager: fix memory leaks when loading save states

src/network/room.cpp
Resolves #3551.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5747)
=> fix(net): prevent gibberish padding on linux

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Check for GL_ARB_copy_image and GL_ARB_get_program_binary.
The `glCopyImageSubData` and `glGetProgramBinary` functions are not supported by OpenGL 3.3, so we need to check for the extensions.
More information about the extensions [here](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_copy_image.txt) and [here](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_get_program_binary.txt)
For `glGetProgramBinary` it logs a warning, while for `glCopyImageSubData` it disables the duplicate texture (like it was done for texture barrier before)
The `glCopyImageSubData` check should help mainly mac users (and maybe some intel users too), as the function was introduced by #5420 on nightly 1588, and we have been suggesting for mac users who experience problems to use nightly 1587, …
=> Check for OpenGL extensions

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/CMakeLists.txt, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure.ui, src/citra_qt/configuration/configure_dialog.cpp, src/citra_qt/configuration/configure_storage.cpp, src/citra_qt/configuration/configure_storage.h, src/citra_qt/configuration/configure_storage.ui, src/common/file_util.cpp, src/common/file_util.h, src/core/settings.cpp, src/core/settings.h
This attempts to Fix #3818
Moved the configuration to the config dialog now You can See, Change and Open the NAND and the SDMC directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5759)
=> Allow custom folder for SDMC and NAND Directories

src/audio_core/sdl2_sink.cpp
This is necessary for sdl audio to work properly in sdl as of current dev version (2.0.15)
Check libsdl-org/SDL#4342 and the commit linked there for more details, but basically they fixed a bug with the use of WASAPI's resampler and apparently that bug might be the cause of our audio working normally up to that point.
This change was only tested on windows for now.
As it'll take a while for 2.0.16 to come out and for us to adopt it, merging this change is not very pressing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5779)
=> sdl2_sink: remove SDL_AUDIO_ALLOW_FREQUENCY_CHANGE flag

src/common/ring_buffer.h, src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hw/gpu.h
I encountered two problems while trying to compile Citra in Fedora 34 using gcc 11.
1. Missing include
2. offsetof macro problem. Looks like in gcc 11 this macro can not be used at runtime anymore, only at compile-time, so runtime variables can not be used as an array subscript. I made a fix for that but it looks a bit clunky. Can someone review it please, may be there's more elegant solution?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5778)
=> gcc 11 compatibility fix (suggestion)

src/core/hle/service/nwm/nwm_uds.cpp, src/core/hle/service/nwm/nwm_uds.h
This implements the EjectClient function. It is used by some games to disconnect a client from the session
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5331)
=> NWM_UDS: implement disconnect_reason and EjectClient

CMakeLists.txt, dist/citra.desktop
This pull request addresses some of the issues reported by the users:
- Compatibility list is unavailable: this is due to the Flatpak CI prohibits the network usage. So to allow the inclusion of a compatibility list, a mechanism to add the list manually was added.
- Use dedicated GPU if possible: this is resolved by adding a hint in the desktop file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5772)
=> Linux: Flatpak-related changes

src/citra_qt/main.ui
Corrected the path where the icon file is located, since the "dist" folder is located next to the binary provided in github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5782)
=> Corrected the path to the headbar icon

src/common/file_util.cpp, src/core/file_sys/ncch_container.cpp, src/core/loader/3dsx.cpp
When the vector is empty, using `&vec[0]` involves undefined behaviour. While that works fine most of the time, Flatpak builds aborted on an assertion or sth around `__builtin_expect`.
I searched for such occurences across the codebase with the regex `(?<!&)&\w+\[0\]` and fixed those that would potentially cause issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5817)
=> Replace `&vec[0]` with `vec.data()`

src/core/file_sys/patch.cpp
I ran into an issue recently where I was trying to apply a BPS patch that adds extra instructions to a game's code.
Despite Flips being able to apply the patch just fine, Citra seems to be refusing to even apply the patch.
I even tested the output from Flips by putting the patched `code.bin` in the mods folder, and that worked just fine. So I assume it's got something to do with how Citra tries to apply the BPS patch.
It seems like Citra makes no attempt to resize the buffer to accommodate any extra code that needs to be added from the patch. This PR attempts to fix that, although I'm not entirely sure if the way this is done is the best way to do it.
--- …
=> fix(bps): Fixes BPS patch changing target size

src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp
#5756 added a warning for `GL_ARB_get_program_binary` but it seems like citra crashes before the warning can be logged, with this we straight up disable the shader cache when the extension is not supported. 
At least according to gpuinfo.org(I'm not sure if there is a more up to date DB somewhere else), only ~20% of devices don't support the extension, and most of them seem to be very old GPUs; So, there might not actually be any modern GPUs that support the functionality without supporting the extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5785)
=> Disable disk shader cache when GL_ARB_get_program_binary is unsupported

.ci/macos/build.sh, .ci/macos/deps.sh
Install externals built for MacOS 10.13, instead of the ones from homebrew that were built for 10.15,
This should hopefully fix newer builds on older mac, also removed the LDFLAGS for the same reason, we can just use the libraries provided by Apple's clang. Fortunately Qt seems to be compiled for 10.12(for whatever reason), so there's no change there.
[Here's ](https://github.com/SachinVin/ext-macos-bin/blob/main/.github/workflows/ci.yml) the CI script used to build, let me know if something can be changed/improved.
Should fix #5606 and #5879.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5854)
=> CI: Install SDL2 and FFMPEG built for macos 10.13

.gitmodules
See yuzu-emu/yuzu#6484 for more details.
This PR updates the discord-rpc submodule to last upstream commit, before it was deprecated in favour of Discord's new GameSDK. Since the new SDK is closed-source, we can't upgrade to it.
However, Discord RPC still uses the same underlying code for Rich Presence and hence RPC compatibilty is not broken (yet!).
The changes from last-updated commit include few minor bugfixes and readme changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5810)
=> Port yuzu-emu/yuzu#6484: "update submodule discord-rpc to latest [now deprecated]"

CMakeLists.txt, src/citra_qt/configuration/configure_motion_touch.cpp, src/citra_qt/configuration/configure_motion_touch.h, src/citra_qt/configuration/configure_motion_touch.ui, src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h
This introduces support for SDL 2.0.14's new motion control support.
Some items of interest:
- ~~I wasn't sure how to make the motion device configurable, since it can't just use guid/port like button/analog can. Marked this with a FIXME in the changeset.~~ Fixed!
- New string means new localizations... I don't suppose "SDL" needs localization, but any config options for bullet 1 probably would.
- ~~Coordinate system conversion probably needs a sanity check - I tested with some games and it seemed fine locally, but the tests didn't explicitly check all 6 values.~~ Fixed!
Also, apologies if I goofed up the style, I'm not terribly good with modern C++...
Fixes #5850
--- …
=> Add support for SDL controller accelerometer/gyro events

.github/workflows/ci-merge.js, .github/workflows/publish.yml, .gitignore
This pull request will add a set of scripts and a new GitHub Actions workflow file to publish Citra Nightly and Citra Canary without our infrastructure.
This will remove the reliance on the current backend server merging script and more transparent to the other contributors.
------
The new workflow will trigger automatically every day at 00:07 (UTC) and check for recent changes made within the past 24 hours. If no changes were made, the publish step is then skipped entirely. For the Canary build, this check will additionally cover all the tagged pull requests: if any pull requests were pushed within the 24-hour timeframe, then a new Canary build will be pushed to `citra-canary` repository.
A manual trigger is also provided in case a build must be made immediately. In which case, someone …
=> CI: do canary merge and nightly publishing on GitHub Actions

src/video_core/swrasterizer/rasterizer.cpp
The software renderer was crashing when I was trying to run Pokemon Y. Apparently this is because an empty texture address should result in a clear color being used for the texture however only the gl renderer did this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5893)
=> Fix software renderer for empty texture addresses

src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h
May fix #5877
Based on [this page](https://www.3dbrew.org/wiki/Config_Savegame#CountryInfo) from 3dbrew.
The current changes add a default subregion for every country on PKHeX's list. The default was chosen simply as the first valid subregion (ends up being the region of the country's capital in most cases I checked).
Currently there's no way to choose the subregion, but a commit in the near future will come to change that.
The subregion list parsed to obtain the subregion data used on this PR was taken from https://github.com/kwsch/PKHeX/tree/master/PKHeX.Core/Resources/text/locale3DS/subregions with permission from @kwsch
For those testing this: the changes should only take place for newly generated config files, or after changing the country on the system configurations.
---
This …
=> cfg: use a default subregion based on the country

src/core/hle/service/frd/frd.cpp, src/core/hle/service/frd/frd.h
Some games apparently use this for the multiplayer display name.
According to [this post](https://community.citra-emu.org/t/name-specified-in-system-settings-doesnt-change-multiplayer-name/414197) on the forums, some examples of games that do that are Mario Sports Superstars and Metroid Prime Federation Force.
I don't have any affected games so I haven't tested this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5792)
=> service/frd: return cfg username on GetMyScreenName

externals/cryptopp/CMakeLists.txt
Regressed by #5669. Building via GNUmakefile upstream works fine: adds `-msse4.1 -maes` for `rijndael_simd.cpp`. From [error log](https://github.com/citra-emu/citra/files/7825315/citra-qt5-s20220105.log):
```c++
FAILED: externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o 
/usr/bin/c++ -DARCHITECTURE_x86=1 -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DENABLE_FFMPEG_VIDEO_DUMPER  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -std=gnu++17 -MD -MT externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o -MF …
```
=> cryptopp: unbreak build on 32-bit x86

src/citra_qt/configuration/configure_input.cpp
circle mod and buttons assigned as analog_from_buttons weren't being accounted for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5755)
=> citra_qt/configure_input: Account for analog buttons when checking for used buttons

src/core/hle/service/gsp/gsp_gpu.cpp, src/core/hle/service/gsp/gsp_gpu.h
Prevents several `-Wsign-compare` warnings from occurring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5395)
=> gsp_gpu: Resolve sign conversion warnings

src/audio_core/hle/ffmpeg_decoder.cpp, src/core/dumping/ffmpeg_backend.cpp
This pull request adds support for the just-released FFmpeg 5.0.
In FFmpeg 5.0, `av_opt_child_class_next` was replaced with `av_opt_child_class_iterate`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5956)
=> dumping/ffmpeg_backend: add support for ffmpeg 5.0

src/core/movie.cpp
While recording or playing a movie file, the left side of the status bar currently displays an input counter which shows how many times the emulator has polled for button inputs during the movie. This information is far less easily understandable and less useful for TASing compared to a frame count. The frame count has a linear relationship with input count that can be expressed with Frame Count = 0.255689103308912 * Input Count. Simply put, instead of having a counter that goes up by 3 or 4 every frame, this makes it a counter that goes up by exactly 1 every frame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5954)
=> Convert Input Count to Frame Count

src/core/dumping/ffmpeg_backend.cpp
Dolphin does it here
https://github.com/dolphin-emu/dolphin/blob/e932a1bfb71c73da48bb75f660b40b5f2c9de4a1/Source/Core/VideoCommon/FrameDump.cpp#L305
fixes #5965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6005)
=> explicitly set timebase for video stream

src/citra_qt/cheats.ui, src/citra_qt/configuration/configure_audio.ui, src/citra_qt/configuration/configure_camera.ui, src/citra_qt/configuration/configure_debug.ui, src/citra_qt/configuration/configure_enhancements.ui, src/citra_qt/configuration/configure_general.ui, src/citra_qt/configuration/configure_graphics.ui, src/citra_qt/configuration/configure_input.ui, src/citra_qt/configuration/configure_system.ui, src/citra_qt/configuration/configure_web.ui, src/citra_qt/debugger/ipc/record_dialog.ui
This changes the tab order for the elements of multiple widgets, particularly in some of the configuration pages, to be a more natural ordering (top to bottom, left to right, respecting grouped elements). Right now certain pages are very confusing to navigate with the keyboard using tab/shift+tab, which is bad from an accessibility and UX perspective.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6019)
=> Improve tab ordering

src/audio_core/dsp_interface.cpp
This changes the mapping the volume control slider to audio scaling factor from logarithmic to cubic. I am by no means a picky person when it comes to audio, but I found the volume too sensitive when adjusting in the mid-to-full loudness range. Looking into what Citra uses, I compared it to some other open source programs and found that most of them were using an exponential formula (specifically cubic, x^3) instead of a logarithmic one. These include [VLC](https://git.videolan.org/?p=vlc.git;a=blob;f=modules/audio_output/waveout.c;hb=a18c4d65700229eff926ef1381524bb21a7aab95#l907), [PulseAudio](https://github.com/pulseaudio/pulseaudio/blob/d851021cf59256a7e56d905ca55974153edd4a75/src/pulse/volume.c#L291), and at least sometimes in …
=> Use cubic mapping for volume control

src/citra_qt/CMakeLists.txt
This was omitted, which seemed to be preventing this tab from being translated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6042)
=> Add configure_enhancements.ui to CMakeLists.txt

src/network/CMakeLists.txt, src/web_service/CMakeLists.txt
This pull request exports OpenSSL linkage from the `web_service` target.
This is useful when #5519 is merged.
This patch has been tested in https://github.com/citra-emu/citra-multiplayer-dedicated for nearly half a year now, so should be safe to merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6045)
=> web_service: infect other targets with OpenSSL exports

src/android/app/src/main/jni/config.cpp, src/citra/config.cpp, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_web.cpp, src/citra_qt/main.cpp, src/citra_qt/multiplayer/chat_room.cpp, src/citra_qt/multiplayer/chat_room.h, src/citra_qt/multiplayer/client_room.cpp, src/citra_qt/multiplayer/direct_connect.cpp, src/citra_qt/multiplayer/host_room.cpp, src/citra_qt/multiplayer/host_room.h, src/citra_qt/multiplayer/lobby.cpp, src/citra_qt/multiplayer/lobby.h, src/citra_qt/multiplayer/state.cpp, src/citra_qt/multiplayer/state.h, src/core/CMakeLists.txt, src/core/announce_multiplayer_session.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/dedicated_room/CMakeLists.txt, src/dedicated_room/citra-room.cpp, src/network/CMakeLists.txt, src/network/announce_multiplayer_session.cpp, src/network/announce_multiplayer_session.h, src/network/network_settings.cpp, src/network/network_settings.h
Moves the related settings to an independent file, and move announce_multiplayer_session to network instead of core.
Should also remove the dependence on glad.
There should be no actual behaviour changes, but some testing would be nice.
Decreases the size of the resulting citra-room executable by 10~15MB
(Measuring on MSVC, there's a 12.300KB reduction in size, about a 85% reduction in the size of the citra-room executable. 
I don't remember if the initial report above was measured on mingw, but I'd guess there's probably a similar relative reduction in size)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5519)
=> Remove citra-room dependence on core

src/common/assert.h, src/common/common_funcs.h
MSVC now supports specifying __declspec on lambda functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6053)
=> common/assert: Use noinline lambda instead of a wrapper template 

src/tests/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/shader/shader_jit_x64_compiler.cpp, src/video_core/shader/shader_jit_x64_compiler.h
Fixes Gunman clive crashing when shader JIT enabled (#6006), there were a couple things that made it crash. The game is still bugged with the interpreter because BREAKC isn't implemented.
The game compiles large-ish loops with BREAKC near the entry, this breaks the back patching of the `jnz`, because Xbyak compiles a short `jnz` in `Compile_BREAKC`, simply passing `T_NEAR` when compiling the `jnz` does the trick.
The game also compiles nested loops(~that it never uses?~ nvm it does). Implemented nested LOOPs in the shader jit, the unit test are pretty basic, but the behaviour should be similar to the interpreter.
I've only tested with Gunman clive 1, and some regression testing doesn't seem to break anything so far.
@Seamed if you can test Gunman clive 2 and possible some other games too, …
=> shader_jit: Fixes for Gunman clive

src/citra_qt/main.cpp
Fixed an issue where screenshot action can be triggered with hotkey even when no game is loaded.Also removed the screenshot disable on pausing the game(although i am not sure why that was included in the first place!).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6070)
=> screenshot fixes

src/core/loader/3dsx.cpp
I stumbled upon a bug with the 3dsx loader implementation:
1. Set the `hdr.code_seg_size` in your 3dsx file to something like `0xFFFFFFFF`.
2. `seg_sizes[0] = (hdr.code_seg_size + 0xFFF) & ~0xFFF` will then be equal to 0, as it overflows then clears the least significant bytes.
3. `program_image` is initialized with the values in `seg_sizes[]`, as such it's size will be smaller than the actual header values.
4. Finally the file is read using `hdr.code_seg_size` as a size, reading `0xFFFFFFFF` bytes into a far smaller vector, leading to a heap-buffer-overflow.
I haven't checked if this can be exploited to achieve code execution, but my initial guess is no, though this could change in the future or if chained with another bug.
I have an example 3dsx file that will trigger this (it will …
=> loader: check for overflow of seg_sizes[] in 3dsx loader

src/citra/emu_window/emu_window_sdl2.cpp, src/citra/emu_window/emu_window_sdl2.h, src/citra_qt/bootmanager.cpp, src/core/frontend/emu_window.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_util.cpp
Fixes:
- GLSL version mismatch - see https://docs.gl/sl4/imageSize
- failure when loading shaders from shader cache
Within `ShaderProgramManager::LoadDiskCache`, `SDL_GL_CreateContext` immediately claims the created context for the current thread, causing a `MakeCurrent()` failure when the newly spun worker thread attempts to claim it. 
This may still work by accident if the main thread releases the context first (race condition), otherwise the shaders will fail to compile. It does seem the new driver is more strict when enforcing context/thread pairing.
Either way, the main thread has no current context after this operation, so save and restore functionality has been added.
This fixes issues I've seen on Win10 / RX 5500 XT / Pokemon Alpha Sapphire. It's necessary to remove Citra's shader …
=> Fix MakeCurrent and shader issues with AMD 22.7 driver

src/android/app/build.gradle, src/android/app/src/main/AndroidManifest.xml, src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/model/Cheat.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/model/CheatEngine.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/model/CheatsViewModel.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/ui/CheatDetailsFragment.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/ui/CheatListFragment.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/ui/CheatViewHolder.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/ui/CheatsActivity.java, src/android/app/src/main/java/org/citra/citra_emu/features/cheats/ui/CheatsAdapter.java, src/android/app/src/main/java/org/citra/citra_emu/ui/TwoPaneOnBackPressedCallback.java, src/android/app/src/main/jni/CMakeLists.txt, src/android/app/src/main/jni/cheats/cheat.cpp, src/android/app/src/main/jni/cheats/cheat.h, src/android/app/src/main/jni/cheats/cheat_engine.cpp, src/android/app/src/main/jni/id_cache.cpp, src/android/app/src/main/jni/id_cache.h, src/android/app/src/main/res/drawable/ic_add.xml, src/android/app/src/main/res/layout-ldrtl/list_item_cheat.xml, src/android/app/src/main/res/layout/activity_cheats.xml, src/android/app/src/main/res/layout/fragment_cheat_details.xml, src/android/app/src/main/res/layout/fragment_cheat_list.xml, src/android/app/src/main/res/layout/list_item_cheat.xml, src/android/app/src/main/res/menu/menu_emulation.xml, src/android/app/src/main/res/values/strings.xml
Based on https://github.com/dolphin-emu/dolphin/pull/10092, with adaptations made for differences in how Citra handles cheats.
You can access the cheat GUI while a game is running.
The landscape view you see above was originally made with Android TV in mind. If I recall correctly, Citra doesn't support Android TV, but since it already was implemented I saw no reason to remove it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6090)
=> android: Add cheat GUI

.ci/android/build.sh, .ci/android/upload.sh, .github/workflows/ci.yml, src/android/app/build.gradle
it has been long overdue, this PR fixes the android version always displaying the commit hash instead of the tag associated with the release.
Added product flavours to append `.canary` so that, canary builds can be installed alongside nightly/playstore releases.
@bunnei I'll need your help to setup the secrets, I'll DM you the details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6108)
=> Android: Sign and publish APKs on GitHub

CMakeModules/GenerateSCMRev.cmake, src/common/CMakeLists.txt, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Shader caches from previous version of citra are creating problems now that the OpenGL version has been bumped to 4.3 (and glsl to 430).
This change should make sure that they're invalidated, and that future changes to glsl will automatically invalidate the caches as well.
The change on the second commit wasn't necessary, but just in case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6117)
=> Invalidate older shader caches

src/video_core/renderer_opengl/renderer_opengl.cpp
pass false for bool anaglyph when calling OpenGL::GetPostProcessingShaderCode in Interlaced conditional branch
fixes https://github.com/citra-emu/citra/issues/6132
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6133)
=> Fix loading custom interlaced shaders (correction to incorrect "anaglyph" = true argument)

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.java, src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.java, src/android/app/src/main/java/org/citra/citra_emu/features/settings/utils/SettingsFile.java, src/android/app/src/main/jni/CMakeLists.txt, src/android/app/src/main/jni/config.cpp, src/android/app/src/main/jni/default_ini.h, src/android/app/src/main/jni/lodepng_image_interface.cpp, src/android/app/src/main/jni/lodepng_image_interface.h, src/android/app/src/main/jni/native.cpp, src/android/app/src/main/res/values/strings.xml
Allows users to use custom textures and dump textures on Android devices. Adds UI and config setting and implementation. Support for custom texture preloading is also available, but the setting in the UI is commented out in SettingsFragmentPresenter.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6144)
=> Android: Add support for custom textures and texture dumping

src/citra_qt/main.cpp
If a game is already running, Citra currently asks for confirmation before opening a new game dropped on the window, but not before opening a new game chosen from the game list. This PR adds confirmation to the latter case.
(Yes, I did this by accident.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6186)
=> citra_qt: ask for confirmation when changing games from the game list

CMakeLists.txt
Before, running clang-format on mingw was broken because mingw and win32 are not mutually exclusive. So, we have to check for mingw if win32 is true.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6188)
=> fix clang format on mingw/msys2

src/citra_qt/main.cpp, src/common/CMakeLists.txt, src/common/literals.h, src/common/memory_detect.cpp, src/common/memory_detect.h
See yuzu-emu/yuzu#3954 for more details.
Logs both physical memory and swap(file) sizes. These values are useful when giving support as yuzu requires a large pagefile/swap(file) in cases of low physical memory (less than 8 GB) to prevent early crashes.
Tested on both Windows and Linux, ~~macOS is untested.~~
**Update**: macOS is unit tested and verified to work on macOS High Sierra 10.13.6
In the log, it will show these 2 lines:
```
Host RAM: 15.85 GB
Host Swap: 16.00 GB
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5380)
=> Port yuzu-emu/yuzu#3954: "main: Log host system memory parameters"

src/citra/config.cpp, src/citra/default_ini.h, src/citra_qt/configuration/config.cpp, src/citra_qt/configuration/configure_enhancements.cpp, src/citra_qt/configuration/configure_enhancements.ui, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp
defaults to false, (right eye)
can be set to true (left eye)
partially addresses https://github.com/citra-emu/citra/issues/4881 by making sure the rgb output in mono mode matches the depth buffer (which is usually the right eye, since it is written last)
i still need to figure out a good way to grab other depth passes, either entirely in ReShade, or by adding some kind of option to expose them from Citra. :G
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6140)
=> add mono_render_left_eye option

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/texture_filters/nearest_neighbor/nearest_neighbor.cpp, src/video_core/renderer_opengl/texture_filters/nearest_neighbor/nearest_neighbor.frag, src/video_core/renderer_opengl/texture_filters/nearest_neighbor/nearest_neighbor.h, src/video_core/renderer_opengl/texture_filters/texture_filterer.cpp, src/video_core/renderer_opengl/texture_filters/texture_filterer.h
Closes #4707, closes #5274
I added a nearest neighbor filter, modeling the code after bicubic. I also renamed the none option in the settings to "none (Linear)". My rationale for that was that if somebody wanted to turn off filtering for performance, they would still know which one is disabling filtering, but they also know that it is effectively a linear filter. Anyway, some comparison screenshots:
**Nearest Neighbor:**
**Linear ("none"):**
It makes text look arguably better, and it makes that title screen look way better with nearest neighbor than linear filtering IMO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6189)
=> Add nearest neighbor texture filter

src/citra/config.cpp
and catch logic_error instead of exception, as stoll should only throw std::invalid_argument and std::out_of_range, and both inherit from it.
Fixes the current CI issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6196)
=> Resolve C4101 warning

src/common/CMakeLists.txt, src/common/string_literal.h, src/core/CMakeLists.txt, src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_tick_counts.cpp, src/core/arm/dynarmic/arm_tick_counts.h
Approximate how many cycles each instruction takes.
This is not an accurate model, and doesn't take into account pipeline effects or interlocks.
Intention is to hopefully improve performance in FMVs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6194)
=> arm/dynarmic: More accurate cycle counting

src/citra_qt/main.cpp, src/citra_qt/main.h
Allows secondary window to recognize `Toggle Screen Layout`, `Swap Screens`,  and `Rotate Screens Upright` hotkeys.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6198)
=> Qt: Implement more hotkeys for secondary window

src/citra_qt/main.cpp
See https://github.com/yuzu-emu/yuzu/pull/8367 for more details.
Original description:
Qt5 and Qt6 don't really do a good job of reporting Windows versions past the 2004 version.
Current: Windows 10 Version 2009
This Patch: Windows 10 Version 21H1 (Build 19043.1706)
Also: Windows 11 Version 21H2 (Build 22000.675)
Fixes: https://github.com/yuzu-emu/yuzu/issues/8362
Just Windows 11 Version 21H2 might be sufficient, but its easier to quickly delete some code than quickly add some code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6295)
=> Port yuzu-emu/yuzu#8367: "Logging: Report Post Windows 10 2004 versions, like Windows 11"

src/android/app/src/main/AndroidManifest.xml
Allow launching from Android TV (Leanback) Launcher.
This also requires marking a few features as optional that are  implied by the camera and microphone permissions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6330)
=> Update AndroidManifest for Android TV

src/core/hle/kernel/svc.cpp
Mimics official kernel behaviour by returning an `ERR_OUT_OF_RANGE` error instead of causing the emulator to crash by an `ASSERT`. Some Luma3DS builds allows custom flags in the processorID, and an application is able to test if they are implemented by checking the svc return value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6354)
=> CreateThread invalid processor ID return error instead of assert.

src/common/common_funcs.h
Should provide a nice stacktrace now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6360)
=> common\common_funcs.h:  use __builtin_trap for Crash()

src/common/file_util.cpp
MSVC dup doesn't seem to like being passed a -1 file descriptor and crashes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6368)
=> Check fd before using dup

src/core/hle/kernel/svc.cpp
Alternative to https://github.com/citra-emu/citra/pull/6333 based on comments there.
Sets the system status to error on svcBreak to trigger the fatal error dialog, same as when ```ERR_F::ThrowFatalError``` is called. This allows the user to choose whether to continue execution or quit the game, rather than silently continuing with no indication of error.
Tested using N3DS Internet Browser which I know currently hits an svcBreak early on. Before nothing would happen and it would continue running, now it throws up the error pop-up with choice as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6364)
=> kernel: Set system error status on svcBreak.

src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java, src/android/app/src/main/java/org/citra/citra_emu/utils/FileUtil.java
This PR intent to fix the report from https://github.com/citra-emu/citra/issues/6370#issuecomment-1483959431 .
Since `OpenFileResultContract` will return content uri, we will need to use `context.getContentResolver().openInputStream` to open `InputStream` instead of using file.
Please feel free to critique, and thanks for your code review 😄 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6373)
=> citra_android: fix crash while load amiibo

.ci/transifex/docker.sh, .github/workflows/ci.yml
See https://github.com/yuzu-emu/yuzu/pull/9058 for more details.
Original description:
Currently we're using the python client which uses an API that they claim will sunset Nov 30, 2022. The new client is written in go, and might be stable.
`tx push -s` actually appears to work properly, some of the other commands require tweaking, like instead of suggesting `tx pull -a` in dist/languages we need to suggest `tx pull -t -a`
I'm going to bother @lat9nq about adding the new client to https://github.com/yuzu-emu/build-environments/blob/master/linux-transifex/Dockerfile
Maybe
RUN wget https://github.com/transifex/cli/releases/latest/download/tx-linux-amd64.tar.gz && tar xf tx-linux-amd64.tar.gz tx && mv tx /usr/bin/tx && rm tx-linux-amd64.tar.gz
is valid, or maybe not
Also `apt-get install -y …
=> Port yuzu-emu/yuzu#9058: "New transifex client needs migrating to"

src/android/app/src/main/java/org/citra/citra_emu/utils/FileUtil.java
This PR fixes: #6394 .
When selecting internal storage root as citra directory, `getFilenameWithExtensions` might return incorrect value.
Please feel free to critique, and thanks for your code review 😄 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6400)
=> citra_android: fix select root as citra directory cause crash

src/android/app/src/main/java/org/citra/citra_emu/features/settings/utils/SettingsFile.java, src/android/app/src/main/java/org/citra/citra_emu/utils/DocumentsTree.java, src/android/app/src/main/java/org/citra/citra_emu/utils/FileUtil.java
This PR fixes: #6406.
As mentioned in the thread, 'openOutputStream' writes without truncation unless an open mode is specified. This PR specifies the open mode as 'wt' to ensure that the open mode is write with truncation.
Please feel free to critique, and thanks for your code review 😄 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6408)
=> citra_android: fix config is getting overwritten by default

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/citra_qt/configuration/configure_graphics.cpp
Since #6347, all qt surfaces have v-sync turned on, which would make it impossible to get higher framerates for speed-up on 60Hz displays, along with a few other oddities, regardless of the v-sync setting.
~~This re-adds the code that changes the default swap interval for all qt surfaces, with a small change to make it more explicit.~~
The opengl surface's swap interval wasn't being changed by the previous code, meaning that it would use the default. This meant vsync was forced to be on, and then the first change I had proposed on this PR had changed it to be off by default.
Now the vsync option actually controls the opengl surface swap interval.
- - - …
=> citra_qt: fix vsync issues

src/core/core.cpp, src/core/savestate.cpp, src/core/savestate.h
Updates zstd to the latest (v1.5.5), which may result in minor speed increases when saving or loading save states.
The better logging will make identifying the revision of loaded save states easier, helping the support team when dealing with users with incompatible save states.
The save state validation at the time of loading is not strictly necessary, as they are already validated in the `ListSaveStates` function, but it'll log the revision if the state is from a different Citra version. I also do not doubt the capacity of a user to somehow hit these new checks.
One of the minor changes intends to ensure the reserved bytes of the header are initialized with zero, which may help future efforts to add new fields to the header.
- - - …
=> Update zstd and improve savestates logging

src/android/app/src/main/res/layout/activity_cheats.xml, src/android/app/src/main/res/layout/activity_main.xml, src/android/app/src/main/res/values-night/citra_colors.xml, src/android/app/src/main/res/values/styles.xml, src/android/app/src/main/res/values/themes.xml
A few fixes and adjustments to make the current theme appear more consistent.
For the cheats activity top app bar color, the difference is *very* subtle but it wasn't the surface color before.
MainActivity BG color -
Before -
After - 
New FAB color
Before -
After -
New Dark Mode BG -
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6439)
=> citra_android: Theme adjustments

src/citra_qt/bootmanager.cpp, src/citra_qt/bootmanager.h, src/citra_qt/loading_screen.cpp, src/core/core.cpp, src/video_core/custom_textures/custom_tex_manager.cpp, src/video_core/custom_textures/custom_tex_manager.h, src/video_core/rasterizer_interface.h
Hello There This Pull request adds a loading screen for the preloading textures. Preloading textures have some problems this pull request solves: 
- citra freezing, windows OS has (citra is not responding) issue
- Cannot stop the emulation while textures are preloading, you have to kill citra process.
This PR can allows us to look at the progression of the preloading textures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6478)
=> Textures loading screen

src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h
This pull request ports some of the SDL fixes related to registering and deleting game controllers. This fixes a bug where the same controller is registered multiple times a second and eliminates some complexity when handling game controllers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6577)
=> input_common: sdl: Port yuzu sdl fixes

src/citra_qt/bootmanager.cpp
Often when exiting citra after launching a game, citra will actually crash with a null-pointer exception. This isn't a big deal as the user is trying to quit anyway; but if the log hasn't been flushed yet, it can end up being truncated and important info being lost.
Fixes https://github.com/citra-emu/citra/issues/6585.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6612)
=> Qt: Fix intermittent crash on exit

.github/workflows/ci.yml, src/android/app/build.gradle, src/android/app/src/main/java/org/citra/citra_emu/CitraApplication.java, src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.java, src/android/app/src/main/java/org/citra/citra_emu/ui/main/MainActivity.java, src/android/app/src/main/java/org/citra/citra_emu/utils/CiaInstallWorker.java, src/android/app/src/main/java/org/citra/citra_emu/utils/DiskShaderCacheProgress.java, src/android/app/src/main/jni/id_cache.cpp, src/android/app/src/main/jni/id_cache.h, src/android/app/src/main/jni/native.cpp, src/android/app/src/main/jni/native.h, src/android/app/src/main/res/values/strings.xml, src/android/build.gradle, src/android/gradle.properties, src/android/gradle/wrapper/gradle-wrapper.properties
Known issues - 
- ~~Installing a cia while another is already in progress will crash~~ Seems to work fine with WorkManager, needs some more testing
- SleepingSnake's issue where starting a game corrupts the update, known to happen Pokémon USUM, doesn't seem to happen with Animal crossing
- ~~"Swiping the app away" from the recent apps, will interrupt the CIA install and corrupt the update~~ Should be fixed with WorkManager edit: Doesn't seem to work with some Chinese phones
- ~~Moving citra to the background will continue installation, but unsure for how long~~ Should be fixed with WorkManager
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6508)
=> Android: Offload CIA installation to background thread 

src/core/hle/service/nfc/nfc_device.cpp
`StartCommunication` doesn't have to be explicitly enabled by the game. This can be enabled automatically by `StartDetection`
Fixes https://github.com/citra-emu/citra/issues/6667.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6671)
=> service: nfc: Start adapter communication on scan

src/core/hle/service/soc/soc_u.cpp, src/core/hle/service/soc/soc_u.h
Setting the TTL value of a socket to 0 with `setsockopt` means to set it to a default value, which corresponds to value 64 (verified by checking the soc module code).
Credits to @m4xw for figuring it out!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6835)
=> SOC: Fix setting TTL to default value when TTL = 0

src/core/hle/service/ac/ac.cpp, src/core/hle/service/ac/ac.h, src/core/hle/service/ac/ac_i.cpp, src/core/hle/service/ac/ac_u.cpp, src/core/hle/service/http/http_c.cpp
This allows the old 3DS browser (SPIDER) to connect to the internet and browse the web.
Screenshot:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6864)
=> http/ac: Fix failing assert and stub GetConnectingProxyEnable

src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_vulkan/vk_shader_gen.cpp
Halves the amount of generated shaders in games like Albw and others (163->74 on my fork from clean start to loading the game and spawning)
OpenGL portion copied and tested on my fork thats a few years behind (on double check didnt notice a difference)
Vulkan portion is completely untested, treated the same as the GL
The root issue is that stale values are causing us to think we need a new shader, when we actually dont.
Also has the nice side effect of also emitting less code in the shader.
Please proof-read & test for opengl and more importantly vulkan since thats completely untested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6895)
=> [ShaderGen] Avoid setting lighting states if components aren't enabled

src/core/core_timing.cpp, src/core/core_timing.h, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
Takes the parallel HLE concept from the following draft PR: #6282
A new method in `HLERequestContext` was added to support HLE multi-threading capabilities: `RunAsync`. This method takes two functions, the first one will be run asynchronously, while the second one will be run in the emulator thread once the result is ready to be placed in the IPC response and return control to the game. Two functions are needed because most HLE objects are not thread safe, so the result cannot be placed into the IPC response directly.
The idea is to relay blocking or intensive IO operations to another thread, instead of pausing the entire emulator thread. With this change, when a game requests an IO operation, the requesting game thread will be put to sleep until the HLE IO operation completes. This gives …
=> Add HLERequestContext::RunAsync

src/citra_qt/main.cpp
The `CustomTexManager` stores a reference to the current `ImageInterface` when created. Calling `RegisterImageInterface` afterwards, overwrites and frees the previous image interface, but the reference in `CustomTexManager` will still be used, even though it is now invalid.
As far as I know this only happens when directly launching a game via command line parameter. In that case, the `GMainWindow` constructor starts the game immediately and `System::Init` will create a default fallback image interface, since none was registered before. Only after this, the `QtImageInterface` is registered, which frees the default image interface. If a game uses custom textures, this results in an immediate use-after-free and in my case a crash.
As a simple fix, I moved the `RegisterImageInterface` call up …
=> Fix use-after-free when running game with custom textures via command line parameter

src/core/hle/service/csnd/csnd_snd.cpp
Applets were spamming the logs with `CSND::ExecuteCommands`, which made it very annoying to read what happened before an applet was opened.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7163)
=> Lower log level of CSND::ExecuteCommands stub warning

src/core/hle/kernel/ipc.cpp, src/core/hle/kernel/ipc.h
The previous implementation didn't guarantee that the mapped buffer pages and the guard pages were continuous, which would cause an ASSERT to fail in the reply path. To fix the issue, a single `MapBackingMemoryToBase` call is now done and then the state and permissions are changed for the guard pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7158)
=> Map MappedBuffer guard pages in a single operation.

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/system_titles.cpp
Adds the TWL tiles that are shipped by default with system updates to the NUS download list. Also, AM is modified so it can list those titles if they are installed. Normally, the titles are stored in TWL NAND, but since we don't have it, they are stored in CTR NAND for now.
This allows the lle NIM module to properly detect the latest system version is installed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7162)
=> Download TWL titles from NUS and list them in AM.

src/core/hle/service/qtm/qtm_s.cpp, src/core/hle/service/qtm/qtm_s.h
Stubs `QTM_S::GetHeadtrackingInfo`, which helps remove unneccessary logs in system settings (for that same reason, the stub warning is set as `LOG_DEBUG`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7166)
=> Stub QTM_S:GetHeadtrackingInfo

src/common/file_util.cpp
Adds the flag `_SH_DENYNO` to `_wfsopen` on Windows, which allows opening the file multiple times without it being locked. Fixes  games failing to open the same file multiple times without closing it first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7161)
=> Unlock RW access to opened files on windows

src/core/hle/service/cfg/cfg.cpp, src/core/hle/service/cfg/cfg.h, src/core/hle/service/cfg/cfg_defaults.cpp, src/core/hle/service/cfg/cfg_s.cpp
Implements cfg methods related to UUID clock sequence. This includes saving MCU data on a new file in the sysdata directory.
(Also implements a default value for `NpnsUrlID`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7169)
=> Implement cfg UUID Clock Sequence

src/core/hle/service/soc/soc_u.cpp, src/core/hle/service/soc/soc_u.h
This PR implements/imporves some missing SOC functionality, which includes:
- Implement initialization and shutdown of the service for individual processes.
- Limit sockets to their owner process.
- Proper handling of closed sockets.
- Proper handling of blocking sockets in `recv` calls.
- Async `connect` and `accept`.
- `SockAtMark`, `GetHostByAddr`, `SendToMultiple`, `CloseSockets`, `AddGlobalSocket` functions.
- More accurate error values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7176)
=> Implement some missing SOC functionality

externals/gamemode/CMakeLists.txt
The Linux build fails to compile because gamemode will try to link against `common` when it's not needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7276)
=> gamemode: Fix compile issues

src/core/hle/service/cecd/cecd.cpp, src/core/hle/service/cecd/cecd.h, src/core/hle/service/cecd/cecd_s.cpp
This allows usage of the LLE news sysmodule. Screenshot:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7278)
=> cecd: Stub GetCecInfoEventHandleSys

src/core/core.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/service/plgldr/plgldr.cpp
Fixes https://github.com/citra-emu/citra/issues/7315
When the thread destruction occurs in the process destructor, owner_process is nullptr so the limit isn't released properly. Also fixed a problem with the PLGLDR service, being always enabled and crashing the home menu if a default 3gx plugin was around. https://github.com/citra-emu/citra/pull/7317 fixes the crash though and allows 3GX plugins to work on the home menu
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7318)
=> kernel: Release thread resource limit in Thread::Stop

src/core/hle/service/cecd/cecd.cpp
While I was looking at the NEWS sysmodule, I noticed the params order for this command were backwards: the info type is the first param, followed by the buffer size.
This is accurate to my reverse engineered code for the NEWS sysmodule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7361)
=> cecd: Fixup GetCecInfoBuffer params order

src/video_core/pica/shader_unit.cpp
This has been done in the hardware renderer for quite some time, but not in the software path. Hero Bank reads r15.w without setting it first and expects it to be set to 1 to properly show the textboxes.
Due to this there was a slight difference in behavior between the implementations. Hardware renderer would display the textboxes correctly, but wouldn't show the text as that is rendered using a geometry shader with the software path. Software shaders wouldn't display anything on the other hand, as the resulting geometry would end up off-screen, due to the missing intialization
On console the game likely relies on vertex shader register preservation. Though, in contrast to geometry shaders that exclusively use the software path, vertex register preservation when combined with hardware …
=> shader_unit: Intialize temporaries on shader invocation

src/core/core.cpp
Fixes another regression from https://github.com/citra-emu/citra/pull/7272/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7330)
=> core: Do not update framebuffer layout on android

src/video_core/rasterizer_cache/rasterizer_cache.h, src/video_core/shader/generator/glsl_shader_gen.cpp
Seems to be the cause of the depth glitches in RADV. Also made sure the null surface is cleared to transparent as RADV also exhibited the black squares in the player's face
Citra (master) | Citra (PR)
-|-
Fixes:
https://github.com/citra-emu/citra/issues/7197
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7376)
=> glsl_shader_gen: Remove invariant qualifier

src/core/hle/service/cam/cam.cpp
Face Raiders for N3DS calls CAM service functions without first calling DriverInitialize that creates the implementation. To prevent crashing, check for this in places the implementation is used and create it. While at it, updated some missed result constants and made use of PopEnum instead of static casts
Fixes:
https://github.com/citra-emu/citra/issues/7353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7368)
=> cam: Ensure camera implementation is not null before using it

src/video_core/pica/pica_core.cpp, src/video_core/pica/shader_setup.cpp, src/video_core/pica/shader_setup.h
Luigi's Mansion Dark Moon, uses a fixed primitive geometry shader to render the rain particles in the first mansion. The geometry shader itself runs correctly, but it tried to multiply the final position with a matrix that was zero. After a bit of experimentation and examining the command lists, I noticed it wasn't initializing these specific geometry shader uniforms during the draw (or at all since the start of the game), but it was doing that for the appropriate vertex uniforms.
The game also seems to enable the gs exclusive configuration switch at specific points it wants to modify geometry uniforms and then disables it again, hinting that it relies on this propagation taking place. The behavior also logically makes sense, uniforms are common state between shader units so it wouldn't …
=> pica_core: Propagate vertex uniforms to geometry setup when not in exclusive mode

src/common/logging/filter.cpp, src/common/logging/types.h, src/core/hle/service/news/news.cpp, src/core/hle/service/news/news.h, src/core/hle/service/news/news_s.cpp, src/core/hle/service/news/news_s.h, src/core/hle/service/news/news_u.cpp, src/core/hle/service/news/news_u.h
This PR is a partial implementation of the NEWS sysmodule. The code is accurate to the reverse engineered sysmodule and has been tested against it on Citra using HLE vs LLE. More info can be seen on [3dbrew](https://www.3dbrew.org/wiki/News_Services)
The sysmodule uses a database named `news.db` where it stores some notification data such as the title, and if there are any new SpotPass or StreetPass notifications. The NEWS sysmodule doesn't handle StreetPass notifications, it only updates the DB header if there are new notifications using the `GetCecInfoEventHandleSys` command.
The sysmodule has a maximum of 100 notifications, and if that limit is reached, the oldest notification is deleted. This is handle by using an internal list of notification IDs sorted by date time, with valid …
=> Implement NEWS service

src/video_core/pica/geometry_pipeline.cpp, src/video_core/pica/pica_core.cpp, src/video_core/pica/pica_core.h, src/video_core/pica/regs_shader.h, src/video_core/rasterizer_cache/texture_codec.h
The following are a bunch of minor fixes, mainly to geometry shaders, that fix the TOA crashing in the tutorial battle to make the game playable. The particles emitted are also correctly rendered.
* The game does not enable GS exclusive mode at any point, which triggers the first assertion in geometry_pipeline. The assertion has been removed as there is no evidence that this disallows geometry shader execution. I have hw-tested this as well and geometry tests work correctly without it as well.
* The game does not initialize GPUREG_GSH_OUTMAP_MASK nor GPUREG_GSH_INPUTBUFFER_CONFIG. After testing, the former is propagated from VS writes under the same conditions as uniforms, while the latter is not progated (and wouldn't make sense either as it has a flag that enabled/disables gs). The game …
=> general: Fixes for Tales of the Abyss

src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
Currently, the RESOLUTION_FACTOR preference is being set with the GRAPHICS_API key and default. Therefore, it will set/retrieve the wrong values
This revision updates the RESOLUTION_FACTOR preference to use the RESOLUTION_FACTOR key and default value. As a result, RESOLUTION_FACTOR and GRAPHICS_API should store and return the correct (separate) values.
**Testing:**
I caught this in my fork (CitraVR)., which uses distinct defaults for RESOLUTION_FACTOR and GRAPHICS_API. To test this change, I verified:
- RESOLUTION_FACTOR preference contains the expected default value in settings
- setting the RESOLUTION_FACTOR preference does not change the value of the GRAPHICS_API preference.
- - - …
=> [SettingsFragmentPresenter.kt] correct RESOLUTION_FACTOR key/default

src/video_core/renderer_software/sw_lighting.cpp, src/video_core/shader/generator/glsl_fs_shader_gen.cpp
Captain Toad Treasure Tracker has an issue where the shadow intensity is too high which makes everything much darker compared to console. Looking at the generated fragment shader as noted in https://github.com/citra-emu/citra/issues/3920 the game samples the shadow texture from the lighting unit, compared to most other games that do it from TEV.
The resulting values from shadow buffer were all zero which made the light very dark. After tinkering a bit, it seems that shadow must be applied before the light ambient factor is taken into account, otherwise the shadow completely erases its contribution to the final pixel light. The game also has a relatively high ambience value so it seems like it's trying to offset the shadow darkness. This makes the shadows looks correct and match hardware …
=> glsl_shader_fs_gen: Apply shadow before ambient light

src/video_core/shader/generator/glsl_shader_gen.cpp
Pokemon Ultra Sun/Moon render a white fade animation on console, though that doesn't show up on Citra. Looking at renderdoc this is again a clipping issue, where the kind-of fullscreen pass the game does is getting discarded. The vertex shader computes the dot product between vec4(0.0, 0.0, 1.00098, 1.00098) and vec4(0.0, 0.0, -1.0, 1.0) which should be zero but it ends up a very tiny positive number. In the shader interpreter the result is the same but -1.0 is -0.9999754 etc.
I'm not sure where this inaccuracy comes from, or if renderdoc is not showing the full number for whatever reason. Either way increasing the epsilon value works around this and it most likely fine. Any value higher than this though is probably pushing it. Given the amount of games with such issues I'm wondering …
=> glsl_shader_gen: Increase z=0 epsillon

src/video_core/rasterizer_accelerated.cpp, src/video_core/renderer_software/sw_rasterizer.cpp, src/video_core/shader/generator/glsl_fs_shader_gen.cpp, src/video_core/shader/generator/glsl_fs_shader_gen.h, src/video_core/shader/generator/shader_uniforms.h, src/video_core/shader/generator/spv_fs_shader_gen.cpp, src/video_core/shader/generator/spv_fs_shader_gen.h
Silly me to assume PICA is a sane GPU that would follow OpenGL ES spec :P
Fantasy Life places the color of each box in const_color[0], but strangely it never uses it in the first stage. The aforementioned stage is configured as follows. It uses GPU_PREVIOUS as the first source and simply passes that to the next stage. The vertex color of the draw is vec4(1.f) so all the boxes appear white.
```
color_results_1 = combiner_output.xyz;
color_results_2 = const_color[0].xyz;
color_results_3 = const_color[0].xyz;
color_output_0 = clamp(color_results_1, vec3(0.0), vec3(1.0));
```
After testing this particular configuration however I noticed something else happened on hardware: the source1 value was replaced with whatever was in source3. This happens to source2 as well, when the combiner is op for …
=> video_core: Use source3 when GPU_PREVIOUS is used in first stage

src/core/CMakeLists.txt, src/core/hle/service/mcu/mcu.cpp, src/core/hle/service/mcu/mcu.h, src/core/hle/service/mcu/mcu_hwc.cpp, src/core/hle/service/mcu/mcu_hwc.h, src/core/hle/service/service.cpp
Allows CTRAging to work on Citra. I'm not sure how it used it work in the past, but the app was stuck waiting for the service handle to become available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7428)
=> service: Stub mcu::HWC
