citra-emu/citra

- src/citra_qt/debugger/graphics.cpp
Setting an object name allows for saving the Graphics Debugger's state (i.e., if it's shown and position). This state is restored when restarting the application.
Fixes issue #173 as this was already done for the Pica Command List.
> Set object name for the Graphics Debugger

- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
- src/video_core/color.h
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/utils.h
- src/video_core/vertex_shader.cpp
- src/video_core/vertex_shader.h
A number of followups to #284, i.e. some fixes but also some new stuff:
* Fixed decoding for some texture formats
* Fixed texture orientation
* Fixed texture wrapping for textures other than the first one
* Implemented alpha blending (only a very limited subset of possible code paths is implemented though)
* Implemented depth testing (only a very limited subset of possible code paths is implemented though)
* Added support for a few more texture enviroment configurations
* Implemented backface culling
Additionally, two small workarounds for some issues are added:
* Fixed framebuffer duplication / slicing bugs in 3dscraft (and probably other applications)
* Applications which don't set a w component for input position attributes now have that component forced to 1.0. This is similar to a …
> pica_progress followups

- src/citra_qt/debugger/callstack.cpp
- src/citra_qt/debugger/callstack.ui
- src/citra_qt/debugger/graphics_breakpoints.cpp
- src/citra_qt/debugger/registers.ui
- src/citra_qt/main.cpp
- src/citra_qt/main.ui
Change popout mode to "Single Window Mode".
Make letter cases consistent in menus and within widgets. The correct way to use letter cases is of course a matter of opinion, but at least now it's more consistent.
> Qt: Letter cases and single window mode

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Technically eliminates two memory leaks as well if this were to ever actually be called.
> dyncom: Remove dead function InterpreterInitInstLength

- src/core/arm/dyncom/arm_dyncom_dec.cpp
- src/core/arm/dyncom/arm_dyncom_dec.h
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Implemented LDREXD/STREXD/LDREXH/STREXH in dyncom. This fixes most games that did not boot before in dyncom, but did in armemu (e.g. Ikachan, Cave Story, etc). Ported the atomic_incs Valgrind test (https://github.com/liquid-mirror/valgrind/blob/7692f169aa556ea177b8e949abff2d3e224580e1/memcheck/tests/atomic_incs.c) to test these, and confirmed the correct output:
<pre>parent starting...
parent waiting for child...
child starting...
child done!
parent_continuing!
FINAL VALUES:  8 bit -74,  16 bit 32694,  32 bit 6913974,  64 bit 682858642110
PASS
parent exits</pre>
> dyncom: Implemented LDREXD/STREXD/LDREXH/STREXH

- src/citra/default_ini.h
- src/core/core.cpp
- src/core/core.h
Changes the default CPU core from armemu to dyncom. While it's worth keeping armemu around a little while longer (it may work better in some cases, and also to stay in synch with 3dmoo), dyncom is pretty much better in every way now. It implements more instructions, it's faster, cleaner, and is compatible with all titles (that I have tested) that previously booted with armemu (and more). That being said, please test with dyncom, and report any issues if you find something that works better with the old (soon to be deprecated) armemu core.
NOTE: If you previously set your config to use dyncom, you'll need to set cpu_core back to 0 with this PR.
> Core: Change default CPU to dyncom.

- src/core/file_sys/disk_archive.h
```
[18:23:24] <yuriks> looks like this is just a dumb bug in DiskFile
[18:23:27] <yuriks> that was masked by the memory leak
[18:24:15] <yuriks> so, if Open fails
[18:24:21] <yuriks> then file is never set, so it's null
[18:24:36] <yuriks> the destructor then doesn't check if file is null before trying to call a method on it
[18:25:28] <yuriks> and on that method, we were leaking the object if the open failed, so the destructor was never being called
```
> FileSys: Fix crash bug in DiskFile exposed by #400

- src/citra/citra.cpp
- src/citra_qt/bootmanager.cpp
This was causing spurious crashes related to destruction order of objects at shutdown.
> Frontends: Shutdown core when emulation is stopped

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/dyncom/arm_dyncom_run.h
- src/core/arm/dyncom/arm_dyncom_thumb.h
- src/core/arm/skyeye_common/skyeye_types.h
citra already has its own typedefs like this.
> skyeye: Remove duplicate typedefs

- src/core/hle/kernel/mutex.cpp
This will happen when the mutex is already owned by another thread. Should fix some issues with games being stuck due to waiting threads not being awoken.
> Mutex: Add the calling thread to the waiting list when needed

- src/common/common_types.h
Those two small changes make Citra able to compile on ARM, as long as _M_GENERIC is defined.
The only remaining uses of x86 code are for the Crash() function used here and there, and for the CRC32 hash function, which we don’t use at all and which isn’t implemented for any CPU that doesn’t have SSE4.2.
> Remove x86 specifics

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Whoever implemented this forgot to store the read value to the destination register.
> dyncom: Fix SWPB

- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
The Interfaces will be deleted by the handle table, so they shouldn't be manually deleted here. Fixes #423.
> Fix double-free in Service manager during shutdown

- src/common/thread_queue_list.h
- src/core/hle/kernel/thread.cpp
Replace all the C-style complicated buffer management with a std::deque.
In addition to making the code easier to understand it also adds support
for non-POD IdTypes.
> Common: Clean up ThreadQueueList

- src/core/hle/service/gsp_gpu.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
Changed GSP to toggle back and forth between the two framebuffers for each frame. This fixes the flicker seen in some games (e.g. Ocarina of Time 3D, 3DSCraft). It also makes both the top and bottom screens render in synchronization. See below:
> GPU: Toggle active framebuffer each frame

- src/core/core.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
This thread will not actually execute instructions, it will only advance the timing/events and try to yield immediately to the next ready thread, if there aren't any ready threads then it will be rescheduled and start its job again.
Closes #430
Depends on #425 
Some benches: http://tinyurl.com/m5on5tq
Some more benches: https://gist.github.com/Subv/aeaf84943721c3c22fba
>  Threads: Use a dummy idle thread when no other are ready. 

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
It will now properly wait the specified number of nanoseconds and then wake up the thread.
Depends on #439
> SVC: Fixed SleepThread

- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
This will keep track of idle ticks for us, and fixes some tickcount-related issues
> Timing: Use CoreTiming::GetTicks to keep track of ticks.

- src/core/core.cpp
- src/core/system.cpp
ARM_Disasm only has static methods, so there's no need to have an instance of it.
> Core: Fixed a crash and removed some unused variables.

- src/core/CMakeLists.txt
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/kernel/timer.h
- src/core/hle/svc.cpp
This PR implements the Timer kernel object.
The timer starts counting when SetTimer is called, and it awakes the waiting threads when the specified interval has passed.
Based on top of #425
Also requires #439
> Implemented timers

- CMakeLists.txt
This enables the /MP compiler flag, which parallelizes builds of by
distributing compilation of individual object files across workes
processes, instead of being limited to per-project parallelism.
Reduces the time for a full compile from 72 s to 45 s on my machine.
> CMake: Enable VS parallel builds for a good reduction in compile times

- src/core/hle/svc.cpp
Warn if a new thread is intended to be run on the system CPU core until we implement correct scheduling for such a thread.
> Warn if a new thread is intended to be run on the system CPU core

- src/citra_qt/debugger/disassembler.cpp
- src/core/arm/arm_interface.h
- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/arm/interpreter/arm_interpreter.cpp
- src/core/arm/interpreter/arm_interpreter.h
- src/core/core.cpp
- src/core/core.h
- src/core/core_timing.cpp
- src/core/hle/function_wrappers.h
- src/core/hle/hle.cpp
- src/core/hle/hle.h
- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/hid_user.cpp
- src/core/hle/svc.cpp
- src/core/hle/svc.h
- src/core/hw/gpu.cpp
This is a continuation of #331.
This purges thread.cpp/.h of most of its usages of Handle, replacing them with (for now) raw pointers. In a follow-up PR I will replace these with reference counted pointers, which will provide proper lifetime management. Logically that should've come before this, but it'd be too much work to reverse the order of the two branches now.
After this I'll follow and remove handles from the rest of the Kernel. When that's done we should be good to enable handle duplication and closing.
> Kernel Lifetime Reform Pt. 2

- CMakeLists.txt
`/Oi` is included in `/Ox` already
> Cleanup: Remove redundant /Oi flag

- CMakeLists.txt
- src/citra/CMakeLists.txt
- src/citra_qt/CMakeLists.txt
This fixes non-Xcode builds on OSX, a Clang warning, and cleans up the CMake files a bit. See commit comments for details (is this a bad way to do it...?)
> Build improvements

- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/service.cpp
- src/core/hle/svc.cpp
Follow up to/depends on #444.
This starts using `boost::intrusive_ptr` for managing the lifetime of kernel objects, which will be required as soon as handle closing is enabled, since objects will be able to exist independently of handles then. After this I will continue to work on removing Handles from the other kernel subsystems.
> Kernel Lifetime Reform Pt. 3

- CMakeLists.txt
Apparently _DEBUG wasn't being set on Linux or OS X. @archshift please test.
> CMake: Consistently set _DEBUG and NDEBUG in all platforms

- .travis-deps.sh
- .travis.yml
Caching won't work on our repository, I explained the reason on the [PR](https://github.com/citra-emu/citra/pull/319) page:
>This won't work. According to Travis:
>>The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure
>If we want to use caching without paid Travis account, we would need to move to Travis's new container-based infrastructure, which would require sudo: false, which means we can't use sudo, which is no good for our linux build.
> Revert "Travis: Enable caching of dependencies"

- src/core/hle/service/y2r_u.cpp
There is no documentation available on this function, but we set the result to false as a stub.
This allows Super Little Acorns to move all the way in game with pp3c.
> Stubbed y2r:u IsBusyConversion

- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/citra_qt/debugger/graphics_framebuffer.h
Fixes two errors from #449
```
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferWidthChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:87
QObject::connect:  (receiver name: 'PicaFramebuffer')
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferHeightChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:88 
QObject::connect:  (receiver name: 'PicaFramebuffer')
````
The other error is caused by a connect call on an invalid object, this->windowHandle() returns nullptr in the GRenderWindow constructor, I don't know of a proper way to fix this
> citra-qt: Fixed some Qt errors on initialization

- src/core/hle/kernel/thread.cpp
If a thread was woken up by something, cancel the wakeup timeout.
> Thread: Prevent waking a thread multiple times.

- appveyor.yml
This adds the `appveyor.yml` file to enable AppVeyor support. All @bunnei has to do is enable the repository on AppVeyor and we should be all set. [Example output](https://ci.appveyor.com/project/chinhodado/citra/build/1.0.20)
> Add appveyor.yml for AppVeyor support

- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
- src/citra_qt/debugger/callstack.cpp
- src/citra_qt/debugger/callstack.h
- src/citra_qt/debugger/disassembler.cpp
- src/citra_qt/debugger/disassembler.h
- src/citra_qt/debugger/registers.cpp
- src/citra_qt/debugger/registers.h
- src/citra_qt/main.cpp
This replaces it by two signals to note when execution stopped and when it continues. It makes more sense like this from a debugging point of view. This also causes the widgets to update immediately after the execution was paused, and not only after the first step.
It's probably best if someone reviewed it a bit.
> Replace OnCpuStepped signal

- src/citra_qt/debugger/callstack.cpp
- src/citra_qt/debugger/callstack.h
This fixes the issue that old members of the callstack would stick around, even when the callstack shortened.
> Qt Callstack: Clear the callstack every time it's updated

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
These were also missing the shifted register case.
> dyncom: Handle the ARM A2 encoding of STRT/LDRT

- src/core/CMakeLists.txt
- src/core/hle/hle.cpp
- src/core/hle/shared_page.cpp
- src/core/hle/shared_page.h
- src/core/mem_map_funcs.cpp
This is basically a copy paste of the config mem support. Addresses taken from 3dbrew's documentation.
Most variables other than the 3d slider and LED statuses aren't implemented yet.
The 3D slider's state defaults to off: previously 3dscraft tries to read the slider state from the shared page, gets garbage, goes into 3D mode, which I don't think is supported yet, and produces garbled graphics. With this change 3dscraft renders in 2D mode.
> Add some support for the shared page

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
A following PR will remove this perceived duplication. However, for now I add them like so, since the other scaling functions have it as well; the fixing of which is out of the scope of this branch.
> dyncom: Implement missing shifts in ScaledRegisterPostIndexed, etc

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
Gets rid of some warnings on higher warning levels. Also it makes the intent more explicit.
> dyncom: Clarify precedence for ternary statements

- src/core/core_timing.cpp
These are only used in this translation unit.
> core_timing: Mark several variables as static

- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
If you arranged the widgets in the way you want them already, the title bars really don't accomplish anything and just take away screen space. This adds an option to hide them.
> Add option to hide dock widget title bars

- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/event.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/mutex.h
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/session.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/apt_u.cpp
- src/core/hle/service/srv.cpp
- src/core/hle/svc.cpp
Complete rewrite of WaitSynchronization1/WaitSynchronizationN. Basically, with our previous implementation, WaitSynchronizationN was entirely broken (this PR fixes #469). This required some pretty massive refactoring, which actually greatly simplified a lot of code. This is a very large change, so I would appreciate a pretty in-depth code review (especially for silly C++ mistakes), as well as extensive testing. However, my usual test suite of homebrew and retail works fine. I also wrote a quite extensive addition to hwtests to validate my implementation (that of which now passes), and as such I'm fairly confident that the implementations of these functions are now pretty sufficiently correct (PR for hwtests to follow once I clean it up). Please let me know if you have any interesting …
> Fix WaitSynchronization

- appveyor.yml
- upload_to_mega.js
This PR will upload the build to Mega upon build completion on AppVeyor. Specifically, it will copy over the required Qt dlls to the build folder, remove the junk files, then compress the build folder into a `.7z` file, and upload that file into a Mega folder.
Why Mega? It provides free 50GB storage, no bandwidth limit for upload/download, no wait for download, has the ability to create folders, can share a whole folder, and the interface is nice. [An example](https://mega.co.nz/#F!HR0CzZKZ!fLqLt_7xO7aKqmeVxwkRKQ).
The name of the result file will be
<first 8 characters of the commit hash> - <first 100 characters of the commit message>.7z
The date of the commit is not included in the file name, since Mega can sort files based on upload date already (see my example folder above)
This will …
> AppVeyor: Upload build to Mega upon build completion

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Narrow scopes for the instruction variables. Remove unnecessary parentheses.
> dyncom: Minor cleanup

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
Implemented alpha testing per 3dbrew. Seems to fix the foliage in OoT:
> Alpha testing

- src/common/common_funcs.h
- src/common/scope_exit.h
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/address_arbiter.h
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/event.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/mutex.h
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/semaphore.h
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/shared_memory.h
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/kernel/timer.h
- src/core/hle/result.h
- src/core/hle/service/apt_s.cpp
- src/core/hle/service/apt_u.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hle/service/hid/hid_user.cpp
- src/core/hle/service/srv.cpp
- src/core/hle/svc.cpp
- src/core/mem_map.h
This continues #455 by converting the rest of the Kernel objects to not use Handles in their internal APIs. It also features some clean-ups around the code enabled by this.
My next PR will resolve some circular reference issues present between Thread and WaitObject, and then finally enable handle closing and object freeing.
PS: I recommend a commit-per-commit review, since they are pretty well organized.
Also, I didn't have time to test much, so I probably broke many things.
> Kernel Lifetime Reform Pt. 4

- src/core/arm/interpreter/armemu.cpp
- src/core/arm/interpreter/arminit.cpp
- src/core/arm/interpreter/armsupp.cpp
- src/core/arm/skyeye_common/armdefs.h
- src/core/arm/skyeye_common/armemu.h
- src/core/arm/skyeye_common/skyeye_defs.h
Removes a lot of unnecessary stuff that's stuffed into the ARMul_State struct. Now it also takes up less space in memory since it gets rid of a few mallocs as well. Will also make removing the armemu interpreter stuff a little easier in the future.
> arm: Cleanup.

- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/shared_memory.h
added `this->` to `base_address` for side-by-side consistency.
> shared_memory: Fix assignments in SharedMemory::Map

- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
These variants exclusively read from the single precision regs and write to double-precision registers
Fixes issues where converted values would be way off from what they should be due to the results being stored in the wrong registers.
This was something super obvious that took way too much time to debug and I feel like an idiot for not noticing it sooner.
> vfp: Fix VCVT

- src/video_core/math.h
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
Implements the other color and alpha modifiers (several games spammed the logger with GPU errors regarding these). E.g., the Cubic Ninja intro logos now both show up with proper fades:
> Implement color/alpha modifiers

- appveyor.yml
It's currently doing 32-bit builds, which are useless since they crash right after booting a game.
> Appveyor: Do x64 builds

- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
This was fixed for vfpsingle, but not vfpdouble
> vfpdouble: Fix the FTOUI NaN sign setting

- src/core/arm/arm_interface.h
- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
* Simplifies scheduling logic, specifically regarding thread status. It should be much clearer which statuses are valid for a thread at any given point in the system.
* Removes some dead code from thread.cpp.
* Moves the implementation of resetting a ThreadContext to the corresponding core's implementation.
I have a more aggressive refactor in progress as well (not yet passing all waitsync tests) which builds on top of these changes.
> Scheduler refactor Pt. 1

- src/core/arm/dyncom/arm_dyncom_thumb.cpp
These don't need to be recreated all the time.
> arm_dyncom_thumb: Make lookup tables static

- src/core/arm/interpreter/armcopro.cpp
- src/core/arm/interpreter/arminit.cpp
- src/core/arm/skyeye_common/armdefs.h
- src/core/arm/skyeye_common/armemu.h
- Removed the Debug parameter from ARMul_State since it isn't used.
- Changed ARMul_CoProInit to a void function. It always returned true.
> arm: Remove TRUE/FALSE defines

- src/core/hle/service/gsp_gpu.cpp
Call SetBufferSwap for each screen on corresponding signal interrupt. Courtesy of @yuriks assisting with debugging Gunman Clive.
> GSP SetBufferSwap fix

- src/core/arm/interpreter/arminit.cpp
- src/core/arm/skyeye_common/armdefs.h
This will never be used. 32-bit is the norm.
> arm: Remove ARM26 support.

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
This is tested to work correctly.
> dyncom: Remove warning for SXTAH

- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/arm/dyncom/arm_dyncom_run.cpp
- src/core/arm/interpreter/arminit.cpp
- src/core/arm/skyeye_common/armdefs.h
- src/core/arm/skyeye_common/vfp/vfp.cpp
- src/core/core.cpp
Sets them into user mode and changes the APSR accordingly.
> Dyncom: Correctly set the ARM modes on dyncom initialization.

- src/core/arm/skyeye_common/armemu.h
This enum value is ORed against in ARMul_Reset (and used to refer to all interrupt bits in the CPSR). So simply updating this is enough because the A bit is an interrupt bit.
> arm: Set the A bit on reset.

- src/core/hw/gpu.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
Implement the remaining framebuffer formats in the OpenGL renderer, and rename the default format from RGB8 to BGR8, since that’s what it is.
> Framebuffer formats

- src/core/hle/service/service.cpp
err:f is a named port, not a service
> Services: Fixed "Tried to connect to named port err:f".

- src/video_core/rasterizer.cpp
Redeclaring the variable inside the switch was causing weird behavior.
> Rasterizer: Fixed a warning in GetWrappedTexCoord.

- src/core/hw/gpu.cpp
in Display Transfers, tested with hwtests.
Verified with https://gist.github.com/Subv/ae2dedc1236b21f9fdbe I'll PR this to the hwtests repo later today after I speak with @Normmatt
> GPU: Fixed the RGBA8 input format and RGB8 output format

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/mem_map_funcs.cpp
SkyEye was apparently written against a memory system that would return unaligned 32-bit reads in a "shifted way". Our Read32 implementation would do the opposite shift, so that the interpreter would end up with the correct value. This assumed that Read32 would only be called with an aligned address, or that if it were called with an unaligned address, the necessary shift would be performed in the interpreter. These changes remove both shifts so that no special behavior is needed for unaligned reads.
Note that the SkyEye interpreter (our interpreter in its current state?) only did this shifting for 32-bit reads. Therefore, we don't need to do anything special for 16-bit reads, and hence the comment was simply removed.
> Clean up unaligned 32-bit memory reads

- src/core/hw/gpu.cpp
Adds RGB5A1 and RGBA4 pixel formats.
@neobrain's code from his pica_progress3 branch.
> GPU: Add support for more framebuffer formats in display transfers.

- src/core/hw/gpu.cpp
> GPU: Fixed RGBA8 as output format in a display transfer.

- src/core/hle/service/y2r_u.cpp
Aero Porter was throwing an "Invalid Handle" fatal error without this.
> Services: Implemented Y2R_U::GetTransferEndEvent

- src/common/common_paths.h
- src/common/file_util.cpp
This allows for easily movable and independent configuration and data directories, using standardized paths.
Here is the specification: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
> Switch to the XDG Base Directory Specification for directory selection

- src/video_core/debug_utils/debug_utils.cpp
This was caused during morton decoding by me not masking the bits of
each coordinate before merging them, so the bits from x could set bits
in y if it was >255.
> Video core: Fix pixelation/blockiness in textures.

- src/video_core/debug_utils/debug_utils.cpp
It was trying to take the LSB from `coarse_x`, which would always be 0
and thus would always return the same texel from each byte. To add
insult to the injury, the conditional was actually the wrong way around
too.
Fixes blocky text in OoT.
> Video core: Fix A4 texture decoding

- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/rasterizer.cpp
- src/video_core/utils.h
Bit 3 is used to specify a raw copy, where no processing is done to the data, seems to behave exactly as a DMA.
Bit 1 is used to specify whether to convert from a tiled format to a linear format or viceversa.
Verified with hwtests
> GPU: Implemented bits 3 and 1 from the display transfer flags.

- src/core/arm/disassembler/arm_disasm.cpp
Also declared an array as static, as it's only used in this translation unit.
> arm_disasm: Remove unused variable

- src/core/arm/disassembler/arm_disasm.cpp
Changed cond_to_str to take a uint32, since unsigned numbers are only ever passed to it, and this can be a source of warnings for some compilers (also indexing an array without bounds checking a signed number is kind of iffy).
> arm_disasm: Show conditional code for BKPT instructions.

- src/core/hle/service/ptm_sysm.cpp
This allows the Home Menu to boot further
> Services/PTM: Stubbed PTM_Sysm::IsLegacyPowerOff.

- src/core/hle/result.h
It's unnecessary to make copies for simple comparisons like this.
> result: Make comparison operators take references

- src/core/hle/service/fs/fs_user.cpp
We won't be emulating this for the foreseeable future and it is needed for Home Menu to boot further
> Services/FS: Stubbed CardSlotIsInserted to always return false

- src/core/hle/service/am_sys.cpp
They will always return 0 titles for every media type for now.
This is needed to boot Home Menu further
> Services/AM: Stubbed TitleIDListGetTotal and GetTitleIDList.

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/citra_qt/debugger/graphics_framebuffer.h
- src/core/hw/gpu.cpp
- src/video_core/CMakeLists.txt
- src/video_core/color.h
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
Implements RGB565 and RGB8 framebuffer support. I also refactored framebuffer format encoding/decoding to use shared code that properly handles endianness. Verified correct behavior with multiple games that exercise different framebuffer formats:
> GPU: Added RGB565/RGB8 framebuffer support and various cleanups.

- src/citra_qt/CMakeLists.txt
- src/citra_qt/debugger/profiler.cpp
- src/citra_qt/debugger/profiler.h
- src/citra_qt/debugger/profiler.ui
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/common/CMakeLists.txt
- src/common/profiler.cpp
- src/common/profiler.h
- src/common/profiler_reporting.h
- src/common/synchronized_wrapper.h
- src/common/thread.h
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/hle/hle.cpp
- src/video_core/command_processor.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
This adds a simple frame and scope-based profiler. You can access it through the Qt UI to see per-frame ms statistics. It should make our bottlenecks (even) more obvious and hopefully allow some quantification when doing optimization efforts.
I just added a few major basic sections to the profiler mostly as examples of usage. Interested parties should go and add more useful scopes. I've also wanted to do more with this, including being able to take a measure of a specified number of frames, which should allow for completely repeatable benchmarks, as well as grouping of categories in a hierarchy. However, right now this is sufficient for my needs and I want to move onto more useful emulation work, so this will do for now. If someone wants to complete these enhancements, feel free to.
> Add profiling infrastructure and widget

- src/video_core/debug_utils/debug_utils.cpp
The problem was a typo, coordinates with x < 2 should apparently use the first lookup table whereas our code was using the second table. The fix was taken from 3dmoo's code https://github.com/plutooo/3dmoo/commit/a57d27cabbb598110b518a6c6637e1265e1811b0#diff-db756bba03e234eb3ad60cf015e7d0adR802
> GPU/Textures: Fixed ETC texture decoding.

- src/citra/emu_window/emu_window_glfw.cpp
- src/citra_qt/bootmanager.cpp
- src/common/emu_window.cpp
- src/common/emu_window.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/video_core.cpp
- src/video_core/video_core.h
Precursor PR to touchpad support. This moves the logic for setting the render window framebuffer layout (e.g. width, height, top screen boundaries, bottom screen boundaries) from the renderer to EmuWindow the implementation. Because for now our two EmuWindow implementations use the same basic layout (top screen + bottom screen scaled to the window size), I made a default function for computing the layout part of EmuWindow so that it can be shared. But this design is more flexible and should allow for more creative things in the future (e.g. making the lower screen a thumbnail, or putting it on a separate window).
> Set framebuffer layout from EmuWindow.

- src/citra/default_ini.h
Apparently inline comments is not necessarily standard in the INI format, and our parser was erroneously parsing the comments as values.
> default_ini.h: Put comments on their own lines

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
These variants are privileged instructions ("LDM/STM (User Register)" variants) so this doesn't affect anything a game could do. May as well be correct about it regardless.
> Minor bugfixes to LDM/STM.

- src/citra/citra.cpp
- src/citra_qt/main.cpp
- src/common/logging/backend.cpp
- src/common/logging/backend.h
- src/common/logging/filter.h
- src/common/logging/text_formatter.cpp
- src/common/logging/text_formatter.h
This puts back 3dscraft to its performance level of before logging.
> Apply the logging filter before sending the message to the queue

- src/core/hw/gpu.h
It was using the same bit position as the "trigger" bit.
> GPU: Use the correct position for the finished bit in memory fills

- src/video_core/primitive_assembly.cpp
Woop woop. No more annoying culling hacks needed.
> Pica/PrimitiveAssembly: Fix triangle strips and fans being generated with incorrect winding order.

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/gsp_gpu.cpp
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
- src/core/hw/hw.cpp
- src/core/hw/hw.h
- src/core/hw/lcd.cpp
- src/core/hw/lcd.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
In the process, adds `hw/lcd` for the LCD registers.  
I still need to test on hardware to confirm that this is correct, but preliminary information suggests so. 
@neobrain, comments?
> Implement SetLcdForceBlack and add implementation for color filling in the GPU code

- src/common/emu_window.h
> EmuWindow: Fixed a reference to a temporary variable

- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
This is based on information on 3dbrew.
Tested with blargSNES, and this is the output, the top screen is now correctly flipped: http://i.imgur.com/yaoAzLj.png
> GPU: Implemented the flip_data (bit 0) bit in display transfers.

- src/video_core/color.h
- src/video_core/debug_utils/debug_utils.cpp
This removes a few annoying warnings in VideoCore.
> Add static_cast around expressions where the compiler doesn’t deduce the right type

- src/common/common_paths.h
- src/common/platform.h
This also adds back the ability to change the name of the default main directory name at compile-time on Windows.
> Fix two minor understandability issues in common

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hle/service/hid/hid_spvr.cpp
- src/core/hle/service/hid/hid_user.cpp
This fixes the freeze when pressing the ocarina on the touch pad in OoT.
>  HID: Proper Signal Interrupts for EnableAccelerometer & EnableGyroscopeLow along  with a stub for GetSoundVolume

- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
It is used to downscale the input image horizontally and vertically, previously we were only downscaling it vertically so this caused a hard-to-debug memory corruption problem.
This fixes 2048 and possibly other games.
Tests at https://github.com/citra-emu/hwtests/pull/29
Still TODO: Implement the actual box filter when downscaling
> GPU: Fixed the bit 25 in the display transfer flags.

- appveyor.yml
This fixes AppVeyor uploading to the build server (although I don't know how this wasn't caught when it built earlier, but w/e)
> Strip newlines on the build name before trying to upload.

- appveyor.yml
No idea why these spaces are only added on recent revisions of Citra
(older revisions did not have this problem).
Let's just remove the spaces then in Powershell.
> Remove mysterious spaces that were added by `git show --format`

- src/core/arm/dyncom/arm_dyncom_dec.cpp
- src/core/arm/dyncom/arm_dyncom_dec.h
Should also fix warnings related to macro redefinitions.
> dyncom: Remove unused/unnecessary macros and macro constants

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
These are system instructions, but they can be easily implemented. Since the dyncom handles banked registers in the background upon mode switching, we don't need to care about handling them explicitly.
> dyncom: Implement RFE and SRS.

- src/core/hle/config_mem.cpp
Since we aren't emulating the actual firmware, games that would use more then 64MB would crash. Because on the real 3ds, the firmware would change its Config Memory to comply with the game's memory resources.
Pokemon Gates to Affinity no longer crashes at boot, and you can almost get in game.
> ConfigMem: Set the app memory to be 96MB instead of the default 64MB

- src/citra_qt/debugger/callstack.cpp
Decode is a static function. There's no need to allocate a disassembler instance.
Technically this function would also leak every time it's called because of this.
> callstack: Remove unnecessary disassembler instantiation

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/core/settings.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
The background color can be seen at the sides of the bottom screen or when the window is wider than normal.
> Allow the user to set the background clear color during emulation

- src/core/hle/service/gsp_gpu.cpp
- src/core/mem_map.h
- src/core/mem_map_funcs.cpp
This gets rid of spurious error messages like these:
```
[  18.481601] HW.Memory <Error> core\mem_map_funcs.cpp:Memory::VirtualToPhysicalAddress:48: Unknown virtual address @ 0x14189c70
[  18.481601] HW.Memory <Error> core\mem_map_funcs.cpp:Memory::PhysicalToVirtualAddress:32: Unknown physical address @ 0x14189c70
[  18.558621] HW.Memory <Error> core\mem_map_funcs.cpp:Memory::VirtualToPhysicalAddress:48: Unknown virtual address @ 0x14046520
[  18.558621] HW.Memory <Error> core\mem_map_funcs.cpp:Memory::PhysicalToVirtualAddress:32: Unknown physical address @ 0x14046520
```
> Clean-up mem_map constants and fix framebuffer translation errors

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
The switch cases will always be hit, but this makes compilers stop complaining.
> dyncom: Suppress uninitialized variable warnings

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/dyncom/arm_dyncom_run.h
- src/core/arm/dyncom/arm_dyncom_thumb.cpp
- src/core/arm/dyncom/arm_dyncom_thumb.h
- src/core/arm/skyeye_common/skyeye_defs.h
Also fixes descriptions in the process.
> dyncom: Remove unnecessary enum and typedef

- src/core/hle/kernel/shared_memory.cpp
Initialize base_address to 0x0. Instead of leaving it as uninitialized (0xcdcdcdcd) which is out of memory range. This should now identify the unmapped block, rather than reporting bad pointer.
> Shared_memory: Initialize base address to 0x0

- src/common/thread_queue_list.h
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/svc.cpp
Adds support for priority boosting for starved threads, priority inheritance for mutexes, some additional (verified) error codes on svcCreateThread, and some additional bug fixes/improvements. I've written some hardware tests that I'll publish at a later time that verify these changes. Some outstanding things for my next PR:
* Identify any other scenarios (other than a mutex wait) that might cause priority inheritance (and implement)
* Implement kernel reschedule on other SVCs as appropriate
* RE other error codes that are used and implement
> Thread priority and scheduler improvements

- src/citra_qt/debugger/graphics_breakpoints_p.h
- src/citra_qt/debugger/profiler.h
- src/citra_qt/util/spinbox.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/arm/skyeye_common/vfp/vfp_helper.h
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
- src/core/file_sys/disk_archive.h
- src/core/hle/kernel/timer.cpp
This was just at its default error reporting level.
The remaining warnings are mostly due to UNREACHABLE() not telling it really is unreachable to the compiler.
> Fix a few warnings as reported by clang 3.6

- src/core/hle/hle.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
This reduces the time for a full recompile from 65.43s to 59.53s (~9%)
> De-inline functions from Interface, removing them from service.h

- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
Also fixed a  bug in the exheader, since some values on 3dbrew were using the  decimal format for some of the types instead of hex resulting in a invalid size for the exheader, to make sure this doesn't happen again I added a static assert for the exheader and for the ncch header, I also decided that logging some of the exheader values(like the stack size, bss size, etc.) would provide somewhat useful debug info.
> Services/Loader: Use more sensible log formats for certain functions along with more info being logged.

- src/citra/emu_window/emu_window_glfw.cpp
- src/citra_qt/bootmanager.cpp
- src/common/emu_window.cpp
- src/common/emu_window.h
Instead of ending the TouchMove when the mouse is dragged outside the touchpad area, clip the coordinates and allow the TouchMove to continue.
> Clip mouse input touchpad area

- .gitmodules
`git config submodule.<submodule>.url some/local/path` can now directly define where to find the submodule.
> Rename git submodules, so they are more easily accessible from external tools

- src/common/common_funcs.h
- src/common/hash.cpp
- src/common/mem_arena.cpp
- src/common/memory_util.cpp
- src/common/platform.h
The old system of just defining macros available in some other platform
was susceptible to silently using the wrong code if you forgot to
include a particular header. This fixes a crash on non-Windows platforms
introduced by e1fbac3ca13d37d2625c11d30cfdece4327b446b.
> Common: Add proper macros to test for architecture pointer size

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
All this was doing was needlessly aliasing a variable.
> dyncom: Remove an unnecessary variable in the interpreter

- src/common/common_funcs.h
- src/common/string_util.cpp
- src/common/string_util.h
- src/core/CMakeLists.txt
- src/core/file_sys/archive_savedata.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/process.h
- src/core/hle/kernel/thread.h
- src/core/loader/3dsx.cpp
- src/core/loader/3dsx.h
- src/core/loader/elf.cpp
- src/core/loader/elf.h
- src/core/loader/loader.cpp
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
- src/core/mem_map.h
This adds a `Process` object to the kernel, which for now only holds kernel process settings. It also adds support for reading those from the ExHeader in NCCHs, or providing default values for other file types.
> Kernel: Process class and ExHeader caps parsing

- src/citra_qt/main.cpp
- src/core/loader/loader.cpp
- src/core/loader/loader.h
It is of very limited practical utility currently, and will soon be
impossible to support due to more accurate memory map emulation.
> Loader: Remove .bin file support

- src/common/common_funcs.h
- src/core/hle/kernel/process.cpp
When the macro was introduced in 326ec51261299e48de97592631c02523da9c8118
it wasn't noticed that it conflicted in name with a heavily used macro
inside of dyncom. This causes some compiler warnings. Since it's only
lightly used, it was opted to simply remove the new macro.
> Common: Remove the BIT macro

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/vertex_shader.cpp
This is a bunch of small GPU emulation fixes/improvements initially started to fix Steel Diver. Commits are all separate and should probably be individually reviewed. Summary:
* Added MADI and FLR vertex shader instructions
* Added combiner buffer (i.e. "previous combiner buffer" color source)
* Added "AddSigned" combiner operation
* Added combiner output scaling
* Fixed a bug with depth testing (via @Subv)
* Fixed a bug with invalid vectors being returned for unimplemented features
> GPU improvements

- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/shared_memory.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ir/ir.cpp
- src/core/hle/svc.cpp
Fixes crashes in MSVC debug mode introduced by #725.
> Fix crashes due to un-initialized GSP shared memory

- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.h
@neobrain, could you confirm that this is correct?
It's been tested with various different games and fixes different textures, including in Animal Crossing, Kirby Triple Deluxe, and SMB3D.
> Implement I4 texture format

- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
Apparently "top" really means top, and not "bottom" like I seemed to be thinking at the time.
> Thread: Correctly set main thread initial stack position

- src/core/arm/skyeye_common/vfp/vfp_helper.h
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
A few games use this instead of being fully IEEE compliant (e.g. Cubic Ninja), along with Default NaN mode (which is already supported).
> vfp: Handle flush-to-zero mode.

- src/core/hle/kernel/thread.cpp
Fixes a crash in swkbd, and could probably fix many other threading bugs
(Sadly it doesn't fix the MoFlex playback bug :( )
> Core/Scheduling: Prepare the new priority in the thread queue when svcSetPriority is called

- src/core/core.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
This felt too easy, but I couldn't trigger any nullptr or assert crashes after running things in a debug build for a while, so I'm gonna call it good.
This preemptively fixes the crash issue @Subv would have created in #748
> Thread: Remove the idle thread

- src/core/hle/kernel/process.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/mem_map.h
The real kernel autogrows the TLS area as more threads are created, up to an unknown limit, but for our purposes this will suffice for now.
This fixes #743
> Core/Memory: Add TLS support for creating up to 300 threads

- CMakeLists.txt
- dist/citra.desktop
- dist/citra.svg
- dist/citra.xml
This makes Citra launchable from DE menus, applications, or by clicking on a 3DS file in a file manager.
For now those files are only installed on Linux, FreeBSD, OpenBSD and NetBSD, as I’m not sure which other platforms would use them, but this list can easily be extended.
> Install a .desktop file to make citra-qt launchable from DE menus

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
A shift here is intended since the representation is imm12:imm4.
No actual behavior is affected by this (the immediate is purely for assembly/disassembly purposes), but it's more correct.
> dyncom: Fix decoding of BKPT's immediate

- src/citra_qt/main.cpp
> Qt: Shutdown emulation session only if EmuThread exists.

- src/core/CMakeLists.txt
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/process.h
- src/core/hle/kernel/resource_limit.cpp
- src/core/hle/kernel/resource_limit.h
- src/core/hle/svc.cpp
- src/core/loader/3dsx.cpp
- src/core/loader/elf.cpp
- src/core/loader/ncch.cpp
Implemented svcs GetResourceLimit, GetResourceLimitCurrentValues and GetResourceLimitLimitValues.
Note that the resource limits do not currently keep track of used objects, since we have no way to distinguish between an object created by the application, and an object created by some HLE module once we're inside Kernel::T::Create.
If you see some place where we can start using resource limits, let me know and I'll implement it either here or in a future PR.
> Core/ResourceLimits: Implemented the basic structure of ResourceLimits.

- src/video_core/command_processor.cpp
This fixes a regression in 3dscraft, and maybe other games.
The behavior is consistent with what happens on 3dscraft on hardware
closes #735
> GPU/DefaultAttributes: Let the attribute data from the loaders overwrite the default attribs.

- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
Adds support for threaded pausing so citra doesn't spin wait on pause. Fixes #779
> Use condition var to properly pause the CPU thread

- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/y2r_u.cpp
- src/core/hle/svc.cpp
This is a few fixes to get Zelda: A Link Between Worlds (boots to the menus, but lots of issues), Zelda: Majora's Mask (shows some graphics, still totally broken), and MOFLEX games (Aero Porter, Brunswick Pro Bowling, etc.) to boot (no video output, but it won't hang). The MOFLEX videos will still try to play, but they will appear as a black screen (and could take a while to compete). 
Obligatory Zelda screenshot:
Summary of changes:
* Cause a threading reschedule on underlying rescheduling mechanisms, not within the SVCs themselves (e.g. if Citra calls them, but not the game, they should still rechedule)
* Trigger the interrupt signal for Y2R conversions being completed (used for MOFLEX videos), even though they are unimplemented at this time
> Thread reschedule and MOFLEX fixes

- src/core/hle/kernel/kernel.h
This fixes a warning, and will error the next time another handle type is added.
> ResourceLimit handles shouldn’t be waitable

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/y2r_u.cpp
Implements unrotated planar YUV 4:2:0 -> RGB24 conversions in Y2R.
Currently only the Y (luma) channel is used, so the results don't
contain color. This will be added in a later PR at some point.
This is enough to get all currently know Moflex videos to decode. (Some
don't display on-screen due to seemingly unrelated reasons.)
Thanks to @archshift for doing the initial implementation which I
cleaned up and then fixed the 8x8 block mode.
> Service::Y2R: Support for grayscale decoding of specific formats

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/CMakeLists.txt
- src/video_core/clipper.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.cpp
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/pica_to_gl.h
- src/video_core/vertex_shader.cpp
- src/video_core/vertex_shader.h
- src/video_core/video_core.cpp
This PR creates a new struct, `Pica::State`, and moves `Pica::Regs` and vertex shader memory there.  The purpose of this struct is to consolidate all Pica memory, primarily to make state management easier, but also cleanliness - as I introduce new features that require additional memory/state, I don't want it sprinkled as static objects all throughout various modules. A few cleanups/refactors were necessary for this change.
> GPU: Consolidate Pica state

- src/citra_qt/bootmanager.cpp
The Qt debug runtime prints a bogus warning on the console if you
haven't called makeCurrent since the last time you called swapBuffers.
This presumably means something if you're using QGLWidget the "regular"
way, but in our multi-threaded use case is harmless since we never call
doneCurrent in the rendering thread.
> Qt: Silence a bogus warning printed when using the debug runtime

- src/core/hle/svc.cpp
This SharedMemory can be passed to service functions (Which should map the memory into their own address space).
Since our services all share the same address space as the running application, all we need to do is assign the base_address of the SharedMemory.
> Core/SVC: Map the shared memory created in CreateMemoryBlock to the specified address

- src/core/hle/service/gsp_gpu.cpp
Used by applications when preparing to launch an applet, leaving this unimplemented would lead to the application reading garbage from the buffers
> Service/GSP: Implemented ImportDisplayCaptureInfo.

- src/core/CMakeLists.txt
- src/core/hle/kernel/vm_manager.cpp
- src/core/hle/kernel/vm_manager.h
- src/core/mem_map.cpp
- src/core/mem_map.h
- src/core/memory.cpp
- src/core/memory_setup.h
This enables more dynamic management of the process address space,
compared to just directly configuring the page table for major areas.
This will serve as the foundation upon which the rest of the Kernel
memory management functions will be built.
> Kernel: Add VMManager to manage process address spaces

- src/citra_qt/main.ui
Fixes #815.
Without any extra widgets, it looks like this:
And with extra widgets, there is still visible space between different widgets because of the empty space that's part of them:
> QT: Remove border around widgets

- src/video_core/command_processor.cpp
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shaders.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/pica_to_gl.h
- src/video_core/vertex_shader.cpp
This is a combination of several Pica emulation improvements. All changes have been implemented for both the SW rasterizer and OpenGL rasterizer. I recommend reviewing each commit separately, as they are well separated. This PR implements:
* Pica command buffer execution registers
* Vertex shader MIN, SLT, and SLTI instructions
* Color "logic operation" (same as `glLogicOp`)
* ~~RG8 texture format~~
* AddSigned combiner function for the alpha channel
Here are some results of these features (although I'm sure there are many more, testing welcome!):
> Pica improvements

- src/citra/config.cpp
- src/citra_qt/config.cpp
- src/core/hw/gpu.cpp
- src/core/settings.h
Changing it makes emulation inherently inaccurate. It also had a wrong
default value (30, whereas the real system has a refresh rate of 60 Hz)
which, even if changed, would continue to be used unless people manually
removed it from their config files.
> Remove gpu_refresh_rate configuration option

- src/core/arm/dyncom/arm_dyncom_thumb.cpp
The pretty cool thing about these not being implemented is that you'd get junk loads and stores whenever they were used in thumb mode :^)
> arm_dyncom_thumb: Implement missing instructions.

- src/core/file_sys/archive_extsavedata.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
Organize the ExtSaveData folders as they are stored in the console.
> ExtSavedata: Save the icon passed to CreateExtSaveData.

- src/common/math_util.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
A batch of smaller fixes to the hardware renderer.
Addresses issue #814 and some bugs in issue #829
* blargSnes rom rendering fixed
* glColorMask implemented
* Fewer black screens
* Depth format handling fixes
* Textures unbound after done using them
* Render-to-texture flush
* Interval intersection math fix
> HW Renderer Screen Fixes

- src/core/arm/skyeye_common/vfp/vfp.h
- src/core/arm/skyeye_common/vfp/vfpinstr.cpp
VFPv2 contains the 32-bit version of the scalar transfer instructions.
> vfp: Implement VMOVBCR/VMOVBRC

- src/video_core/pica.h
Trivial change and fixes several warnings in the clang build.
> video_core: add extra braces around initializer

- appveyor.yml
This will help people who don’t have much bandwidth to download only what they want, and not the Qt dll again and again.
It is put in an hidden directory by default, in order to not confuse normal users who do need the Qt dll.
> Create a second Windows archive with only the binaries

- src/video_core/renderer_opengl/renderer_opengl.cpp
This helps differentiate the various Mesa drivers, especially hardware and software ones, or in multi-GPU setups.
> Log the GL driver’s vendor and renderer

- src/core/hle/function_wrappers.h
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
This changes how we emulate svcWaitSynch to ensure that wait objects are always acquired by the right thread. My solution with this PR is to always call the SVC when a thread is awoken until conditions are satisfied for it to continue. A side-effect of this is that threads will often be scheduled that are not actually able to run, resulting in unnecessary context switches (this could result in a hopefully minor performance hit). This is because when a wait_object becomes available, all waiting threads will be awoken, so whichever don't acquire the resource will still be scheduled then rescheduled. However, this actually makes our code much simpler/cleaner, as we can get rid of all the state management cruft trying to "predict" the next best thread to run. This fixes #432. I suspect it …
> Fix svcWaitSynch to correctly acquire wait objects

- .gitconfig
- CMakeLists.txt
- hooks/pre-commit
Enforce the "no tab, use spaces" policy with a pre-commit hook.
This hook is installed through cmake if the user didn't set up any pre-commit hook before (so that we don't override it).
This will also check for trailing spaces
> Enforce the "no tab, use spaces" policy with a pre-commit hook.

- src/core/hle/kernel/session.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/y2r_u.cpp
This should hopefully encourage people to add these (without using magic numbers) to service returns in the future.
> Add helpers to create IPC command buffer headers and descriptors

- appveyor.yml
The default os has Qt now, so there's no need for the unstable os.
> AppVeyor: Remove os: unstable

- src/video_core/clipper.cpp
"warning C4305: 'argument' : truncation from 'double' to 'float'"
First commit here and I figured I would start on something simple like Warning Silencing
> VideoCore: Fix Floating Point Warning

- src/core/arm/skyeye_common/arm_regformat.h
- src/core/arm/skyeye_common/vfp/vfp.cpp
- src/core/arm/skyeye_common/vfp/vfp.h
- src/core/arm/skyeye_common/vfp/vfpinstr.cpp
Also has a side-benefit of correcting access to the FPEXC register. Only privileged mode stuff. No userland changes.
> vfp: Handle accesses to FPINST/FPINST2 system registers.

- src/core/arm/skyeye_common/vfp/vfp.cpp
- src/core/arm/skyeye_common/vfp/vfp.h
This is technically cruft from armemu code, where it took specific function pointer types (where an init routine with a return code was one of them).
> vfp: Change return type of VFPInit from unsigned int to void.

- src/core/hw/gpu.cpp
And a bit of cleanup before that.
I only tested it on the according test in hwtests, which is now passing: https://github.com/citra-emu/hwtests/blob/master/source/tests/gpu/displaytransfer.cpp#L497
> Implement blended downscaling for display transfers

- appveyor.yml
This avoid intermittent build failures due to a commit not being
reachable using a fixed depth, at the expense of longer checkout times.
> AppVeyor: Remove submodule checkout depth

- src/core/loader/ncch.cpp
Another possibility that keeps uppercase hex:
"0x%" PRIXPTR, (uintptr_t) exheader_header.arm11_system_local_caps.resource_limit_descriptor
but it requires a cast and importing inttypes.h
> Loader: Fix format specifier warning

- CMakeLists.txt
Debug was missing compiler flags, causing MSVC to default it to building
with optimizations enabled (making for a not very useful binary for
actual debugging...). Additionally, the variables were re-organized to
remove some redundancy, the old Release build type was removed, and
RelWithDebInfo was renamed to take its place instead.
> CMake: Fix Debug build configuration in MSVC

- src/citra/CMakeLists.txt
- src/citra_qt/CMakeLists.txt
This will help packaging tremendously, as a `make DESTDIR=… install` will now put every file at their place.
Ideally we should do that on other systems as well, but I don’t know them enough to enable this command there.
> Tell cmake to install the compiled binaries on Linux

- src/core/file_sys/archive_savedata.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/event.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/process.h
- src/core/hle/kernel/vm_manager.cpp
- src/core/hle/kernel/vm_manager.h
- src/core/loader/3dsx.cpp
- src/core/loader/elf.cpp
- src/core/loader/ncch.cpp
- src/core/mem_map.cpp
- src/core/mem_map.h
- src/core/memory.cpp
The code now properly configures the process image to match the loaded
binary segments (code, rodata, data) instead of just blindly allocating
a large chunk of dummy memory.
> Core: Properly configure address space during binary loading

- src/core/hle/applets/applet.cpp
- src/core/hle/applets/applet.h
- src/core/hle/applets/swkbd.cpp
- src/core/hle/applets/swkbd.h
- src/core/hle/kernel/process.h
- src/core/hle/kernel/shared_memory.h
- src/core/hle/service/apt/apt.h
`std::shared_ptr` wasn’t included from `<memory>` as it should have.
I also fixed the other includes related to the applet.
> Fix applet includes using iwyu

- src/common/common_funcs.h
this prepares citra to be build with Visual Studio 2015.
There is still [a linker error](https://gist.githubusercontent.com/Apology11/c99fe8a3f51cbf587503/raw/76d66f8befa1ec24a48a69cf92bdb0ddd620d2bb/gistfile1.txt), but as far as I´ve read this is a problem [tracked by microsoft](http://stackoverflow.com/questions/30765256/linker-error-using-vs-2015-rc-cant-find-symbol-related-to-stdcodecvt).
> build with visual studio 2015

- src/citra_qt/CMakeLists.txt
- src/citra_qt/debugger/graphics_breakpoint_observer.h
- src/citra_qt/debugger/graphics_tracing.cpp
- src/citra_qt/debugger/graphics_tracing.h
- src/citra_qt/main.cpp
- src/common/file_util.h
- src/core/CMakeLists.txt
- src/core/hle/service/gsp_gpu.cpp
- src/core/hw/gpu.cpp
- src/core/hw/hw.cpp
- src/core/hw/lcd.cpp
- src/core/tracer/citrace.h
- src/core/tracer/recorder.cpp
- src/core/tracer/recorder.h
- src/core/tracer/tracer.h
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
Adds support for recording CiTraces within Citra (tl;dr: record all GPU commands sent to a game, so that https://github.com/citra/citrace-player can replay them arbitrarily often). The functionality is exposed in a new debugging widget called "CiTrace Recorder".
NOTE: CiTracing needs to be started and halted at GPU breakpoints. The GUI mostly takes care of not allowing the user to start/stop at any other time anyway, but there are still some rough edges.
> Add CiTrace recording support

- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/citra_qt/debugger/graphics_framebuffer.h
- src/common/color.h
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
Implements basic stencil testing functionality. Also adds two new framebuffer viewing formats: D24X8 and X24S8, each of which spans 32 bits per pixel but only shows the depth and/or stencil values.
The code in this PR was tested against portal3DS, which uses stencil testing to implement "looking through portals". Here's a screenshot showing it in action, as well as the X24S8 framebuffer viewing format (showing that the area covered by a portal is setting a mask for rendering anything beyond the portal).
Revision history:
* ~~fa770594a29d123ca5612c91603aaf1e13f932be~~
* 5e79706db23a956ea0d6f3e5cc5a57b3a5d86b5e
> Implement stencil testing

- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
Should Fix #923.
Not sure if I need to lock on ```running_mutex``` and even why this lock is needed in first place.
> Qt: Fix disassembly widget stepping

- src/core/hw/y2r.cpp
Fix initializer-list narrowing warning (u32 -> u8)
> Y2R: Fix narrowing warning

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
Implemented missing DOT3_RGB texture combiner. However it is not 100% accurate.
The hardware tests are  available at https://github.com/Lectem/3DS_gpu_tests/tree/DOT3_RGB
Sources : 
https://github.com/smealum/ctrulib/blob/2fed2f42411e0cf69e7c61bcae657139ca5cf1b8/libctru/include/3ds/gpu/gpu.h#L193
http://chimera.labs.oreilly.com/books/1234000001814/ch08.html#TextureCombiners
> DOT3_RGB combiner

- src/video_core/clipper.cpp
Output the actual number of triangles, and start counting triangles at 1 when printing logs.
> Pica/Clipper: Output proper number of triangles in debugging logs.

- src/core/file_sys/archive_romfs.cpp
- src/core/file_sys/archive_romfs.h
- src/core/file_sys/archive_savedatacheck.cpp
- src/core/file_sys/disk_archive.cpp
- src/core/file_sys/disk_archive.h
- src/core/file_sys/file_backend.h
- src/core/file_sys/ivfc_archive.cpp
- src/core/file_sys/ivfc_archive.h
- src/core/hle/service/fs/archive.cpp
- src/core/loader/3dsx.cpp
- src/core/loader/3dsx.h
- src/core/loader/elf.cpp
- src/core/loader/elf.h
- src/core/loader/loader.cpp
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
This is a rebase of #911.
I also added an unrelated extra cleanup to related parts of the code.
> Do not load entire RomFS to memory, read from the file as needed instead (rebased)

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Also a side-benefit of not having implementation-defined behavior.
> arm_dyncom_interpreter: Simplify assignment in SMLAW

- .travis-deps.sh
Also removes the `brew tap` command, which is irrelevant now that Travis taps `homebrew/versions` by default.
> Update homebrew before building, which no longer uses SourceForge

- src/core/hle/kernel/thread.cpp
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/hle/service/dsp_dsp.h
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/gsp_gpu.h
- src/core/hle/service/nwm_uds.cpp
- src/core/hle/service/nwm_uds.h
- src/core/hle/service/srv.cpp
- src/core/hle/service/srv.h
- src/core/hle/service/y2r_u.cpp
- src/core/hle/service/y2r_u.h
This commit fixes several kernel object leaks. The most severe of them
was threads not being removed from the private handle table used for
CoreTiming events. This resulted in Threads never being released, which
in turn held references to Process, causing CodeSets to never be freed
when loading other applications.
> Ensure all kernel objects are released during shutdown

- src/common/file_util.h
> Remove the unused and commented GetThemeDir prototype from FileUtil

- src/core/arm/dyncom/arm_dyncom_thumb.cpp
cc @lioncash 
Ref. ARM sections A6.2.3 and A8.8.103.
The change to the `Rs` variable is cosmetic. Both versions of the code are equivalent.
> Dyncom: Support for a new ARMv6 Thumb MOV encoding

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/video_core/pica.h
Also added its name to the texture viewer widget.
Fixes some artifacts in games that use this format, like Crashmo
> Rasterizer/Textures: Fixed a bug where the I4 format would get twice the real stride

- src/core/hle/service/service.cpp
Changes the log to use hex in the parameter list instead of decimal.
> Change trace/unimplemented service call logs to use hex

- src/video_core/vertex_shader.cpp
This fixes the OoT NaN/white/black triangle glitch.
> Pica: Fix DP3 instruction, which wasn't assigning to the w component

- src/video_core/pica.h
This was found and hwtested by Lectem in https://github.com/Lectem/3DS_gpu_tests/tree/wrap_modes
> Pica: Correct switched S/T texture wrapping registers

- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
It tells the GPU to not swizzle/de-swizzle the input during the transfer.
Verified with https://github.com/citra-emu/hwtests/pull/36
Closes #853
> GPU/DisplayTransfer: Implemented bit 5 in the transfer flags.

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/citra_qt/debugger/graphics_cmdlists.h
Title says it all. This is useful for analyzing command lists more efficiently, e.g. by searching for specific commands.
> citra-qt: Add support for copying the command list contents to clipboard.

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/hle/svc.cpp
- src/core/hle/svc.h
Previously it would just re-read the already decoded instruction and extract the immediate value.
> dyncom: Pass SVC immediates directly.

- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/command_processor.cpp
- src/video_core/pica.h
- src/video_core/primitive_assembly.cpp
- src/video_core/vertex_shader.cpp
- src/video_core/vertex_shader.h
Just register definitions, nothing else.
VS and GS registers share the same layout, so this is mostly restructuring and renaming. Furthermore, VertexShader interfaces were changed to make less assumptions about the shader pipeline configuration (i.e. VS<->GS).
If you agree that GitHub is doing a terrible job at diffing this, try `git diff --word-diff=color --ignore-all-space` instead.
> Pica/Shader: Add geometry shader definitions.

- src/core/hle/kernel/thread.cpp
They'll be reset if needed during the next svcWaitSynchronization call (if there's any pending)
> Kernel/Scheduling: Clean up a thread's wait_objects when its scheduled.

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/am_app.cpp
Named the service functions in am:app as per 3dbrew.
This fixes an illegal read loop in Steel Diver
Related to #961
Pic for reference
> Services/AM: Stubbed am:app::GetNumContentInfos to return 0 results.

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/pica_to_gl.h
I only implemented them in the hw renderer, but I left a comment in the sw renderer.
Closes #898
3dscraft pics for reference
> GPU: Added registers for min and mag texture filters

- src/video_core/renderer_opengl/gl_state.cpp
In OpenGL 3, texturing is always enabled, and this call is invalid.
While it produced no effect in the rest of the execution, it wouldn't
have the intended effect of disabling texturing for that unit. Instead
bind a null texture to the unit.
> GL Renderer: Remove erroneous glEnable(GL_TEXTURE_2D) calls

- src/citra_qt/debugger/graphics_breakpoints.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hw/gpu.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.h
* IncomingDisplayTransfer: Triggered just before a display transfer is performed.
* GSPCommandProcessed: Triggered right after a GSP command is processed.
* BufferSwap: Triggered when the buffers flip
As a side note, I suggest dropping the Pica naming from these classes and having them be used for general GPU breakpoints, and then get rid of the GraphicsDebugger class.
> Qt/GPU Breakpoints: Added three more breakpoint types

- src/core/hle/service/gsp_gpu.cpp
Verified to be what GSP does via REing. Fixes invalid virt->phys
translation error spam in some games.
> GSP: Don't try to write memory fill registers if start address is 0

- src/citra_qt/debugger/graphics_breakpoints.cpp
- src/citra_qt/debugger/graphics_breakpoints.h
- src/citra_qt/debugger/graphics_breakpoints_p.h
Changed it so that we don't have to select and click the Enable button when enabling/disabling a breakpoint, now it is done via a checkbox next to the breakpoint's name.
Removed the now redundant Enable button and second column of the list.
The QTreeView's headers are now hidden, seeing how we don't need them anymore.
Pic
> Qt/GPU Breakpoints: Changed the widget to have a checkbox next to each bp type

- src/core/hle/function_wrappers.h
- src/core/hle/svc.cpp
"signed/unsigned mismatch"
I am unsure of exactly the best way to deal with this but to me it seemed ideal to make the comparison with two variables of the same type.
Of course this does present the unlikely scenario that the variable 'i' could be negative because its no longer unsigned.
Whats the ideal or recommended way to fix this?
> Core\HLE : Fix Warning

- src/core/arm/skyeye_common/armdefs.h
> armdefs: Remove unnecessary extern keywords

- src/video_core/vertex_shader.cpp
- Replaces `std::stack` with `boost::static_vector` (much faster)
- Replaces two references to u32 types with values (simpler, faster)
- Makes program counter an index instead of a pointer (simpler, faster)
> Optimisations and cleanups in the shader interpreter

- src/citra_qt/debugger/graphics_cmdlists.cpp
I seperated the data column into "Register" and "New Value" for the sake of clarity.
I also switched to using a QTableView because it is godamn faster, scrolling with a QTreeView with a lot of elements is extremely slow.
> citra-qt: Improve pica command list widget

- src/citra/default_ini.h
It got forgotten in d65b42a69abbde2130c77917e7db5722799a6896.
> Remove dead gpu_refresh_rate option from the default ini file

- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/rasterizer.cpp
- src/video_core/vertex_shader.cpp
Some disabled debugging functionality was being called from rendering
routines in VideoCore. Although disabled, many of them still allocated
memory or did some extra work that was enough to show up in a profiler.
Gives a slight (~2ms) speedup.
> VideoCore: #ifdef out some debugging routines

- src/citra_qt/config.cpp
There was a mistake in #873 where the values that get saved are just the index of the buttons, not the key mapped to the buttons.
> Settings: Fix saving wrong values for input configuration

- src/citra_qt/main.cpp
Small change to update the start menu. With this commit, the start menu is renamed to "Continue" while the emulator is running. In stop function, the start menu text is set back to "Start".
> Update Start menu text to match with the real state of the emulator.

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
This is considered deprecated in the ARM manual (using PC as an operand), however, this is still able to be executed on the MPCore (which I'm quite sure would be rare to begin with).
> dyncom: Handle left-operand PC correctly for data-processing ops

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
This was used prior to InterpreterTranslate existing.
> dyncom: Remove an unused variable

- src/video_core/command_processor.cpp
- src/video_core/vertex_shader.cpp
Two small GPU fixes. See individual commit messages for more info.
Notably, one of them fixes the UI in Fire Emblem, which is now playable:
Test homebrew at:
- https://github.com/yuriks/3DS_gpu_tests/tree/color-clamping
- https://github.com/yuriks/3DS_gpu_tests/tree/vertex-loading
> Misc. GPU vertex loading fixes

- src/citra_qt/bootmanager.cpp
- src/citra_qt/debugger/disassembler.cpp
> citra-qt: Adjust initializer list order

- src/core/hle/service/am/am.cpp
- src/core/hle/service/ldr_ro.cpp
> core: Eliminate some unused variable warnings

- src/common/string_util.cpp
The char16_t/char32_t implementations aren't present in the library and
cause linker errors. This is a known issue that wasn't fixed in VS2015
RTM.
> Common: Work around bug in MSVC2015 standard library

- src/video_core/command_processor.cpp
This gives a ~2/3 reduction in the amount of vertices that need to be
processed through the vertex loaders and the vertex shader, yielding a
good speedup.
> Videocore: Implement simple vertex caching

- src/common/logging/backend.cpp
- src/common/logging/text_formatter.cpp
Add a case of `Log::Level::Count` to all switch statements that dispatch on `Log::Level`.  The case simply asserts `false` and notes the invalid log level.
This removes a couple warnings under Clang.
> Handle invalid `Log::Level::Count`

- src/core/arm/disassembler/arm_disasm.cpp
- src/core/arm/disassembler/arm_disasm.h
Disassemble the following 32-bit ARMv6K hint instructions:
NOP, SEV, WFI, WFE, YIELD
and the REX instructions:
LDREX, LDREXB, LDREXD, LDREXH, STREX, STREXB, STREXD, STREXD
None of these instructions have Thumb encodings in the ARMv6K instruction set.
> Disassembler: ARMv6K instructions

- src/core/arm/disassembler/arm_disasm.cpp
This part of disassembly only determines the opcode, there's no need for offset calculation here.
Also gets rid of higher level compiler warnings on OSX.
> arm_disasm: Remove unnecessary code

- src/core/arm/disassembler/arm_disasm.cpp
- src/core/arm/disassembler/arm_disasm.h
Disassemble all the ARMv6 media instructions.
Packing:
PKH, SEL
Sign-extension and zero-extension:
{SX, UX}{TAB, TAB16, TB, TB16, TAH, TH}
Saturation:
{S, U}{SAT, SAT16}
Reversal*:
REV, REV16, REVSH
Parallel addition and subtraction:
{S, U, Q, UQ, SH, UH}{ADD16, ASX, SAX, SUB16, ADD8, SUB8}
Signed multiply and divide
SMLAD, SMUAD, SMLSD, SMUSD, SMLALD, SMLSLD,
SMMLA, SMMUL, SMMLS
Sum of absolute values
USAD8, USADA8
\* These instructions also have Thumb encodings in ARMv6 which are not implemented in this pull request.
> arm_disasm: ARMv6 media instructions

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_resource_manager.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
If an OpenGL object is created, bound to a binding using the state
tracker, and then destroyed, a newly created object can be assigned the
same numeric handle by OpenGL. However, even though it is a new object,
and thus needs to be bound to the binding again, the state tracker
compared the current and previous handles and concluded that no change
needed to be made, leading to failure to bind objects in certain cases.
This manifested as broken text in VVVVVV, which this commit fixes along
with similar texturing problems in other games.
> OpenGL: Fix state tracking in situations with reused object handles

- src/citra_qt/debugger/callstack.cpp
- src/citra_qt/debugger/graphics_tracing.cpp
- src/core/arm/disassembler/arm_disasm.cpp
- src/core/arm/disassembler/arm_disasm.h
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/skyeye_common/vfp/vfp.cpp
- src/core/tracer/citrace.h
- src/video_core/debug_utils/debug_utils.cpp
The ARM core was ridden with those, but there was also an occurence in the CitraQt debugger.
This commit is purely stylistic, there is no change in behaviour.
> Replace standard uint*_t and int*_t with CommonTypes’ u* and s* types

- src/common/bit_field.h
- src/common/common_funcs.h
`__forceinline` is a MSVC extension, which may confuse some people working on the codebase.
Furthermore, the C++ standard dictates that all names which contain adjacent underscores are reserved.
> Stop defining GCC always_inline attributes as __forceinline

- src/common/logging/backend.cpp
Add a case of `Log::Class::Count` to the switch statement that dispatches on `Log::Class`.  The case simply calls the `UNREACHABLE` macro.
Like PR #1018, this removes a warning under Clang.
> Handle invalid `Log::Class`

- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
I propose to save the path to files recently loaded (symbols and roms).
I am not sure how to avoid the new variables in the class. I think, I am forced to add the QSignalMapper. About the list of paths, I could avoid it, using QSettings, but it would make the code more complicated.
> citra-qt: save path for recent files loaded

- src/core/loader/loader.cpp
Give `FileType::CIA` a string representation and indicate that CIA loading support is unimplemented.
This removes a few warnings under Clang.
> Handle `FileType::CIA` in `switch` statements

- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/citra_qt/debugger/graphics_vertex_shader.h
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/pica.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_interpreter.h
- src/video_core/shader/shader_jit_x64.cpp
A number of functional improvements to the shader disassembler (which is now an actual debugger):
* When the emulator halts at a VertexLoaded breakpoint, the vertex attributes are shown in the shader debugger
* Unreached instructions are colored yellow in the shader disassembly
* Shaders can be dumped from the GUI
* More output semantics than before are recognized when dumping shaders
* Each shader interpreter cycle records its inputs and outputs now, so that they can be inspected in the GUI (think of this as stepping through the shader and inspecting data, just that it's all done automatically and you just select a particular "iteration" to analyze in the GUI)
Obligatory screenshot:
This PR pends on #929 .
> Shader debugger improvements

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
The monospace font was not being used on Windows, this has been fixed.
I added the mask and moved its expansion into WritePicaReg.
A widget was created to replace the previous one every single time a row was selected, which caused some slowdowns. No widget is now created if not needed.
> citra-qt: Improve pica command list widget (add mask, fix some issues)

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/common/color.h
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.h
Manual address and rebase of #985.
Verified correct against hardware via hwtest: https://github.com/yuriks/3DS_gpu_tests/tree/hilo8-test
> videocore: Added RG8 texture support

- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Implements the missing EX2 (exponential base 2) and LG2 (logarithm base 2) shader instructions both in the interpreter and in the JIT.
Using std::exp2 and std::log2 is probably imprecise w.r.t. the hardware. It depends on how the GPU computes floating-points operations internally and if it is still IEEE-754 compliant (despite using very likely 24-bit floating-points internally).
Note that these instructions seem to perform the operation only on the first component and assign the result to all enabled destination's components. Very simple hardware tests to verify this behavior are available here: https://github.com/aroulin/3ds-gpu-tests.
Fixes #1021
> Shader: Implement EX2 and LG2 in interpreter/JIT

- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Caller-saved registers were not saved when calling functions from the shader JIT. We must also save some XMM registers depending on their uses in the JIT and the ABI.
> Shader: Save caller-saved registers in JIT before a CALL

- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/gsp_gpu.h
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
Fixes glitchy garbage in Fire Emblem 3D scenes.
> GPU: Implement TextureCopy-mode display transfers

- src/citra_qt/main.cpp
- src/citra_qt/main.h
* avoid duplicates
* always put the last file loaded to top of the list
I tried to add tooltips in order to show the fullpath when the mouse is hovering the item, but in fact, tooltips for QAction in QMenu are not shown at all.
> Improvements for MRU

- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Implements SGE, SGEI and SLT shader instructions in the interpreter and the JIT.
Simple hardware tests are available here: https://github.com/aroulin/3ds-gpu-tests.
> Shader: Implement SGE, SGEI and SLT in interpreter/JIT

- src/common/x64/emitter.cpp
- src/common/x64/emitter.h
This should also technically silence a few ubsan warnings if used when the shader JIT is running.
> emitter: Remove pointer casts

- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Implements DPH and DPHI in the interpreter and in the JIT.
-  The JIT implementation could be merged with the DP4 implementation using a few if's statements.
- Tests revealed that the component with w=1 is SRC1 and not SRC2, it is now fixed on 3dbrew.
- Tests are for now available here:
- DPH: https://github.com/aroulin/3ds-gpu-tests/blob/master/dph-tests/source/main.c
- DPHI: https://github.com/aroulin/3ds-gpu-tests/blob/master/dphi-tests/source/main.c
I'll work on integrating the tests to https://github.com/citra-emu/hwtests. ~~It might take me a few days to clean/adapt the automated test suite, especially to handle the different shaders compilations and make the test suite generic for different shader instructions.~~
@neobrain is working on a shader test framework so maybe I should …
> Shader: Implement DPH and DPHI in interpreter/JIT

- src/common/x64/emitter.cpp
- src/common/x64/emitter.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
RCP (RSQ) computes only the source vector's first component reciprocal (reciprocal of square root). It is not surprising as these are transcendental functions typically executed on SFUs.
Confirmed by tests available here:
- https://github.com/aroulin/3ds-gpu-tests/blob/master/rcp-tests/source/main.c
- https://github.com/aroulin/3ds-gpu-tests/blob/master/rsq-tests/source/main.c
> Shader: RCP and RSQ computes only the 1st component

- src/video_core/debug_utils/debug_utils.cpp
This should prevent some weird behaviors when the sw renderer is being used during a breakpoint
> HWRenderer: Only reload the framebuffer from gpu memory if the hw renderer is in use during a breakpoint

- src/video_core/shader/shader.cpp
`shader_map` was only defined on x86 architectures, but was cleared on shutdown
with no `#ifdef` protection. `#ifdef` this out so non-x86_64 architectures can be built.
> Shader JIT: ifdef out reference to ifdef'd out shader_map

- src/video_core/shader/shader_jit_x64.cpp
MOVA converts new address register values from floats to integers **using truncation**.
- specified here http://3dbrew.org/wiki/Shader_Instruction_Set#Instructions
- I validated this behavior on hardware: https://github.com/aroulin/3ds-gpu-tests/blob/master/mova-tests/source/main.c
This fixes an issue in The Legend of Zelda: A Link Between Worlds where the UI boxes were not drawn
in the main menu screen.
Before (with the shader JIT): 
After (with the shader JIT and the shader interpreter):
> Shader JIT: Fix float to integer rounding in MOVA

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
This hugely reduces the number of texture uploads in some games (e.g. ZMM, where it results in a pretty significant overall performance boost).
Before:
After:
> gl_rasterizer_cache: Cache textures based on hash in addition to address.

- src/video_core/pica.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Fixes or verifies some floating-point edges cases in the shader interpreter and JIT. The most visible effect of this PR is that OoT doesn't have missing interface elements anymore.
- Automated test suite at aroulin/3ds-gpu-tests#1
- Some info gathered during the making of this PR can be found in 3DBrew: [Shader_Instruction_Set#Floating-Point_Behavior](http://www.3dbrew.org/wiki/Shader_Instruction_Set#Floating-Point_Behavior)
- This has a modest perf impact in the JIT: 2.21ms -> 2.62ms (+18%) in the OoT inventory screen.
Thanks @FioraAeterna for help and ideas when doing hwtests and implementing this in the JIT.
> Shader FP compliance fixes

- src/core/hle/kernel/process.cpp
Dumb typo which sneaked in through review on #1025.
Allows the Smash demo to boot.
> Kernel: Fix wrong linear heap base on titles using newer kernels

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/pica_to_gl.h
And implemented stencil in the hw renderer.
Implemented more stencil functions.
This was verified using hw tests, some of which can be found [here](https://gist.github.com/Subv/692aaf09d4593018bbcc).
I'll update the information on 3dbrew later.
Fixes #1039 and _maybe_ some of the problems with #1041
hwtests: https://github.com/Subv/3ds-homebrew/tree/master/gpu_stencil_tests
There's currently a bug related to changing the stencil buffer with the OpenGL renderer, it seems to only happen on Intel and is apparently a driver bug, a report has been filed [here](https://communities.intel.com/message/324464)
> Rasterizer: Corrected the stencil implementation.

- src/core/file_sys/disk_archive.cpp
> Services/FS: Correctly tell the guest app whether a file was correctly opened or not

- src/video_core/command_processor.cpp
- src/video_core/pica.h
This is the equivalent of the "first" parameter in glDrawArrays, it tells the GPU the vertex index at which to start rendering.
Tested with https://github.com/Subv/3ds-homebrew/tree/master/gpu_draw_arrays_offset
> GPU: Implemented register 0x22A PICA_REG_DRAW_VERTEX_OFFSET

- src/video_core/shader/shader_jit_x64.cpp
SGE is incorrectly emulated w.r.t. NaN behavior as the CMPSS SSE instruction is using NLT.
`a >= b` is not equivalent to `!(a < b)` because of NaN.
Behavior checked on hardware: 
https://github.com/aroulin/3ds-gpu-tests/tree/master/fp-tests
> Shader JIT: Fix SGE/SGEI NaN behavior

- hooks/pre-commit
This allows importing of external libraries into externals/ without
having to reformat them. Unfortunately it also allows whitespace to be
introduced in files like the root CMakeLists.txt, but that is a small
downside compared to the tradeoff.
> Only check src/ directory for whitespace errors in the pre-commit hook

- src/common/microprofile.h
This typedef happened to be defined through a include path in the standard libraries in 2013, but isn't anymore in 2015. Ideally I'll upstream the fix, but this will do until then.
> Common: Fix MicroProfile compilation in MSVC2015

- src/core/hle/svc.cpp
Cubic Ninja waited for the frame to end by spinning on a loop calling
GetSystemTick while doing nothing else. Since GetSystemTick doesn't
cause a reschedule (which advances time), this meant that very little
emulated time would pass inside that loop, causing the game to spend
most of the frame burning away CPU.
> SVC: Advance time when calling GetSystemTick to escape busy-wait loops

- src/common/CMakeLists.txt
- src/common/bit_set.h
- src/common/x64/abi.cpp
- src/common/x64/abi.h
- src/common/x64/emitter.h
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Fixes misaligned stack when calling external functions from the shader JIT. Both the Win64 and the System V ABIs require a 16-byte aligned stack when calling a function.
[Agner's Calling Conventions 5. Stack Alignment](http://www.agner.org/optimize/calling_conventions.pdf)
The 64 bit systems keep the stack aligned by 16. The stack word size
is 8 bytes, but the stack must be aligned by 16 before any call instruction.
Consequently, the value of the stack pointer is always 8 modulo 16 at
the entry of a procedure.
[System V ABI 3.2.2 The Stack Frame](http://www.x86-64.org/documentation/abi.pdf):
[…], the value (%rsp + 8) is always a multiple of 16 when control 
is transferred to the function entry point.
[Win64 Software Conventions](https://msdn.microsoft.com/en-us/library/ew5tede7.aspx):
The …
> x64: Proper stack alignment in shader JIT function calls

- src/citra_qt/bootmanager.cpp
- src/citra_qt/main.cpp
- src/video_core/pica.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/renderer_opengl/gl_resource_manager.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/pica_to_gl.h
plus two small fixes/cleanups
Fixes #978
> OpenGL: Use Sampler Objects to decouple sampler config from textures

- externals/glad/CMakeLists.txt
> CMake: Add missing library required by Linux for compiling glad

- src/video_core/shader/shader.h
- src/video_core/shader/shader_jit_x64.cpp
- Change return type of register offsets functions from `int` to `size_t` to decouple them from the signed x64 displacement and adds checks to make sure any needed cast is well-defined.
- Use emitter's SCALE_1 constant.
I think it is clearer to do the distinction between an unsigned register offset a base register block and the x64 displacement which can be signed although this can be argued.
> Shader: Use constants and proper type casts

- src/citra_qt/debugger/disassembler.cpp
- src/citra_qt/debugger/registers.cpp
Picked up #156 if order to finish #67. If any other debugger tool should use it, just say it and I'll add it.
> citra-qt: Use monospace font on Disassembler and ARM Registers

- src/citra_qt/main.cpp
Even though they weren't visible in the UI, old entries would never be removed from the list and would be stored in the config file across sessions.
> citra-qt: Trim recently used files list to size when insterting new item

- src/citra_qt/main.cpp
> citra-qt: Separate UI layout state in a separate section of the config

- CMakeLists.txt
- appveyor.yml
- src/citra/CMakeLists.txt
This adds an option in CMake that'll download a binary package of Qt binaries. With this (and the #1019 workaround also included in this branch) it's possible to compile Citra with VS2015.
> CMake: Add option to download Qt binaries

- CMakeLists.txt
The `option` commands have been moved to the top of the file, so that
the relevant options are registered in the CMake cache even if one of
the required libraries is not found. This solves an ergonomic problem
when using bundled libraries where you have to first download GLFW
before being able to select the option to also download Qt.
> CMake: Make all cache options appear even in case of errors

- src/citra_qt/debugger/graphics.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/gsp_gpu.h
May fix additional texture caching issues. (Though mostly in homebrew, I haven't seen any commercial software use this to flush anything but command lists.)
> GSP: Implement command 0x05, used for flushing caches

- CMakeLists.txt
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/cfg/cfg.h
These blocks are required by various games to boot. (Including ALBW, Fire Emblem, and more.)
**NOTE:** You will have to delete your existing save at `user/nand/data/00000000000000000000000000000000/sysdata/00010017/00000000/config` in order for these changes to take effect.
> Service/CFG: Add additional blocks to default save data

- src/core/loader/3dsx.cpp
- src/core/loader/3dsx.h
- src/core/loader/loader.cpp
Addresses #1166 
@fincs I'm not sure if the size is right. I kinda just assumed that `filesize - offset = romfs_size`
So if the RomFS isn't appended like that, it needs to be changed.
That being said, I tested it with a few RomFS-enabled 3dsx files, and also a few 3dsx files that didn't use it. Works as expected, and gracefully fails to open RomFS when not there too.
> Implement 3dsx RomFS

- src/core/file_sys/ivfc_archive.cpp
Now that MSVC 2015 supports the %z family of specifiers, this can be used.
> ivfc_archive: Fix a printf specifier

- src/core/hle/service/cfg/cfg.h
This fixes a TODO left over from when we supported MSVC 2013.
> Use a constexpr function for country initialization in service/cfg

- src/citra_qt/CMakeLists.txt
- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
- src/citra_qt/game_list_p.h
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
- src/citra_qt/util/util.cpp
- src/citra_qt/util/util.h
- src/common/file_util.cpp
- src/common/file_util.h
- src/core/loader/loader.cpp
- src/core/loader/loader.h
To open a game, double click on a menu item. Uses the config keys `gameListRootDir` and `gameListDeepScan`. The former is, rather obviously, the root directory to scan for games in. The latter is whether you would like the game list to recurse through subdirectories to find games.
Looking for testers on different platforms!
- SMDH integration for game icons, proper game names and descriptions, etc.
- Search/filter bar, using regex
- Different game list layouts, e.g. grid-style layout.
- Pop up window while the game list is populating (a la Dolphin)
- Option for caching game list (no re-scanning on startup)
> Initial implementation of a game list

- src/citra_qt/CMakeLists.txt
- src/citra_qt/Info.plist
- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
This PR brings two things:
* **Fix the coordinates of mouse events in high-DPI modes (on all platforms).** Mouse events didn't account for the window DPI.
* **Enable high-DPI UI on OS X.** The OS will render the widgets using the system screen DPI (instead of being locked at @1x resolution).
For this we have to customize the app manifest file (named `Info.plist` on OS X) — instead of using the default cmake-generated one. This custom app manifest will also enable greater control of the app metadatas on OS X : I already have some code to fix the app icon and improve the app name displayed by the system.
Apart from the OS X app manifest, no changes are made to the existing high-DPI rendering code already present in Citra.
> citra-qt: high-DPI fixes and Retina on OS X

- src/citra_qt/main.cpp
Properly hides the game list upon toggling from external window mode to single window mode. Previously, both the game list and the render window would have been shown at the same time upon toggling.
Fixes #1188
> Game list: propely hide on toggling window mode

- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
I've implemented a simple encryption check which compares the program IDs in the NCCH header and the extended header to see if the ROM is encrypted. I changed all of the header values to be explicitly little-endian to prevent any surprises if Citra gets ported to a big-endian microwave oven. I also changed the program ID from a uint8 array to a u64_le.
Issue #708
> Loader: Implement NCCH encryption check

- src/citra_qt/main.cpp
Currently the "Use hardware renderer" or "Use Shader JIT" settings aren't persisted across launches when set from the Qt GUI. This PR makes those settings persistent.
> citra-qt: save hardware-rendering and shaders-jit settings

- src/citra_qt/game_list.cpp
- src/citra_qt/main.cpp
change file path encoding method to support non-Latin characters (issue #730)
#1192 rework
> citra-qt: Change file path encoding

- src/core/hle/service/csnd_snd.cpp
- src/core/hle/service/csnd_snd.h
The stub sets byte 0x4 of CSND command buffer to 1.
csndPlaySound of ctrulib waits until that byte becomes non-zero.
Therefore, homebrew playing sound by CSND does not freeze any more.
> Added CSND_ExecuteType0Commands stub.

- src/video_core/command_processor.cpp
Related to #1170 
None of my games do this but I figured it'd be a good thing to know if it does happen.
> GPU/Loaders: Log an error when a loader tries to load from a component beyond the available ones

- src/citra/citra.cpp
- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/skyeye_common/armstate.cpp
- src/core/arm/skyeye_common/armstate.h
- src/core/core.cpp
- src/core/gdbstub/gdbstub.cpp
- src/core/gdbstub/gdbstub.h
- src/core/settings.h
- src/core/system.cpp
I used Dolphin's gdbstub for this one. As per the guidelines, I changed the C-style casts to C++-style casts and put everything I planned to expose behind the Gdbstub namespace, among other things. In addition, I changed the way breakpoints are stored and accessed from using arrays to unordered_maps as per Subv's suggestion on IRC, which should open up the possibility for better access times and more than 10 breakpoints per type.
Features:
- Read, write, access (r/w), and execution breakpoints
- Read/modify registers
- Read/modify memory
- Stepping
- Suspending
Using IDA Pro to connect to the gdbstub also works well. Things like step over and set IP also work. 
The default port is 24689 which can be modified in the config ini files. Set the USE_GDBSTUB preprocessor flag in citra, …
> gdbstub implementation

- CMakeLists.txt
As per https://github.com/citra-emu/citra/issues/1054.
If I'm not mistaken, RTTI was only disabled on Windows. Please correct me if I missed a gcc/clang compiler switch which disables RTTI currently.
> Enable RTTI on Windows builds.

- src/common/vector_math.h
Also prevent using unary minus for unsigned Vec by mistake
> Common: silence Vec warnings on msvc

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
Uniform Buffer Objects allow us to upload all our uniforms in a single OpenGL call instead of multiple ones.
This increases performance a little bit.
> Shaders: Use UBOs instead of individual uniforms in the generated frag shaders

- src/core/hle/service/ssl_c.cpp
Added function names for Initialize and GenerateRandomData in ssl:C (names came from 3dsbrew). Found these functions while testing the game SPEC ~KAN~.
> Add Initialize and GenerateRandomData function names to ssl:C

- src/core/hle/service/ssl_c.cpp
After doing some more research and determining exactly what was causing SPEC ~KAN~ to freeze during save data initialization, The game calls GenerateRandomData three times while it's initializing the save data on the first run, and if the data returned on the third call is the same as the data returned on the first call are not different then it will continue looping until it gets something different. The game would assume that everything was initialized properly if you closed the game and ran it again. This fixes the issue of it looping on the first run of the game.
I thought it was logical that the RNG gets seeded when the SSL service is initialized, but if there's a better way to do this then I'd be up for changing it.
> Add stub functions for Initialize and GenerateRandomData in ssl:C

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
The support for GL_ARB_explicit_uniform_location is decent, but not that good (53% according to http://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_explicit_uniform_location).
Luckily, only a single place uses the explicit uniform location now: the textures uniform. So we can use regular location without much changes.
This fix the shader compilation on Intel HD 4000 (#1222 ; cc @bunnei).
_Disclaimer: I have no idea what I'm doing. But I'm eager for pointers and feedback :)_
> Use regular uniform location

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
I hastily merged #1253, which had several issues, including:
* Vertex shader still used fixed uniform positions
* Furthermore, the corresponding GL extension was not requested
* GL version requested during shader generation was wrong
* GL fragment shader uniforms were being uploaded without checking their validity
> renderer_opengl: Fix uniform issues with #1253

- src/citra_qt/game_list.cpp
- src/common/file_util.cpp
- src/common/file_util.h
ScanDirectoryTreeAndCallback, before this change, coupled error/return codes and actual return values (number of entries found). This caused confusion and difficulty interpreting the precise way the function worked.
Supersedes, and closes #1255.
> Refactor ScanDirectoryTreeAndCallback to separate errors and retvals

- src/core/arm/skyeye_common/armstate.h
std::array isn't always guaranteed to explicitly zero out it's contents without an initializer list.
> armstate: Zero out the registers on creation

- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
This was discovered and verified by @fincs. The tev combiner buffer
actually lags behind by one stage, meaning stage 1 reads the initial
color, stage 2 reads stage 0's output, and so on.
Fixes character portraits in Fire Emblem: Awakening and world textures
in Zelda: ALBW.
Fixes #1140
> PICA: Properly emulate 1-stage delay in the combiner buffer

- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/y2r_u.cpp
- src/core/hw/gpu.cpp
- src/video_core/CMakeLists.txt
- src/video_core/clipper.cpp
- src/video_core/clipper.h
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/hwrasterizer_base.h
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_base.cpp
- src/video_core/renderer_base.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/swrasterizer.cpp
- src/video_core/swrasterizer.h
This removes explicit checks sprinkled all over the codebase to instead just have the SW rasterizer expose an implementation with no-ops for most operations.
Also does a few other cleanups in that interface.
> VideoCore: Unify interface to OpenGL and SW rasterizers

- src/video_core/primitive_assembly.cpp
It was skipping the second vertex assignment and using uninitialized garbage when assembling the corresponding triangle.
Fixes the sf2dlib sample.
> GPU/PrimitiveAssembler: Fixed drawing triangle fans.

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
This simplifies the coordinate system used by the OpenGL renderer so that screen-based coords don't need to be flipped by taking into account the framebuffer size.
cc @Subv
> OpenGL: Flip framebuffers during transfer rather than when rendering

- src/core/hle/svc.cpp
another reason why conditional macros outside of determining system specifics is a bad thing.
> svc: Fix compilation with LOG_TRACE enabled

- src/video_core/renderer_base.cpp
This fixes various bugs that appear in the HW rasterizer after switching
between it and the SW one during emulation.
> VideoCore: Sync state after changing rasterizers

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
For example, you can nonsensically do:
```cpp
uint32_t thread_value = 0;
uint32_t cpsr_prev = 0;
uint32_t cpsr_after = 0;
asm volatile (
"MRS %[cpsr_prev], APSR\n"
"MRC p15, 0, %[thread_out], c13, c0, 3\n"
"MRC p15, 0, APSR_nzcv, c13, c0, 3\n"
"MRS %[cpsr_after], APSR\n"
: [thread_out]"=r"(thread_value), [cpsr_prev]"=r"(cpsr_prev), [cpsr_after]"=r"(cpsr_after)
);
printf("Thread URO: 0x%08X\n", thread_value);
printf("CPSR Prev : 0x%08X\n", cpsr_prev);
printf("CPSR After: 0x%08X\n", cpsr_after);
```
and have it work on the 3DS.
> dyncom: Handle modifying the APSR via an MRC instruction

- src/core/hle/kernel/timer.cpp
> HLE/Timers: Reset OneShot timers when they are acquired instead of when they're triggered

- externals/glad/include/glad/glad.h
- externals/glad/src/glad.c
- src/video_core/renderer_opengl/renderer_opengl.cpp
This extension allows the driver to communicate errors, warnings and improvement suggestions about our usage of the API, which we then log using our standard mechanism.
In the future we will also likely be using it to insert debug information in our GL stream, to help us understand better what is going on.
I’m not satisfied with the first commit, I regenerated our Glad files from http://glad.dav1d.de/ using the exact same options we were already using plus GL_KHR_debug, and it included a crapload of other imports at the same time…
I haven’t tested on a driver that doesn’t expose the extension, but the guard should be enough anyway.
> Add optional GL_KHR_debug support

- src/core/arm/disassembler/arm_disasm.cpp
Uhh, I'm like 80% sure that this change is correct? I'm just trying to get my foot in the door, I don't really know what I'm doing yet. Before this pull request, width was not being used at all, and since this function is used for different size opcodes, it wouldn't make sense to just always append h.
> DisassembleMemHalf: actually use width in determining opcode name

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
Uses offsets in the hardware renderer fragment shader to emulate depth near plane + polygon offsets. Should fix z-fighting as in #1150 including ALBW along with making the "inner" sub in the Sub Wars title screen consistent with the software renderer.
> hwrasterizer: Use depth offset

- src/core/file_sys/archive_backend.cpp
- src/core/file_sys/archive_backend.h
This doesn't return by reference so const isn't really necessary
> archive_backend: Remove unnecessary const from return types

- src/core/loader/elf.cpp
One of these was just moving a cast over to a C++ cast for consistency.
> elf: Don't cast away const

- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
If the bit 0 of the JMPU instruction is set, then the jump condition
will be inverted. That is, a jump will happen when the boolean is false
instead of when it is true.
Fixes normals in lots of stuff for #1264
> Shader: Implement "invert condition" feature of IFU instruction

- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
There was a mistake in the JMP code which meant that one instruction at
the destination would be skipped when the jump was taken. This commit
also changes the meaning of the culprit parameter to make it less
confusing and avoid similar mistakes in the future.
> Shader JIT: Fix off-by-one error when compiling JMPs

- src/core/CMakeLists.txt
- src/core/hle/kernel/vm_manager.cpp
- src/core/hle/kernel/vm_manager.h
- src/core/memory.cpp
- src/core/memory_setup.h
- src/core/mmio.h
Intention is for devices that require memory mapped I/O to implement the `MMIORegion` interface which would handle the reads/writes for that memory region.
Intention is for `MapMMIO` calls to go into `InitLegacyAddressSpace`.
Ping @yuriks as I seemed to be implementing something that was on his TODO list.
> Memory: Implemented MMIO

- src/video_core/renderer_opengl/renderer_opengl.cpp
The nVidia driver is *extremely* spammy on this category, sending a
message on every buffer or texture upload, slowing down the emulator and
making the log useless.
> OpenGL: Downgrade GL_DEBUG_SEVERITY_NOTIFICATION to Debug logging level

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
Fixes the framebuffer sync logic to use the memory region actually 'cached' by the OpenGL framebuffer texture, instead of the current framebuffer registers (which may have changed in the meantime without a framebuffer commit). Fixes #829.
> hwrasterizer: Use proper cached framebuffer addr/size

- src/common/bit_field.h
- src/common/emu_window.cpp
- src/core/hle/kernel/process.cpp
- src/core/hle/result.h
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ptm/ptm.cpp
- src/core/hle/service/soc_u.cpp
- src/core/hw/gpu.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
Making BitField trivially copyable for `memcpy` safety.
Rationale for removing assignment operator:
11:45 < neobrain_> yeah, I figured a while ago it would be better to move the "intended" usage of BitField towards member
functions rather via operator overloading. then it shouldn't be much of a problem anymore
11:46 < neobrain_> I mean, essentially that's already done, and we should just remove the overloaded operators and replace all
usage by explicitly calling Value() and Assign()
12:54 < merrymage> neobrain_: Something like this?
https://github.com/MerryMage/citra/commit/927d7d9da31facd536cf385bcf92f936a9db12d1
13:20 < neobrain_> merrymage: yes.
13:21 < neobrain_> although, we probably want to keep around the implicit conversions, since they don't really do any harm.
> BitField: Make trivially copyable and remove assignment operator.

- src/video_core/command_processor.cpp
This adds support for padding attributes, as defined on [3dbrew](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_ATTRIBBUFFERi_CONFIG1). I created a small example (which runs on real hardware) [here](https://github.com/ds84182/3ds-gpu-stuff/tree/master/attribute_padding).
> Add support for padding vertex attributes

- src/citra_qt/main.cpp
- src/citra_qt/main.h
Implementation for #1335
It should also be done for citra-cli (GLFW), but there is no easy way to show a message box using this API.
> Add check before closure when emulation is running

- src/common/x64/emitter.cpp
The L bit is supposed to be the 3rd bit.
> x64 Emitter: Fix L bit in VEX prefix

- src/core/hle/svc.cpp
This allows The legend of legacy to boot. Fixes #1432
> Add THREADPROCESSORID_ALL on SVC::CreateThread

- src/citra_qt/debugger/graphics_cmdlists.cpp
- src/citra_qt/debugger/graphics_framebuffer.cpp
- src/citra_qt/debugger/graphics_tracing.cpp
- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/CMakeLists.txt
- src/video_core/clipper.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/pica.cpp
- src/video_core/pica.h
- src/video_core/pica_state.h
- src/video_core/primitive_assembly.cpp
- src/video_core/primitive_assembly.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
This adds support for Immediate Mode Vertex Submission. I have tested this with Mii Maker and [Citro3D's Immediate Mode example](https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu/immediate).
Triangles are drawn when the PICA GPU Mode register is reset to configuration mode.
> Add immediate mode vertex submission

- src/core/loader/ncch.cpp
This is useful for all sorts of things, but mainly to identify save
folders more easily.
> Loader/NCCH: Log the program ID during loading

- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
This has been confirmed on hardware. Together with #1461, fixes Etrian Odyssey IV.
> Pica: Write depth value even when depth test is disabled

- src/citra_qt/main.cpp
This fixes a bug on Linux (maybe Windows too), on systems where the locale does separate float numbers with ",". Qt through QApplication changes the locale. The new locale affects std::to_string behavior in shaders generation.
The string will be "0,0000" instead of "0.0000" causing numerous problem such as invalid shaders.
My solution is to set back an appropriate locale after QApplication instantiation.
> Set the appropriate locale to get float conversion working using to_string

- src/audio_core/hle/dsp.h
- src/audio_core/hle/pipe.cpp
- src/audio_core/hle/pipe.h
- src/core/hle/service/dsp_dsp.cpp
Pipe 2 is a DSP pipe that is used to initialize both the DSP hardware (the application signals to the DSP to initialize) and the application (the DSP provides the memory location of structures in the shared memory region).
This PR implements that pipe, in addition to several service functions in the dsp::DSP service.
> AudioCore: Implement Pipe 2

- src/citra_qt/debugger/graphics_vertex_shader.cpp
As documented here: https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_SH_ATTRIBUTES_PERMUTATION_LOW
```
GPUREG_VSH_NUM_ATTR	242	0001	00000004	
GPUREG_VSH_ATTRIBUTES_PERMUTATION_LOW	2bb	1111	00076310	
GPUREG_VSH_ATTRIBUTES_PERMUTATION_HIGH	2bc	1111	00000000	
```
Regs mean: v7=attr4 v6=attr3 v3=attr2 v1=attr1 v0=attr0
Citra would show: v2=attr3 v1=attr1 v0=attr0
(= 3 registers instead 4+1 [because some widgets are hidden by accident] and also mapped the wrong way around ("v2 = attribue 3" instead "v3 = attribute 2"))
This PR fixes this bug.
> Fix attribute mapping in vs debugger

- src/common/common_funcs.h
- src/video_core/shader/shader.h
The GL rasterizer already uses alignas, so we may as well move everything over.
> Common: Get rid of alignment macros

- src/common/CMakeLists.txt
- src/common/alignment.h
- src/video_core/command_processor.cpp
Fixes #1488 and possible a good chunk of others.
Not tested against real hw, not documented on 3dbrew but very very very likely.
Not sure yet wether each component or just each attribute vec is aligned.
Example (Super Smash Bros Demo Characters) of problematic uploads in current master:
Outline:
```
v0.z [Vertex 206], format 0x2, base 0x18201B00, stride 18, element size: 2: 3192.000000
v1.x [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -43.000000
v1.y [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -118.000000
v1.z [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -6.000000
v2.x [Vertex 206], format 0x1, base 0x18201B09, stride 18, element size: 1: 141.000000
v2.y [Vertex 206], format 0x1, base 0x18201B09, stride 18, …
```
> Align attribute components

- src/common/common_types.h
The signature for the copy constructor and copy assignment operators generated by the compiler contain a const reference parameter, so we may as well specify that for consistency.
Also make the default constructor constexpr so it doesn't hamper objects that use it from being constexpr.
> common: Minor changes to NonCopyable

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/ndm/ndm.cpp
- src/core/hle/service/ndm/ndm.h
- src/core/hle/service/ndm/ndm_u.cpp
- src/core/hle/service/ndm/ndm_u.h
- src/core/hle/service/service.cpp
SuspendDaemons , ResumeDaemons , OverrideDefaultDaemons
The NDM file move to /core/hle/service/ndm/ now!
Signed-off-by: JamePeng <jame_peng@sina.com>
> Reorganize the ndm service path for implement dummy function

- src/citra/emu_window/emu_window_sdl2.cpp
> SDL2: Explicitly use RGB8 color buffer.

- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
Fixes https://github.com/citra-emu/citra/issues/974
Includes fixes for:
- Interpreter
- Shader JIT
- VS Debugger
My assumption is that MADI will invert src2 and src3, also putting the offset on src3.
~~This is just an educated guess and untested (due to a lack of test code).~~ Confirmed.
I had to change some parts of nihstro (https://github.com/neobrain/nihstro/pull/47) but didn't fix its assembler / disassembler.
> Fix MAD/MADI encoding

- src/video_core/shader/shader.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Adds a check to ensure the memory allocated for cached compiled shaders is not full. If so, it clears the cache and frees up the memory to be used for new shaders. I also bumped the size up to 8MB to make this happen less frequently (although it was already pretty infrequent).
Also, we should have _at least_ been doing this between each game before, so you'd eventually hit this issue just by playing a few different games in a row.
Fixes #1443
Fixes #1081 
Fixes #1127
> Clear JIT cache

- src/video_core/pica.h
Turns out the viewport offset is 10 bit signed.
Game is Digimon World ReDigtize Decode. Previously didn't render Agumon in the load / save menu.
3DS (Image by Romsstar)
Currently crashes on Citra (Addressed in #1518 ) or doesn't draw Agumon with hw renderer.
Fixed (SW Renderer only):
HW rendering has other issues with this title so only SW rendering was used to test this.
3dbrew already said that it was 10 bit but it was still wrong about signedness. I've already changed it there to reflect these findings from Digimon.
> PICA: Fix viewport offset

- src/video_core/command_processor.cpp
pcmaker informed me about a [regression with "Thor - Thunder of Gods"](http://i.imgur.com/IcbBtoj.jpg) since #1496.
As @yuriks and me hw-tested the aligment this came as a surprise.
I had a lot of trouble debugging this issue because the alignment looked fine while debugging it. Then I noticed that my debug code tested the alignment by aligning locally in each vertex (load_address = 0 for testing), while Citra was doing it globally because load_address can be unaligned.
The hw-test we did also only ever used aligned buffers so we never hit this case. (Sorry!)
This PR makes the alignment local to each vertex. It fixes the Thor regression, Super Smash Bros also still works. I didn't test any other games yet.
With the assumption that alignment happens to avoid accessing multiple words from …
> PICA: Alignment happens locally in vertex

- src/common/vector_math.h
Previously Vec4's SetZero would only reset three of its four elements.
> vector_math: Add missing member in Vec4's SetZero function

- .travis-deps.sh
- .travis-upload.sh
Our nightly builds currently do not include a dylib of SDL2 along in the archive. This requires the user to hunt down and build/install the appropate version of SDL2.
This fixes that by adding the appropriate libraries to the archive using `dylibbundler`. `dylibbundler` also runs `install_name_tool` as appropriate to update the dylib references in the `citra` executable.
This is likely a better solution than #1468 which I originally proposed. Would like someone who actually develops programs for OS X to comment.
> OS X: Use dylibbundler to include dylibs required by citra in nightly build

- src/core/gdbstub/gdbstub.h
gdbstub.h could not be used without including common_types.h as noticed in PR #1368
> Fix missing header

- src/core/hle/kernel/session.h
- src/core/loader/loader.h
Left the respective commits separate for review. Will squash them if preferred.
> core: Mark some helper functions as constexpr

- src/core/arm/skyeye_common/armstate.cpp
FIQ mode has seven banked registers (R8 to R14), not two.
> armstate: Correct FIQ register banking

- src/core/file_sys/archive_extsavedata.h
`shared` appears in the initializer list before `mount_point`
Silences a warning; simple stuff.
> archive_extsavedata: Fix member initialization order

- src/video_core/pica.h
- src/video_core/shader/shader.cpp
Something along these lines fixes most of #1504
What happens in Digimon?
* vs outmap_total is 5 = 5 output registers used
* vs outmap_mask is 0x2F (you might see where this is going..)
* shader wrote to o0, o1, o2, o3 and o5
* you know where the output semantics for o5 are configured? right.. vs outmap_o4
* said differently: outmap is packed tightly
Therefore I added a second index to count the actual outmap (output_attributes in citra) index.
As the file was already opened I switched the loop indices to unsigned.
I'm not sure about vs_output_total early out and it should be tested on actual HW.
I felt a little safer adding it because I wouldn't want possibly disabled (cause they are not included in output_total) regs overwriting outputs.
I didn't know how to walk in the game as no button …
> Respect vs output map

- src/video_core/command_processor.cpp
- src/video_core/pica.cpp
- src/video_core/pica.h
- src/video_core/pica_state.h
- src/video_core/primitive_assembly.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
This fixes some issues I missed when reviewing #1394 and also forward-ports some extra features from my old branch:
- Unifies some duplicated code paths between immediate mode and batch vertex draws.
- Fixes initialization of the PicaState struct to not memset over PrimitiveAssembler.
- Adds support for primitive restart.
- Tweaks and moves a few things around to more closely match behavior from the hardware with unusual register values and command sequences.
cc @ds84182
> Immediate-mode improvements

- src/common/emu_window.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hle/service/hid/hid_spvr.cpp
- src/core/hle/service/hid/hid_user.cpp
This is just a back-end implement, so that front-end can be implemented with convenience in the future. I made two stubbed function left in `EmuWindow` for front-end.
Most behavior are confirmed by this [hardware test](https://github.com/wwylele/ctrhwtest/tree/master/acc_and_gyro)  
The axis system for gyroscope that I used (with x-y-z successively in each entry) is different from which in 3dbrew and ctrulib (with y and z swapped as x-z-y). I did this to make it consistent with accelerometer's axis. The axis explanation is documented in code.
The behavior of `GetGyroscopeLowCalibrateParam` is unclear, so I stubbed it with the output from my 3ds. Please help find the right way to implement this.
I test these with Kirby Triple Deluxe, by editing the return value of two functions in …
> hid: implement accelerometer and gyroscope back-end

- src/citra_qt/config.cpp
- src/citra_qt/game_list.cpp
On Windows10 with codepage 950
Before (can not open that game)
After (it is fine)
**But it just a temporary fix! **
There are more problems with [here](https://github.com/citra-emu/citra/blob/master/src/common/file_util.cpp#L444)
Citra use FindFirstFileA / FindNextFileA as default ,but these functions can not correctly handle filename. for example : 
There are some file names
```
ゲーム.cci (Japanese)
경기.cci (Korean)
游戏.cci  (Simplified Chinese)
遊戲.cci  (Traditional Chinese) (local environment)
game.cci (English)
```
Only 遊戲.cci & game.cci are correctly loaded. 
`ゲーム.cci`  with UTF-8 
`e3 82 b2 e3 83 bc e3 83 a0 2e 63 63 69`
dump ffd.cFileName got
`3f 3f 3f 2e 63 63 69`
and it cause error and output `core\loader\loader.cpp:Loader::IdentifyFile:49: Failed to load file ./???.cci`
I can keep …
> Fix Qt string encode problem on Windows

- src/core/hle/service/cfg/cfg_i.cpp
- src/core/hle/service/cfg/cfg_s.cpp
- src/core/hle/service/cfg/cfg_u.cpp
According to 3dbrew all of the cfg ports share a common set of methods which were previously only implemented in cfg:u.  ctrulib will attempt to connect to the highest privilege port available with the assumption that these shared methods exist across all ports.
> Add common methods to all cfg:* ports

- src/video_core/renderer_opengl/pica_to_gl.h
Just something I've been annoyed with lately: clang complains about these (`unsigned` would be fine but ARRAY_SIZE() gives a `size_t` - so I prefer that).
There are other warnings I'd like to be silent but this will do for now.
> Avoid warnings by casting to size_t for ARRAY_SIZE() comparisons

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/cecd/cecd.cpp
- src/core/hle/service/cecd/cecd.h
- src/core/hle/service/cecd/cecd_u.cpp
when games don't get valid event handles, they break with fatal error
> cecd:u: stub GetCecInfoEventHandle, GetChangeStateEventHandle

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/dlp_srvr.cpp
- src/core/hle/service/dlp_srvr.h
- src/core/hle/service/service.cpp
Dummy implementation dlp:SRVR Service. Only response result success.
Fixed Luigi's Mansion 2 https://github.com/citra-emu/citra/issues/1615 This PR + https://github.com/citra-emu/citra/pull/1613
> Dummy implementation dlp:SRVR Service.

- src/video_core/renderer_opengl/gl_rasterizer.cpp
Work around [this mesa bug](https://bugs.freedesktop.org/show_bug.cgi?id=94148). It's also the sane thing to do anyway.
I'm not sure if ASSERT_MSG() is meant to catch errors which should be presentable to the user or wether it should be a debugging aid (absent from release builds). - Probably worth another issue.
This line however was copied from elsewhere in the same file so.. insta-merge?
> OpenGL: Check for framebuffer completeness

- .travis-build.sh
- .travis-deps.sh
- .travis.yml
- CMakeLists.txt
Quite overdue
As Travis CI devs are continually dedicated to providing only the most up-to-date compiler tools, they use vitrual environments containing Mac OS X 10.9 with XCode 6.1 (LLVM 3.5) and Ubuntu Trusty with the blazingly up-to-date GCC 4.9. So we cannot use the regular `-std=c++14` switch. So we need to use `-std=c++1y` (the name of C++14 when it didn't have a concrete date).
> CMakeFiles: Compile as C++14

- src/citra_qt/config.cpp
- src/citra_qt/game_list.cpp
- src/citra_qt/main.cpp
- src/common/file_util.cpp
- src/common/string_util.cpp
- src/common/string_util.h
fix #1584 #730 
Use wide version functions for Windows. It fix file name & dir path encode problem.
`SetConsoleOutputCP(CP_UTF8);` can fix console
with `SetConsoleOutputCP(CP_UTF8);`
(Consolas)
(default font style)
> Fix filename&path encode problem on Windows

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Only one instruction fixed, not sure if another pc-based instructions must be aligned, too.
PR fixes the game **Conception 2: Children of the Seven Stars**
> Fix thumb ADR instruction alignment

- src/video_core/renderer_opengl/gl_rasterizer.cpp
It was already present elsewhere, and got duplicated in 693cbc1f8ff4b7c01c0f30b871e8301e6867d4c2.
> OpenGL: Fix a double framebuffer completeness checks.

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
This PR implements 2 of the 4 "allow"-registers which are probably used for powergating (as suggested by @yuriks).
\- Some games such as Tappingo still depend on them for disabling depth/stencil writes.
I've chosen the name "allow" myself and I'd be happy to change it to something more fitting.
Essentially those are read/write-enable registers for the buffers.
I use the term "buffer" when it refers to color-, depth- and/or stencil-buffer.
While the RGBA register field is 4 bits it will still control all channels at once, it's not a bitmask.
Depth and stencil share 2 bit. It also controls access to both buffers at once and is not a bitmask.
I did not yet test wether there are more bits which are tested in either of those registers.
This PR implements the write-permission fully in the …
> Implement buffer-write allow registers

- src/citra_qt/CMakeLists.txt
- src/citra_qt/config.cpp
- src/citra_qt/configure.ui
- src/citra_qt/configure_debug.cpp
- src/citra_qt/configure_debug.h
- src/citra_qt/configure_debug.ui
- src/citra_qt/configure_dialog.cpp
- src/citra_qt/configure_dialog.h
- src/citra_qt/configure_general.cpp
- src/citra_qt/configure_general.h
- src/citra_qt/configure_general.ui
- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
- src/citra_qt/hotkeys.cpp
- src/citra_qt/hotkeys.h
- src/citra_qt/hotkeys.ui
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
- src/citra_qt/ui_settings.cpp
- src/citra_qt/ui_settings.h
I have worked on a new widget to configure Citra:
There is nothing in "Input" tab since we don't have the input widget yet.
Additionally, I have centralized all the configuration in Config class. Now, we should have one configure file only.
> Implementation for a configure widget

- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/primitive_assembly.cpp
Resolves #1635 
`grep` for "Dump" and "DUMP_GEOM" found nothing related to this feature anymore.
Use RenderDoc or write your own dumper if you want to dump geometry.
(I'll probably come up with a new dumper at some point as I'm working on an improved shader debugger which fits the bill for this one)
> Pica: Remove geometry dumper (PICA_DUMP_GEOMETRY)

- src/citra/citra.cpp
- src/citra_qt/config.cpp
- src/citra_qt/configure_debug.cpp
- src/citra_qt/configure_general.cpp
- src/citra_qt/main.cpp
- src/core/settings.cpp
- src/core/settings.h
This is a quick-and-dirty hack (mostly untested too).
`master` doesn't load config with CitraQt at the moment so no matter what your settings say: you are starting with SW Rasterizer (and maybe also interpreter?). It also means you can't trust the config dialog because that claims you are running with HW Rendering.
it's probably not smart to do it this way but `master` is currently broken so we need a fix.
I also ordered the GDB calls because I'm pretty sure enabling the server will open a socket on the *previously* specified port. I'm not sure if GDB can even change the port while the server is running?
> CitraQt: Apply config at startup

- src/common/file_util.h
`Common::UTF8ToTStr` call requires `#include "common/string_util.h"`
Also spotted a few things in IOFile while I was there.
> FileUtil: Missing #include, Add const to IOFile methods

- src/common/x64/emitter.cpp
- src/common/x64/emitter.h
- src/video_core/command_processor.cpp
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
Specifically, this is a new and improved implementation of flow control for the shader JIT. Previously, the shader JIT inlined CALL and JMP instructions. This had several issues: 1) Inlining all subroutines resulted in bloated shaders being generated, and 2) JMP to arbitrary addresses (and nested jumps) couldn't be supported.
With these changes, any arbitrary CALL/JMP will now work. Furthermore, this results in pretty constant compiled shader sizes of around ~40kb, so I changed allocation to happen on the fly (preventing cache clearing and recompiling of previously compiled shaders).
The changes in this patch could also be leveraged to support arbitrary (read: wacky) IF and LOOP instructions... But I didn't feel like doing this, particularly because these instructions in the JIT are a bit …
> Shader JIT Part 2

- src/common/thread.h
`Barrier` as currently implemented is a one-shot synchronisation barrier that is unsafe to be reused. Here we make it reusable.
> Thread: Correct Common::Barrier implementation

- src/video_core/debug_utils/debug_utils.cpp
Noticed this while doing the IOFile changes.
> debug_utils: use std::make_unique for initializing PicaTrace

- src/citra_qt/configure.ui
Allows Qt to automatically calculate a minimum size, preventing [this](http://i.imgur.com/7Ckbhqb.png).
> Configure Dialog: Remove minimumSize property

- src/core/loader/ncch.cpp
Fix for `ReadIcon`, `ReadBanner` and `ReadLogo`, though they havn't been used yet
> loader: only decompress code section

- src/core/hle/service/soc_u.cpp
-Implement `GetSockOpt`/`SetSockOpt`
-Fix bug in `RecvFrom` where sending from localhost does not fill in `src_addr`/`src_addr_len` on Linux
`SOC_U::RecvFrom` was crashing due to odd behavior in Linux where `src_addr` was not being filled in, and `src_addr_len` was being set to `0`.  This caused `src_addr.sa_family` to become invalid, failing `CTRSockAddr::FromPlatform`'s assertion that `sa_family` must be `AF_INET`.
> SOC:U GetSockOpt/SetSockOpt

- src/common/file_util.cpp
On Windoiws, `_wstat64` doesn't work with a driver root without slash, which cause failure to try select a driver root as game list. Also fixed C-style `StripTailDirSlashes` for `string::back` to work.
> Fix driver root identification on Windows

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/citra_qt/configure_general.cpp
- src/citra_qt/configure_general.ui
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/y2r_u.cpp
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
- src/core/memory.cpp
- src/core/memory.h
- src/core/settings.cpp
- src/core/settings.h
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica.h
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_base.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
- src/video_core/swrasterizer.h
- src/video_core/video_core.cpp
- src/video_core/video_core.h
Credit to @yuriks for providing the solid starting point of this branch with his opengl-tex-forwarding branch!
* When possible, all accesses to memory by the rasterizer (textures and framebuffers) put the region into a 'surface' (OpenGL texture) so it can forward surfaces across frames and across commands, such as fill/clear->render->transfer->display.
* Some example cases:
* Re-using an entire surface, e.g. for the framebuffer.
* Re-using a subrect of a surface, e.g. for bottom screen rendered within subrect of top screen framebuffer.
* Doing a blit from surface to surface without downloading and uploading the surface's texture to the CPU, e.g. for a display transfer.
* The surface cache is an interval_map to allow for overlapping surfaces, and to allow for better performance using both …
> Hardware Renderer Texture Forwarding

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- Adds missing sync calls for specular light uniforms for new shaders
- Reorders function declarations in header to match definitions in source
> HWRasterizer: Lighting Sync + Cleanup

- src/common/file_util.h
The protection was already used in dsp.h so I just added these for other uses of std::is_trivially_copyable. Thanks to this, I can compile citra with my "old" GCC 4.9.
> Protect use of std::is_trivially_copyable to compile with GCC 4.9

- .travis-deps.sh
- CMakeLists.txt
- src/citra/CMakeLists.txt
- src/common/assert.h
- src/core/hle/service/am/am.cpp
- src/video_core/shader/shader_jit_x64.cpp
The big change is moving to CMake 3.1. Other changes
fix compiler errors noticed on Clang 3.9 / OSX.
Fixes #1711
> Fixes for #1711 and other compilation errors.

- src/citra_qt/debugger/graphics_breakpoints.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
And allow the compiler to inline by moving the actual check to the header.
Saves 1%+ in vertex heavy situations as std::map lookups are quite expensive. As Citra was doing one per Pica reg write, that can be replaced with an array lookup, I thought that might be worth fixing.
> Replace std::map with std::array for graphics event breakpoints

- src/citra_qt/CMakeLists.txt
This had been forgotten in df81fa11fc8972a5775a57ccde1e0ef8d7fbfe64.
Fixes #1711.
> Qt Frontend: Add Threads::Threads import in CMakeLists.txt

- src/audio_core/audio_core.h
- src/audio_core/hle/common.h
- src/audio_core/hle/dsp.h
Very minor change.
Done so that everything under `src/audio_core/hle` doesn't have to `#include "audio_core/audio_core.h"`.
(Done as it's own PR to not clutter up the others.)
> AudioCore: Move samples_per_frame and num_sources into hle/common.h

- src/video_core/CMakeLists.txt
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/shader/shader.h
- src/video_core/vertex_loader.cpp
- src/video_core/vertex_loader.h
These can later be optimized (JIT-ed) and cached, just like in Dolphin or PPSSPP. Turns out Citra spends quite a lot of time loading vertex data, so this will help. As a bonus, command_processor.cpp gets easier to read.
Later, it would also be nice to refactor away the primitive assembler and use GL-native indexing, then the vertex loader and vertex shader JIT can take a number of vertices to decode in one go and handle their own loops.
Not sure what the best place to keep the MemoryAccesses class is.
I also optimized it, so Citra now spends quite a bit less time on vertex loading even if no smart caching is done yet.
> Extract a "Vertex loader" class from command_processor.cpp

- src/audio_core/CMakeLists.txt
- src/audio_core/interpolate.cpp
- src/audio_core/interpolate.h
Black-box tested against actual DSP firmware. Annoyingly I couldn't get it exact; that would have to wait for white-box RE. Error in values is +/- 1. `scale_factor` chosen for minimum error.
> AudioCore: Implement interpolation

- src/audio_core/audio_core.cpp
- src/audio_core/hle/dsp.cpp
- src/audio_core/hle/dsp.h
The DSP and applications read from one region while writing to another.
Replicating this is required for correct behavior.
> AudioCore: CurrentRegion() -> ReadRegion(), WriteRegion()

- src/audio_core/CMakeLists.txt
- src/audio_core/audio_core.cpp
- src/audio_core/audio_core.h
- src/audio_core/hle/dsp.cpp
- src/audio_core/hle/dsp.h
- src/audio_core/null_sink.h
- src/audio_core/sink_details.cpp
- src/audio_core/sink_details.h
- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/core/settings.cpp
- src/core/settings.h
SDL2Sink coming later.
This PR introduces a global list of sink types available, `g_sink_details`. This is intended to be filled in [like this](https://github.com/MerryMage/citra/blob/26092a7071e1a224516c0f094e527c6b746913d6/src/audio_core/sink_details.cpp).
`SinkDetails::id` is not automatically based on the index because that may vary depending on audio libraries available when compiling.
> Audio Config: Implement null sink and implement sink configuration

- src/video_core/renderer_opengl/gl_rasterizer.h
Looks like someone forgot to copy `const_color`.. Instead of adding another block of code I figured it's easier to loop over the stages.
Only tested OoT and saw no regressions.
No idea if this fixes anything.
(I originally wanted to include this fix in #1704 but I figured I should do this separately for now because I still don't have a good solution for said PR and I'm not sure when I will..)
> OpenGL: Copy TevStageConfig using a loop. Fixes bug: const_color not copied

- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/cfg/cfg.h
An easy patch. Fixes Kirby's Robobot Planet (and maybe some other games) that wants this block. Value (zero) and flag (0xE) is taken from my real console's config savedata.
Edit: please help test #1258, #1486 and #1600.
> add config block 0x00170000; remove duplicated content

- src/video_core/renderer_opengl/gl_rasterizer.h
Should fix #1752 by reverting erroneous change from #1745 (Sorry :disappointed: ).
This keeps the loop but removes the bad line.
I've also made the comment more clear so this doesn't happen again.
~~Untested, will test soon.~~ Just tested playing OoT, started off at 304MB RAM usage, went up to 391MB RAM after playing for 40 minutes (I've played through almost the entire deku tree). Fixed?
> OpenGL: Don't copy const_color (Reverts #1745)

- src/citra_qt/debugger/graphics_breakpoints.cpp
- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/command_processor.cpp
- src/video_core/debug_utils/debug_utils.h
Another small change to prepare for geometry shaders which will introduce "Geometry shader invocation".
1. Renames the VertexLoaded-events to VertexShaderInvocation ("Vertex shader invocation")
2. Moves the debug events closer to the actual ::Run() of the shader
(The next changes will be larger, I'm aware that these tiny PRs are annoying)
> Pica: Rename VertexLoaded breakpoint to VertexShaderInvocation

- src/core/core.cpp
- src/core/hle/hle.cpp
- src/core/hle/hle.h
- src/core/hle/kernel/thread.cpp
Because I'm impatient.
Supersedes #1561
> hle: Get rid of direct global access to g_reschedule

- src/core/loader/loader.cpp
Fixes a small bug: when opening an encrypted ROM citra says "Unknown error" instead of information about decryption.
Was introduced in my game list icon PR. Sorry!
> fix loader: return proper result

- src/citra/emu_window/emu_window_sdl2.cpp
- src/citra_qt/main.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
On SDL2 this allows it to use SDL_GL_GetProcAddress() instead of the
default function loader, and fixes a crash when using apitrace with an
EGL context.
On Qt we will need to migrate from QGLWidget to QOpenGLWidget and
QOpenGLContext before we can use gladLoadGLLoader() instead of
gladLoadGL(), since the former doesn’t expose a function loader.
> Move glad initialisation to the frontend

- src/core/hle/applets/mii_selector.cpp
- src/core/hle/applets/mii_selector.h
- src/core/hle/applets/swkbd.cpp
- src/core/hle/applets/swkbd.h
- src/core/hle/service/apt/apt.h
This is preliminary work for a fix we need in #1689
> HLE/Applets: Use the correct size for the framebuffer SharedMemory

- src/audio_core/hle/pipe.cpp
- src/audio_core/hle/pipe.h
- src/citra/config.cpp
- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/citra_qt/util/util.cpp
- src/core/gdbstub/gdbstub.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/hw/gpu.cpp
- src/core/loader/3dsx.cpp
- src/core/tracer/recorder.cpp
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/pica_state.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
This PR is a step towards fixing all warnings under the MSVC.
There are 3 major classes of warnings that need fixing:
- implicit type casts where data can be lost
- code paths where not all branches return
- comparisons between signed/unsigned values
I only look to fix implicit type casts here, and only for the `citra` project directly. I make no changes to `microprofile` or `nihstro` here.
I'm looking to fix the other classes of warnings in other PRs.
> fixup simple type conversions where possible

- src/core/hle/kernel/process.h
- src/core/hle/svc.cpp
- src/core/loader/ncch.cpp
We do not currently implement any cores other than the AppCore (Core 0).
> Kernel/Threading: Warn when a thread can be scheduled in the Syscore (Core 1)

- src/audio_core/hle/source.cpp
> source: Fix missing logging arguments

- src/core/arm/dyncom/arm_dyncom.cpp
The other mode was system mode.
> dyncom: Reset the context into user mode correctly

- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_shader_gen.h
This is my proposal to solve the issue in #1621 and #1690 where the padding bytes of the PicaShaderConfig struct would get random values and therefore fail the memcmp test.
It would result in new shaders being generated for every new random pad which quickly fills up the available memory with shaders and wastes too much time compiling them.
Making PicaShaderConfig a POD apparently only means we have to avoid the initializations of members which was useless anyway. It should be safe to assume that all data members will be set by PicaShaderConfig::CurrentConfig - otherwise the whole concept of copying the pica state would be fundamentally broken anyway.
(It surprised me that ~~`std::array`~~ (thanks MSVC..) and `BitField` are both considered POD tbh)
I think the POD / memset is the best …
> Pica: PicaShaderConfig is TC and cleared before use

- src/video_core/clipper.cpp
- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
This PR [implements W-Buffers](https://www.mvps.org/directx/articles/using_w-buffers.htm) and fixes hardware depth-mapping (scale + offset).
The formulas for the depth-mapping were guessed after testing on hardware.
The results are still about 3 bits inprecise in the lower bits due to rounding and precision issues probably. This is still somewhat better than the current `master` solution which produces complete garbage for some mappings.
This PR implements this in the SW-Rasterizer and the HW-Renderer.
---
This PR was [tested using a HW-Test](https://github.com/JayFoxRox/3ds-tests/tree/master/depth-write) ([Planar results where top.zw = bottom.zw](https://docs.google.com/spreadsheets/d/1E8xvJIbj_MVygWtr4ELPuzOJPqEv4yGeHQuKG6kFmTc/edit#gid=0) & [Perspective …
> Implement W-buffer and fix depth-mapping

- src/citra_qt/debugger/graphics_vertex_shader.cpp
- src/video_core/command_processor.cpp
- src/video_core/pica.cpp
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
`Setup()` is an objectless function in master and it means that one would have to set up VS or GS before each run which is not suitable due to them being run in alternating pattern (VS is ran a couple of times to generate GS input, then GS runs. The process repeats for each group of vertices until enough GS input data is available again).
Rather than keeping the `Setup()` function in `Shader::` I moved it to a `class ShaderSetup::` (which maintains per shader type state which is not already in the Pica regs) so we can `Setup()` for VS or GS seperately.
I've also decided to rename the `Shutdown()` function to avoid ambiguity and I also kept it out of `ShaderSetup`.
This is more useful because VS and GS should be able to share the same shader cache.
If we would have called `Shutdown()` on …
> Turn ShaderSetup into a class

- src/citra_qt/debugger/graphics_tracing.cpp
- src/video_core/command_processor.cpp
- src/video_core/pica_state.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/vertex_loader.cpp
Another part of my GS branch.
ShaderSetup still stores the fixed per vertex attributes even if that is not directly tied to any specific shader type (VS / GS). Commit moves this into the generic Pica state.
UnitState (which is a helper struct for shader execution) contains state information which is only necessary for the interpreter. Commit moves this into respective functions as local variables.
(One could argue that it's part of the shader unit state, but it's not easily observable from the outside and JIT / Interpreter don't use the same variables, so this was just a memory hog and confusing)
The program_counter is initialized to the VS entry point now which might appear weird because it came from `config` before, however, we always use the VS as config source so this shouldn't break …
> Cleanup ShaderSetup (Part 1)

- src/core/hle/kernel/memory.cpp
- src/core/hle/kernel/process.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/memory.h
The memory pages are allocated from the BASE region as per the real kernel.
Each thread gets a 0x200-byte area from the 0x1000-sized page, when all 8 thread slots in a single page are used up, the kernel allocates a new page to hold another 8 entries.
This is consistent with what the real kernel does.
With this and #1689, only the VRAM mapping remains in the table of fixed legacy mappings.
> Kernel/Threads: Dynamically allocate the TLS region for threads.

- .gitmodules
> gitmodules: citra-emu/soundtouch → citra-emu/ext-soundtouch

- src/core/CMakeLists.txt
- src/core/hle/applets/applet.h
- src/core/hle/applets/mii_selector.cpp
- src/core/hle/applets/swkbd.cpp
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/memory.cpp
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/shared_memory.h
- src/core/hle/result.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/bcfnt/bcfnt.cpp
- src/core/hle/service/apt/bcfnt/bcfnt.h
- src/core/hle/service/csnd_snd.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ir/ir.cpp
- src/core/hle/svc.cpp
This PR corrects the implementation of Shared Memory thorough the codebase.
SharedMemories created by HLE processes are backed by memory located in the BASE linear heap region (Unless stated otherwise by the call to Create), as per the real kernel.
With this we can get rid of some very nasty hacks, like the APT Shared Font being located at a fixed address. This PR implements a function to automatically relocate the dumped shared font from the 0x18000000 address to whatever address the allocator places it at. This fixes an issue where we were placing the shared font in the middle of the APPLICATION memory region (Possibly breaking games that use that part of the region).
All error codes were verified by reverse engineering unless otherwise stated.
There are some sanity checks that can not …
> Kernel: Implemented shared memory.

- src/core/hle/kernel/memory.cpp
Reserve enough space in the vector that holds the linear heap memory to prevent relocations of the backing memory when growing too much.
This can be considered a temporary fix until we rewrite all our service handlers to not depend on GetPointer.
Closes #1790
> Memory: Fixed a regression caused by #1695 and #1689.

- src/core/hle/service/dsp_dsp.cpp
Downgrade from `WARNING` to `DEBUG` since we don't need to know it's being called x times a second.
May make headphones being inserted a config option in the future.
> DSP_DSP: Remove GetHeadphoneStatus logspam

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
The latest bugs have reminded me that I should run valgrind more often.
I then noticed that pretty much every GL state caused 1 uninitalised [sic, valgrind] access.
This PR fixes this by value-initializing those variables.
It's really not that important though because the access is basically: `if (new_value != current_value) { current_value = new_value; dirty = true; }` (the logic still works, it's just not nice to do it).
Furthermore I noticed how different my depth-modifier uniform synced compared to every other uniform sync in gl_rasterizer. This PR fixes that in another commit too.
> Avoid uninitialised in hw renderer + Only sync depth if necessary

- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_interpreter.h
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
*aka Cleanup ShaderSetup (Part 2)*
The shader JIT in `master` reads from a register struct (part of UnitState) and the uniform struct (part of ShaderSetup) with functions providing an offset into the register / uniform structs to access a certain member.
This commit instead gives the JIT full access to the UnitState and ShaderSetup so it's easier to see where the data is read from / written to (+ it's more extensible as we are running low on usable registers). Commit also introduces functions to get the offset into the uniform struct where calculations were inlined before.
I've also adapted the new function signature of the JIT for the interpreter.
(Also part of my GS implementation, as the ShaderSetup/Uniforms was hardcoded to VS)
---
You should enable jit before running this, I was just …
> Refactor JIT

- src/core/arm/arm_interface.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/svc.cpp
~~Improves~~ Fixes #1777 ~~(= does not fix it completly!)~~
~~Doing this in svcCreateThread doesn't work (its too late probably because the thread is already scheduled after creation in the kernel code).
This should really be reset to 0 on CPU level and only set to something else in the Kernel / Service HLE (probably also true for other regs in that function?)~~
I'm stupid, MerryMage is the best :heart: 
---
[HW-Tested using this](https://github.com/JayFoxRox/3ds-tests/commit/3eb17d9e7f4f310ebf1d989a81d11bf36ca2bac0)
Result on actual 3DS (by einstein95):
```
old_fpscr: 0x03C00010
new_fpscr: 0x03C00000
old_fpscr: 0x00000000
new_fpscr: 0x03C00000
old_fpscr: 0x03C00000
new_fpscr: 0x03C00000
old_fpscr: 0x03C00010
new_fpscr: 0x03C00000
```
Citra:
```
old_fpscr: 0x00000000
new_fpscr: 0x00000000 …
```
> Set fpscr for new threads

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Fixes  #1636  and probably #862 .
There is a read-after-write in SMLAD (etc.) if Rd = Ra.
These [instructions are present in ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/e5920425b02b0feaf45971bf1c8b8abc541f5ae1/libavcodec/arm/vp8dsp_armv6.S#L1522) where this causes bugs.
This PR fixes it.
I've also searched for `RD |=`, `RD +=` etc. in this file (and only this file!) but couldn't find anything. So hopefully it was the only bug of this kind.
> Fix read-after-write in SMUAD, SMLAD, SMUSD, SMLSD

- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
This will make it easier to have a GUI combiner / Tev debugger later.
It also extends the Tev dumper by new source types and operations.
I've decided to only prototype the 3 most important functions in the header:
- One to get a string for a stage alpha channel,
- one for the color channel
- and the function to dump all stages at once to `LOG_TRACE` (which existed before).
This also changes display of the functions from byte style to float style (which is more common in the graphics world). If we end up wanting to show actual GPU register values we'll have to replace said code anyway + I don't think it will happen anytime soon.
---
It should be noted that the current `DumpTevStageConfig` function is pretty useless because the `Pica::g_state.regs.GetTevStages()` call is usually inlined = …
> Refactor Tev dump

- appveyor.yml
`on_success` script breaks because `test_script` changes the current working directory
> Appveyor: Restore working directory after test_script

- src/core/hle/svc.cpp
Fixes deadlock in an extreme situation:
Say an event A is scheduled to be signaled in 1000 cycles (such event can be GSP event, HID event, etc.). Now thread B calls `WaitSynchronizationN` to wait for A. In our old `WaitSynchronizationN`, the following will happen:
- B checks A, and finds that it is not signaled;
- B prepares to sleep (`wait_thread = true;`);
- calls `HLE::Reschedule()`, where `Core::g_app_core->AddTicks(4000);` steps over A's cycles, and A gets signaled (without any thread waited)
- Back to `WaitSynchronizationN`, B register itself to wait for A, and sleeps, leaving A in signaled state.
- If A doesn't get signaled again, B will sleep forever.
The solution is to call `HLE::Reschedule()` at the end of `WaitSynchronizationN` instead, so that event A's state won't change …
> SVC::WaitSynchronizationN: Reschedule at the end

- src/video_core/command_processor.cpp
- src/video_core/vertex_loader.cpp
- src/video_core/vertex_loader.h
Superficial things that weren't really necessary to be brought up in the initial PR that introduced it.
cc @hrydgard For one thing I wasn't really certain of. Does it make sense to allow setting up the same VertexLoader more than once (this is likely "probably no", but I just want to make sure)? If it doesn't I can modify the relevant PR to just early return  (or assert) if it's already set up.
> VertexLoader: Minor changes

- src/core/hle/kernel/vm_manager.cpp
- src/core/memory_setup.h
* `memory_setup.h` didn't need to include `memory.h` but did need to include `mmio.h`
* `vm_manager.cpp` was including `memory.h` via `memory_setup.h`
> Memory: Added necessary headers and removed unnecessary header

- src/video_core/pica.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
This should fix #1840 .
Eventually we should get rid of that stupid notify handler thing - it's been a problem way too often.
Also I only looked at the lighting struct in Pica::Regs for this PR, it's possible that more parts of the shader are affected by stuff like this.
It would be nice if someone ( @tfarley ?) could confirm that none of these are used as shader uniform / all of them used in shader code.
> OpenGL: Set shader_dirty on lighting changes

- src/core/arm/skyeye_common/vfp/vfp_helper.h
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
This is a followup to #1568 
There is an error in master where [denormals would be flushed in `vfp_double_unpack`](https://github.com/citra-emu/citra/blob/master/src/core/arm/skyeye_common/vfp/vfp_helper.h#L360)
After flushing the denormal exception is set in fpscr.
Note how `fpscr` is a pointer. However, it's [passed *by value* to `vfp_double_cpdo`](https://github.com/citra-emu/citra/blob/master/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L1178).
\- This means that the denormal exception is never propagated back to the CPU context.
(Same problem exists for single precision float too)
---
All other exceptions are normally propagated using an `u32 exceptions` return value.
This PR fixes the issue by returning a `u32 exceptions` from the unpack functions.
Furthermore I went through the …
> Fix float exceptions

- src/core/arm/dyncom/arm_dyncom_dec.cpp
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
This fixes the printf bug (which is actually a bug in "dtoa")
The buggy code is:
```C
ds = (d2.d - 1.5) * 0.289529654602168 + 0.1760912590558 + i * 0.301029995663981;
k = (int) ds;
```
Example values were 0x3ff999999999999a for d2.d (double) and int i = -3.
When ds is -0.6, k would currently be 0x80000000 when 0 is expected (suggested by running dtoa on my x64).
Changing the 2 lines from `if (vdm.exponent >= 1023 - 1)` to just 1023 makes printf work fine (I think?) but I didn't really test it much.
You can find [similar code in qemu](https://github.com/qemu/qemu/blob/master/fpu/softfloat.c#L3126) which also compares using `if ( aExp < 0x3FF )` = `if (!(aExp >= 0x3FF))` = `if (!(aExp >= 1023))`.
There might be some shifting of the mantissa which makes this change incorrect so I'd prefer if …
> Fix ftoi and disable VFPv3

- src/common/common_funcs.h
We currently provide them for non-MSVC platforms. Do the same for MSVC. (I'll be using them in the future.)
> common_funcs: Provide rotr and rotl for MSVC

- src/core/hle/service/cfg/cfg.cpp
As I said in #1433, there shouldn't be two username blocks, so remove one of them, and clean up some format problem.
But I am still afraid of making mistake. @Romsstar or anyone else please help test to ensure this doesn't cause any regression (first remove the config file `nand/data/0000000000000000/sysdata/00010017/00000000/config` and then run games).
> Config block: clean up

- src/citra_qt/debugger/callstack.cpp
- src/core/file_sys/archive_backend.cpp
- src/core/hle/applets/mii_selector.cpp
- src/core/hle/applets/mii_selector.h
- src/core/hle/applets/swkbd.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/apt.h
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/hle/service/frd/frd.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/soc_u.cpp
- src/core/hle/service/ssl_c.cpp
- src/core/memory.cpp
- src/core/memory.h
- src/core/mmio.h
Most usages were replaced by the new functions Memory::ReadBlock and Memory::WriteBlock, which take into account segmentation of memory pages.
There are 14 usages of GetPointer left, down from the 54 usages we had before.
Original work by @MerryMage.
> Memory: Remove most usages of GetPointer

- src/citra_qt/game_list.cpp
- src/citra_qt/game_list_p.h
- src/common/file_util.cpp
- src/common/file_util.h
Fixes #1115.
Also improves the performances of DiskArchive’s directory
implementation a lot, simply by not going through the entire tree
instead of just listing the first level files.
Thanks to JayRoxFox for rebasing this on current master!
> Make recursive FileUtil functions take a maximum recursion

- src/video_core/command_processor.cpp
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
In `master`, running a shader automaticly generates an output vertex.
Due to the conversion (output registers --> vertex) being lossy we can't use the data to forward a vertex from the VS to the GS easily.
A shader execution only modifies the UnitState output registers anyway, so I introduce OutputRegisters instead.
These can be converted to an OutputVertex for the rasterizer or be used as input to GS later.
(This PR is part of my GS branch)
---
I don't particularly like replacing `state.registers.output` by `state.output_registers.value` but I wasn't sure how to do it nicely otherwise. At least this way the `ToVertex` function is tied to the `OutputRegisters`.
> Retrieve shader result from new OutputRegisters-type

- src/core/hle/result.h
- src/core/hle/service/gsp_gpu.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
Fix https://github.com/citra-emu/citra/issues/1716
All credits to @Phanto-m
Also:
- move the shared memory creation/free to constructor/destructor.
- change result code in RegisterInterruptRelayQueue to  SUCCESS after first initialization (prevent blue screen between UnregisterInterruptRelayQueue/RegisterInterruptRelayQueue)
- change DEBUGPROC callback function signature
> gsp::gpu: Reset g_thread_id in UnregisterInterruptRelayQueue

- src/core/CMakeLists.txt
- src/core/hle/service/dlp/dlp.cpp
- src/core/hle/service/dlp/dlp.h
- src/core/hle/service/dlp/dlp_clnt.cpp
- src/core/hle/service/dlp/dlp_clnt.h
- src/core/hle/service/dlp/dlp_fkcl.cpp
- src/core/hle/service/dlp/dlp_fkcl.h
- src/core/hle/service/dlp/dlp_srvr.cpp
- src/core/hle/service/dlp/dlp_srvr.h
- src/core/hle/service/service.cpp
Specifically, dlp::CLNT and dlp::FKCL
Moves all DLP services to their own folder like with other services that contain multiple sub-modules.
> service: Add other DLP services

- src/core/gdbstub/gdbstub.cpp
Fixes issues with IDA and probably other debuggers. If an invalid virtual address was accessed, it would continue attempting to access it because it never saw an error and did not receive it's data in full.
> gdbstub: E0 should be E00

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra/emu_window/emu_window_sdl2.cpp
- src/citra_qt/bootmanager.cpp
- src/citra_qt/config.cpp
- src/common/emu_window.cpp
- src/common/emu_window.h
- src/common/key_map.cpp
- src/common/key_map.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/settings.h
The procedure to map inputs on current master is like this:
Frontend keyboard event -> `EmuWindow::KeyPressed/KeyReleased` -> `KeyMap::GetPadKey` -> set bit field in `PadState` for each field.
This procedure assumes that each physical keyboard key one-to-one maps to a 3DS pad button, which is not true for analog input like circle pad. So I refactored it to:
Frontend keyboard event -> `KeyMap::PressKey/ReleaseKey` -> `EmuWindow::ButtonPressed/ButtonReleased/CirclePadUpdated/...` -> set button state and circle pad state
All keyboard inputs are grouped into two category: directly mapped keys and indirectly mapped ones. For directly mapped ones, `KeyMap::PressKey/ReleaseKey` will directly call `EmuWindow::ButtonPressed/ButtonReleased` with mapped buttons. For indirectly mapped ones, `KeyMap` …
> Refactor input mapping & implement circle pad modifier

- src/core/hle/service/hid/hid.cpp
#1789 is causing error on clang build (Why it passed the build in the PR ? :confused: ) , also on gcc 6.1 as @linkmauve said.
>[ 66%] /home/travis/build/citra-emu/citra/src/core/hle/service/hid/hid.cpp: In function ‘Service::HID::PadState Service::HID::GetCirclePadDirectionState(s16, s16)’:
>
/home/travis/build/citra-emu/citra/src/core/hle/service/hid/hid.cpp:47:75: error: call of overloaded ‘abs(float)’ is ambiguous
> HID: add missing header

- src/core/CMakeLists.txt
- src/core/hle/function_wrappers.h
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_port.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/svc.cpp
This is part of an ongoing effort to implement support for multiple processes.
For now the goal is to allow applications to register their own services via srv:RegisterService.
See the sequence diagram below to get an overview of how this all fits together.
> Kernel: Added ClientPort and ServerPort classes, along with svcCreatePort.

- src/video_core/command_processor.cpp
- src/video_core/pica.h
- src/video_core/pica_state.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
This implements fog mode 5.
(Known fog modes are None = 0; Fog = 5; Gas = 7. `master` treats everything like mode 0)
---
The fog mode is fully implemented in SW rasterizer and HW renderer.
[The fog was hardware tested](https://github.com/JayFoxRox/3ds-tests/tree/6aa1be178d67f115d3f9e3652affaa343dd188b8/fog) (against all logic op modes, blend modes, RGBA write masks, Z-Buffer / W-Buffer, LUT overflows / underflows, LUT index wrapping) and it's been found that this fog mode is like a final-combiner for the R, G, B channels. There is no alpha fog or dual source blending.
The overflow of the fog_lut_offset was confirmed on hardware. I didn't want to change the size of the BitField though because there might be reasons why 3dbrew lists it as 16 bit and we can't read back the actual size of the …
> Implement standard fog (fog mode 5)

- appveyor.yml
Seems to have been broken by some change in Sourceforge. Switched to using chocolatey instead. The downside is that the chocolatey package doesn't add `WinSCP.com` to the path. I used `WinSCP.exe` instead but that unfortunately doesn't capture the output into the terminal.
> Fix AppVeyor WinSCP download

- .travis-build.sh
- .travis-deps.sh
- .travis.yml
- CMakeLists.txt
The OSX build already uses Qt 5, so nothing needs to change here for that.
This also bumps the distribution of Ubuntu that we use up from Precise Pangolin (12.04) to Trusty Tahr (14.04). We also finally drop support for Qt 4 variants with this.
> CI: Use Qt 5 and GCC 6 on Ubuntu CI builds

- src/citra_qt/debugger/profiler.cpp
This is a fix for PR #1785. The scaling was being done with the wrong value as a base, causing incorrect scale factors and unnecessary scaling in low-dpi screens. In addition, the window size wasn't being scaled, causing misalignment of screen elements.
cc @MerryMage
> Qt: Fix MicroProfile dpi scaling

- src/citra_qt/game_list.cpp
- src/common/file_util.cpp
- src/common/file_util.h
ForeachDirectoryEntry didn't actually do anything with the `recursive`
parameter, and the corresponding callback parameter was shadowing the
actual recursion counters in the user functions.
> Fix recursive scanning of directories

- src/common/logging/backend.cpp
- src/video_core/debug_utils/debug_utils.cpp
The r-value overload already gets selected, and the `std::move` technically inhibits copy elision.
> Remove superfluous std::move in return std::move(local_var)

- src/core/hle/kernel/thread.cpp
_Yet another alternative to #1868 and #1854_
#1854 doesn't resolve all related issues (such as #1861), ~~I'd like to close it later~~ closed.
I like the thought of #1868, but it seems that it needs to fix too much stuff, and more issues tend to occur when more changes are made.
So I want a simple, temporary fix to make citra works for most cases, before we rewrite the scheduler (if it is going to be).
The common issue of #1856 and #1861 is that the scheduler doesn't bother switching to the same thread. So the simple fix here is to switch to the same thread if needed (when the thread was waiting on objects), so that it can perform PC modification (causes of `ThrowFatelError` in #1856 and #1861), ~~pop from ready queue~~ change state to RUNNING (= mark the thread popped from ready queue, …
> Switch context to the same thread if necessary

- src/video_core/pica.h
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/pica_to_gl.h
Nuff' said.
More efficient implementations that use glScissor or multiple rectangles in the swrast can be done later.
> PICA: Implement scissor test

- src/core/hle/service/fs/fs_user.cpp
CreateLegacySystemSaveData
3dbrew says it is "obsolete", but it's used by the Music application.
> HLE/FS: Document some command parameters and implemented command 0x08560240

- src/citra_qt/CMakeLists.txt
- src/citra_qt/configure.ui
- src/citra_qt/configure_dialog.cpp
- src/citra_qt/configure_dialog.h
- src/citra_qt/configure_system.cpp
- src/citra_qt/configure_system.h
- src/citra_qt/configure_system.ui
- src/citra_qt/main.cpp
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/cfg/cfg.h
- src/core/hle/service/cfg/cfg_i.cpp
- src/core/hle/service/cfg/cfg_s.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
This PR should be reviewed commit per commit.
Here is explanation for each commit.
>Service::CFG: name sound output modes
>Service::CFG: add missing language
These are independent to the rest of commits. The enum members are used nowhere (even not in the following system settings configure tab, because it matches codes to combo box indexes directly). They are added there just for completeness.
Note that `SoundOutputMode` happens to be the same as [`DSP::HLE::DspConfiguration::OutputFormat`](https://github.com/citra-emu/citra/blob/master/src/audio_core/hle/dsp.h#L355-359). I still defined a separate enum, for the following reason:
- these two enum are too far away from each other in the code tree.
- they are not related in program logic. It is the game that relates them.
>Service::CFG: add …
> Implement config savegame editing & clean up

- externals/cmake-modules/FindSDL2.cmake
Citra uses the SDL2_DLL_DIR variable to copy the dll to the output directory on windows, however it is only set when using the bundled version of SDL2. 
Users that had CITRA_USE_BUNDLED_SDL2 set to false would have to copy the dll manually.
> Fixes SDL2.dll copy to bindir on windows

- src/core/core_timing.h
- src/core/hle/shared_page.cpp
- src/core/hle/shared_page.h
This implemented synchronizing the system time in the `SharedPage` with actual system time. According to [the reaserch](https://github.com/wwylele/ctrhwtest/tree/master/sharedpage), it is updated every hour on real 3DS. so implemented it the same way here. Also, the name of the first field of `SharedPage` was changed, for its behaviour on real 3DS.
When translating system time to 3DS format, I uses Jan 1, 2000 as an auxiliary epoch, for the following reason:
- it is a limit in real 3DS settings
- `epoch = 1970` for `time_t` is not a real standard, and one needs to deal with timezone when using it
- directly using `epoch = 1900` (real 3DS epoch) may result in invalid values, for it is before `time_t`'s epoch.
There is a known issue: game uses the formula `SharedPage.date_time + …
> Implement actual system time

- CMakeLists.txt
This option makes the generated binary crash with an illegal
instruction when the target CPU doesn’t support the SSE4.1 extension
(see #1968), with no noticeable performance increase compared to a
generic build.
> Remove the -msse4.1 on ¬MSVC

- src/common/emu_window.cpp
Fix for #1944 . I am very surprised nobody encounter this one so, I suspect this is only in Linux + Qt5.5.
When we call render_window->hide(), GGLWidgetInternal::resizeEvent() is called with a size of 0 which lead to EmuWindow::FramebufferLayout::DefaultScreenLayout having an assert on the width/height.
> Protection against a resize of size 0

- .travis-upload.sh
This PR addresses the issue of the nightly builds crashing on OS X #1929 #1932 #1958 #1221 .
So here's a little bit of analysis: the crashes occurred between citra-20160609-7139e63-osx-amd64 and citra-20160610-0c56c9f-osx-amd64. 
Which correspond to these two Travis builds: https://travis-ci.org/citra-emu/citra/jobs/136853816 https://s3.amazonaws.com/archive.travis-ci.org/jobs/136853816/log.txt and https://travis-ci.org/citra-emu/citra/jobs/136414732 https://s3.amazonaws.com/archive.travis-ci.org/jobs/136414732/log.txt.
And these two files: https://builds.citra-emu.org/citra/nightly/osx-amd64/citra-20160609-7139e63-osx-amd64.tar.xz (works) https://builds.citra-emu.org/citra/nightly/osx-amd64/citra-20160610-0c56c9f-osx-amd64.tar.xz (crashes).
The crash error messages addressed have these …
> Travis Build: OS X Startup Crash Fix

- src/citra_qt/Info.plist
The Info.plist template incorrectly uses parentheses instead of curly braces,
which means that building the .app bundle using regular 'make' results in the
variable not being replaced, and hence the app bundle won't start because the
executable name is incorrect.
This commit fixes this issue.
> CMake: Fix Info.plist template for citra_qt/OSX

- src/core/hle/service/apt/apt.cpp
In case the shared font file is missing, it seems better to log an error than to crash.
> Shared font file: Instead of segfaulting, log an error to remind the user to dump it

- .travis-deps.sh
- CMakeLists.txt
Qt 5.7 added a new check for c++11 compilers (see https://github.com/citra-emu/citra/issues/1931#issuecomment-229549577 for more information) which meant that because citra was setting the c++1y flag directly, cmake assumed that it needed to set c++11 on any target that linked to Qt. This broke the build whenever a c++14 feature was used on targets that linked against Qt. This change specifies that C++14 compilers are required, and it adds the -std=c++14 (or -std=gnu++14 for builds in gcc) flag on every build target.
> CMake: Fix for QT 5.7 overwriting -std=c++1y flag

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Related test: https://github.com/MerryMage/3ds-tests/tree/master/stm
`stmfd r13!, {pc}` currently stores the incorrect value to the stack (seems to always be `8`).
Correction for the ~~System~~ STM (User registers) version of the instruction (line 3231) based on manual.
> Dyncom: Correct implementation of STM for R15

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
In the case when RD === RN, RD was updated before AddOverflow was called
to check for an overflow, resulting in an incorrect state of the Q flag.
> dyncom: Read-after-write in SMLA

- src/core/hle/kernel/session.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/cam/cam.cpp
- src/core/hle/service/csnd_snd.cpp
- src/core/hle/service/srv.cpp
All the MoveHandleDesc and CopyHandleDesc usages were checked on hardware (client side).
TransferHandleDesc has been removed because it was wrong and duplicated CallingPidDesc.
I also added some utilities for a future IPC helper.
> fix #1942 and add a few IPC functions for descriptors

- appveyor.yml
This has been untested and no effort went into this :smiley: 
It has been blatantly stolen from the [AppVeyor docs](https://www.appveyor.com/docs/build-cache/)
It should reduce [problems like the inability to install WinSCP on the CRO merge] (https://ci.appveyor.com/project/bunnei/citra/build/1.0.3782#L1448)
However, I'm not sure if the cache is ever cleaned automaticly. So if WinSCP gets a more serious security update we'll probably have to do something?
> AppVeyor: Cache chocolatey packages

- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/bcfnt/bcfnt.cpp
- src/core/hle/service/apt/bcfnt/bcfnt.h
This allows a file dumped from either an o3DS or a n3DS (and potentially even an original unrebased file) to be used.
@endrift Can you test this with your file that didn't work before?
> Auto-detect original shared_font.bin memory base

- src/video_core/renderer_opengl/gl_shader_gen.cpp
Apparently kids these days don't know how to code.
This error came up so often on the forums that I felt like it was easier to finally push my ~~fix~~ workaround for it, instead of telling them what to do again (which usually resulted in more questions).
---
Essentially all this does is add a dummy zero constant into the shader in case of an unimplemented branch (which still gives a critical log error).
This avoids generating invalid shaders which would stop execution due to the uniform block size mismatch.
IIRC there is a similar case elsewhere in that code but I don't remember exactly. If the error comes up on the forums again I'll be here with a follow-up PR.
---
This shouldn't really change anything aside from preventing a ~~crash~~ failed assertion on entering World 1-1 in Super …
> OpenGL: Avoid error on unsupported lighting LUT

- src/audio_core/audio_core.cpp
- src/audio_core/audio_core.h
- src/audio_core/hle/dsp.cpp
- src/audio_core/hle/dsp.h
- src/audio_core/null_sink.h
- src/audio_core/sdl2_sink.cpp
- src/audio_core/sdl2_sink.h
- src/audio_core/sink.h
- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/citra_qt/configure_audio.cpp
- src/citra_qt/configure_audio.ui
- src/core/settings.cpp
- src/core/settings.h
Time-stretching was a post-processing effect to adjusts audio speed to match emulation speed, helping prevent audio stutter. This comes at the cost of extra variable audio latency (currently approximately 100 to 300 milliseconds + additional audio-pipeline delay).
This PR provides a user-configurable option to disable this post-processing effect. This removes the artificial audio latency at the cost of stutter if emulation speed strays above or below 100%.
This PR consists of three commits:
* Changes the interface of `AudioCore::Sink` to accept a pointer instead of a `std::vector`.
* Implementing non-stretched audio.
* Exposing a configuration option.
> User-configurable option to enable/disable time-stretching of audio

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra/emu_window/emu_window_sdl2.cpp
- src/citra_qt/CMakeLists.txt
- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
- src/citra_qt/config.cpp
- src/citra_qt/configure.ui
- src/citra_qt/configure_debug.cpp
- src/citra_qt/configure_debug.ui
- src/citra_qt/configure_dialog.cpp
- src/citra_qt/configure_general.cpp
- src/citra_qt/configure_general.ui
- src/citra_qt/configure_graphics.cpp
- src/citra_qt/configure_graphics.h
- src/citra_qt/configure_graphics.ui
- src/citra_qt/main.cpp
- src/core/settings.h
- src/core/system.cpp
- src/core/system.h
- src/video_core/video_core.cpp
Adds a new tab to the Qt Configuration UI for graphics settings, and moves relevant settings there. Also adds a setting to enable V-Sync, mostly just as a quick & easy frame limiter until we have a better solution. Obligatory screenshot:
> Qt graphics configure & V-Sync option

- appveyor.yml
While we're cutting down on archive sizes...
> appveyor: Remove tests.exe and tests.pdb from archive

- appveyor.yml
In relation to https://github.com/citra-emu/citra/pull/2037 it seemed like the consensus was RelWithDebInfo doesn't add much and it'd be better to just move the pdb files to a separate zip if they are needed for that build.
This PR uploads them to a different directory, but that dir may not exist on the build server. That may require manual intervention.
> Create a separate archive for debug symbols on windows

- CMakeLists.txt
The builds used to contain pdb information, and while it compresses well, it takes up too much bandwidth to host. Developers can use the RelWithDebInfo to get a fast build with debugging symbols. This should reduce build size on windows from roughly 12MB compressed to 7MB.
> MSVC: Add RelWithDebInfo and removing debugging from Release.

- .travis-build.sh
- .travis-deps.sh
- .travis.yml
Xcode 7.3.1 provides a compiler with better C++14 support compared to [Xcode 6.1](https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions) which Travis uses by default.
Had to remove `xcpretty` (log prettyfier) because the version of Ruby provided on these images was segfaulting!
I've set `MACOSX_DEPLOYMENT_TARGET=10.9` so we're still producing a OS X 10.9 compatible build despite using a 10.11 build machine.
> travis: Update to XCode 7.3.1

- src/audio_core/codec.cpp
> codec: Fix ADPCM distortion caused by incorrect nibble order

- src/audio_core/hle/dsp.cpp
- src/audio_core/sdl2_sink.cpp
Fiddling with numbers.
Outputting 1024 samples and dropping samples after 1024 gave pretty much no slack to timing issues.
> audio_core: Tweak audio latency

- src/citra_qt/configure_system.cpp
Fix a bug in #2044 and a hidden bug long ago (Sorry!). ~~The birthday combo box didn't get filled properly because the signal-slot connection was performed after reading system setting data. Now the connection is moved to the ui file. the code order is changed. Also explicitly update the combo box in `ReadSystemSetting` because `setCurrentIndex` won't always emit `currentIndexChanged` - if `setCurrentIndex` sets the same index as it was (in this case, if the birthday is in January), `currentIndexChanged` won't be emitted.~~
The old bug: when the birthday is in January, `setCurrentIndex` in `ReadSystemSetting` won't emit `currentIndexChanged` because the index doesn't actually get changed, resulting birthday combo box unfilled.
Bug in #2044, the `ReadSystemSetting` call moves before the …
> Qt: fix birthday combo box updating

- src/video_core/shader/shader_interpreter.cpp
The static meant that after the first execution, these lambda context
would be pointing to a random location on the stack. Fixes a random
crash when using the interpreter.
> VideoCore: Fix dangling lambda context in shader interpreter

- .travis-deps.sh
Probably due to additional Travis caching, cmake is now already
installed when the script runs. This causes the unlink to remove the
symlink to the executable, which is then not re-added by the install
(since it's already installed).
> Travis: Fix OS X build

- .travis-build.sh
Fixed:
- When clang-format found a problem, `diff` would return non-zero which terminated the build, before even print the lint.
- If a PR didn't change any source code (like this), `git diff ` would return non-zero which terminated the build.
> Fix clang-format lint

- src/citra_qt/main.cpp
Always shutdown the system whenever `LoadROM` fails. (partially) fixes #1965.
> Qt: shutdown system if error on loading ROM

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
> OpenGL: Take cached viewport sub-rect into account for scissor

- src/core/hw/gpu.cpp
- src/core/memory.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
Sorry for putting many things into one PR. But there are so many issues at the same place, so I prefer working on them together.
This PR should be reviewed commit by commit:
- `rasterizer: separate TextureCopy from DisplayTransfer` & `gpu: move MemoryFill, TextureCopy and DisplayTransfer into functions`: the original code indented too much to read. Split them into different functions
- `gpu: add validity check for TextureCopy, DisplayTransfer and FillMemory`: an alternative to #2078 & #2057. IMO all validity check should be performed before dispatching to rasterizer. I still didn't do hardware test for these though. Hardware tests can be done after this cleanup.  
-  `memory: fix IsValidVirtualAddress for RasterizerCachedMemory`: bonus from the commit above
-  ` gpu: keep the old signal …
> GPU: DisplayTransfer & MemoryFill cleanup and param check

- src/core/file_sys/archive_backend.h
- src/core/file_sys/disk_archive.cpp
- src/core/file_sys/disk_archive.h
- src/core/file_sys/ivfc_archive.cpp
- src/core/file_sys/ivfc_archive.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
Found this unimplemented when writing toys for 3DS file system. So I implemented it, and tested it with my toys against real 3DS.
I plan to clean up all FS error codes in the future, so leave the `// TODO: verify description` for now.
> FS: implement DeleteDirectoryRecursively

- src/citra_qt/CMakeLists.txt
- src/citra_qt/debugger/wait_tree.cpp
- src/citra_qt/debugger/wait_tree.h
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/core/hle/kernel/event.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.h
- src/core/hle/svc.cpp
I just found this in the TODO list and gave a try. 
How it looks:
When game is paused, it lists all threads, and show their status and what are they waiting for (recursively).
Needs more testing, because I don't have many games to test all cases.
Also please help improve the expression in the "tree view" (list view in fact)
If this is what it supposed to be, I will also try implementing other debugger.
> Debugger: implement wait tree widget

- src/common/vector_math.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader_interpreter.cpp
Stopping on a GPU breakpoint at certain points of Mii Maker causes a crash in the vertex shader interpreter as it tries to produce debug info using bogus vertex data. This fixes a bug which happens to stop triggering the crash, though the root causes (the debug info is generated even without valid vertex/shader data and the interpreter doesn't do proper bounds checks of data generated by the shader) remain.
> Fix/mask crash in shader debugger in Mii Maker

- src/core/gdbstub/gdbstub.cpp
IDA Pro don't add ":" to "qSupported", so, gdbstub don't send back target.xml with register descriptions, and we can't see status bits.
before PR:
after:
> Small fix to let IDA see target.xml

- src/core/hle/service/nwm_uds.cpp
Just make my comment in #2041 into a PR. I did more research after that comment but didn't get more useful result. Since the network isn't going to be implemented any time soon, it is better to prevent games from using it.
Here is [the hwtest to get the error code](https://github.com/wwylele/ctrhwtest/tree/master/network-init) (turn off wifi and run)
> NWM: stub Initialize with an error

- README.md
Update donation info in the readme as it is currently directing to a dead link. Info was adapted from: https://citra-emu.org/page/donate
Also made a couple of minor grammatical changes.
> Update Donation Info in Readme

- .travis-deps.sh
Removes cmake from the install list. Cmake now up to date on the new travis mac image meaning brew install cmake would throw an error. Doing `--force` means force reinstalling it every build, and ignoring error codes means that you potentially will miss other build breaking errors that could occur at this phase.
> Fix Travis build issue on mac

- src/core/hle/applets/erreula.cpp
- src/core/hle/applets/mii_selector.cpp
- src/core/hle/applets/swkbd.cpp
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/apt.h
Names now make sense and match 3dbrew.
> APT/Applets: Renamed the members of the SignalType enum.

- src/video_core/command_processor.cpp
We don't need to perform this loop if the CiTrace recorder is not enabled.
> GPU/CiTrace: Avoid calling GetTextures() when not necessary.

- src/audio_core/sdl2_sink.cpp
Today I noticed that we don't log properly audio errors, this PR should help in situations like https://github.com/citra-emu/citra/issues/2205
> Improve verbosity of audio errors

- src/core/hle/service/cfg/cfg.cpp
This is found needed by Pokemon games, which also causes a freeze at intro in Pokemon Sun/Moon:
```
[ 723.289812] Service.CFG <Error> core/hle/service/cfg/cfg.cpp:GetConfigInfoBlockPointer:285: Config block 0x90000 with flags 2 and size 8 was not found
```
From observation of a config file dumped from my 3DS, 0x90000 and 0x90001 blocks has exactly the same size(8), flags(0xE) and contents, so my theory is these two blocks are duplicated from the same data. Needs to confirm.
One need to remove the pre-existing config file to test this.
> cfg: add config block 0x00090000

- README.md
Change "OS X" to "macOS" as Apple no longer uses the OS X branding as of 10.12. Also update the wiki page link as it broke with the new title.
> Change "OS X" to "macOS" in the Readme

- .travis-deps.sh
- CMakeLists.txt
I cannot change the title of the post, **also TRAVIS is affected by this change**  (*).
This PR is following https://github.com/citra-emu/ext-windows-bin/pull/4 and targeting issue https://github.com/citra-emu/citra/issues/2189
Now there is support for audio capture.
I tested this with 2 different games, it would be useful to have more feedback.
Ideally this should be the only version of SDL kept in the build folder, in practice I didn't have any problem.
(*) or at least should be.
> Windows, move to SDL2-2.0.5

- .travis-upload.sh
- .travis.yml
@archshift has been MIA for a while, so our builds server is currently
down. Furthermore, uploading is broken in both Linux and macOS:
- The version of lftp in Trusty doesn't support the sftp:auto-confirm
option, which means that uploading would hang, even if the server
weren't down. It currently tries to connect forever and fails the
build with a timeout.
- lftp was removed from Homebrew, so it wasn't being installed on macOS
and invoking it just failed.
> Travis: Remove build uploading

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/memory.cpp
- src/core/memory.h
Subv commented that this was something left out from the original jit pr. Dynarmic has a fast path for memory access if you expose the memory backing the page table, and will gracefully fall back to calling citra's memory read and writes if the pointer at that addess is null. See here for the implementation: https://github.com/MerryMage/dynarmic/blob/master/src/backend_x64/emit_x64.cpp#L1863
This is just a simple fix that adds a method to return the array that backs the page table's memory.
> Expose page table to dynarmic for optimized reads and writes to the JIT

- src/common/common_paths.h
- src/common/file_util.cpp
- src/common/file_util.h
Hello, this is my first PR, I tried to address #2177 and move the default location of the "user" folder to AppData/Roaming/Citra Emulator/(*).
If there is a "user" folder next to citra executable, that folder will take priority (portable mode).
Configuration changes should be handled with care to avoid problems between different versions.
Also note that SHGetKnownFolderPath works only on Windows Vista and later.
Thanks to @linkmauve for the suggestions he gave me yesterday.
Let me know what you think.
(*) After a bit of discussion we decided for Roaming instead of Local.
> Change "user" folder default location to AppData/Roaming/ on Windows systems

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/mic_u.cpp
- src/core/hle/service/mic_u.h
It's just stub to avoid errors, related with not mapped memory and not created event.
after update to SDL 2.0.5 (current release) will be possible to implement audio capturing
> MIC_U: Stub service funcions

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_state.cpp
This fixes the lingering outlines in Pokemon and other games.
> Rasterizer/Memfill: Set the correct stencil write mask when clearing the stencil buffer.

- src/common/key_map.cpp
- src/video_core/rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
Many more remain.
A lot of them are generated by nihstro, specifically this line: https://github.com/neobrain/nihstro/blob/9f7bf870815c6bc6bdb4e86cbc2d1de80daf141b/include/nihstro/shader_bytecode.h#L764 (Int to Bool coercion)
> Build: Fixed a few warnings.

- .travis-build.sh
- .travis-deps.sh
- .travis.yml
- src/video_core/pica.h
We were using a SVN version of clang-format (due to the stable repo not being whitelisted by travis) which may change randomly and break our formatting/build. Changed to manually install a stable version using sudo.
> Travis: Use a stable version of clang-format

- src/video_core/shader/shader_jit_x64.cpp
There was a bug in the fallback path for FLR (Floor shader instruction) which would respect the current rounding mode instead of actually truncating.
As only non-SSE4.1 CPUs were affected by this broken fallback path the issue reports we got were pretty confusing. We should probably add detected CPU features to our log files in the future.
This was responsible for #2209 and #1743 .
I did not check the other fallback paths yet. But I'll make sure to test all paths in any shader-jit issue we'll receive in the future.
> shader_jit: Fix non-SSE4.1 path where FLR would not truncate

- src/core/hle/service/gsp_gpu.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
First commit is the actual fix. Others are small cleanups/ticking-time-bomb bugfixes.
Fixes #2246, #2261.
> OpenGL: Fix DisplayTransfer accel when input width != output width

- CMakeLists.txt
Microprofile currently has a number of issues on Mingw that (at least, to my eye) would require a major reworking of how it internally works. This PR disables Microprofile on Mingw builds so that they are actually usable.
As of now, Citra (Mingw) crashes when attempting to load a game, with an assertion error @ [externals/microprofile/microprofile.h, line 1177](/citra-emu/citra/tree/master/externals/microprofile/microprofile.h#L1177). Furthermore, much of the timing components of Microprofile do not actually work regardless of this assertion. The rewrite of Microprofile (assuming it fixes this bug) isn't an option at this point due to its lack of a non-web UI.
> Disable Microprofile on Mingw builds

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_util.cpp
We recently had a lot of issues with people reporting "Uniform block size did not match!" which usually has one of 3 reasons:
- A broken shader (= compilation fails due to us not having implemented a certain codepath). The block size will be 0.
- Broken code / Alignment issues. This can happen if the last element is not 16 bytes in size (as the spec is unclear wether the block size will be aligned to the next 16 byte block or truncated). The block size will vary a little.
- A broken driver. The block size could vary greatly depending how it intepreted our shader. This should rarely happen.
To show these kind of errors better, the `ASSERT_MSG` was extended to show the expected and received block size.
Additionally the shader source code will be `LOG_ERROR`'d in case of program linking …
> Print shaders in case of error

- src/core/CMakeLists.txt
- src/core/file_sys/archive_other_savedata.cpp
- src/core/file_sys/archive_other_savedata.h
- src/core/file_sys/archive_savedata.cpp
- src/core/file_sys/archive_savedata.h
- src/core/file_sys/archive_source_sd_savedata.cpp
- src/core/file_sys/archive_source_sd_savedata.h
- src/core/file_sys/errors.h
- src/core/hle/result.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
This allows games / applications to access a save data archive that belongs to others. 
There are two types of such save data archive: 
- `OtherSaveDataGeneral` is often used by save manager application or homebrew save editors. An application needs some special bits set in the exheader to access this archive type. With this archive type the application can read/write any save data stored in SDMC or in the game card. A tested case is my [FS tester](https://github.com/wwylele/3DS-FS-Tester) ([compiled version](https://github.com/wwylele/3DS-FS-Tester/releases/download/1.0/wwylele_fs_tester.cxi)) (Note that the program uses software keyboard to input commands, so you may want to merge [this commit](https://github.com/wwylele/citra/commit/0baf9f8fb6f0cd160d735c59d44a43d005539e2d) so that you …
> FS: implement archives for other game save data

- src/core/file_sys/archive_extsavedata.cpp
- src/core/file_sys/archive_ncch.h
- src/core/file_sys/archive_romfs.h
- src/core/file_sys/archive_sdmc.h
- src/core/file_sys/archive_sdmcwriteonly.h
- src/core/file_sys/archive_systemsavedata.h
- src/core/file_sys/path_parser.h
- src/core/file_sys/savedata_archive.h
Prevents implicit conversions.
> file_sys: Make a few single-argument constructors explicit

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
This OpenGL call synchronize the worker thread of the nvidia blob.
It can be verified on linux with the __GL_THREADED_OPTIMIZATIONS=1 environment variable.
Those errors should not happen on tested drivers.
> Drop framebuffer completeness check.

- src/core/CMakeLists.txt
- src/core/hle/service/mvd/mvd.cpp
- src/core/hle/service/mvd/mvd.h
- src/core/hle/service/mvd/mvd_std.cpp
- src/core/hle/service/mvd/mvd_std.h
- src/core/hle/service/qtm/qtm.cpp
- src/core/hle/service/qtm/qtm.h
- src/core/hle/service/qtm/qtm_s.cpp
- src/core/hle/service/qtm/qtm_s.h
- src/core/hle/service/qtm/qtm_sp.cpp
- src/core/hle/service/qtm/qtm_sp.h
- src/core/hle/service/qtm/qtm_u.cpp
- src/core/hle/service/qtm/qtm_u.h
- src/core/hle/service/service.cpp
Adds the two New3DS-only modules.
Just adds the submodules that have any uncovered commands.
> service: Add mvd and qtm services

- src/core/hw/gpu.cpp
We were writing 4 times as much data, and thus reading (and writing) garbage to the linear heap when replaying the traces with the citrace player.
> Fixed the gpu command list size when creating CiTraces.

- src/core/CMakeLists.txt
- src/core/hle/service/ptm/ptm.cpp
- src/core/hle/service/ptm/ptm_gets.cpp
- src/core/hle/service/ptm/ptm_gets.h
- src/core/hle/service/ptm/ptm_play.cpp
- src/core/hle/service/ptm/ptm_play.h
- src/core/hle/service/ptm/ptm_sets.cpp
- src/core/hle/service/ptm/ptm_sets.h
- src/core/hle/service/ptm/ptm_sysm.cpp
- src/core/hle/service/ptm/ptm_sysm.h
- src/core/hle/service/ptm/ptm_u.cpp
- src/core/hle/service/ptm/ptm_u.h
So it appears that Nintendo decided to have two services specifically for getting and setting system time because Nintendo.
It also turns out that several other PTM services have access to ptm:u's command set.
ptm:s is also apparently an exact alias for ptm:sysm.
This is based off documentation on 3dbrew, of course.
> service: Minor PTM changes

- src/core/hle/service/ptm/ptm.cpp
The third parameter of Write is actually a bool type, not an int.
> ptm: Use boolean instead of integral value

- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/apt.h
This PR do not provide startup argument for applications at all instead of garbage
Partially fix **Inazuma Eleven 3: won't boot** #2030 (Now it shows LEVEL 5 logo before stuck)
> APT::GetStartupArgument: force clear startup argument

- src/citra/citra.cpp
- src/citra/citra.rc
- src/citra_qt/citra-qt.rc
- src/common/bit_set.h
- src/common/logging/text_formatter.cpp
- src/common/string_util.cpp
- src/common/thread.cpp
- src/common/timer.cpp
- src/core/gdbstub/gdbstub.cpp
This involves 3 kind of changes:
- Lowercase spelling for includes (`Windows.h` and `WinSock2.h`)
- Use of gcc intrinsics (Old check was for `_WIN32`, not the compiler)
- Use of forward slashes as path seperator (present in *.rc files, used for exe icon path)
Additionally I decided to update the icon name in the rc files.
One was kind of arbritrary, the other one referenced GLFW which we aren't even using anymore.
---
This currently does not pack SDL2 or Qt5 dependencies properly (which is done conditionally for MSVC builds). I intend to do this in a follow-up PR as we still have various Qt version checks which I'd like to remove anyway (as chances are very slim we'll ever support Qt4 or below again).
It's also not a cross-compile issue, but rather a lack in the original mingw support.
> Support mingw cross-compilation

- src/tests/CMakeLists.txt
```
$ (cmake -DENABLE_SDL2:BOOL=false /path/to/citra; gmake)
[...]
[ 85%] Linking CXX executable tests
../common/libcommon.a(microprofile.cpp.o): In function `MicroProfileThreadStart(pthread**, void* (*)(void*))':
src/common/microprofile.cpp:(.text+0x41): undefined reference to `pthread_create'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```
> Unbreak QT-only build after 75ee2f8c6702

- CMakeLists.txt
This removes the need for manually setting the CXX flags (cf. https://github.com/citra-emu/citra/wiki/Building-For-Linux#building-citra) as well as allowing macOS users to build with gcc.
> CMakeLists: Autodetect clang and only then use libc++

- src/citra_qt/debugger/wait_tree.cpp
- src/core/CMakeLists.txt
- src/core/hle/ipc.h
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_port.h
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/client_session.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/result.h
- src/core/hle/service/apt/apt.h
- src/core/hle/service/apt/apt_a.cpp
- src/core/hle/service/apt/apt_s.cpp
- src/core/hle/service/apt/apt_u.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/soc_u.cpp
- src/core/hle/service/srv.cpp
- src/core/hle/svc.cpp
This is an overhaul of #1911 and a continuation of #1842
This PR is part of an ongoing effort to implement multiprocess support in Citra.
All handles obtained via srv::GetServiceHandle or svcConnectToPort are references to ClientSessions.
Service modules will wait on the counterpart of those ClientSessions (Called ServerSessions) using svcReplyAndReceive or svcWaitSynchronization[1|N], and will be awoken when a SyncRequest is performed.
All IPC parameter translation for LLE modules will happen inside the implementation of svcReplyAndReceive, this is not implemented in this PR.
All IPC parameter translation for HLE modules should happen in the SessionRequestHandler class, this is not implemented in this PR.
HLE Interfaces are no longer kernel objects, and now derive from …
> Kernel/IPC: Use Ports and Sessions as the fundamental building block of Inter Process Communication.

- .gitmodules
- CMakeLists.txt
- externals/CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/x64/xbyak_abi.h
- src/common/x64/xbyak_util.h
- src/video_core/CMakeLists.txt
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64.h
~Currently this crashes because the Citra and Dynarmic versions of Xybak conflict and cause ODR violations. Use merrymage/dynarmic#62 to fix this.~ Since merged and added to the PR.
Unified diff is probably more pleasant than Split for this one. I tried to keep this code a straight semantic port from the previous one. I'll make some cleanups in following PRs.
> Convert shader JIT to Xbyak

- src/video_core/command_processor.cpp
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
This does, in fact, remove instructions from the code, but I haven't checked if it's actually discernibly faster.
> VideoCore: Eliminate an unnecessary copy in the drawcall loop

- src/core/memory.cpp
This prevents individual writes touching a cached page, but which don't
overlap the surface, from constantly hitting the surface cache lookup.
Fixes extreme slowdown in Bravely Default intro video exposed by #2266.
> Memory: Always flush whole pages from surface cache

- src/video_core/shader/shader_jit_x64.cpp
> shader_jit_x64: Use LOOPCOUNT_REG as a 64-bit reg when indexing

- src/core/arm/dyncom/arm_dyncom_trans.h
- src/core/hle/service/dlp/dlp.h
- src/core/hle/service/srv.h
Three more files missing header guards.
> core: Add missing #pragma once directives where applicable

- src/core/hle/service/hid/hid.cpp
float literals need to have the 'f' prefix.
> hid: Get rid of a double -> float truncation warning

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/skyeye_common/armstate.cpp
- src/core/core.cpp
- src/core/gdbstub/gdbstub.cpp
- src/core/gdbstub/gdbstub.h
Currently, this is only ever queried, so adding a function to check if the server is enabled is more sensible.
If directly modifying this externally is ever desirable, it should be done by adding a function to the interface, rather than exposing implementation details directly.
> gdbstub: Remove global variable from public interface

- src/core/hle/service/fs/archive.cpp
`GetTypeName()` is not a member anymore.
`LOG_TRACE` often hides mistakes ...
> Fix debug build from #2249

- src/common/file_util.cpp
A regrettably ugly fix for an asinine but seemingly unavoidable issue.
> Common: Fix gcc build on macOS

- src/citra_qt/debugger/wait_tree.cpp
- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/svc.cpp
Threads will now be awakened when the objects they're waiting on are signaled, instead of repeating the WaitSynchronization call every now and then.
The scheduler is now called once after every SVC call, and once after a thread is awakened from sleep by its timeout callback.
This new implementation is based off reverse-engineering of the real kernel.
See [here](https://gist.github.com/Subv/02f29bd9f1e5deb7aceea1e8f019c8f4) for a more detailed description of how the real kernel handles rescheduling.
Fixes #2125 even with @neobrain's changes.
Fixes #2091
Fixes #2119 
Fixes #2028 
Fixes #2026
Fixes #2041
These changes provide a more stable framework for implementing #1904. I actually have an implementation in mind already, following what the real kernel does.
This PR will make it much easier …
> Threading: Reworked the way our scheduler works.

- src/core/hle/kernel/kernel.cpp
This is a regression from #2260 . I don't know if this is a proper fix. @Subv if you are going to fix this in a better way, feel free to close this.
The issue itself appears in the following scenery:
A thread calls `WaitSynchN` on two events A and B with `wait_all = false`. Then the events A signals, waking up the thread. The thread then immediately executes to the end and `Stop` itself. Note that because it is in the `wait_all=false` situation, the thread didn't record the objects it was waiting on, therefore it can't remove itself from B's list. Now the thread is in DEAD status, and B signals. B still think the thread is alive, and continue to get it by `GetHighestPriorityReadyThread`. Since the thread is dead and cannot be resumed, it remains in B's list forever, resulting in an …
> Kernel: remove object's waiting thread if it is dead

- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
- src/citra_qt/game_list_p.h
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/core/file_sys/archive_source_sd_savedata.cpp
- src/core/file_sys/archive_source_sd_savedata.h
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
What changed:
* Added `Loader::GetProgramId`.
* Added static function `ArchiveSource_SDSaveData::GetSaveDataPathFor`.
* Added signal `GameList::OpenSaveFolderRequested`.
Issues that arose:
* The least messy way I could think of to expose a way to get the save data path was to implement a static function.
* I really really wanted to use a `boost::optional<u64>` to represent the `program_id` since not all formats have a program id.
Screenshot:
> game_list: Add a context menu with "Open Save Location"  option

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
Currently we leave all dead thread in the `thread_list` and never remove them until exiting the game. This has a significant impact on game that loves to create small threads frequently (such as Pokemon Sun, which creates thousands of threads in 10 minutes). In this case, the `thread_list` grows up quickly and slows down all functions that iterating over the list, as users reported "games slow down after an hour".
I did a profiling on Pokemon running for 40 minutes, with the character standing there without any input. The frame rate drops from 25 FPS at the beginning to 20 FPS at the end. The profiling shows a time difference spending on a function between the beginning and the end:
The first 5 minutes:
The last 5 minutes:
The profiling results after the change shows no difference in the …
> Thread: remove the thread from the thread list when exiting

- src/core/memory.cpp
Reverts citra-emu/citra#2321
This introduced a pretty big performance regression, at least with my game library. It's most pronounced in ZMM w/ GCC (see bleeding edge build 94 - with the change, vs. 99 - without the change). Some of the other games I tested are less affected. Microprofile is broken on GCC, and I just tested this with bleeding edge, so I'm not really sure the exact bottleneck - needs more investigation before we reintroduce the change (or a similar one).
> Revert "Memory: Always flush whole pages from surface cache"

- src/citra_qt/main.cpp
*Fixed game_list focus issue.
previously, if we pressed down/up +enter after game started, the game list would load the previous/next game from list. setting focus on render_window fixes this issue.
> Fixed game_list focus issue.

- src/video_core/renderer_opengl/gl_rasterizer.cpp
See #2219.
I couldn't find any other instances of using true/false when setting a GLboolean / calling a function that takes GLboolean.
> Use GL_TRUE when setting color_mask

- src/citra_qt/main.cpp
- src/citra_qt/main.h
Makes the initialization process a tad easier to grok, since the constructor isn't just a glob of random unrelated behaviors.
> citra-qt: Move bits of constructor behavior to named functions

- src/citra_qt/debugger/disassembler.h
Breakpoints has been const correct with regards to what the DisassmblerModel needs for quite a while now.
> disassembler: Remove mutable specifier from breakpoints member variable

- src/common/file_util.cpp
This is a regression from 707cc66362e613925bbdd0c2abed7959a42decad (#2343). The regression only effects Linux and MacOS version. The sysdata directory was removed, which causes that shared_font can't be found. Also, on the Windows version, sdmc and nand directory are assigned twice.
> file_util: fix missing sysdata path

- src/core/core.cpp
Yet another regression from #2343 (232ef55c1a13552e5ba8b72d61d1d072f5851598, issue #2373). `cpu_core` doesn't get reset when shutting down, causing `IsPoweredOn(){return cpu_core != nullptr;}` not working properly. I kind of want to restore the old `bool is_powered_on;` method, but not sure.
_Three regressions from one PR is ridiculous._
> Core: reset cpu_core in Shutdown to make IsPoweredOn work properly

- src/video_core/renderer_opengl/gl_shader_gen.cpp
This fixes the broken lighting in Zelda: ALBW (As reported by Migue via Discord).
**Broken (master):**
**Fixed (this PR):**
---
The error is caused by a wrapping of the texture in `LUT[4]` (`GL_TEXTURE_7`) where the red channel (so `texture(LUT[4], index)[0])` will be a ramp from 0.0 to 1.0 accross its width of 256 pixels.
Hence turning samples at texcoord 0.0 into the value 0.5 (average of 0.0 (left border) and 1.0 (right border)).
Note that this also removes the scaling with `255.0/256.0` (`FLOAT_255`) because I'm not sure what it was supposed to do (as offsetting from 0.0 wasn't done and scaling would have to be done using: *stupidme* check what yuriks wrote below for the proper formula).
All of the clamping has been moved into the texture object now which means we can simplify the …
> Lighting LUT Quickfix

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/citra_qt/configure_general.cpp
- src/citra_qt/configure_general.ui
- src/citra_qt/configure_system.ui
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/cfg/cfg.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
- src/core/settings.h
Added an option to auto-select region based on game region lockout info. System language will also be override if the region is auto-selected and the chosen language is not available. Also made this option as default value. This aims to reduce false positive caused by selecting a wrong region.
~~I'd like to add a prompt that the system language setting may be overrided. but not sure how to add it (add a tooltip?or make a description bar on the bottom of the configuration dialog?)~~ Added a tooltip
> Config: auto-select region and language

- .gitignore
- .travis-upload.sh
- .travis.descriptor.json.in
- .travis.yml
- CMakeLists.txt
- appveyor.yml
In an effort to get nightly builds back online, I went and found two providers for nightly builds. The first is bintray, a site that has an OSS plan with 1TiB bandwidth and both travis and appveyor can upload to it directly. Additionally, I got permission to upload to fosshub as well, which can provide us upwards of 5TiB a month, but they do not use any deploy scripts to upload (so no changes for this pr), and I will be working directly with the fosshub account in order to get the nightly builds hosted on there as well. 
One thing to note with this PR, I have added Appveyor artifacts, meaning each pull request will be built and stored in Appveyor. There is some argument about whether we should somehow disable this as it poses a security concern if someone submits a malicious PR and tricks …
> Add deploy to bintray for builds to master

- .travis.yml
- appveyor.yml
Bintray is rejecting the key that travis is sending, so i tried to reencrypt it. If this fails we'll need to wait for bunnei to reencrypt the bintray api key.
I was considering just pushing this to master directly, but I wasn't sure if that would trigger the build bots, so i will just pr it and instamerge this.
Also changes appveyor to upload to a long git hash (since travis is stuck uploading to the full hash name)
> Try a different encrypted bintray api key for travis.

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/nfc/nfc.cpp
- src/core/hle/service/nfc/nfc.h
- src/core/hle/service/nfc/nfc_m.cpp
- src/core/hle/service/nfc/nfc_u.cpp
- src/core/hle/service/service.cpp
This PR mostly for pass Fatal Error in game **Mini-Mario & Friends - amiibo Challenge** (no amiibo emulating, so, no way to pass amiibo scanning)
> Service/NFC: stub GetTagInRangeEvent

- .travis.yml
- appveyor.yml
Travis doesn't seem to want to deploy on tag and I saw travis' commandline script generate this on: block so it might be a viable alternative.
Also adds more information to the releases page.
> Change travis to deploy on push to citra-nightly. 

- src/citra_qt/debugger/wait_tree.cpp
- src/core/hle/kernel/event.cpp
- src/core/hle/kernel/event.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/mutex.h
- src/core/hle/kernel/semaphore.cpp
- src/core/hle/kernel/semaphore.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/timer.cpp
- src/core/hle/kernel/timer.h
- src/core/hle/svc.cpp
Not all syscalls should cause reschedules, the first commit attempts to remedy that, however, it still does not cover all cases.
See https://github.com/Subv/citra/issues/7 for progress on what's being done..
The other commits implement mutex priority inheritance as per the 3DS's kernel. The implementation is based on reverse engineering of the kernel.
Fixes #2395 
Fixes #2360
A commit by commit review of this should be easier.
> Kernel: Mutex priority inheritance and synchronization improvements.

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
Pretty self-explanatory, we won't be using these again.
> Kernel: Remove some unused functions.

- src/core/hle/kernel/semaphore.cpp
The regression was caused by a missing check in #2260.
The new behavior is consistent with the real kernel.
> Kernel/Semaphore: Fixed a regression in semaphore waits.

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
With this we avoid an useless temporary deschedule of the current thread.
Closes #2383
> Don't yield execution in SleepThread(0) if there are no available threads to run

- src/citra/emu_window/emu_window_sdl2.cpp
- src/citra/emu_window/emu_window_sdl2.h
- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
- src/common/CMakeLists.txt
- src/common/math_util.h
- src/common/quaternion.h
- src/common/thread.h
- src/common/vector_math.h
- src/core/CMakeLists.txt
- src/core/frontend/emu_window.cpp
- src/core/frontend/emu_window.h
- src/core/frontend/motion_emu.cpp
- src/core/frontend/motion_emu.h
As a continuation of #1549.
This is a relatively old branch of mine, which still contains problems. But I want to PR this before it  becomes completely stale, and discuss some questions below.
Usage: move mouse in the emulation window while holding the right button.
It emulates the accelerometer and gyroscope in a very limited range: it can only tilt in the direction of mouse movement, no rotate about the vertical (y) axis, and no linear acceleration. I also limited the tilt angle to be less than 90 degree, because I received reports saying that freeing the range to 180 degree will confuse the user (I also felt that when testing).
I don't have many games using motion sensor, so not sure if there is other common motion should be emulated.
In `EmuWindow`, gyroscope data is "stretched" …
> Emulate motion sensor in frontend

- appveyor.yml
Appveyor currently errors out when pushing to master because it attempts to upload the artifacts to github, but github rejects the key (as that key is is only for citra-nightly and citra-bleeding-edge)
https://ci.appveyor.com/project/jroweboy/citra/build/1.0.266#L1785 is what the appveyor output looks like on push to master.
> Prevents appveyor from attempting to deploy except on the nightly repo

- src/citra_qt/configure_general.ui
- src/citra_qt/configure_graphics.ui
- src/citra_qt/configure_input.ui
Warnings fixed:
```
C:\projects\citra\src\citra_qt\configure_graphics.ui : warning : The name 'verticalLayout_2' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_21'. [C:\projects\citra\build\src\citra_qt\citra-qt.vcxproj]
C:\projects\citra\src\citra_qt\configure_graphics.ui : warning : The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_31'. 
C:\projects\citra\src\citra_qt\configure_input.ui : warning : The name 'label_34' (QLabel) is already in use, defaulting to 'label_341'. [C:\projects\citra\build\src\citra_qt\citra-qt.vcxproj]
C:\projects\citra\src\citra_qt\configure_input.ui : warning : Z-order assignment: '' is not a valid widget. `
```
> Qt: Fix UI related warnings and bonus ui file format 

- src/core/hle/service/gsp_gpu.cpp
The formula from decompiling gsp module
fix Citra crash in game **Skylanders - Spyros Adventure**
fix annoying:
```
[   3.738355] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:96: invalid start address 0x00000000
[   3.738736] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:96: invalid start address 0x00000000
```
> GSP::WriteHWRegsWithMask: fix register mask

- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hw/gpu.cpp
We should correct this before #2439.
Moved HID updating event from GPU to its own module. Separated three devices updating. Corrected the updating ticks using empirical values.
The ticks values are got from [this test](https://github.com/wwylele/ctrhwtest/tree/master/hid_time_test). Usage: press A to test the updating frequency for each HID event; press X/Y to enable/disable gyroscope/accelerometer
Test result (on a JAP old 3DS):
- PAD0/1 event updates ~235 times per second with accelerometer disabled, or ~233 times per second with accelerometer enabled.
- Accelerometer updates ~104 times per second.
- Gyroscope updates ~101 times per second.
Fixes touch pad not working issue in some games (tested Nintendo Video and Nintendo 3DS Sound)
> HID: manages updating itself using correct ticks

- CONTRIBUTING.md
The Citra forum (discuss.citra-emu.org) has recently been down. The link that has been added 
in this file now leads to an error pages. I update updated the link so it now leads to Citra's new
forum.
> Updated Citra forum link

- src/core/hle/service/hid/hid.cpp
Forgot to reset this when implementing acceleroeter and gyroscope :stuck_out_tongue:
> HID: reset acceleroeter and gyroscope index in Init

- src/core/hle/service/mic_u.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/shader/shader.cpp
I had some fun fixing some warnings on MSVC, included some useless warnings ["by design"](https://msdn.microsoft.com/en-us/library/b6801kcy.aspx)
```
C:\projects\citra\src\core\hle\service\mic_u.cpp(96): warning C4800: 'u32': forcing value to bool 'true' or 'false' (performance warning) 
C:\projects\citra\src\core\hle\service\mic_u.cpp(205): warning C4800: 'u32': forcing value to bool 'true' or 'false' (performance warning) 
C:\projects\citra\src\core\hle\service\mic_u.cpp(255): warning C4800: 'u32': forcing value to bool 'true' or 'false' (performance warning) 
C:\projects\citra\src\core\hle\service\mic_u.cpp(285): warning C4800: 'u32': forcing value to bool 'true' or 'false' (performance warning) 
C:\projects\citra\src\video_core\renderer_opengl\gl_rasterizer.h(79): warning C4800: …
```
> Fixing some MSVC warnings

- src/audio_core/sdl2_sink.h
```
In file included from citra/src/audio_core/sink_details.cpp:11:
citra/src/./audio_core/sdl2_sink.h:25:10: warning: 'SetDevice' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void SetDevice(int device_id);
^
citra/src/./audio_core/sink.h:39:18: note: overridden virtual function is here
virtual void SetDevice(int device_id) = 0;
^
```
just adding override to the end of line in sdl2_sink.h made it disappear.
> fixed the override warning

- src/common/hash.cpp
- src/common/hash.h
Bisected from #2471 
Switch ComputeHash64 len param to size_t instead of int.
Fixes following warning on MSVC:
```
C:\projects\citra\src\core\hle\service\dsp_dsp.cpp(142): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```
> Switch ComputeHash64 len param to size_t instead of int

- src/core/frontend/emu_window.cpp
Bisected from #2471 
Fix 6 conversion warnings on MSVC from float to s16
```
C:\projects\citra\src\core\frontend\emu_window.cpp(101): warning C4244: '=': conversion from 'float' to 's16', possible loss of data
C:\projects\citra\src\core\frontend\emu_window.cpp(102): warning C4244: '=': conversion from 'float' to 's16', possible loss of data 
C:\projects\citra\src\core\frontend\emu_window.cpp(103): warning C4244: '=': conversion from 'float' to 's16', possible loss of data
C:\projects\citra\src\core\frontend\emu_window.cpp(112): warning C4244: '=': conversion from 'float' to 's16', possible loss of data 
C:\projects\citra\src\core\frontend\emu_window.cpp(113): warning C4244: '=': conversion from 'float' to 's16', possible loss of data …
```
> core: emu_window.cpp, fix conversion warnings from float to s16 on MSVC

- src/video_core/renderer_opengl/gl_rasterizer_cache.h
This are some boost related warnings, so, since we can't change the code directly neither fix it, I chose to do this, in addition: [Boost Warnings Guidelines](https://svn.boost.org/trac/boost/wiki/Guidelines/WarningsGuidelines)
I chose to do it this way, and don't add the `-Wno-unused-local-typedefs` to the flags, because we have other warnings of this type, that are not boost related.
Silenced warnings:
```
/usr/local/include/boost/icl/concept/interval.hpp:110:60: warning: unused typedef 'domain_type' [-Wunused-local-typedef]
/usr/local/include/boost/icl/concept/interval.hpp:111:60: warning: unused typedef 'domain_compare' [-Wunused-local-typedef]
/usr/local/include/boost/icl/concept/interval.hpp:124:60: warning: unused typedef 'domain_compare' [-Wunused-local-typedef] …
```
> video_core: silence unused-local-typedef boost related warnings on GCC

- src/citra/citra.cpp
- src/core/file_sys/archive_extsavedata.cpp
- src/core/file_sys/archive_sdmc.cpp
- src/core/file_sys/savedata_archive.cpp
- src/core/hle/service/err_f.cpp
Fixes all warnings on OSX builds about unhandled enumeration values on switchs, In addition, I took some time to adds missing control path messages to citra.cpp on rom load.
Fixed warnings:
```
/Users/travis/build/citra-emu/citra/src/core/file_sys/archive_extsavedata.cpp:96:17: warning: enumeration value 'FileFound' not handled in switch [-Wswitch]
/Users/travis/build/citra-emu/citra/src/core/file_sys/archive_sdmc.cpp:54:13: warning: enumeration value 'FileFound' not handled in switch [-Wswitch]
/Users/travis/build/citra-emu/citra/src/core/file_sys/archive_sdmc.cpp:97:13: warning: enumeration value 'FileFound' not handled in switch [-Wswitch]
/Users/travis/build/citra-emu/citra/src/core/file_sys/archive_sdmc.cpp:145:13: warning: enumeration value 'DirectoryFound' not handled in switch …
```
> Fix OSX build warnings about unhandled enumeration values.

- src/core/core.h
This, should, fix, 132, warnings, on, GCC,  ¯\\_(ツ)_/¯.
They happen to exist due to CPU function being declared static on a `.h` file but don't being used in it's own `.cpp` file.
```
/Users/travis/build/citra-emu/citra/src/core/core.h:118:23: warning: unused function 'CPU' [-Wunused-function]
```
PR by guess & docs all around the net, couldn't find nothing official, open to alternative solutions.
Shortened the build log a bit lol:
> core: inline CPU, 132 warnings fixed on GCC

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
(>ლ)
```
/Users/travis/build/citra-emu/citra/src/video_core/renderer_opengl/gl_rasterizer.cpp:719:11: warning: unused type alias 'PixelFormat' [-Wunused-local-typedef]
/Users/travis/build/citra-emu/citra/src/video_core/renderer_opengl/gl_rasterizer.cpp:720:11: warning: unused type alias 'SurfaceType' [-Wunused-local-typedef]
/Users/travis/build/citra-emu/citra/src/video_core/renderer_opengl/gl_rasterizer_cache.cpp:175:11: warning: unused type alias 'SurfaceType' [-Wunused-local-typedef]
```
> video_core: Removed unused type alias

- src/audio_core/hle/source.cpp
- src/audio_core/hle/source.h
Simple loops to start fixing #2093. This handles all the loops I've seen in commercial games, though the DSP engine can in theory manipulate the way it loops beyond replaying the entire buffer (hence, warnings).
> Support looping HLE audio

- src/citra_qt/configure_input.cpp
this case is unneeded because no enumeration value can possibly correspond to it
> removal of the -1 case in the configure_input switch

- src/core/settings.cpp
as far as i could tell this cast is unneeded because [GDBStub::SetServerPort](https://github.com/citra-emu/citra/blob/master/src/core/gdbstub/gdbstub.cpp#L897) takes a u16 and [values.gdbstub_port](https://github.com/citra-emu/citra/blob/master/src/core/settings.h#L116) is already a u16.
> removed the possibly uneeded cast on values.gdbstub_port

- src/video_core/shader/shader_jit_x64_compiler.cpp
Fixes #2498, and potentially other shader JIT crash
Here is a recap of what happens in #2498. It is basically many small things happen at the same time:
First, the shader in question is loaded with some leftover code from a previous shader. When compiling the shader, `FindReturnOffsets` scans the code including the leftover, and generates some garbage return offsets, which are function calls in the leftover to the true part of the shader. This is still OK-ish, because we have [the address check on the potential return](https://github.com/citra-emu/citra/blob/master/src/video_core/shader/shader_jit_x64_compiler.cpp#L774), which should prevent the code from returning on a garbage return offsets.
But the bad thing is, the garbage return address is in shader main() routine. During main() …
> ShaderJIT: add 16 dummy bytes at the bottom of the stack

- src/core/hle/config_mem.cpp
The data from my N3DS with latest firmware
> Core: update Kernel Config Memory to latest version (11.2)

- src/citra_qt/debugger/graphics/graphics_tracing.cpp
- src/citra_qt/debugger/graphics/graphics_vertex_shader.cpp
- src/citra_qt/debugger/graphics/graphics_vertex_shader.h
- src/common/bit_set.h
- src/video_core/clipper.cpp
- src/video_core/command_processor.cpp
- src/video_core/pica.h
- src/video_core/pica_state.h
- src/video_core/primitive_assembly.cpp
- src/video_core/primitive_assembly.h
- src/video_core/rasterizer.cpp
- src/video_core/rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_interpreter.h
- src/video_core/vertex_loader.cpp
- src/video_core/vertex_loader.h
These include small functional changes, so not strictly refactors, but nothing major.
Again, recommend reviewing each commit individually.
> Oh No! More shader changes!

- src/core/CMakeLists.txt
- src/core/hle/ipc.h
- src/core/hle/ipc_helpers.h
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/service.h
- src/core/hle/service/y2r_u.cpp
The way citra generates and parses IPC requests right now is dangerous and inaccurate. Many services do not generate answers to IPC requests correctly, while it is not a problem for games emulation (nintendo's API doesn't seem to do any kind of checks) it could become an obstacle if/when IPC request translation is implemented.
An example of such problem can be seen here : https://github.com/citra-emu/citra/blob/master/src/core/hle/service/fs/fs_user.cpp#L72
``` c++
cmd_buff[1] = file_res.Code().raw;
if (file_res.Succeeded()) {
cmd_buff[3] = Kernel::g_handle_table.Create(*file_res).MoveFrom();
} else {
cmd_buff[3] = 0;
LOG_ERROR(Service_FS, "failed to get a handle for file %s", file_path.DebugStr().c_str());
}
```
We have 2 issues : 
- The command header (cmd_buff[0]) is not updated to …
> IPC helper

- src/video_core/texture/etc1.cpp
I was getting an error when trying to build with MSVC15 Update3 (a bit weird since appveyor didn't catch the error) as it would somehow decay `u8[2]` into `const u8 *` and couldn't convert it back to` const unsigned char (&)[2]`
> Use std::array<u8,2> instead of u8[2] to fix MSVC build

- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
- src/citra_qt/main.cpp
When loading game_list, we are loading all files inside the directory, despite they are any kind of file. This fills the log with a few unnecesary lines regarding the file load of X file, which are of no use at all. With this, we only attemp to load the files we commonly use (The ones we can load through File->Load File...)
> QT: GameList don't attemp to load non-game files

- src/citra_qt/game_list.cpp
completeSuffix returns everything after the first period, which means
that a file such as `foo.bar.3ds` would not get recognized.
> Qt/GameList: Use suffix() to parse the file extension

- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
Incorrect behaviour due to sign extending to 32 bits instead of to 16 bits.
Example:
sxtb16 r7, r12, ror #24
with r12 = 0xa2656cc0
expected result in r7: 0x006cffa2
actual result in r7:   0xffffffa2
> dyncom: Correct SXTAB16 and SXTB16

- hooks/pre-commit
This is constantly causing problems (#2155, #2510 and so on) and is not that useful. We already have format check in CI.
> hook: remove clang-format check

- src/citra/emu_window/emu_window_sdl2.cpp
- src/citra_qt/bootmanager.cpp
- src/citra_qt/main.cpp
- src/common/CMakeLists.txt
- src/common/scm_rev.cpp.in
- src/common/scm_rev.h
A highly requested feature from the citra community moderators. This will hopefully give an "at-a-glance" look at what build each person asking for help is using, so the moderators don't have to search for commits to see if the person they are helping are actually using citra nightly builds. 
Nightly builds now have "Citra nightly" in the titlebar
Bleeding edge builds now have "Citra bleeding edge" in the titlebar
Uploads from CI on the master repo have "Citra master" in the titlebar
Any other build just has "Citra unofficial" in the titlebar
> Gui: Change title bar to include build name

- .travis-upload.sh
A common report from macOS users is they can't figure out how to unzip the
program. This will allow them to double click to unzip the archive which
is what users on macOS expect.
> Use gzip instead of lzma on macOS releases

- src/core/hle/kernel/timer.cpp
- src/core/hle/kernel/timer.h
- src/core/hle/svc.cpp
Also added some error checking in the SetTimer svc.
Huge thanks to @TuxSH for spotting these deficiencies.
Please note that the timer_callback_handle_table HandleTable is currently a source of memory leaks due to Timer objects never reaching 0 references. (ping @yuriks )
> Timers: Immediately signal the timer if it was started with an initial value of 0

- .travis-upload.sh
macOS uses bsdtar which doesn't have the -a flag which determines compression based on file extension. This should (finally) get macOS nightly builds back online.
> Change travis tar command to specify compression format

- src/core/hle/service/ir/ir.cpp
- src/core/hle/service/ir/ir.h
- src/core/hle/service/ir/ir_rst.cpp
- src/core/hle/service/ir/ir_rst.h
- src/core/hle/service/ir/ir_user.cpp
- src/core/hle/service/ir/ir_user.h
I am going to make circle pad pro IR implementation, and this is the first step. Just moving code around but not changing anything
Unlike those of other services, The three ports of IR services, "ir:u", "ir:USER" and "ir:rst", expose totally different set of functions and are served for different works: "ir:u" is for low level IR communication; "ir:rst" is for low level handling of new 3DS additional buttons and c-stick (not actually IR related); "ir:USER" is the high level interface above the other two. They don't "share" functions and status, so it makes no sense to put all functions into one file.
> IR: separate functions of each port to their own files

- CONTRIBUTING.md
An extra ".citra-emu.org," was left when the link was changed to the current forum URL, so I fixed that.
> Fixes typo on Citra forum link.

- src/core/hle/svc.cpp
Just refined the error for each case, this way we can know better under which circumstances syscore emulation is really needed. It can also help isolate certain issues from each other.
> Refined thread launch on syscore error messages

- appveyor.yml
There is an issue with AppVeyor and Xamarin log spam since long ago: http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
We simply don't need that lines (About 56 lines in total) in the log either.
> appveyor: workaround for unnecesary Xamarin log spam

- src/common/file_util.cpp
- src/core/file_sys/archive_extsavedata.cpp
- src/core/file_sys/archive_sdmc.cpp
- src/core/file_sys/archive_sdmcwriteonly.cpp
- src/core/file_sys/archive_source_sd_savedata.cpp
- src/core/loader/loader.cpp
- src/core/loader/ncch.cpp
Logging file name and path have several problems:
- Too verbose and can distract one from finding the actual problem
- Can contain sensitive personal information (e.g. username) and user can upload the log with it without knowing it.
- The way a user to name their game file can sometimes lead to misunderstanding about piracy or something.
The aim of this PR is to lower the level of logs that contains file name and path and that is often logged. (generally all <=Warning log are now <=Debug).
> Reduce host file name and path logging

- src/core/hle/service/apt/apt.cpp
Translate parameter count should be 4 for two unmap buffer descriptors. The `Wrap` one is already correct. Sorry I just forgot to fix both of them...
> apt: fix RequestBuilder parameters for Unwrap

- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
- src/citra_qt/main.cpp
- src/input_common/keyboard.cpp
- src/input_common/keyboard.h
credit to @Hawkheart for the original PR #2479. This is the rebased version of the same idea on the new input system.
Should fix #2392 
btw I also tested the SDL frontend, which doesn't seem to have this issue on my PC. If anyone finds the same issue in SDL frontend, I can add the same fix to it.
> Qt: Release all pressed buttons when window focus is lost [rebased]

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/config.cpp
- src/citra_qt/configure_graphics.cpp
- src/citra_qt/configure_graphics.ui
- src/common/framebuffer_layout.cpp
- src/common/framebuffer_layout.h
- src/core/frontend/emu_window.cpp
- src/core/settings.h
Allows users to scale and place both screens how they want. This takes care of most frame layout related feature requests for now, until simpler solutions are made.
It's not the most user-friendly thing - setting where the edges of the screens are within the render window may not be that intuitive for some, and then there's having to change 8 settings when you change the window size - so perhaps this would be best as just an .ini setting for advanced users?
Regardless, here's what the settings currently look like:
> Add custom layout settings.

- src/core/hle/service/ptm/ptm.cpp
This is a leftover from #2132 . 3DS file system doesn't allow opening ExtSave file with create flag, which was corrected in that PR. But the operation in ptm module was not corrected and couldn't create the GameCoin file.
> ptm: create SharedExtSave file before openning it

- src/core/hle/function_wrappers.h
- src/core/hle/svc.cpp
From libctru:
`Result svcOutputDebugString(const char* str, s32 length);`
I don't know what a real unit would return so I left it void as-is.
Without the length parameter, my shorter debug outputs have the end of previous messages attached to them.
> Fix OutputDebugString syscall

- src/core/hle/service/soc_u.cpp
this commit fixes the errors in the soc_u implementation involving converting and sending the correct error code to the 3ds software
the current implementation had a fault where it would set cmd_buffer[1] to the value of the converted ERRNO message.
This implementation is incorrect because cmd_buffer[1] should be zero if the functions return an error message.
The converted error message should be contained in cmd_buffer[2] instead of cmd_buffer[1].
A working example of this pull request can be observed if you run the 3ds sockets example on linux/osx with citra as root and then access the ip address displayed in the window.
As of rn the windows portion of this code is broken where it returns an invalid address family
> error conversion fixes for soc_u

- src/core/hle/shared_page.cpp
- src/core/hle/shared_page.h
We already stubbed the battery state in the PTM service, but there is another API that is more common used by games, which is the shared page. This PR stubbed the battery state in the shared page with the same value as the one in PTM service.
> shared_page: stub battery state

- src/core/hle/ipc.h
- src/core/hle/ipc_helpers.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/ptm/ptm.cpp
- src/core/hle/service/ptm/ptm.h
- src/core/hle/service/y2r_u.cpp
This is a follow-up of #2027 and part of #2531.
The IPC helpers code was cleaned and specializations for u8/u16/bool were added, and use Push/PopRaw(memcpy) as an implementation.
The u64 specializations still use bitshifts, I wasn't sure if I should keep it that way or use Push/PopRaw too.
A PeekStaticBuffer method was also added so that we can read values and descriptions of the static buffers.
APT was fully rewritten with the IPC helpers, and ctrulib should be able to remove its hack once this is merged @fincs .
I had to modify PTM a bit too so that I could rewrite APT:CheckNew3DSApp.
> IpcHelper enhancement and APT refactor

- src/video_core/regs_framebuffer.h
(The issue was reported by @emmauss on discord, it was hw-tested by @wwylele based on a hardware-test originally written by me. I'm submitting this on behalf of @wwylele who has enough PRs to worry about)
---
This was an attempt to fix a bug in "Fantasy Life" which reportedly uses blend equation 14 when creating a female character. See #2276 (note that it's [still not fixed by this PR because of this](https://github.com/citra-emu/citra/issues/2276#issuecomment-265439959)).
Blend equation 14 does not exist because the [field which stores the blend equation is only 3 bits wide](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_BLEND_FUNC).
This leads to an UNREACHABLE assertion in pica_to_gl.h
This is caused because [the code in master (at the time of …
> Pica/Regs: Correct bit width for blend-equations

- src/citra_qt/main.cpp
This commit will remove the inner border on the status bar cells under Linux.
I undid the first commit to replace the tab with spaces.
> Better looking status bar under Linux Ubuntu

- src/citra/default_ini.h
- src/input_common/sdl/sdl.cpp
Controllers like Xbox have left/right triggers that are ideal for binding with 3DS ZL/ZR, but they are exposed via axis API. Also, one may want to bind controller stick (axis API as well) to 3DS D-pad. This resolves the problem of not being able to bind axis to button.
Usage: `button_*="engine:sdl,joystick:*,axis:*,threshold:*,direction:+/-"`. refer to the comment in the code for detail
Here are some example:
Binding controller stick to 3DS D-pad:
```
button_down="engine:sdl,joystick:0,axis:1,threshold:0.5,direction:+"
button_left="engine:sdl,joystick:0,axis:0,threshold:-0.5,direction:-"
button_right="engine:sdl,joystick:0,axis:0,threshold:0.5,direction:+"
button_up="engine:sdl,joystick:0,axis:1,threshold:-0.5,direction:-"
```
Binding Xbox trigger to 3DS ZL/ZR (not confirmed working):
``` …
```
> input_common/sdl: add support for binding button to axis

- src/video_core/regs_texturing.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/swrasterizer/rasterizer.cpp
- src/video_core/swrasterizer/texturing.cpp
Knowledge source:
- [Documentation on 3dbrew](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_TEXENVi_OPERAND): "Value 7 - Dot3 RGBA"
- [OpenGL documentation](https://www.khronos.org/registry/OpenGL-Refpages/es1.1/xhtml/glTexEnv.xml): GL_DOT3_RGB and GL_DOT3_RGBA have the same formula, but "The scalar results for GL_DOT3_RGB and GL_DOT3_RGBA are placed into each of the 3 (RGB) or **4 (RGBA)** components on output.
Hardware test: ~~not yet.~~ result verified. For more details see below.
Fixed game: Monster Hunter X/Generations / XX
Screenshot (black bottom screen is GS related):
> rasterizer: implement combiner operation 7 (Dot3_RGBA)

- src/citra_qt/configuration/configure_input.cpp
- src/core/CMakeLists.txt
- src/core/hle/service/ir/extra_hid.cpp
- src/core/hle/service/ir/extra_hid.h
- src/core/hle/service/ir/ir_user.cpp
- src/core/hle/service/ir/ir_user.h
- src/core/settings.cpp
Circle pad pro (ZL, ZR and right circle pad) is implemented, along with the minimum set of required ir:USER service functions. For documentation of them please refer to [3dbrew:Circle Pad Pro](https://www.3dbrew.org/wiki/Circle_Pad_Pro) and [3dbrew:IRUSER Shared Memory](https://www.3dbrew.org/wiki/IRUSER_Shared_Memory). 
Some trivial service functions, such as `ReceiveIrnop` and `GetConnectionStatus`, are not implemented, because, from my observation, games usually read data/status directly from the shared memory instead of calling these functions. To minimize the diff, I left them unimplemented. If any games are found using them, I will implement them.
Note on new 3DS input: new 3DS additional HID hardware is mainly handled by ir:rst service, which is not implemented here. However, new …
> ir: implement circle pad pro

- src/citra_qt/configuration/configure_system.cpp
- src/citra_qt/configuration/configure_system.h
- src/citra_qt/configuration/configure_system.ui
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/cfg/cfg.h
This will allow that each citra gets its own console_unique_id and gets rid of the hardcoded 0xDEADC0DE.
It will create a random console_unique_id when the config savegame is created.
To also have to ability to change the console_unique_id without formatting the complete config savegame a button was added to the system config dialog which allows to generate a new random console_unique_id.
One minor draw back is that this won't allow to set the console_unique_id manually. But most users won't ever need to set it manually, and those i need to set it, should know how to edit the savegame. On the other side adding a textbox for that in the ui, seemed way to much for a feature used that rarely.
> Create a random console_unique_id

- src/video_core/regs.h
- src/video_core/regs_texturing.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_shader_gen.h
- src/video_core/swrasterizer/rasterizer.cpp
See [here](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_TEXUNIT_CONFIG) for documentation of the register in question. We currently only respect the low 3 bits. Texture 2 coordinates should be chosen according to bit 13.
[Here is a hardware test](https://gist.github.com/wwylele/fb8306a1facbff5fe77f5db7142f78ef) adapted from the "graphics/gpu/textured_cube" example program. In the test, the texture is bind as texture 2, and the shader outputs the original texture coordinates to coord2, and the negated coordinates to coord1. Press A to flip bit 13 of the register, and texture flipping, as the result of switching coordinates, can be observed.
Don't know if this fix any games.
> pica: use correct coordinates for texture 2

- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
I fixed some minor mistakes of the search filter
- Bug that made the filter result label invisible if the game list folder couldn't be found
- Formatting mistakes on some multiline comments
- Corrected typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2682)
> citra-qt: game list search function fixed minor mistakes

- src/core/arm/skyeye_common/vfp/vfp_helper.h
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
The reverted commit was intended to be a cleanup but actually changed behavior.
The VFP_NAN_FLAG sentinel value was incorrectly being propagated to the guest FPSCR.
Closes #2690
Closes #2680
Closes #2691
Closes #2681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2696)
> Dyncom/VFP: Revert edf30d8 and fix the FPSCR getting invalid values.

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hle/service/ir/ir.cpp
- src/core/hle/service/ir/ir.h
- src/core/hle/service/ir/ir_rst.cpp
- src/core/hle/service/ir/ir_rst.h
- src/core/hle/service/ir/ir_user.cpp
- src/core/hle/service/ir/ir_user.h
- src/core/settings.cpp
This is another API parallel to ir:USER (#2606) that let games access new-added HID on new 3ds. It works similar to the HID service. I don't know any games using this, though, so it would be great if anyone know/find one. On the other hand, all homebrew apps compiled with ctrulib will automatically load this service when initializing HID, if it detects the machine as a new 3ds. So to test this, **you need turn on `is_new_3ds` in the config file** and run a homebrew app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2676)
> ir: implement new 3ds HID via ir:rst

- src/citra_qt/game_list.cpp
- src/citra_qt/game_list.h
- src/citra_qt/game_list_p.h
Instead of tying the QFileSystemWatcher to the GameList and updating in the UI thread, this change moves it to the worker thread. Since it gets deleted and recreated as part of the worker thread, this prevents it from
ever getting used from multiple threads (which is why it was originally done on the UI thread)
macOS users have had issues recently where for some reason their default game list is to some directory where its too large and appears to permanently lock up the main thread.
The original reason that the `QFileSystemWatcher` was placed on the main thread was because of an odd behavior with sharing a watcher to a different thread. When the watcher was shared to a new thread, and the thread would end, the watcher would emit the `directoryChanged` signal for each of the directories …
> Frontend: Prevent FileSystemWatcher from blocking UI thread

- src/video_core/command_processor.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64.cpp
- src/video_core/shader/shader_jit_x64_compiler.cpp
- src/video_core/shader/shader_jit_x64_compiler.h
This code is part of the geometry shader (GS) implementation written by me which is based on work by @ds84182 .
This PR shouldn't change any behaviour currently (except maybe for cases where GS is active, but those are bugged anyway). It merely prepares the registers for GS.
I'd recommend inclusion in bleeding-edge to figure out if there are any issues.
However, this went through a larger refactor shortly before creating this PR, so review / testing should be done first.
Review per commit; see commit description too.
---
* The limit for VS (Vertex Shaders) appears to be 512 program words (compared to 4096 for GS). We should probably introduce a template parameter or something to handle these differences between VS / GS structure. However, that's beyond the scope of this PR. I can create …
> Prepare Pica registers for Geometry Shaders

- src/video_core/regs_framebuffer.h
- src/video_core/regs_pipeline.h
- src/video_core/regs_rasterizer.h
- src/video_core/regs_texturing.h
I compared the pica register definition in citra with [3dbrew documentation](https://www.3dbrew.org/wiki/GPU/Internal_Registers), and these are all registers that are differ in the bit field length. (except for shader related registers, because I don't want to conflict with ongoing GS change).
~~I haven't done any hardware test yet, and will try to do when I get time. I bring these here first to see if anyone who worked on these registers knows the correct length. Please comment in code if you can confirm if 3dbrew is correct or wrong.~~
All of them are hwtested except for the `pipeline.command_buffer` one. See comments below for test detail. For the `pipeline.command_buffer`, I am not able to do the test, so I dropped a comment there and left the actual code unchanged .
---
This change …
> pica: correct bit field length for some registers

- src/video_core/command_processor.cpp
This fixes a regression from #2695 (bug can be seen in Monster Hunter). The `value` variable is a pitfall， which doesn't contain the current register value if the command comes with a mask.
I also check other use of `value` in command processor, but all of them are used for FIFO registers (lut, shader program code, etc.), which are not likely used with a mask. It would be better if we can figure out if the mask actually have any effects to these registers, but I think we can do this after this quick fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2709)
> pica: use correct register value for shader bool_uniforms

- src/core/CMakeLists.txt
- src/core/hle/service/nwm/nwm_uds.cpp
- src/core/hle/service/nwm/nwm_uds.h
- src/core/hle/service/nwm/uds_beacon.cpp
- src/core/hle/service/nwm/uds_beacon.h
These beacon frames are verified to be correct by comparing them to a real wifi pcap capture of a Smash Bros 4 on a real 3DS.
The NWM key is needed for these to be exactly the same as on a real 3DS. For Citra's purposes, an all-zero key is enough.
We use the 802.11 beacon frame structure because that's what games expect to receive when calling ReceiveBroadcastBeaconData
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2661)
> Services/UDS: Generate 802.11 beacon frames when a network is open.

- src/video_core/swrasterizer/clipper.cpp
- src/video_core/swrasterizer/rasterizer.h
Found when I tried to implement TextureCube. This should also affect the implemented Projection2D. Hopefully these are the only two places where `tc0_w` is missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2713)
> swrasterizer: add missing tc0_w attribute processing

- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
Previously we were letting vadd flush the value to positive 0, but there are cases where this behavior is wrong, for example,
vsub: -0 - +0 = -0
vadd: -0 + +0 = +0
Now we'll flush the value to +0 inside vsub, and then negate it.
This was verified using the vsub fuzz test from https://github.com/MerryMage/dynarmic/blob/master/tests/arm/vfp_vsub_f32.inc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2694)
> Dyncom/VFP: Perform flush-to-zero on the second operand of vsub before sending it to vadd.

- src/core/CMakeLists.txt
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/client_session.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/kernel/session.h
- src/core/hle/result.h
This PR is supposed to fix some of the TODOs introduced by #2249.
Namely properly managing the current connection count of the kernel ports.
The current connection count is increased when a session is created to the port, and it is decremented when said session is destroyed.
The port will be kept alive so long as the session is still alive.
There are still a few things left, like awaking all the waiting threads of a ClientPort when its connection count goes below the max, but that's something that will be implemented later when ClientPort inherits from WaitObject.
This implementation depends deeply on not keeping any extra owning references to ServerSessions, there should only be one for HLE services: the one stored in SessionRequestHandler::connected_sessions.
If this invariant is …
> Kernel: Properly update port counters on session disconnection.

- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
- src/core/arm/skyeye_common/vfp/vfpsingle.cpp
closes #1990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2692)
> Dyncom/VFP: Convert denormal outputs into 0 when the FTZ flag is enabled.

- .gitmodules
- CMakeLists.txt
- externals/CMakeLists.txt
More info at http://fmtlib.net/
This was based on @jroweboy's work on his spdlog branch, but with modifications. Namely, I don't manually add the include directory for fmt. Rather, individual libraries should add it using `target_link_libraries` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2732)
> Add the fmt string formatting library

- src/video_core/renderer_opengl/gl_shader_gen.cpp
Discovered while poking around for #2726.
Current order of operations (rotate then normalize) seems to produce a
lot more distortion than normalizing and then rotating. This makes Citra
results match pretty closesly with hardware, and indicates that hardware
may also be using lerp instead of slerp to interpolate the quaternions.
[Test](https://gist.github.com/yuriks/e5b9fbacbc558587525fb22733a14fa1) results:
System | 70° | 85°
-|-|-
3DS | ![deg70-3ds](https://cloud.githubusercontent.com/assets/341401/26519177/108c9486-4272-11e7-9237-6f1a1006cc9f.png) | ![deg85-3ds](https://cloud.githubusercontent.com/assets/341401/26519178/14e72a6e-4272-11e7-815b-a611ee89fcec.png)
Citra (this PR) | ![deg70-citra-new](https://cloud.githubusercontent.com/assets/341401/26519185/2c10cdd0-4272-11e7-8f3f-fd9c2d5 …
> OpenGL: Improve accuracy of quaternion interpolation

- src/video_core/regs_texturing.h
- src/video_core/swrasterizer/rasterizer.cpp
Currently only implemented in the software renderer, not in gl one. I have some questions regarding to this implementation and incoming gl implementation:
- `// TODO: Refactor so cubemaps and shadowmaps can be handled` what kind of refactor is preferred here?
- When implementing in gl, should gl's cube mapping be used, or we store them in 6 texture2D and manually convert the coordinates?
And [here](https://www.dropbox.com/s/l6zzmkiw4gh1eoq/texture_box.zip?dl=1) is a testing program
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2721)
> swrasterizer: implemented TextureCube

- src/citra_qt/bootmanager.cpp
- src/citra_qt/bootmanager.h
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/core/core.cpp
- src/core/core.h
- src/core/file_sys/archive_ncch.cpp
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/err_f.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/fs_user.cpp
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
As a forum/Discord moderator, we see many people ask for support when their solution is simply to dump their system files and shared font. So, what this PR does is it displays a QMessageBox dialog when one of these errors happens.
A dialog box will be shown when the following happens:
- The shared font is missing.
- The system/home files are missing.
- An encrypted ROM is loaded (This was already in, but I had to fix it because something was breaking it from being shown.).
- OpenGL requirements not being met (Again, this was already in, but I'm not sure if it was really working.).
- Any other unknown fatal error.
Here's how it works:
- When the error happens within core, Core::System::GetInstance().SetStatus() is called.
- In the main loop within bootmanager.cpp,  the Core Loop returns …
> Display QMessageBox Dialogs For Errors

- src/core/CMakeLists.txt
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
Most of the code that works with this is or will be in the kernel, so it's a more appropriate place for it to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2752)
> HLE: Move SessionRequestHandler from Service:: to Kernel::

- src/core/CMakeLists.txt
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/result.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
Depends on:
Have a separate function to set HLE handlers for ports and sessions instead of passing them in during creation. See commit message for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2753)
> Add SetHleHandler to ServerPort/ServerSession

- src/core/CMakeLists.txt
- src/core/hle/kernel/client_port.cpp
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/server_port.cpp
- src/core/hle/kernel/server_port.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/result.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/sm/sm.h
- src/core/hle/service/sm/srv.cpp
- src/core/hle/service/sm/srv.h
Depends on:
Moves the srv/sm implementation to a sub-directory and tasks it with handling service registrations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2754)
> Handle service registrations using sm/srv

- src/core/CMakeLists.txt
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/sm/sm.h
- src/core/hle/service/sm/srv.cpp
- src/core/hle/service/sm/srv.h
From the main commit's description:
> The old "Interface" class had a few problems such as using free
> functions (Which didn't allow you to write the service handler as if it
> were a regular class.) which weren't very extensible. (Only received one
> parameter with a pointer to the Interface object.)
> 
> The new ServiceFramework aims to solve these problems by working with
> member functions and passing a generic context struct as parameter. This
> struct can be extended in the future without having to update all
> existing service implementations.
Please hold off on actually migrating stuff to this new framework for now. I have some other API changes planned/half-implemented which, while backwards compatible, should save a lot of work when writing handlers, so it's probably better to …
> New service framework

- src/core/hle/ipc.h
- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/service.cpp
- src/core/hle/service/sm/srv.cpp
Only on ServiceFramework™-based services (aka, just sm/`srv:` for now.) Changes include:
- Use a separate command buffer copy instead of working directly with the caller's.
- Make handle lookup/creation the responsibility of the Kernel/Framework
Commits are probably reviewable individually.
Depends on citra-emu/ext-boost#11 for `small_vector`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2774)
> Add basic support for IPC translation for HLE services

- src/video_core/regs_texturing.h
- src/video_core/renderer_opengl/pica_to_gl.h
- src/video_core/swrasterizer/rasterizer.cpp
- src/video_core/swrasterizer/texturing.cpp
This is intended to avoid crash in #2740 and #2742.
(Remade after bunnei's comment)
Based on previous hardware test, mode 4-7 is implemented in the software rasterizer, and partially implemented in gl rasterizer. Mode 4 and 5 doesn't have their direct counterpart in opengl, so they are not fully implemented. Also added warning log for these mode in opengl (not added for sw one because it would be too verbose)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2743)
> pica/rasterizer: implement/stub texture wrap mode 4-7

- src/video_core/regs_lighting.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
[Here](https://gist.github.com/wwylele/f61d6653620bb763ab9dc7a60a9831ce) is my notes when testing these features on 3DS.
[Here](https://github.com/wwylele/ctrhwtest/tree/master/lighting-cp) is a testing program with different bumping modes and lut inputs combined. The bump map this program uses consists of vectors of different directions, length and z-components. With this PR, the only difference between 3DS and citra is in the middle of the cube faces, where the bump map value is exactly (0.0, 0.0, 0.0), using normal map mode, CP input and "renorm" off. In this situation there is actually a divide-by-zero when projecting the vector, and game usually shouldn't have an zero normal vector, so I am not going to fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Fragment lighting: implement lut input 5 (CP) and tangent mapping

- src/video_core/regs_lighting.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_shader_gen.h
Reference formula on 3dbrew: http://mathb.in/64694. G0 and G1 are geometric factors
The test result shows that the formula for geometric factors in 3DS is not [the standard Cook-Torrance one](http://ruh.li/images/CookTorranceGeometricAttenuation.png). To get the correct formula, [a testing program](https://github.com/wwylele/ctrhwtest/tree/master/geo_factor) is used. Some assumptions are made when finding the formula:
- the formula on 3dbrew is correct
- G only depends on normalized vector N (normal), V (view) and L (light), and can contain half-angle vector H (still depends on V and L)
- spherical symmetry, as in, rotating N, V and L by the same angle won't change G value 
Based on these assumptions, G value is sampled for different combinations of N, V and L (with two-sided-diffuse on). …
> Fragment lighting: implement geometric factor

- src/core/hle/kernel/memory.cpp
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/timer.cpp
- src/core/hle/result.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/cam/cam.cpp
- src/core/hle/service/cecd/cecd.cpp
- src/core/hle/service/cfg/cfg.cpp
- src/core/hle/service/csnd_snd.cpp
- src/core/hle/service/dsp_dsp.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/gsp_gpu.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ir/ir_rst.cpp
- src/core/hle/service/ir/ir_user.cpp
- src/core/hle/service/mic_u.cpp
- src/core/hle/service/nfc/nfc.cpp
- src/core/hle/service/nwm/nwm_uds.cpp
- src/core/hle/service/ptm/ptm.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/sm/srv.cpp
- src/core/hle/service/y2r_u.cpp
It is now 2017 and rvalue qualifiers on `this` are a thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2790)
> Remove ResultVal::MoveFrom

- src/video_core/pica_state.h
- src/video_core/regs_lighting.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
Currently on the GL renderer, we use the texture linear filter for LUT interpolation. This approach have the following problems:
- if the delta entry the game assigns is not the difference between two entries, linear filter will produce different output from real 3DS. (less likely)
- hard to handle sampling at the edge due to different coordinates convention between OpenGL and PICA (see #2367 and #2551). Note that the [-1.0, 1.0] sampling mode in PICA, which works in a two's complement way, is the root of most lighting issue, because GL will interpolate between LUT(-1.0) and LUT(1.0) and generate wrong result at the adge.
Solution: just do what PICA do. Both LUT value and delta are uploaded to the shader and proper interpolation is calculated there. Since the filter is not used any more, …
> gl_rasterizer: fix lighting LUT interpolation

- src/citra/config.cpp
- src/citra_qt/configuration/config.cpp
Changing the default game UI screen from white (1.0) to black (0.0) allows for easier viewing of the game window.
When taking screenshots for the compatibility database, we agreed on a black background would be easier. 
Making this the default background color.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2795)
> Change default UI background from white to black.

- src/video_core/pica_state.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/swrasterizer/rasterizer.cpp
Follow up of #2792. Use texture buffer for fog LUT, and move entry decoding from shader to pica_state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2800)
> gl_rasterizer: use texture buffer for fog LUT

- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
The following behaviours are confirmed on hardware and fixed in citra accordingly:
- The total size is always aligned down to 16 bytes (i.e. the same unit of width/gap)
- If the total size (aligned) is zero, 3DS freezes.
- If both `input_width` and `input_gap` are zero, then the input is treated as contiguous data with length `size` (i.e. behaves the same as `input_gap == 0` and `input_width != 0`)
- If `input_width == 0` and `input_gap != 0`, 3DS freezes
- The two points above also apply to the output.
- There are some other cases can cause 3DS freeze, but I didn't test it very much. Probably not worth to emulate them now.
The test program is here: https://github.com/wwylele/ctrhwtest/tree/master/texture-copy-test
(Note: if you want to run this test in citra, please merge …
> gpu: fix edge cases for TextureCopy

- src/core/hle/function_wrappers.h
- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/client_session.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/svc.cpp
This svc takes care of most IPC duties, more information can be found [here](https://www.3dbrew.org/wiki/IPC#svcReplyAndReceive)
It behaves mostly as WaitSynchronizationN with wait_all = false, except for IPC buffer translation.
The target thread of an IPC response will now wake up when responding.
IPC buffer translation is currently not implemented.
Error passing back to svcSendSyncRequest is currently not implemented.
cc @yuriks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2793)
> Kernel/SVC: Partially implemented svcReplyAndReceive

- src/common/logging/text_formatter.cpp
Already defined here: https://github.com/citra-emu/citra/blob/56d718b2a1d6385c88c2044f780280a5dfbc6072/CMakeLists.txt#L83
Which generates the following warning.
```
C:\projects\citra\src\common\logging\text_formatter.cpp(9): warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition
```
There are more on Cryptopp and Dynarmic, to a total of 9... but I think that those ones should be addressed  with an `#ifndef` on the upstream, and not silenced by adding /wd4005.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2814)
> Remove unnecessary WIN32_LEAN_AND_MEAN macro definition

- src/core/CMakeLists.txt
- src/core/hle/romfs.cpp
- src/core/hle/romfs.h
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/bcfnt/bcfnt.cpp
(This is me having OCD...)
**Just in case of misunderstanding, this PR doesn't eliminate the need of shared font. It only changes the loading format of the shared font**
This mimics the way how the real APT service loads the shared font archive. The result is verified against the data from real hardware, the data from citra running NS sysmodule, and shared_font.bin itself. With this we can get rid of the weird shared_font.bin file and have all system data uniformly stored in system archives. A fallback to the old shared_font.bin is provided for compatibility.
To use this, 3dsutils needs to be modified to dump the font archive. Add this to the source code:
```
// savedatacheck/0004009b00014002.bin
u64 binary_lowpath_0004009b00014002[] = { 0x0004009b00014002, 0x00000001ffffff00 }; …
```
> load shared font from system archive

- .gitmodules
This makes it easier for packagers to preload all submodules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2830)
> Make enet use the same convention as other submodules

- CMakeLists.txt
Does this by looking in `.gitmodules` and grepping the paths to all the submodules out of it, and checking for the presence of the `.git` folder in each of those paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2829)
> CMakeLists: Check that all submodules are present

- src/citra/CMakeLists.txt
- src/citra/emu_window/emu_window_sdl2.cpp
- src/network/CMakeLists.txt
- src/network/packet.cpp
- src/network/packet.h
- src/network/room.cpp
- src/network/room.h
- src/network/room_member.cpp
- src/network/room_member.h
This PR is a continuation of #2803 
It implements:
- Sending/handling JoinRequests
- Sending/receiving WifiPackets
- Disconnect handling
- Send/receive chat messages
- Send a game title
Things still to come:
1. A way to register and invoke callbacks
2. A way to register a room to our server api
3. Make use of the network implementation inside nwm::uds
4. The UI
It's probably best to review each commit separately.
To test this PR use [https://github.com/B3n30/citra-1/tree/network_test](https://github.com/B3n30/citra-1/tree/network_test)
It's currently possible to test:
- create room
- destroy room
- join room
- leave room
- send/receive chat messages
- receive RoomInformation
What's currently missing in test:
- send/receive WifiPackets
- send game title 
--- …
> Enable data transfer over ENet

- src/core/core.cpp
- src/core/loader/ncch.cpp
- src/core/telemetry_session.cpp
- src/video_core/renderer_opengl/pica_to_gl.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
This is the third part of a set of changes to add a telemetry framework to Citra. In the near term, this will be used for user-submitted compatibility data to our own custom service endpoint (services.citra-emu.org). My goal, however, is to make this very generic, and allow us to easily log useful/interesting data fields throughout the emulator, and then upload them to our service at a later time. In the long term, we may use this for anonymous telemetry, critical errors and crash reports, measuring how often features are used, etc.
The general design right now is to have essentially a "metadata log", which is just a list of logged data fields. A data field considers of:
* **Name** - String used as a key to access the field, must be unique to a given log (otherwise overwrite previous …
> telemetry: Log performance, configuration, and system data.

- .gitmodules
- externals/CMakeLists.txt
- externals/json/README.md
- externals/json/json.hpp
It is nonsensical to pull in a 100mb+ repository, with tests, documentation and so on for a single C++ header. This PR removes the link to the upstream repository and substitutes it for the aforementioned header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2833)
> Don't pull in entire JSON repo for single header file

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Changed on of the depth buffer condition from `depth_write_enable` to `(depth_write_enable &&  allow_depth_stencil_write)`. In other places in the code base, these two bools are always `&&` together, so I assume this one is just forget to add.
This eliminates the "Color and depth framebuffer memory regions overlap" spam in smash bros, where the game sets the depth buffer address the same as the color buffer. The relevant command list is
```
GPUREG_STENCIL_TEST	105	1111	ff00ff10
GPUREG_STENCIL_OP	106	1111	00000000	
GPUREG_DEPTH_COLOR_MASK	107	1111	00001f40	 // depth_test_enable = false, depth_write_enable = true
GPUREG_DEPTHMAP_ENABLE	06d	1111	00000001	
GPUREG_DEPTHMAP_SCALE	04d	1111	00bf0000	
GPUREG_DEPTHMAP_OFFSET	04e	1111	00000000	
GPUREG_FRAMEBUFFER_FLUSH	111	1111	00000001 …
```
>  gl_rasterizer_cache: fix using_depth_fb

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
Follow up of #2800 . I still kept these textures in separate unites because they don't have good numerical relationship to pack them into one texture like the lighting LUT one. We can pack them whenever it is more unit space is needed, anyway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2816)
> gl_rasterizer: use texture buffer for proctex LUT

- appveyor.yml
Nightly on Windows is currently bringing up error messages about missing SSLEAY.dll and LIBEAY.dll because Appveyor has OpenSSL installed, so cURL will attempt to use that. We would rather have it use the native windows ssl (SSPI) instead. Simply turning off "Use OpenSSL" makes everything work again.
Fixes nightly missing DLLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2844)
> Use WinSSPI instead of OpenSSL

- src/network/room.cpp
- src/network/room.h
This fixes issue https://community.citra-emu.org/t/latest-nightly-fails-to-make-in-linux/2628.
The main issue is that there is a bug in gcc < 6.0 leading to this error message although the code is by C++11 definition totally legit.
But since a lot of distributions/packages ship as their default gcc version 5.4, this issue should be addressed.
This PR also fixes a const definition the should be a constexpr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2847)
> Fixed build error "too many initializers for ‘const MacAddress"

- .travis-deps.sh
- .travis-upload.sh
- .travis.yml
- appveyor.yml
This PR introduces 7zip artifacts for both the Travis and Appveyor buildbots. This is so that the Qt Installer Framework can actually grab binary files directly from Github.
Why does this make references to nightly, rather then abstract for nightly/bleeding-edge?
Few reasons - the main repository is currently designed exclusively to produce artifacts for nightly. This is something that should hopefully change in a future PR, but that also requires changes on the bleeding edge/canary side, so I will defer that.
Why are subfolders used ("nightly") inside archives?
Qt Installer Framework extracts archives into the root of the installation folder. This allows for clean seperation between nightly & canary.
--- …
> Produce 7zip artifacts on Travis and Appveyor

- src/video_core/shader/shader_interpreter.cpp
Here is [a shader demonstrating the bug](https://gist.github.com/wwylele/67088d9e43f082938f0da520a1228851). You can attach it to the "simple_tri" example in devKitPro and test it. Take out the loop code in this shader for example:
```
...
09    loop instr.flow_control.dest_offset=11
10  { add r1.x, r1.x, r2.x ; color.r+=0.2
11    add r1.y, r1.y, r2.x ; color.g+=0.2 }
12    add r1.z, r1.z, r2.x ; color.b+=0.2
...
```
when executing the loop instruction, `program_counter=9`, `instr.flow_control.dest_offset=11` (recall this means here the last instruction in the loop, inclusive), and the current interpreter will do 
```
call(offset = 9+1 = 10, num_instructions = 11-9+1 = 3, return_offset = 11+1 = 12,...)
```
as can be seen, `num_instructions` is calculated wrongly as 3, which should be 2. …
> pica/shader_interpreter: fix off-by-one in LOOP

- src/core/file_sys/archive_sdmc.cpp
- src/core/file_sys/savedata_archive.cpp
rip citrahax 1.0. 2.0 coming to a citra near you!
This fixes renaming of files with invalid paths, and adds the same checks that are used by other components of the archive implementations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2850)
> Handle invalid filenames when renaming files/directories

- CMakeLists.txt
- src/common/scm_rev.cpp.in
- src/common/scm_rev.h
- src/core/core.h
- src/core/hle/service/apt/apt.cpp
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
- src/core/telemetry_session.cpp
Adds a few more fields to telemetry that we'd like before going live:
- ProgramName (title string stored in games)
- BuildDate (of the application)
- RequiresSharedFont (if a game tries to use the shared font)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2855)
> Telemetry: Add several more useful fields

- src/citra_qt/main.cpp
User pointed out on the Discord server that "nothave" is erroneously concatenated. Added a space to prevent it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2860)
> Quickfix typo in OpenGL 3.3 error message

- src/video_core/command_processor.cpp
- src/video_core/regs_pipeline.h
One step toward GS. This is the most tricky finding about GS until now, so I want to put it here for discussion first.
I didn't hwtest the exact behaviour of the register `gs_unit_exclusive_configuration` (0x0244, `GPUREG_VSH_COM_MODE` on [3dbrew](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_VSH_COM_MODE)), but as the theory suggested
> This register sets whether to use the geometry shader configuration or reuse the vertex shader configuration for the geometry shader shading unit. 
This means everything uploaded to VS regs should also be uploaded to the special GS unit.
A real use case of this, _Professor Layton and the Miracle Mask_, is found in recent test of GS experimental implementation. A simplified PICA command list the game sends is …
> pica: upload shared shader code & swizzle to both unit

- src/core/hle/service/cfg/cfg.cpp
This PR updates CryptoPP.
This, along with other upstream changes, fixes a potential type ambiguity for `byte` with the upcoming introduction of `std::byte` + other native definitions of such, meaning that there is no chance for conflict.
All upstream changes: https://github.com/weidai11/cryptopp/compare/841c37e34765487a2968357369ab74db8b10a62d...58b731c64515f7442ed20f8b33482ed3c058e1d4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2862)
> Update CryptoPP (byte ambiguity)

- .travis-upload.sh
- .travis.yml
- appveyor.yml
Previously, Citra would deploy when it was on `citra-emu/citra-nightly`. This hardcoded branch meant that building bleeding-edge/canary required a dedicated patchset, and that references to tags could not be used (both AppVeyor and Travis only support `branch` filtering or `tags`, not both).
This fixes this, by deploying only when a tag has been specified. This has a host of advantages:
- Nightly and canary no longer need to have their own independent build scripts.
- Tags can be created as required (which includes `citra-emu/citra` itself, if "stable" builds wanted to be created), and individual pushes won't cause the entire system to collapse.
- This fixes the race condition between Travis and AppVeyor.
This introduces a few issues:
- Webhooks need to be fixed (nightly is ready, …
> Travis/AppVeyor: Deploy based upon tags

- src/video_core/swrasterizer/lighting.cpp
implicit tuple constructor is c++17 thing, which is not supported by some not-so-old libraries (for example, the one with gcc5). Play safe for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2868)
> SwRasterizer/Lighting: use make_tuple instead of constructor

- src/core/hle/service/hid/hid.h
- src/core/hle/service/ir/ir_rst.cpp
Unused PadState bits usually means nothing to commercial games, but some homebrew programs (such as devkitPro-3ds-examples/input/read-controls) assume they are all zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2863)
> HID: zero unused PadState bits

- .travis-upload.sh
- appveyor.yml
This generates the correct folder structure for QtIFW builds from the tag name.
Tag -> folder conversion:
Tag name    |  Folder name
------------- | --------------
canary-212  |   canary
nightly-999 |  nightly
nightly        |  nightly
\<undef\>     |  head
Overall directory structure:
```
C:\Program Files\Citra: (or Linux/Mac equiv.)
nightly:
citra[.exe]
citra-qt[.exe]
...
canary:
citra[.exe]
citra-qt[.exe]
...
<folder name>:
citra[.exe]
citra-qt[.exe]
...
maintenancetool[.exe]
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2867)
> Implement correct folder structure for CI builds

- .travis-build-docker.sh
- .travis-build.sh
- .travis-deps.sh
- .travis.yml
Travis seems to be sticking to Ubuntu 14.04 for the next century, so this PR implements Docker as a means to get around that. A standard Ubuntu 16.04 image from the Docker repository is used, and there is no need for hacked up PPAs/etc. This adds a minute or two of additional build time.
This fixes Linux builds not finding the correct versions of linked libraries, and ensures that we are using `libpng16` as well. This has been tested on Arch (02/08/17) and Ubuntu 16.04.
This also has the additional benefit of allowing Docker images of different distributions to be used, if that was a requirement (Debian, Ubuntu 17.04, etc).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2 …
> Travis: Use Docker to build for Linux

- src/video_core/renderer_opengl/gl_shader_gen.cpp
This is a small flaw in #2762 . `SampleTexture` is always called even if bump mapping is disabled, in which cases the game can set the texture unit to an invalid state (say disabled unit 0 or proctex unit) and generate an error log. This doesn't affect the actual game play, but just being annoying in logging.
Now the code construction turns into a lambda and only gets called on need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2875)
> gl_shader_gen: don't call SampleTexture when bump map is not used

- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/apt/apt.h
This gives each applet type its own set of events as per the real NS module.
This depends on #2840 , reviewers should focus on the last commit only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2843)
>  Services/APT: Use an array to hold data about the 4 possible concurrent applet types (Application, Library, HomeMenu, System)

- src/core/hle/service/dsp_dsp.cpp
It is possible to write DSP firmware that's smaller than 0x37C bytes in size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2881)
> dsp_dsp: Remove size assertion in LoadComponent

- src/core/CMakeLists.txt
- src/core/core.cpp
- src/core/loader/ncch.cpp
- src/network/packet.cpp
- src/network/packet.h
- src/network/room.cpp
- src/network/room.h
- src/network/room_member.cpp
- src/network/room_member.h
This PR is the third regarding the ENet inclusion.
With this PR the libnetwork is fully functional. There might still be some features that could be added, though.
The features added in this PR:
- Set the GameInformation of the RoomMember the moment they change
- The callback interface for RoomMember
here's an example of how to hook a function to one of the events:
``` // Callback identifier for the OnStateChanged event.
static Network::RoomMember::Connection<Network::RoomMember::State> state_changed;
void OnStateChanged(const Network::RoomMember::State) {
...
}
if (auto room_member = Network::GetRoomMember().lock())
wifi_packet_received = room_member->ConnectOnWifiPacketReceived(OnWifiPacketReceived);
...
//Every connected function must be disconnected
if (auto room_member = …
```
> Added missing parts in libnetwork

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/swrasterizer/clipper.cpp
- src/video_core/swrasterizer/rasterizer.h
Fixes #2248. A related hwtest can be found there below
OpenGL convention for depth range in the normalized device coordinate is [-1,1], which is different from the one of PICA [-1, 0]. We do correct transformation in the fragment shader, but didn't take the clipping plane difference into account. In the clip space, OpenGL clips vertices against -w<=z<=w, while PICA clips them against -w<=z<=0. This is correctly implemented in the swrasterizer/clipper. In order to achieve the same result in GL rasterizer, a user-defined clipping plane is added at z<=0. 
I reserved another GL user-defined clipping plane, for future implementation for PICA user-defined clipping plane.
The other three commits are some no-op clean-up. See commit message for detail
--- …
> gl_rasterizer: add clipping plane z<=0 defined in PICA

- src/input_common/motion_emu.cpp
Sorry, this is a flaw from #2861 . The thread is initialized before `status_mutex` and can run fast enough to access the uninitialized mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2894)
> motion_emu: fix initialization order

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/arm/skyeye_common/armstate.h
- src/core/file_sys/archive_backend.cpp
- src/core/hle/applets/erreula.cpp
- src/core/hle/applets/mii_selector.cpp
- src/core/hle/applets/mint.cpp
- src/core/hle/applets/swkbd.cpp
- src/core/hle/kernel/kernel.h
- src/core/hw/gpu.cpp
- src/core/hw/gpu.h
Visual Studio 2017 15.3 reports 137 warnings in total (many of which come from externals) and 67 warnings in the ```core``` project as of 21204ba488fd00be4cc6e44998c5d7c8bd0fec91, this PR fixes 13 of those warnings, bringing down the number of ```core``` warnings to 54. This PR does not touch the other projects or the warning settings in cmake.
ref #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2888)
> Fixed some warnings in the core project.

- src/core/hle/kernel/thread.cpp
This is necessary for loading multiple processes at the same time.
The main thread will be automatically scheduled when necessary once the scheduler runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2893)
> Kernel/Threads: Don't immediately switch to the new main thread when loading a new process.

- src/citra/citra.cpp
- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/CMakeLists.txt
- src/citra_qt/configuration/config.cpp
- src/citra_qt/configuration/configure.ui
- src/citra_qt/configuration/configure_dialog.cpp
- src/citra_qt/configuration/configure_web.cpp
- src/citra_qt/configuration/configure_web.h
- src/citra_qt/configuration/configure_web.ui
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/ui_settings.h
- src/core/settings.h
- src/core/telemetry_session.cpp
- src/core/telemetry_session.h
- src/web_service/telemetry_json.cpp
- src/web_service/telemetry_json.h
- src/web_service/web_backend.cpp
- src/web_service/web_backend.h
This is the fourth part of a set of changes to add a telemetry framework to Citra. In the near term, this will be used for user-submitted compatibility data to our own custom service endpoint (services.citra-emu.org). My goal, however, is to make this very generic, and allow us to easily log useful/interesting data fields throughout the emulator, and then upload them to our service at a later time. In the long term, we may use this for anonymous telemetry, critical errors and crash reports, measuring how often features are used, etc.
With this change, I've added the following:
* Settings UI for configuring telemetry related fields
* "Callouts", one-time important messages to the user, which is currently used to indicate the addition of telemetry
* TelemetryId, a user-unique random number …
> Telemetry UI and final touches

- src/video_core/regs_framebuffer.h
- src/video_core/swrasterizer/framebuffer.cpp
- src/video_core/swrasterizer/texturing.cpp
The reason i'm using ASSERT(false) in some places instead of UNREACHABLE() is that I can not be sure that the code is actually unreachable, there are gaps in the depth format values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2892)
> Warnings: Fixed a few missing-return warnings in video_core.

- src/citra/config.cpp
- src/citra/default_ini.h
- src/citra_qt/configuration/config.cpp
- src/core/frontend/emu_window.cpp
- src/core/frontend/emu_window.h
- src/core/frontend/input.h
- src/core/hle/service/hid/hid.cpp
- src/core/settings.h
This is a follow-up of #2497 and #2861 , and it is the last one remained to integrate into the input system.
Unlike the other inputs, touch input is highly bound to the window, so instead of decoupling it from `EmuWindow`, I let `EmuWindow` becomes the factory provider, and wrapped the plain touch state previously in `EmuWindow` into the `TouchState`, which implements the device factory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2899)
> Refactor touch input into a TouchDevice

- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/swrasterizer/lighting.cpp
- src/video_core/swrasterizer/lighting.h
- src/video_core/swrasterizer/rasterizer.cpp
This is the last part of SwRasterizer/Lighting to reach feature parity with the GL one, including normal map, tangent map and LUT input CP. See #2762 for the GL counterpart and related hwtest.
----
This also includes a revision of the CP formula: if we assume that `normal` is a unit vector, then the term `/ dot(normal, normal)` is a no-op. This assumption doesn't hold true for the edge case that `bump_renorm` is off and the map contains unnormalized vectors. Further hwtest shows that PICA probably makes the same assumption, which makes sense because thus it doesn't need to do expensive division. The detailed test result is shown below, using the program in #2762, in normal map mode, with CP input and `bump_renorm` off
|3DS|GL(master) with old formula |SW or GL(this branch)* with revised …
> SwRasterizer/Lighting: implement bump mapping

- src/audio_core/hle/source.cpp
- src/audio_core/interpolate.cpp
- src/audio_core/interpolate.h
Perform interpolation of audio buffers on a frame-by-frame basis.
This is so that changes to rate_multiplier are reflected immediately in the next frame and not when the current buffer ends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2858)
> interpolate: Interpolate on a frame-by-frame basis

- src/video_core/renderer_opengl/gl_shader_gen.cpp
>>These developers have found it difficult to prioritize their efforts
>
>This just sounds like nonsense to me. I'm sure devs aren't sitting around going "hmm now what?". This sounds like a solution in search of a problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2909)
> video_core: report telemetry for gas mode

- appveyor.yml
Releases will be built with both mingw and msvc and the binaries of both
builds will be uploaded to github releases
Tests are run against both builds.
Since this doubles the build time for appveyor, I've also taken steps to reduce the build time by having bunnei turn on a feature in appveyor and travis that cancels builds if a newer build is push. This fixes an issue where a PR is merged to master, then the release bot will push a tag for it, and the tag release build will have to wait for the master build to finish first. With the change to turn on rolling builds, the tag build will cancel the master build so the release won't be held up by the useless build for master.
--- …
> Build: Add mingw64 compile support to appveyor

- src/core/CMakeLists.txt
- src/core/hle/service/nwm/nwm_uds.cpp
- src/core/hle/service/nwm/nwm_uds.h
- src/core/hle/service/nwm/uds_beacon.cpp
- src/core/hle/service/nwm/uds_beacon.h
- src/core/hle/service/nwm/uds_connection.cpp
- src/core/hle/service/nwm/uds_connection.h
There is currently no connection stage tracking, a client is considered "Connected" when it receives the EAPoL Logoff packet from the server, this is not yet implemented.
The received beacon frames are stored in a circular buffer of 15 elements, where new elements displace the older ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2831)
> Services/UDS: Handle beacon frames and the basic AP connection sequence frames.

- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/swrasterizer/lighting.cpp
[Here](https://github.com/wwylele/ctrhwtest/tree/master/fresnel-test) is the hwtest. The test result shows that the Fresnel factors from each light don't get multiplied together; instead all of them are ignored except the last one.
It is also tested that "the last one" means the last one in `LightingRegs::light_enable` slots, not the last one in `LightingRegs::light` array. This can be test by modifying [the slot assignment order](https://github.com/fincs/citro3d/blob/4ada36b6cd60ccf28c6abe931b574aaf5dda5827/source/lightenv.c#L61-L67) in citro3d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2914)
> pica/lighting: only apply Fresnel factor for the last light

- appveyor.yml
`libicu` needs to be included for mingw, but the current globbing pattern used to copy the dlls to the build directory also grabs the dlls for debug. The purpose of using file globbing was to avoid hard coding versions for the dlls, in order to make sure that future updates to appveyor's version of mingw won't break the build. This change just removes any of the debug dlls for `icu` which shaves off over 10MB from the mingw download
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2918)
> Remove excess debug dlls for mingw build

- src/video_core/CMakeLists.txt
- src/video_core/command_processor.cpp
- src/video_core/geometry_pipeline.cpp
- src/video_core/geometry_pipeline.h
- src/video_core/pica.cpp
- src/video_core/pica_state.h
- src/video_core/primitive_assembly.cpp
- src/video_core/primitive_assembly.h
- src/video_core/regs_pipeline.h
- src/video_core/regs_shader.h
- src/video_core/shader/shader.cpp
- src/video_core/shader/shader.h
- src/video_core/shader/shader_interpreter.cpp
- src/video_core/shader/shader_jit_x64_compiler.cpp
- src/video_core/shader/shader_jit_x64_compiler.h
Credit to @ds84182 and @JayFoxRox  for their original implementation, and to @fincs for their research on GS
Sorry for putting all these stuff into one PR. These commits only work when come together, and I didn't find a good way to split them.
Probably better to review this commit by commit. Detailed description is in each commit message.
Most unknowns from the original implementation were resolved in recent research. There are still a few unknowns remained to test, for which I made assumptions and put ASSERT for them. This branch has been tested in bleeding edge and no ASSERT crash has been reported.
----
For anyone who has reviewed [JayFoxRox's GS branch](https://github.com/jayfoxrox/citra/pull/49), implementation difference in this branch are listed here for reference:
- respects the …
> PICA: implemented geometry shader

- .travis-build.sh
This fixes that osx builds won't send any telemetry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2923)
> travis_OSX: build with system curl

- CMakeLists.txt
- CMakeModules/DownloadExternals.cmake
- appveyor.yml
- externals/CMakeLists.txt
The mingw builds aren't submitting telemetry because the curl library
they are linked against is configured to use openSSL and openSSL looks
for the certificates in the users home folder. This keeps it from
contacting web services because it can't communicate over SSL.
This commit adds a download in mingw builds that will download a
precompiled curl for mingw linked against winssl and sspi.
This change is dependent on https://github.com/citra-emu/ext-windows-bin/pull/7 so **do not merge before that one** This PR won't even build properly without it. I'm submitting this PR now so we can get the ext-win-bin one merged sooner than later, so we can get this one merged as well. After that one is merged, we will need to do some more testing on different machines to verify that everything is …
> Build: Enable SSL in mingw by linking against WinSSL

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/core.cpp
- src/core/hle/kernel/memory.cpp
- src/core/hle/kernel/memory.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/vm_manager.cpp
- src/core/hle/kernel/vm_manager.h
- src/core/loader/3dsx.cpp
- src/core/loader/elf.cpp
- src/core/loader/ncch.cpp
- src/core/memory.cpp
- src/core/memory.h
- src/core/memory_setup.h
- src/tests/core/arm/arm_test_common.cpp
This PR also implements a proper Memory::GetPhysicalPointer that doesn't depend on the current process' memory map.
This is just one step towards the ultimate goal of being able to load multiple processes simultaneously in citra.
This PR has a performance regression regarding dynarmic and fast page-table access. It should be reimplemented once dynarmic supports runtime pagetable switches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2842)
> Kernel/Memory: Give each process its own page table and allow switching the current page table upon reschedule

- src/video_core/regs_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/swrasterizer/clipper.cpp
Not sure if this is used by any games, but since it was also tested in my previous PR, it can be just implemented now so that we won't forget it later.
[Here is a test program](https://github.com/wwylele/ctrhwtest/tree/master/clip-plane)
In GL implementation, the clipping calculation is in the vertex shader, which now needs uniform input. So I let vertex shader and fragment shader share the same uniform block and put the clip coefficient there.
I also flipped the sign convention of the sw clipper to use the same rule that GL and PICA use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2900)
> PICA: implement custom clip plane

- .travis-build-docker.sh
Fixes issue that linux builds can't send telemetry.
It could be necessary that users have to install libcurl on their system for citra to work:
`apt-get install libcurl4-openssl-dev`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2936)
> WebService: Set USE_SYSTEM_CURL for travis linux builds

- src/core/CMakeLists.txt
- src/core/file_sys/archive_selfncch.cpp
- src/core/file_sys/archive_selfncch.h
- src/core/file_sys/ncch_container.cpp
- src/core/file_sys/ncch_container.h
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
NCCH parsing was split off into `FileSys::NCCHContainer` to allow for multiple NCCHs to be loaded in the NCCH loader. If an update NCCH is found in `sdmc:/Nintendo 3DS/.../title/<TID High>/<TID Low>/content/00000000.app` its ExeFS and ExHeader will override the base game's ExeFS and ExHeader, and the UpdateRomFS in SelfNCCH will load from the update NCCH instead of the base game NCCH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2927)
> Loader/NCCH: Add support for loading application updates

- src/citra_qt/configuration/configure_graphics.ui
- src/citra_qt/configuration/configure_system.cpp
- src/citra_qt/configuration/configure_web.cpp
This doesn't fix all untranslated strings, though. There are some strange problem with game_list.cpp where adding missing tr() generates `tr cannot be called without context` warnings. Qt might gets confused with multiple/nested class there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2949)
> citra-qt: fix some untranslated strings

- src/video_core/utils.h
It is now better. The modulo also make it clearer (which are optimized to &7 anyway)
https://godbolt.org/g/W6VQt1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2951)
> Optimized Morton

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/hle/kernel/thread.cpp
- src/core/loader/3dsx.cpp
- src/core/loader/elf.cpp
- src/core/loader/ncch.cpp
- src/core/memory.cpp
- src/core/memory.h
- src/tests/core/arm/arm_test_common.cpp
Restores the page table optimization in the CPU JIT.
Completes [this card](https://github.com/citra-emu/citra/projects/3#card-4172636).
* `Core::CPU().LoadContext` must be called after `Memory::SetCurrentPageTable`, so the CPU state is set to the correct instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2952)
> Switchable Page Tables

- src/core/file_sys/archive_selfncch.cpp
- src/core/file_sys/archive_selfncch.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/core/loader/3dsx.cpp
- src/core/loader/ncch.cpp
The loaders now register each loaded ROM with the SelfNCCH factory, which keeps the data around for the duration of the emulation session.
When opening the SelfNCCH archive, the factory queries the current program's programid and uses that as a key to the map that contains the NCCHData structure (RomFS, Icon, Banner, etc).
This is another PR on the Road To Multiprocess (TM)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2947)
> HLE/Archives: Allow multiple loaded applications to access their SelfNCCH archive independently.

- src/audio_core/codec.cpp
- src/audio_core/codec.h
- src/audio_core/hle/source.h
- src/audio_core/interpolate.cpp
- src/audio_core/interpolate.h
The current code inserts and deletes elements from the beginning of the audio buffer, which is very inefficient in an std::vector.
Profiling was done using VisualStudio2017's Performance Analyzer in Super Mario 3D Land.
Before this change: AudioInterp::Linear had 14.14% of the runtime (inclusive) and most of that time was spent in std::vector's insert implementation.
After this change: AudioInterp::Linear has 0.36% of the runtime (inclusive)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2958)
> Audio: Use std::deque instead of std::vector for the audio buffer type (StereoBuffer16)

- src/common/vector_math.h
- src/video_core/swrasterizer/clipper.cpp
It is unlikely we will ever use this without first doing a Cast to a signed type.
Fixes 9 "unary minus operator applied to unsigned type, result still unsigned" warnings on MSVC2017.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2907)
> Disable unary operator- on Math::Vec2/Vec3/Vec4 for unsigned types.

- src/core/core.cpp
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
- src/core/loader/3dsx.cpp
- src/core/loader/3dsx.h
- src/core/loader/elf.cpp
- src/core/loader/elf.h
- src/core/loader/loader.h
- src/core/loader/ncch.cpp
- src/core/loader/ncch.h
- src/core/memory.cpp
- src/core/memory.h
- src/tests/CMakeLists.txt
- src/tests/core/arm/arm_test_common.cpp
- src/tests/core/memory/memory.cpp
The loaders will now just create a Kernel::Process, construct it and return it to the caller, which is responsible for setting it as the current process and configuring the global page table.
This behavior is needed for loading extra NCCHs while a game is already running (applets, system modules, etc).
This PR can be reviewed commit by commit.
Ultimately I want to make it so `current_page_table` is no longer needed, and all operations happen on the currently scheduled process by default, with overloads to operate on any arbitrary process:
```cpp
IsValidVirtualAddress(VAddr) = IsValidVirtualAddress(g_current_process, VAddr);
GetPointer(VAddr) = GetPointer(g_current_process, VAddr);
...
```
and so on
--- …
> Loaders: Don't automatically set the current process every time we load an application.

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/wait_object.cpp
- src/core/hle/svc.cpp
This change makes for a clearer (less confusing) path of execution in the scheduler, now the code to execute when a thread awakes is closer to the code that puts the thread to sleep (WaitSynch1, WaitSynchN). It also allows us to implement the special wake up behavior of ReplyAndReceive without hacking up WaitObject::WakeupAllWaitingThreads.
If savestates are desired in the future, we can change this implementation to one similar to the CoreTiming event system, where we first register the callback functions at startup and assign their identifiers to the Thread callback variable instead of directly assigning a lambda to the wake up callback variable.
I wanted to add [some tests](https://gist.github.com/Subv/7d83131e571f34ffcbf0ac8c4edc7182) for this new code but that's currently blocked by …
> Kernel/Threads: When putting a thread to wait, specify a function to execute when it is awoken

- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/memory.cpp
- src/core/memory.h
We can use these for accessing the memory of a different process using virtual addresses.
I plan on using these overloads when implementing command buffer translation for svcReplyAndReceive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2971)
> Memory: Add overloads for ReadBlock and WriteBlock that operate on a specific process.

- .travis-build.sh
- .travis-upload.sh
This commit produces a fat-binary with two slices. The x86_64 slice
is for all x64 systems, and the x86_64h slice targets x64 systems
starting with Haswell. The latter allows the compiler to use newer
instructions that are not available on older microarchitectures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2982)
> macOS: Build x86_64h slice

- src/core/CMakeLists.txt
- src/core/file_sys/archive_ncch.cpp
- src/core/file_sys/ncch_container.cpp
- src/core/file_sys/ncch_container.h
- src/core/file_sys/title_metadata.cpp
- src/core/file_sys/title_metadata.h
- src/core/loader/ncch.cpp
- archive_ncch now uses NCCHContainer instead of loading a .romfs
- Backward compatibility with existing is maintained through RomFS override, ExeFS override has also been added which fixes #2735 
- A class for reading from and writing to TMDs has been added, which paves the way for title install via CIAs
- archive_ncch will use title metadata to determine the content ID for the main executable. This allows for decrypted NAND contents to be used without altering the file structure.
- The NCCH loader will also use title metadata to determine the content ID for update NCCHs, given 
RomFS and ExeFS override is per-NCCH. For example, if I have a update of Smash installed as `sdmc:/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/000ee000/content/000 …
> file_sys/archive_ncch: use NCCHs/.apps instead of .romfs files, NCCH section override

- src/core/gdbstub/gdbstub.cpp
- src/core/hle/function_wrappers.h
- src/core/hle/svc.cpp
Memory::GetPointer is an unsafe function that will only bring us potential out-of-bounds access and buffer overruns if the emulated address space stops being always contiguous for whatever reason.
After this PR there are only 7 remaining references to GetPointer, 2 of which are the declaration and definition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2991)
> Remove more usages of GetPointer.

- src/core/hle/service/nwm/nwm_uds.cpp
**_Super Street Fighter IV: 3D Edition_** is calling the deprecated _nwm::UDS Initialize_ function with command header `0x000102C2` but in _Citra_ it uses `0x00010442` instead which causes the crash due to the game receiving garbage data.
Credits to @Subv
https://github.com/citra-emu/citra/issues/2959#issuecomment-332081439
Fixes issue #2959
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3002)
> Change command header in nwm::UDS Initialize function

- src/citra_qt/configuration/config.cpp
- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
- src/citra_qt/ui_settings.h
I  added mode fullscreen for play with more comfort.
For display fullscreen,  just click on action bar or the shortcut : alt+return
For exit fullscreen just click in alt+return or escape
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3001)
> citra-qt : Adding fullscreen mode

- src/video_core/renderer_opengl/gl_rasterizer_cache.h
Eliminate the following warning in MinGW:
```
warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
#pragma GCC diagnostic ignored "-Wunused-local-typedef"
^~~~~~~~~~~~~~~~~~~~~~~~
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3033)
> Fix typo for -Wunused-local-typedefs

- src/core/hle/service/nwm/uds_beacon.cpp
- src/core/hle/service/nwm/uds_data.cpp
Eliminate the following warning shown in GNU/MinGW compiler
`#warning "You may be using a weak algorithm that has been retained for backwards compatibility. Please '#define CRYPTOPP_ENABLE_NAMESPACE_WEAK 1' before including this .h file and prepend the class name with 'Weak::' to remove this warning."`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3031)
> externals: Remove Crypto++ weak algorithm warning

- src/citra_qt/configuration/configure_debug.ui
Fixes this warning:
`The name 'label' (QLabel) is already in use, defaulting to 'label1'.`
Also rename a few class names accordingly.
Reduce warning count from 59 --> 57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3030)
> citra-qt: Rename derivative class name

- src/core/hle/service/soc_u.cpp
Eliminate the following warning in MinGW compiler:
```
C:/projects/citra/src/core/hle/service/soc_u.cpp:32:0: warning: "EIDRM" redefined
#define EIDRM 2001
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/pthread.h:63:0,
from C:/msys64/mingw64/include/c++/6.3.0/x86_64-w64-mingw32/bits/gthr-default.h:35,
from C:/msys64/mingw64/include/c++/6.3.0/x86_64-w64-mingw32/bits/gthr.h:148,
from C:/msys64/mingw64/include/c++/6.3.0/ext/atomicity.h:35,
from C:/msys64/mingw64/include/c++/6.3.0/bits/basic_string.h:39,
from C:/msys64/mingw64/include/c++/6.3.0/string:52,
from C:/msys64/mingw64/include/c++/6.3.0/stdexcept:39,
from C:/msys64/mingw64/include/c++/6.3.0/array:39,
from C:/msys64/mingw64/include/c++/6.3.0/tuple:39,
from C:/msys64/mingw64/include/c++/6.3.0/unordered_map:41,
from …
```
> Remove some errno constants as it was already defined

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3037)
> Fix Missing libpcre2-16-0.dll from both latest Nightly and Canary builds #3036

- .travis.yml
It's annoying to wait for travis-ci to build for linux and osx, to then see that clang-format is wrong. This changes the build order to first check for clang-format, then build linux and then osx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3034)
> Change build order to check clang-format first

- .travis/linux/build.sh
- src/citra_qt/main.cpp
QKeySequence::Cancel requires Qt 5.6, which our buildbots do not support.
Also ensure that an error in the Linux build-script propagates upwards.
Closes #3022 and #3023.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3028)
> citra_qt: Remove use of QKeySequence::Cancel

- src/audio_core/sdl2_sink.cpp
We currently do not handle the cases when channel number or channel format differ from what we expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3046)
> sdl2_sink: Disallow audio device from changing any parameter other than the frequency

- appveyor.yml
This PR is a workaround for SDL2 2.0.6 having a bug with audio output, the bug report is right here: https://bugzilla.libsdl.org/show_bug.cgi?id=3858 - Thanks @MerryMage !
This PR also downgrades the SDL2 version to 2.0.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3047)
> Workaround for SDL2 2.0.6 audio issues

- src/core/file_sys/archive_ncch.cpp
https://github.com/citra-emu/citra/blob/f75dd34747f35cda5ae8ca2c74439034aa0f5b1f/src/core/file_sys/archive_ncch.cpp#L196
This is hidden behind `LOG_TRACE` so it only breaks debug build. So again, please consider adding debug build to CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3053)
> file_sys: Add missing header for PRIU64

- src/video_core/swrasterizer/clipper.cpp
- src/video_core/swrasterizer/clipper.h
- src/video_core/swrasterizer/rasterizer.cpp
- src/video_core/swrasterizer/rasterizer.h
- src/video_core/swrasterizer/swrasterizer.cpp
- src/video_core/swrasterizer/swrasterizer.h
I'm not sure if I am doing it correctly, hence the [RFC] tag.
I've read online and got to know that `static_cast` performs no runtime checks and I believe that is the reason all warnings got rid completely.
These are the warnings I'm trying to get rid of in GNU/MinGW compiler:
```
C:/projects/citra/src/video_core/swrasterizer/rasterizer.cpp: In function 'void Pica::Rasterizer::ProcessTriangleInternal(const Pica::Rasterizer::Vertex&, const Pica::Rasterizer::Vertex&, const Pica::Rasterizer::Vertex&, bool)':
C:/projects/citra/src/video_core/swrasterizer/rasterizer.cpp:380:55: warning: narrowing conversion of 'border_color.Pica::TexturingRegs::TextureConfig::<unnamed union>::r.BitField<0, 8, unsigned int>::operator unsigned int()' from 'unsigned int' to 'unsigned char' inside { } …
```
> Get rid of narrowing conversion warning (-Wnarrowing)

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/am_app.cpp
- src/core/hle/service/am/am_sys.cpp
Fixes #2980 (thanks to @mailwl for finding the actual issue there)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3048)
> Services/AM: Implement GetPatchTitleInfos, Misc Cleanup

- src/core/memory.cpp
Making a comment easier to read by changing the order of the verb to make a correct sentence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3060)
> Correcting word order of a comment in memory.cpp

- .travis.yml
- .travis/linux-frozen/build.sh
- .travis/linux-frozen/docker.sh
- .travis/linux-frozen/install_package.py
Related to #3023.
Adds a build which pulls specific versions of packages so we can ensure new code is compatible with those specific library versions. Unfortunately Ubuntu's apt repositories remove older versions regularly, so we can't use apt-get's built-in version specifiers and have to pull the packages directly from Ubuntu's archives.
Justification for each version:
* Qt 5.2: 5.2 is the newest version available in repositories of some Linux distributions
* SDL 2.0.4: No particular reason
* libicu52: Required for pulling Qt 5.2 because the Xenial repositories no longer have this package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3027)
> travis: Add build with frozen versions for dependencies

- src/core/hle/service/nwm/nwm_uds.cpp
- src/core/hle/service/nwm/nwm_uds.h
- src/core/hle/service/nwm/uds_data.cpp
- src/core/hle/service/nwm/uds_data.h
This implements some missing/unimplemented functions in the NWM::UDS-Service:
- SendTo
- PullPacket
- Bind
- Unbind
- GetNodeInformation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2989)
> Service/UDS: Implement Bind, Unbind, SendTo, PullPacket, and GetNodeInformation

- src/core/hle/service/ac/ac.cpp
- src/core/hle/service/ac/ac.h
- src/core/hle/service/ac/ac_i.cpp
- src/core/hle/service/ac/ac_i.h
- src/core/hle/service/ac/ac_u.cpp
- src/core/hle/service/ac/ac_u.h
- src/core/hle/service/service.cpp
~There are a few service functions whose command header doesn't seem to match their parameters, why does `CreateDefaultConfig`, with a command header of `0x00010000`, work on a static buffer?~
~3dbrew has no information on that function~
I've reverse engineered a bit of the AC module and fixed some missing/wrong parameters in the response command buffers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2992)
> Services/AC: Converted the ac:i and ac:u services to the new service framework.

- src/core/hle/service/soc_u.cpp
Soc_u is the reason for most of the WSAStartup issues. It calls WSAStartup only on SOC_U::InitializeSockets,
but calls WSACleanup every time it gets destructed in addition to SOC_U::ShutdownSockets. Thus calling WSACleanup way more often than WSAStartup and thus close it although other parts of the code still need the sockets.
With that, we should test if removing WSAStartup in web_service is possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3067)
> Removed duplicate calls of WSACleanup in soc_u.

- src/core/hle/kernel/errors.h
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/mutex.h
- src/core/hle/svc.cpp
This behavior was reverse engineered from the 3DS kernel.
It is unknown if this affects any games.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3042)
> Kernel/SVC: Don't let svcReleaseMutex release a mutex owned by another thread

- src/core/hle/kernel/mutex.cpp
Fixes a regression in #3042.
Closes #3079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3080)
> Kernel/Mutex: Add a missing return in Mutex::Release

- src/citra_qt/aboutdialog.ui
- Widgets are located at fixed position with fixed size, instead of managed by layouts
- Line breaks are hardcoded to fixed location in the text.
- The links don't work due to missing the `openExternalLinks` flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3081)
> citra-qt: fix broken About box

- src/citra_qt/debugger/wait_tree.cpp
- src/core/CMakeLists.txt
- src/core/hle/kernel/errors.h
- src/core/hle/kernel/ipc.cpp
- src/core/hle/kernel/ipc.h
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/server_session.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/svc.cpp
Currently only MoveHandle, CopyHandle and CallingPid translate descriptors are implemented.
The real kernel's ReplyAndReceive will retry the call until one of the objects can be acquired without causing a translation error, this is not currently implemented and the code will instead assert that the translation was a success.
With this you can now run system services in LLE.
It's better if you review this commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2981)
> Kernel/SVC: Implement LLE command buffer translation in ReplyAndReceive

- src/core/hle/service/ac/ac_i.cpp
- src/core/hle/service/ac/ac_u.cpp
The number was reverse engineered from the AC module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3078)
> Services/AC: Corrected the number of concurrent connections for AC_I and AC_U

- src/core/hle/kernel/thread.cpp
System services usually have Core1 in this field, but citra was running them in Core0 regardless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3082)
> Kernel/Thread: Run the main thread in the CPU specified by the process' exheader.

- src/core/file_sys/cia_container.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/am_app.cpp
- src/core/hle/service/am/am_sys.cpp
This PR can be reviewed commit-by-commit.
This PR renames three functions which require DLC TIDs and adds appropriate errors for when non-DLC TIDs are passed to them. Mapped buffers are passed back as appropriate. Some previous warnings have also been fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3087)
> Services/AM: Add errors and adjust naming for accuracy

- src/core/file_sys/cia_container.cpp
found this while failing at making a CIA Installation UI, Subv told me to get rid of it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3092)
> Get Rid of Redundant !

- src/core/hle/service/am/am.cpp
"a" and "w" screws with 0xA (\n) bytes on Windows machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3114)
> Services/AM: Fix content writing on Windows

- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/server_session.cpp
The error code 0xC920181A will be returned by svcReplyAndReceive when the wakeup callback runs.
This lets LLE services be properly notified of clients closing the connection so they can end their handler threads instead of letting them linger indefinitely, taking up connection slots in their parent port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3088)
> Kernel/Sessions: Wake up any threads waiting on a ServerSession when its client is closed

- CMakeLists.txt
hicolor is the preferred location for applications. See https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3007)
> Install Linux icon in hicolor instead of pixmaps

- src/core/hle/ipc.h
- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/ac/ac.cpp
- src/core/hle/service/apt/apt.cpp
- src/core/hle/service/frd/frd.cpp
- src/core/hle/service/fs/fs_user.cpp
- src/core/hle/service/ir/ir_user.cpp
- src/core/hle/service/nwm/nwm_uds.cpp
- src/tests/core/hle/kernel/hle_ipc.cpp
The real kernel requires services to set up their static buffer targets ahead of time. This implementation does not require that and will simply create the storage for the buffers as they are processed in the incoming IPC request.
Static buffers are kept in an unordered_map keyed by their buffer id, and are written into the already-setup area of the request thread when responding an IPC request.
This fixes a regression (crash) introduced in #2992.
This PR introduces more warnings due to the [[deprecated]] attribute being added to void PushStaticBuffer(VAddr buffer_vaddr, size_t size, u8 buffer_id); and VAddr PopStaticBuffer(size_t* data_size);
--- …
> Kernel/IPC: Implement StaticBuffer translation for HLE services that use the HLERequestContext architecture.

- src/core/arm/dynarmic/arm_dynarmic.cpp
Bugfix of 67a70bd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3135)
> arm_dynarmic: ClearInstructionCache should clear all instruction caches

- appveyor.yml
This fixes #3051. The main cause is described here https://gitlab.kitware.com/cmake/cmake/issues/17436. Appveyor currently uses cmake 3.9.2 which has this issue. In 3.9.6 the issue is fixed. So we set mingw to use that version. This will also prevent future updates of cmake (which can be positive and negative). The other solution described in the link would be to insert `list(REMOVE_ITEM CMAKE_C_IMPLICIT_LINK_LIBRARIES gcc_eh)`.
Since i can't go in-game with my Windows VM I only tested that citra doesn't crash on verifying the token. Would be good to test if the other crashes are fixed, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3141)
> Appveyor: on mingw set cmake version to 3.9.6

- src/citra/citra.cpp
- src/core/file_sys/title_metadata.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
This PR can be reviewed commit-by-commit.
This PR adds command-line CIA installs with the `-i` or `--install=` argument. Installation is done using the `CIAContainer` and `CIAFile` classes, `CIAContainer` to initially check if a CIA is valid, and `CIAFile` to handle the actual installation.
Example CIA installation command:
`citra -i scummvm.cia`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3113)
> SDL CIA Installation

- src/audio_core/audio_core.cpp
- src/common/CMakeLists.txt
- src/common/fifo_queue.h
- src/common/threadsafe_queue.h
- src/core/core.cpp
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hle/applets/applet.cpp
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/cam/cam.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ir/extra_hid.h
- src/core/hle/service/ir/ir_rst.cpp
- src/core/hle/service/nwm/nwm_uds.cpp
- src/core/hle/shared_page.cpp
- src/core/hw/gpu.cpp
- src/tests/CMakeLists.txt
- src/tests/core/core_timing.cpp
The current CoreTiming has an error that Events scheduled with a cycles_into_future > 0 are called way to late. 
Since thee current implementation is very convoluted and not well documented we decided to just rewrite the whole CoreTiming (adopt the current version from Dolphin).
It was tested that this version and the error isn't there anymore.
This also fixes a wrong BASE_CLOCK_RATE_ARM11 (#2445) and add the ability to jump cycles by ns (in addition to ms and us).
It also adds some overflow handling when calculation cycles out of ns/us/ms.
In a last step it adds Test for checking CoreTiming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3119)
> CoreTiming: Reworked CoreTiming

- src/core/hle/kernel/hle_ipc.cpp
This could happen if the guest application performs a request with static buffer id X, and the service module responds with another static buffer with the same id X.
Closes #3158 #3152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3160)
> HLE/IPC: Don't assert in HLERequestContext::AddStaticBuffer when there's already a static buffer with the desired id

- src/core/file_sys/ncch_container.cpp
- src/core/file_sys/ncch_container.h
Paves the way for proper NCSD loading, NCSD partition parsing in NCCH archives (for the manual applet, DLP, maybe update partitions), parsing of NCCHs held within CIAs (for frontend parsing, possible loaders). Pretty much anything with an NCCH (or several) not at 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3120)
> file_sys/ncch_container: Expose ncch_offset during instantiation and in OpenFile

- src/network/packet.cpp
Previously this would cause a -Wnull-conversion warning
This is a remnant of the safe-bool idiom that was made obsolete with C++11 and greater via explicit conversion operators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3162)
> packet: Simplify operator bool overload

- src/audio_core/hle/source.cpp
Bugfix for ff280800.
`has_played` was not updating.
Note `input_queue` is a priority queue so elements would be reordered appropriately on insert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3151)
> Audio/HLE/Source: Fix looped state not updating

- src/tests/common/param_package.cpp
Keeps our unit-testing library up to date. Since it's a major version update, quite a bit of legacy stuff was removed from the library, along with several improvements, which can be found in the changelog [here](https://github.com/catchorg/Catch2/releases)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3161)
> externals: Update catch to v2.0.1

- src/citra/citra.cpp
This allows to connect to a room with the SDL frontend
Usage: -m, --multiplayer=nick:password@address:port with Nickname, password, address and port for multiplayer. Password and port can be optional
This PR requires #3068 to get merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3072)
> SDL: add multiplayer options

- src/citra_qt/main.cpp
- src/citra_qt/main.h
- src/citra_qt/main.ui
Adds QT CIA installation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3144)
> QT CIA installation

- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/fs/archive.h
- src/tests/core/hle/kernel/hle_ipc.cpp
The last missing block of `HLERequestContext`. A `MappedBuffer` object is used to represent the memory block the kernel sets up for the service.
Note that this kind of translation is asymmetrical: for client->service request, the kernel sets up the mapped buffer; for service->client response, the kernel unmaps the buffer instead. Because `MappedBuffer`'s lifetime is managed by the context, we don't need to do anything in the response other than modifying the command buffer.
In the test, the reading buffer (with permission R) is tested in command buffer request, while writing buffer (with permission W) is tested after command buffer response. This is because the real kernel can copy the buffer data only after unmapping when handling response, and the HLE implementation can be in the same …
> Kernel/IPC: Implement MappedBuffer translation for HLE services that use the HLERequestContext architecture.

- src/tests/CMakeLists.txt
- src/tests/video_core/shader/shader_jit_x64_compiler.cpp
- src/video_core/CMakeLists.txt
- src/video_core/shader/shader_jit_x64_compiler.cpp
- src/video_core/shader/shader_jit_x64_compiler.h
We reimplement log2f and exp2f in assembly.
Algorithms were inspired by those found in Mesa I've used a higher order approximation for exp2 than they did for more accuracy.
Performance numbers (for 1.2 billion sequential calls of the same instruction on my machine):
| Instruction | Old time | New time |
| ------------- | ------------- |  ------------- |
| `ex2` | 21.5s | 8.8s |
| `lg2` | 13.3s | 7.3s |
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3145)
> shader_jit_x64_compiler: Remove ABI overhead of LG2 and EX2

- src/core/hle/ipc_helpers.h
- src/core/hle/service/fs/archive.cpp
- src/core/hle/service/sm/srv.cpp
Although the move/copy bit in the handle descriptor doesn't mean anything to HLE service, it does make a different from client's point of view. A game can specifically check this bit if it matches expected result. IIRC I observed a similar checking code in service, which can be reused by games. So we should allow HLE service be able to specify this move/copy bit.
Among the four current user of `PushObjects`, `SRV::EnableNotification` was specifically marked as copying handles before `HLERequestContext` implemented, so this behaviour is restored here. ~~The other three don't have clear documentation anywhere whether they were move or copy, so I left them as-is.~~ According to Subv, they are indeed all `Move`
--- …
> ipc_helper: split PushMoveObjects and PushCopyObjects

- src/common/vector_math.h
Makes behavior between both overloads consistent.
Technically, `i` can also be made `size_t` or `ptrdiff_t` (if we'd like to keep signed around), to avoid sign-extending all the time before the access, but I'd probably keep that for a second PR if doing that is desirable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3185)
> vector_math: Return by const reference for const operator[]

- .gitmodules
This PR switches the Inih Submodule from it's mirror repository `svn2github/inih` to it's official repo at `benhoyt/inih`
As explained in Info, svn2github is a Mirror Host, which was used mainly as there was no official repo for inih at the time it was originally added. However, now that there is a Official repo, svn2github would be considered unnecessary as well as inconsistent to keep around. This commit aims to make it easier to manage this submodule in the future, as well as able to fix/report issues related to inih, should any appear in the foreseeable future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3178)
> Inih: Switch inih to It's Official Repository @ benhoyt/inih

- src/core/arm/skyeye_common/vfp/vfp_helper.h
- src/core/arm/skyeye_common/vfp/vfpdouble.cpp
Fixes two issues that will never happen:
1. There are cases when VFP_REG_ZERO will be non-zero, but these will never be encoutered in well behaved guest code (i.e. writing to D16).
2. If CONFIG_VFPv3 is defined, accessing VFP_REG_ZERO would be out of bounds.
The double `vfp_compare` is now more-or-less identical to its single counterpart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3174)
> dyncom: Remove VFP_REG_ZERO

- src/core/hle/service/nfc/nfc.cpp
- src/core/hle/service/nfc/nfc.h
Fixes an issue in Smash 4's version 1.1.7 where a Kirby amiibo (or an invalid Amiibo) would constantly be scanned in.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3173)
> Services/NFC: Stub StartTagScanning as it should be for o3DS

- src/video_core/pica_types.h
The compiler might not flatten the branches, so it's better to check the rarely true condition first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3193)
> video_core: optimize NaN check

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/arm/dyncom/arm_dyncom_interpreter.cpp
- src/core/core.cpp
- src/core/core.h
- src/tests/core/arm/dyncom/arm_dyncom_vfp_tests.cpp
We also correct the CPU JIT's implementation of Step while we're at it.
The JIT now does the equivalent of following when executing a SVC instruction:
CoreTiming::AddTicks(ticks_executed);
SVC::CallSVC(imm32);
ticks_to_execute = std::max(CoreTiming::GetDowncount(), 0);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3184)
> core/arm: Improve timing accuracy before service calls in JIT

- src/citra_qt/configuration/configure_input.cpp
- src/citra_qt/configuration/configure_input.h
- src/citra_qt/configuration/configure_input.ui
- src/input_common/main.cpp
- src/input_common/main.h
- src/input_common/sdl/sdl.cpp
- src/input_common/sdl/sdl.h
This PR adds the ability to configure controls using SDL gamepads (or joysticks, I guess). I created some scaffolding so that the settings dialog can ask for inputs from input backends. Basically, there is now an abstract DevicePoller class (if anyone has a better name, let me know) which can be implemented by different backends to return inputs.
There are a few ugly corners, which might or might not be a problem:
- The poller for SDL devices drops all SDL events it doesn't need. The Qt frontend doesn't use them, so it should be fine, but there might be other problems I'm not aware of.
- Configuring the analog sticks might be a bit confusing, because now you can configure them with 5 buttons, or an actual analog stick. Might need a better GUI for this.
- The buttons still have placeholder …
> Allow input configuration with SDL joysticks

- src/core/hle/service/apt/apt.cpp
This adds the Applet ID to the message on Assert when a unknown id is encountered.
We recently get some messages that games crash on that point. The games usually crash later when citra tries to emulate the applet.
This will help to identify which applets are missing. Dumping that applet and adding the id to the list of applets could fix those games.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3225)
> Applet: Print unknown AppletId on ASSERT

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/dyncom/arm_dyncom.cpp
- src/core/arm/dyncom/arm_dyncom.h
- src/core/hle/service/ldr_ro/cro_helper.cpp
- src/core/hle/service/ldr_ro/ldr_ro.cpp
Add the necessary interface to ARM_Interface, then uses it in the ro service. Reduces stuttering during loading and unloading of CROs.
Based on @Phanto-m's suggestion [here](https://github.com/Phanto-m/dynarmic/commit/0b522d462a153ca0c09a4d10fb7dadad3cecee0b#commitcomment-26017040).
Previous PR: #2925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3227)
> Allow for partial invalidation of instruction cache

- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/dyncom/arm_dyncom.h
Avoids implicit conversions. Fairly trivial change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3228)
> arm: Make CPU backend constructors explicit

- src/core/arm/dyncom/arm_dyncom_dec.cpp
- src/core/arm/dyncom/arm_dyncom_dec.h
This isn't used externally anywhere (and really shouldn't be, because it would mean decoding logic is being duplicated elsewhere in some form, or that assumptions are being hardcoded about the table layout).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3229)
> arm_dyncom_dec: Hide the decoding table from external view
