citra-emu/citra

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Also joins the REV ops into one common place.

dyncom: Implement REVSH

---

src/core/arm/skyeye_common/vfp/vfpinstr.cpp

Removes some dead code, also removes some log messages that are no longer relevant.

VFP: Minor cleanup, functionally the same.

---

src/citra_qt/main.cpp
src/core/loader/loader.cpp

Support room format .3ds files

Loader: Add support for loading NCCH ROMs with the .3DS extension

---

src/core/hle/kernel/address_arbiter.cpp

AddressArbiter: Ported arbitration type 2 from 3dmoo.

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Easy skyeye todo fix.
Also 420th PR snipe.

dyncom: Actually set the Q flag for SMLABB/SMLABT/SMLATB/SMLATT

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Just in case some game studio let the intern write inline assembly or something.

dyncom: Partially emulate BXJ

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Moves over SMLALXY from the armemu. With this, all SM* ops are now implemented.

dyncom: Move over SMLALXY

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/arm/arm_interface.h
src/core/arm/dyncom/arm_dyncom.cpp
src/core/core_timing.cpp
src/core/core_timing.h

I'm looking for comments on this, it's needed to get a clean implementation of Timers and wait timeouts, please note that I only implemented it for Dyncom because the armemu code scares me to death.

Ported the CoreTiming namespace from PPSSPP

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Wasn't doing proper sign-extension

dyncom: Fix SMULWB/SMULWT

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

These need to be done as a 64-bit operation.

dyncom: Fix UMAAL

---

src/common/common.h
src/common/log.h
src/common/logging/log.h
src/core/hle/result.h
src/core/hle/service/apt_u.cpp
src/core/hle/service/fs/fs_user.cpp
src/core/hle/service/gsp_gpu.cpp
src/core/hle/service/hid_user.cpp
src/core/hle/service/ptm_u.cpp
src/core/hle/service/service.h
src/core/hle/service/srv.cpp
src/core/hle/svc.cpp

* Log all called service functions (under trace)
* Compile out all trace logs under release for performance.
* Add Archive ID to fs:USER debug logs involving opening the archive.

Small additions and fixes to logging

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Previously, MSR would always execute, regardless of its condition flags.

dyncom: Fix conditional execution of MSR

---

src/video_core/vertex_shader.cpp

@neobrain's code from his pica_progress3 branch.

Pica/VertexShader: Implement JMPC/JMPU/CALLC/CALLU.

---

src/video_core/vertex_shader.cpp

@neobrain's code from his pica_progress3 branch.

Pica/VertexShader: Implement the MAD instruction.

---

src/core/CMakeLists.txt
src/core/hle/service/apt_s.cpp
src/core/hle/service/apt_s.h
src/core/hle/service/apt_u.cpp
src/core/hle/service/cfg/cfg_s.cpp
src/core/hle/service/cfg/cfg_s.h
src/core/hle/service/ptm_sysm.cpp
src/core/hle/service/ptm_sysm.h
src/core/hle/service/service.cpp

cfg:s, ptm:sysm, apt:s.
apt:s is almost exactly the same as apt:u as per 3dbrew

Services: Added some missing services.

---

src/citra_qt/debugger/graphics_cmdlists.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/pica.h

@neobrain's code from his pica_progress3 branch.

Pica/Rasterizer: Add ETC1 texture decompression support.

---

src/core/hle/kernel/address_arbiter.cpp
src/core/hle/kernel/address_arbiter.h
src/core/hle/svc.cpp

WaitIfLessThanWithTimeout and DecrementAndWaitIfLessThanWithTimeout

AddrArbiter: Implement arbitration types 3 and 4.

---

src/core/hle/service/apt_u.cpp

Also renamed some handles in the APT:U service to be more descriptive.
Fixed a typo in InquireNotification

APTU: Stubbed NotifyToWait, taken from 3dmoo.

---

src/core/hle/service/gsp_gpu.cpp
src/core/hle/service/gsp_gpu.h
src/core/hw/gpu.cpp
src/core/hw/gpu.h
src/core/hw/hw.cpp
src/video_core/renderer_opengl/renderer_opengl.cpp

Please see individual commit messages.
This fixes the blinking issue present in several games. (See last commit.)
The hwtest mentioned is at https://github.com/yuriks/3ds-gputest/tree/master/flipping

Correctness fixes for GPU flipping and interrupts

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Handles the shifted register variant.

dyncom: Handle the ARM A2 encoding of LDRBT/STRBT.

---

src/core/loader/3dsx.cpp
src/core/loader/3dsx.h
src/core/loader/elf.cpp
src/core/loader/elf.h
src/core/loader/loader.cpp
src/core/loader/loader.h
src/core/loader/ncch.cpp
src/core/loader/ncch.h

Clean up the loader to open the file only once and pass the IOFile around to functions requiring it, and add a real file detection function based on its magic.

Improve the loader a bit

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Removes some unused macros and cleans up indentation inconsistencies

dyncom: Minor cleanup

---

src/core/CMakeLists.txt
src/core/hle/service/cam_u.cpp
src/core/hle/service/cam_u.h
src/core/hle/service/ptm_play.cpp
src/core/hle/service/ptm_play.h
src/core/hle/service/service.cpp

Stubbed some services

---

src/core/hle/service/cam_u.h

Withholding my profanity towards Xcode.

cam_u.h: fix indentation

---

src/core/arm/interpreter/armemu.cpp
src/core/arm/skyeye_common/vfp/vfp.cpp
src/core/arm/skyeye_common/vfp/vfp.h
src/core/arm/skyeye_common/vfp/vfpdouble.cpp
src/core/arm/skyeye_common/vfp/vfpinstr.cpp

This will also get rid of a few (~15) warnings

Cleanup: Logging in Core

---

src/video_core/pica.h
src/video_core/rasterizer.cpp

Cf http://3dbrew.org/wiki/GPU_Commands#Parameter_format_for_command_0x0107

Pica: Implement color/alpha channel enable.

---

src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/interpreter/arminit.cpp
src/core/arm/skyeye_common/armdefs.h
src/core/core.h
src/core/hle/kernel/thread.cpp

Remove unnecessary/unused struct variables.

arm: Clean up ARMul_State

---

src/video_core/pica.h
src/video_core/rasterizer.cpp

Implements all Pica blend factors except for SourceAlphaSaturate. I wasn't totally sure what that one should look like, so if someone wants to chime in I'll add it to this PR as well.

Pica: Implement blend factors.

---

src/citra_qt/debugger/disassembler.cpp
src/citra_qt/debugger/disassembler.h
src/citra_qt/debugger/disassembler.ui

Fixes up some minor annoyances with the disassembly widget:
* Crashes when double-clicking fixed
* Horrible responsiveness when scrolling fixed

Disassembler improvements

---

src/common/logging/log.h

Just something minor I noticed while reading the code.

Fix a wrong file name in a comment

---

src/core/arm/skyeye_common/vfp/vfp.cpp
src/core/arm/skyeye_common/vfp/vfp_helper.h
src/core/arm/skyeye_common/vfp/vfpdouble.cpp
src/core/arm/skyeye_common/vfp/vfpsingle.cpp

Cleans out more code and groups related constants together.

Cleanup related to vfp_helper.

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/skyeye_common/arm_regformat.h

Adds the registers that were left out of some coprocessor ranges.

dyncom: Add more regs to MCR/MRC

---

src/core/file_sys/archive_backend.h
src/core/file_sys/archive_extsavedata.cpp
src/core/file_sys/archive_extsavedata.h
src/core/file_sys/archive_romfs.cpp
src/core/file_sys/archive_romfs.h
src/core/file_sys/archive_savedata.cpp
src/core/file_sys/archive_savedata.h
src/core/file_sys/archive_savedatacheck.cpp
src/core/file_sys/archive_savedatacheck.h
src/core/file_sys/archive_sdmc.cpp
src/core/file_sys/archive_sdmc.h
src/core/file_sys/disk_archive.cpp
src/core/file_sys/disk_archive.h
src/core/file_sys/ivfc_archive.cpp
src/core/file_sys/ivfc_archive.h
src/core/hle/result.h
src/core/hle/service/fs/archive.cpp
src/core/hle/service/fs/archive.h
src/core/hle/service/fs/fs_user.cpp
src/core/hle/service/ptm_u.cpp
src/core/loader/loader.cpp

There's some code related to gamecoin that I had to disable since it wouldn't work with the new stuff. @Subv said he's going to fix it.

FS: Allow multiple instances of the same archive type to be open at once

---

src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/config.cpp
src/common/logging/log.h
src/core/hle/service/cfg/cfg_u.cpp
src/core/hle/service/dsp_dsp.cpp
src/core/hle/service/ldr_ro.cpp
src/core/settings.h

Please note that GenHashConsoleUnique was pretty much taken from 3dmoo

Services: Stub some functions

---

src/core/hle/service/gsp_gpu.cpp

Implemented WriteHWRegsWithMask for GSP.

Implemented WriteHWRegsWithMask for GSP

---

src/citra_qt/CMakeLists.txt
src/citra_qt/debugger/graphics_breakpoint_observer.cpp
src/citra_qt/debugger/graphics_breakpoint_observer.h
src/citra_qt/debugger/graphics_framebuffer.cpp
src/citra_qt/debugger/graphics_framebuffer.h
src/citra_qt/debugger/graphics_vertex_shader.cpp
src/citra_qt/debugger/graphics_vertex_shader.h
src/citra_qt/main.cpp

Adds a simple shader disassembly widget. Some fine-tuning would still be useful probably, but I wanted to get this out so I can focus on other things for now.
Screenshot:
Pretty sure Windows build is broken once again, so some error messages or build fix patches would be appreciated :)

Vertex shader debugger

---

src/common/logging/backend.cpp

Fixes an assertion upon executing citra in debug mode.

backend: Add logging subentry for ldr

---

src/core/arm/dyncom/arm_dyncom_dec.cpp
src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/dyncom/arm_dyncom_run.cpp
src/core/arm/dyncom/arm_dyncom_run.h
src/core/arm/dyncom/arm_dyncom_thumb.cpp
src/core/arm/interpreter/arminit.cpp
src/core/arm/interpreter/armsupp.cpp
src/core/arm/skyeye_common/armdefs.h
src/core/arm/skyeye_common/armemu.h
src/core/arm/skyeye_common/skyeye_defs.h
src/core/arm/skyeye_common/vfp/vfp.cpp
src/core/arm/skyeye_common/vfp/vfp_helper.h
src/core/arm/skyeye_common/vfp/vfpdouble.cpp

- Remove several typedefs for ARMul_State.
- Remove unused functions
- Remove unused/unnecessary headers
- Removed unused enums, etc.

arm: General cleanup

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Idiotville: Population: 1 - Inhabitant name: Lioncash

dyncom: Actually set the destination register for USAD8/USADA8.

---

src/core/hle/service/gsp_gpu.cpp
src/core/hle/service/gsp_gpu.h
src/core/hw/gpu.cpp
src/core/hw/gpu.h
src/video_core/clipper.cpp
src/video_core/command_processor.cpp
src/video_core/pica.h
src/video_core/rasterizer.cpp
src/video_core/vertex_shader.cpp

Touches lots of stuff in basically all areas of the PICA200 code. No real game changers other than rounding off existing code by bugfixing and/or implementing particular configurations.

More PICA200 Emulation Fixes

---

src/core/core_timing.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/gpu_debugger.h

core/video_core: Use in-place construction where possible

---

src/video_core/vertex_shader.cpp

Previously it wouldn't jump back to the start of the loop code once it reached the end of the block.
Fixes the texture problems in a lot of games.
Closes #592

Pica/VertexShader: Fixed LOOP with more than one iteration.

---

src/video_core/rasterizer.cpp

- Fixes a regression with #594.

Rasterize with the correct color component order.

---

src/common/common_funcs.h
src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/err_f.cpp

This was RE'd from the errdisp applet.

Added information reporting from ThrowFatalError

---

src/citra/config.cpp
src/citra/default_ini.h
src/citra/emu_window/emu_window_glfw.cpp
src/citra_qt/bootmanager.cpp
src/citra_qt/config.cpp
src/core/hle/service/hid/hid.h
src/core/settings.h

I used ctrulib’s input example to make sure it was correct.

Frontends, HID: Add New 3DS specific pad buttons, and stub the touch one.

---

src/video_core/rasterizer.cpp

rasterizer: Add support for RGBA4 framebuffer format.

---

src/core/arm/interpreter/arminit.cpp
src/core/arm/skyeye_common/armdefs.h

We don't care about any of these.

arm: Remove unnecessary booleans

---

src/core/file_sys/archive_systemsavedata.cpp
src/core/file_sys/archive_systemsavedata.h
src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/fs/archive.cpp

Required to get Home Menu further.

Archives: Properly implemented the SystemSaveData archive.

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

This is defined by ARM as a read-only register.

arm: The CP15 Main ID register is not writeable

---

src/core/hw/gpu.h
src/video_core/color.h
src/video_core/pica.h
src/video_core/rasterizer.cpp

This allows Virtual Console games to display properly.

Added RGBA5551 compatibility in the rasterizer

---

src/core/arm/skyeye_common/vfp/vfp_helper.h
src/core/arm/skyeye_common/vfp/vfpdouble.cpp

Silences some warnings when compiling with VS.

vfp: Get rid of warnings

---

src/common/assert.h

I'd love if someone could check disassemblies for gcc and clang to see if it works fine there too.
cc @neobrain :)

Asserts: Use lambdas to keep assertion code away from the main code path

---

src/citra_qt/debugger/graphics_vertex_shader.cpp
src/video_core/vertex_shader.cpp

Includes more opcodes to implement in the future.

Update nihstro submodule to the initial release version.

---

src/core/hle/service/cfg/cfg.cpp

Updated GetConfigInfoBlock with actual error codes. Verified with hwtests.

Fix errorcodes for bad config block request

---

src/core/hw/gpu.cpp
src/core/hw/gpu.h

Verified with hwtests: https://github.com/citra-emu/hwtests/pull/30

GPU: Corrected the 24 bit memory fills component order

---

src/citra/emu_window/emu_window_glfw.cpp
src/citra/emu_window/emu_window_glfw.h
src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h
src/common/emu_window.cpp
src/common/emu_window.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h
src/core/hle/service/hid/hid_user.cpp
src/core/hw/gpu.cpp

Adds (preliminary) touchpad support. Tested with homebrew, as well as OoT with both frontends:
I'm calling it "preliminary" because I just implemented the basics to make it work, there are some things in HID shared memory that I'm not emulating (pointed out in the TODOs), and furthermore there might be some behavioral subtleties that I missed (test feedback is appreciated!)

Touchpad support

---

src/core/arm/arm_interface.h
src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/dyncom/arm_dyncom.h
src/core/hle/service/hid/hid.cpp
src/core/hle/svc.cpp

arm_interface: Get rid of GetTicks.

---

src/video_core/vertex_shader.cpp

Credits go to @RHY3756547 for spotting this issue (I rewrote his fix, though, since some ideas came to my mind for cleaning up the shader emulation code).
This should still fix some issue in Super Monkey Ball, hopefully.

Pica/VertexShader: Fix a bug caused due to incorrect assumptions of consecutive output register tables.

---

src/video_core/debug_utils/debug_utils.cpp
src/video_core/utils.h

Changed colour to color in:
util.h, TGAHeader variable names
debug_util.cpp, comment

Changed occurences of colour to color for consistency

---

src/common/thread.h

The helper classes are rendered obsolete by C++11 lambdas. Also made
formatting conform to our code style.
Note: Because these aren't used anywhere in the codebase I couldn't really test them.

Common: thread.h cleanups

---

src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/interpreter/arminit.cpp
src/core/arm/skyeye_common/armdefs.h
src/core/arm/skyeye_common/armemu.h
src/core/core.h

Gets rid of a sizeable amount of stuff in armdefs.

dyncom: Remove more unused/unnecessary code

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/hle/hle.cpp
src/core/hle/hle.h
src/core/hle/svc.cpp
src/core/hle/svc.h

It was a convoluted mess for whatever reason.

HLE: Clean up SVC dispatch mechanism

---

src/video_core/command_processor.cpp
src/video_core/pica.h
src/video_core/vertex_shader.cpp
src/video_core/vertex_shader.h

Fixes the crash in some games like Picross E and Cubic Ninja.

GPU: Implemented default vertex shader attributes.

---

src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/process.cpp
src/core/hle/kernel/process.h
src/core/hle/kernel/thread.cpp
src/core/hle/kernel/thread.h
src/core/hle/svc.cpp

I suggest we create a helper function called GetCurrentProcess, analogous to our GetCurrentThread.

Core/HLE: Implemented the SVCs GetProcessId and GetProcessIdOfThread

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

There's no other coprocessor outside the VFP (which has its own VMOV variants) in which the MPCore can send/retrieve data from.
Stubbed so citra won't crash and burn on the odd chance someone actually tries to use these.

dyncom: Stub MCRR and MRRC

---

src/core/hle/service/ptm/ptm.cpp
src/core/hle/service/ptm/ptm.h
src/core/hle/service/ptm/ptm_play.cpp
src/core/hle/service/ptm/ptm_sysm.cpp
src/core/hle/service/ptm/ptm_u.cpp

I hope Subv doesn't mind... Because I really like how for the HID services have all their stuff in one area, so you don't have to duplicate the same functions all over the place in the related services to it.

PTM: Changed the ptm services  to be like the IR, HID, and APT services.

---

README.md

Update README.md, removing the old Roadmap link and adding the TODO list

---

src/core/arm/skyeye_common/vfp/vfpsingle.cpp

VFP: Log as trace to get rid of spamming.

---

src/core/arm/dyncom/arm_dyncom_thumb.cpp

Whiteboards are pretty handy for this sort of thing

arm_dyncom_thumb: Merge STR/LDR table subsets.

---

src/core/hle/service/hid/hid.cpp

Modifying a variable twice across a sequence point.

hid: Get rid of undefined behavior

---

.travis-build.sh
.travis-deps.sh

Replacement for #842. Continuation of #346 now that xcpretty has supported warnings. [Sample output](https://travis-ci.org/chinhodado/citra/jobs/65013305).

Use xcpretty for xcodebuild on Travis

---

src/core/arm/dyncom/arm_dyncom_thumb.cpp

Prior to this, it'd assume writeback always occurred. However, it should only occur if Rn is not in the register list. Writeback always occurs with STMIA in thumb mode, so it's fine.

arm_dyncom_thumb: Fix handling of writeback for thumb LDMIA

---

src/core/arm/skyeye_common/arm_regformat.h
src/core/arm/skyeye_common/vfp/vfp.cpp
src/core/arm/skyeye_common/vfp/vfpinstr.cpp

These are able to be accessed in any privilege mode.

vfp: Handle accesses to the VFP media feature registers

---

src/core/hw/hw.cpp

hw: Fix mismatched Write call

---

src/core/CMakeLists.txt
src/core/hle/service/y2r_u.cpp
src/core/hle/service/y2r_u.h
src/core/hw/y2r.cpp
src/core/hw/y2r.h

This implements support for all combinations of conversion formats to the y2r implementation. There are still some unknown hardware that haven't been RE'd, but they don't seem to affect the output on my tests.

Color support for Y2R

---

src/core/hle/service/soc_u.cpp

These were found by reverse engineering the soc binary

Services/SOC: Added command headers to some of the soc commands.

---

.travis-build.sh
.travis-deps.sh
.travis-upload.sh
.travis.yml

The expectation was that this would improve build times but they seem to have stayed about the same.
"Most projects see an improvement in build times. We’d love to hear from you if you don’t.", if someone cares enough to contact them about it.
Branch build is green: https://travis-ci.org/citra-emu/citra/builds/70465190

Travis: Remove use of sudo to enable use container-based builds

---

src/video_core/pica.h
src/video_core/rasterizer.cpp
src/video_core/renderer_opengl/pica_to_gl.h

Added GL_CLAMP_TO_BORDER support

---

src/common/bit_field.h

Fixes #913
cc @neobrain @condut

Common: Fix mask generation in BitField

---

src/video_core/command_processor.cpp

The handlers are sorted by register index for improved readability.

Pica/CommandProcessor: Move default attribute setup to the proper position.

---

src/core/hle/service/fs/fs_user.cpp

Namely OpenFileDirectly, OpenDirectory and OpenArchive

Services/Logging: Log more useful information when some operations fail.

---

src/citra_qt/debugger/graphics_cmdlists.cpp
src/citra_qt/debugger/graphics_vertex_shader.cpp
src/citra_qt/debugger/profiler.cpp
src/common/string_util.cpp
src/core/core_timing.cpp
src/core/loader/3dsx.cpp
src/video_core/command_processor.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/pica.h
src/video_core/vertex_shader.cpp

Yet More Warning Fixes

---

src/video_core/pica.cpp
src/video_core/pica.h

This greatly speeds up the command list debug widget.

Videocore: Don't reinitialize register name map on every query

---

src/citra/config.cpp
src/citra/emu_window/emu_window_glfw.cpp
src/citra_qt/bootmanager.cpp
src/citra_qt/config.cpp
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h
src/core/settings.h

As @neobrain suggested in #870 I moved the input mappings into an array and use an enum of Key Values to index the array.

Move input values into an array (#870)

---

src/core/hle/service/am/am_net.cpp

This is based off of 3DBrew and I happened to notice these were missing from the tables.

am_net: Update function table data

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/skyeye_common/vfp/vfpinstr.cpp

More corner-case handling of rare possible operations.

dyncom: Handle the case where PC is the source register for STR/VSTM/VLDM

---

src/citra_qt/main.cpp

This commit adds the save of the path where the last file have been loaded.
However, I don't know if it is a good to keep the path in main.h.

Save the path leading where the last file have been loaded

---

CMakeLists.txt
src/common/common_funcs.h
src/common/file_util.h

Fixes a few minor issues to let Citra compile under MinGW.

Fix building under MinGW

---

src/common/x64/emitter.cpp
src/common/x64/emitter.h

The last four commits can be squashed down to one if necessary.

emitter: Minor cleanup

---

src/video_core/shader/shader_jit_x64.cpp

Same thing, less code to read.

shader_jit: Replace two MDisp usages with MatR

---

src/core/hle/kernel/process.cpp
src/core/hle/kernel/shared_memory.cpp
src/core/hle/kernel/shared_memory.h
src/core/hle/service/apt/apt.cpp

Two small fixes for regressions introduced by #940.
Fixes #1066.

Fix heap-management regressions

---

src/video_core/pica.cpp
src/video_core/pica.h

Pica: Add the vertex_offset register to the Pica registers map.

---

src/video_core/command_processor.cpp
src/video_core/shader/shader_jit_x64.cpp

Fixes some warnings due to format specifiers.

video_core: Fix format specifiers warnings

---

src/core/hle/service/cam/cam_u.cpp

Information from https://github.com/smealum/ctrulib/pull/161, which will be added to 3dbrew shortly.

Add cam:u service function names to its function table

---

src/citra_qt/debugger/graphics_cmdlists.cpp
src/citra_qt/debugger/graphics_vertex_shader.cpp
src/citra_qt/debugger/graphics_vertex_shader.h

A grab bag of improvements to the shader debugger. See individual commits.
cc @neobrain
Branch history:
- yuriks/citra@8275ad6cef470c1ab91536de66506c9086770a2e

Shader Debugger Improvements

---

src/core/hw/y2r.cpp

Keeps compilers/static analyzers quiet.

y2r: Give local variables an initial value

---

src/video_core/clipper.cpp
src/video_core/command_processor.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/pica.cpp
src/video_core/pica.h
src/video_core/primitive_assembly.cpp
src/video_core/rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/renderer_opengl/gl_rasterizer_cache.h
src/video_core/renderer_opengl/gl_shader_util.cpp
src/video_core/renderer_opengl/gl_state.cpp
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/shader/shader_interpreter.cpp
src/video_core/shader/shader_interpreter.h
src/video_core/shader/shader_jit_x64.h
src/video_core/utils.cpp
src/video_core/video_core.cpp

Sorts them all and makes the paths consistent.

video_core: Reorganize headers

---

src/citra_qt/debugger/profiler.cpp
src/citra_qt/debugger/profiler.h
src/common/chunk_file.h
src/common/memory_util.cpp
src/core/core_timing.cpp

Pass 2 Electric Boogaloo (with minor other changes). That should be all of them this time.

Replace 0 literals with nullptr where applicable

---

src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h
src/citra_qt/main.cpp

Stop emulation when render window is closed

---

src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h

citra-qt: Fix connect error on startup (#449)

---

src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h

Fix for the refresh issue is back (cf #1084 ).

Fix refresh issue (only)

---

src/core/hle/service/cfg/cfg.cpp
src/core/tracer/recorder.cpp
src/video_core/gpu_debugger.h
src/video_core/rasterizer.cpp
src/video_core/renderer_opengl/renderer_opengl.h

Also tested compiling under Ubuntu with these changes, couldn't spot any issues.

Fix some xcode 7 (llvm) warnings

---

appveyor.yml

Updates AppVeyor YML file to use Visual Studio 2015.

AppVeyor: Use Visual Studio 2015

---

src/citra_qt/main.cpp
src/core/arm/skyeye_common/vfp/vfp.cpp
src/core/arm/skyeye_common/vfp/vfp.h
src/core/arm/skyeye_common/vfp/vfpdouble.cpp
src/core/loader/3dsx.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/rasterizer.cpp

The LOG_* function itself already appends one.

Remove newlines in LOG_* calls

---

src/core/hle/service/ptm/ptm.cpp
src/core/hle/service/ptm/ptm.h
src/core/hle/service/ptm/ptm_u.cpp

Add GetTotalStepCount Stub

---

src/core/file_sys/archive_backend.h
src/core/file_sys/disk_archive.cpp
src/core/file_sys/disk_archive.h
src/core/file_sys/ivfc_archive.cpp
src/core/file_sys/ivfc_archive.h
src/core/hle/service/fs/archive.cpp
src/core/hle/service/fs/archive.h
src/core/hle/service/fs/fs_user.cpp

Fixes SSB demo showing "no free space" error screen on boot.

Implement FS_User::GetFreeBytes

---

src/core/gdbstub/gdbstub.cpp

Previously, the padding wasn't correctly accounted for which caused the gdbstub to read and write everything after R15 (starting with the dummy FPA registers) incorrectly, which caused CPSR to not be handled correctly. Everything appears to be working as expected with this change.

Fix read and write register blocks in gdbstub

---

src/core/hle/function_wrappers.h
src/core/hle/kernel/memory.cpp
src/core/hle/kernel/memory.h
src/core/hle/kernel/process.cpp
src/core/hle/kernel/thread.cpp
src/core/hle/svc.cpp
src/core/hle/svc.h

This makes smealum/ctrulib@b96dd51d3349961189d4ab1bc2a5c45deff21c09 work with Citra.
cc @fincs @Steveice10

Kernel: Implement svcGetSystemInfo

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/cam/cam.h

Followup to #1102
Original author @mailwl

Services/Cam: Added new log type and camera enums from 3dbrew.

---

src/common/file_util.cpp

I find there is a mistake in #1256. Line of return was deleted and not rewrite it.

Add a return value in ForeachDirectoryEntry 

---

src/core/hle/kernel/address_arbiter.cpp
src/core/hle/kernel/thread.cpp

This was verified with hwtests.
hwtests at https://github.com/citra-emu/hwtests/pull/37

SVC: Fixed ArbitrateAddress to behave as it does on hardware.

---

src/citra_qt/debugger/callstack.cpp
src/citra_qt/debugger/registers.cpp
src/core/core.cpp
src/core/core.h

Death to inconsistent pointer state.

core: Use unique_ptr for holding the interpreter instances

---

src/citra_qt/main.cpp

@Normmatt, can you test whether this fixes #1205?

Gamelist: supply default settings for QSettings config

---

src/common/key_map.h

key_map: Use std::tie for comparisons

---

src/common/color.h

color: Make trivial helpers constexpr

---

src/common/logging/backend.h

backend: defaulted move constructor/assignment

---

README.md

It looks too good NOT to put in there! :wink:

Add website to README. Be proud of it!

---

src/video_core/renderer_opengl/gl_state.cpp

renderer_opengl: Initalise fragment shader LUT textures

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/ir/ir.cpp
src/core/hle/service/ir/ir.h
src/core/hle/service/ir/ir_user.cpp

code from https://github.com/citra-emu/citra/issues/1292
Circle Pad Pro still not supported.

Initial implementation ir:user

---

src/core/hle/service/cfg/cfg.cpp

Fixes missing block issue in #1129.

Service/CFG: Add block 0x000A0000 (username) to default config file

---

README.md

Links on README.md don't exist.

Update Building Links

---

src/core/hle/service/ac_u.cpp

code from: Heroes of the ruin - Hangs at title screen #1157
also fix: Project X Zone 2 - Unimplemented StoreDataCache #1428

ac:u IsConnected implemented

---

src/core/hle/service/dsp_dsp.cpp

It would be useful to know what version of the DSP firmware is used by an application when receiving a bug report.

DSP: Print hash of firmware to console

---

src/core/hle/result.h

core: Use unrestricted union to hold storage of ResultVal value

---

src/core/hle/kernel/process.cpp
src/core/hle/kernel/process.h
src/core/memory.cpp

Memory: Do correct Phys->Virt address translation for non-APP linheap

---

src/citra_qt/main.cpp
src/citra_qt/main.h
src/core/core.cpp
src/core/core.h
src/core/loader/loader.cpp
src/core/system.cpp
src/core/system.h
src/video_core/renderer_base.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_opengl/renderer_opengl.h
src/video_core/video_core.cpp
src/video_core/video_core.h

This PR brings some error popup when something get wrong while loading a ROM. Two cases are handled (at the moment) :
* the user machine does not have OpenGL 3.3
* the ROM is (probably) encrypted
The goal is to give better feedback to the user (with the hope they will stop spamming IRC/GitHub issues crying that the ROM is encrypted).

Output errors in GUI

---

src/core/system.cpp

Fix missing return

---

src/common/x64/emitter.h

Derived partially from an existing pull request that's up for Dolphin. Just figured I'd put it up here as well in case it's desirable.

emitter: constexpr/misc changes

---

src/core/hle/service/gsp_lcd.cpp
src/core/hle/service/http_c.cpp
src/core/hle/service/soc_u.cpp
src/core/hle/service/ssl_c.cpp

Updated based on information from 3dbrew. Trivial stuff

hle: Update service function tables

---

src/core/hle/service/gsp_gpu.cpp

gsp_gpu: Change 0 literal to nullptr

---

src/core/hle/service/hid/hid.cpp

hid: fix pad update

---

src/citra/citra.cpp

citra: Shutdown cleanly if ROM load fails

---

src/citra_qt/main.cpp
src/citra_qt/main.h

Register ROM started through the gamelist in the list of ROM recently started

---

src/core/hle/service/fs/fs_user.cpp

Simple stub for GetArchiveResource.
Fixes #1481.
Disabling JIT, Fire Emblem If is "playable" (random soft lock during battles).

GetArchiveResource stub

---

src/core/file_sys/archive_backend.h
src/core/file_sys/archive_extsavedata.cpp
src/core/file_sys/archive_extsavedata.h
src/core/file_sys/archive_romfs.cpp
src/core/file_sys/archive_romfs.h
src/core/file_sys/archive_savedata.cpp
src/core/file_sys/archive_savedata.h
src/core/file_sys/archive_savedatacheck.cpp
src/core/file_sys/archive_savedatacheck.h
src/core/file_sys/archive_sdmc.cpp
src/core/file_sys/archive_sdmc.h
src/core/file_sys/archive_systemsavedata.cpp
src/core/file_sys/archive_systemsavedata.h
src/core/file_sys/disk_archive.cpp
src/core/file_sys/disk_archive.h
src/core/file_sys/file_backend.h
src/core/file_sys/ivfc_archive.cpp
src/core/file_sys/ivfc_archive.h
src/core/hle/result.h
src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/fs/archive.cpp
src/core/hle/service/fs/archive.h
src/core/hle/service/fs/fs_user.cpp
src/core/hle/service/ptm/ptm.cpp

Return the correct error codes for the tested situations, this fixes Mario Kart 7's save bug and possibly many others.
Closes #1295 
Closes #1158 
Closes #875

HLE/FS: Fixed many corner cases in our file handling

---

src/audio_core/CMakeLists.txt
src/audio_core/codec.cpp
src/audio_core/codec.h

Decoders for the above three codecs, self-explanatory.

DSP: Implement audio codecs (PCM8, PCM16, ADPCM)

---

src/common/emu_window.h
src/core/hle/service/hid/hid.cpp

Found these when doing #1549 . Fix them to correspond with new-added one.

Remove unnecessary const & replace pointer with reference

---

src/citra_qt/game_list.cpp

Attempt to fix compilation issue from #1541
It needs additional testing, to see if my modification does not cause a regression with #1541.

Compilation fix

---

src/audio_core/CMakeLists.txt
src/audio_core/hle/common.h
src/audio_core/hle/dsp.h
src/audio_core/hle/filter.cpp
src/audio_core/hle/filter.h

In implementing this I went for ease of understanding. Modern compilers probably do a good job optimizing things like this anyway.
Matches firmware output exactly.

DSP: Implement audio filters (simple, biquad)

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Calling `Core::SingleStep()` at the start of a 20 instruction basic block causes the translation of 20 instructions followed by the execution of one instruction. Calling `Core::SingleStep()` again causes the translation of 19 instructions followed by the execution of one instruction.
This is a O(n^2) use of the cache. The cache can be quickly overwhelmed when single-stepping a lot (for example, if you're writing a JIT that single-steps the interpreter on unknown instructions).
This PR fixes that. It also improves the speed of single-stepping in the JIT so that's a bonus.

Prevent cache overflow when single stepping

---

src/core/hle/result.h
src/core/hle/service/gsp_gpu.cpp
src/core/hle/service/gsp_gpu.h

I haven't contributed to citra for a while so if there is anything that breaks the code style just let me know.

GSP: Return proper error codes for register writes

---

src/core/arm/dyncom/arm_dyncom.cpp

Fix **The Legend of Dark Witch - Won't boot** #1587

Update cpsr (T)humb bit while creating thread

---

src/citra/citra.cpp
src/core/gdbstub/gdbstub.cpp

This includes all changes from WinterMute's PR #1383. Since there hasn't been any updates to the PR, bunnei suggested I take it over since he wants to get these changes merged.
For the most part the code should be the same as WinterMute's except it contains the changes proposed by Subv, neobrain, and bunnei in the last PR.

Adopted WinterMute's gdbstub changes

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

Partially fix **Fifa 13 - Unknown virtual address @ 0x008C2554** #1319

Fix BLX LR opcode interpretation

---

src/core/hle/shared_page.cpp
src/core/hle/shared_page.h

pass through endless loop:
Batman Arkham Origins Blackgate - Won't boot #1610
Anpanman to Touch de Waku Waku Training

Set Kernel config "Hardware Inited" to 1 (true)

---

src/common/file_util.cpp
src/common/file_util.h
src/video_core/debug_utils/debug_utils.cpp

Loosely based off of a changeset @delroth opened at one point for Dolphin, but with minor other changes.

IOFile: Minor API changes

---

src/core/hw/y2r.cpp

fix:the num_tiles should be allowed when its value is 128

---

src/core/hle/config_mem.cpp
src/core/hle/hle.cpp
src/core/loader/3dsx.cpp

core: Clean out some unnecessary header includes

---

src/video_core/rasterizer.cpp

When using the SW-rasterizer Crash Time 3D spams the log with:
`HW.GPU <Critical> video_core/rasterizer.cpp:operator():1005: Unknown alpha blend factor 4`
This PR attempts to cause the same behaviour as with the HW renderer ([GL man page](https://www.opengl.org/sdk/docs/man/html/glBlendFuncSeparate.xhtml)) by implementing all remaining modes for the alpha factor.
Essentially this means:
* Color factor for R,G,B: R,G,B
* Alpha factor for R,G,B: A,A,A
* Color factor for A: A = same as equivalent alpha factor \[missing from the SW-Rast. in `master`\]
* Alpha factor for A: A
~~This was not HW-tested in any way.~~ The only commerical game I tested this on is Crash Time 3D.
~~\- [Subv suggested this is not what hardware does](https://github.com/citra-emu/citra/issues/1039#issuecomment-131869274) …

Rasterizer: Allow all blend factors for alpha blend-func

---

CMakeLists.txt
externals/microprofile/microprofileui.h
src/citra/CMakeLists.txt
src/citra_qt/debugger/graphics_framebuffer.cpp
src/common/assert.h
src/core/gdbstub/gdbstub.cpp
src/core/hle/service/fs/fs_user.cpp
src/core/loader/ncch.cpp
src/video_core/pica.h

This commit fixes various build errors I encountered when building with clang 3.9
There are also some build errors in nihstro, which I will propose a separate PR for.

Fix various build errors encountered on Clang 3.9 on OS X

---

src/core/hle/service/y2r_u.cpp
src/core/hle/service/y2r_u.h

I rebase my fork code and redo it ,and I give up the alignment for compatibility
This change will fixed the Application EX Troopers(エクストルーパーズ) some Graphics problem！

Update the code of service y2r!

---

src/core/hle/service/y2r_u.cpp

Basically a cleanup to #1447, which was fine, but my OCD got to me. It was also a bit easier for me to just merge and submit a followup PR than overly nitpick, particularly with the volume of PRs we've been getting lately.

y2r_u: Cleanup some formatting.

---

src/audio_core/audio_core.cpp
src/audio_core/hle/pipe.cpp
src/audio_core/hle/pipe.h
src/core/hle/result.h
src/core/hle/service/dsp_dsp.cpp
src/core/hle/service/dsp_dsp.h

Had a little dive into dsp::DSP and this is what I came back with.
* Corrected handling of interrupts.
* Added return IPC headers.

DSP Service: Cleanup

---

.gitmodules
CMakeLists.txt
src/audio_core/CMakeLists.txt

This PR just contains SoundTouch. Sumbitted in preparation for another audio-related PR.

Externals: Add soundtouch

---

src/core/hle/service/gsp_gpu.cpp

easy PR, tested on many games, don't break compatibility (even with games, which starts library applets)

gsp::Gpu: implement AcquireRight, ReleaseRight functions

---

src/core/hle/service/ac_u.cpp
src/core/hle/svc.cpp

code from Lost Heroes 1 and 2 - Won't boot #1601

ac:u: stub CloseAsync; align memory size in svc:GetProcessInfo(type=2)

---

src/video_core/shader/shader.cpp

Nothing special. Part of a cleanup for geometry shaders.

Pica: Replace logic in shader.cpp with loop

---

src/audio_core/CMakeLists.txt
src/audio_core/hle/common.h
src/audio_core/hle/dsp.cpp
src/audio_core/hle/dsp.h
src/audio_core/hle/filter.h
src/audio_core/hle/source.cpp
src/audio_core/hle/source.h

This should close a lot of audio related issues.
This PR performs per-source audio processing and reporting of audio status back to the application.

DSP/HLE: Implement Source processing

---

src/core/hle/applets/mii_selector.cpp
src/core/hle/applets/mii_selector.h

Main reason of PR - make Crosswords Plus working

Layout Mii parameters input/output, and return success as result of applet work

---

src/citra_qt/CMakeLists.txt
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/game_list_p.h
src/core/loader/3dsx.cpp
src/core/loader/3dsx.h
src/core/loader/loader.cpp
src/core/loader/loader.h
src/core/loader/ncch.cpp
src/core/loader/ncch.h

@JamePeng told me this makes it much easier to find games.

Qt: display game icon and title in the game list

---

src/common/swap.h

Just minor associated changes with the swap.h header in common.

Swap: Minor changes

---

src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_state.cpp
src/video_core/renderer_opengl/gl_state.h
src/video_core/renderer_opengl/pica_to_gl.h

This was missing somehow.
Another one of those "how did that even work"-moments. (Though I must admit, seeing anything but FUNC_ADD is unlikely..)
Fixes #1452  (gates are coloured but I didn't check if it's the correct color, I just assume so)
//Edit: SW renderer already implemented these.

OpenGL: Support blend equation

---

src/core/CMakeLists.txt
src/core/hle/service/act_a.cpp
src/core/hle/service/act_a.h
src/core/hle/service/act_u.cpp
src/core/hle/service/service.cpp

Everything is taken from [3dbrew](https://www.3dbrew.org/wiki/ACT_Services).
Sorry for making 6 commits, this is the first time I actually do something on GitHub. I'll try to figure out more, but now I simply edited the files on the webpage and unfortunately every change made a new commit.

Update ACT:U and create ACT:A

---

src/citra_qt/CMakeLists.txt
src/citra_qt/configure.ui
src/citra_qt/configure_audio.cpp
src/citra_qt/configure_audio.h
src/citra_qt/configure_audio.ui
src/citra_qt/configure_dialog.cpp

Added Audio tab to configuration dialog

Config: Audio sink configuration

---

src/citra_qt/debugger/profiler.cpp

Not sure if this is the best way to do this.

Microprofile: DPI-aware drawing

---

src/audio_core/CMakeLists.txt
src/audio_core/hle/dsp.cpp
src/audio_core/hle/dsp.h
src/audio_core/hle/mixers.cpp
src/audio_core/hle/mixers.h

Includes audio output.
Only implemented well-understood portions of the firmware.

DSP/HLE: Implement mixer processing

---

src/citra_qt/configure_audio.cpp

Config: Restore previously selected audio sink option

---

src/citra/citra.cpp
src/citra_qt/game_list.cpp
src/citra_qt/game_list_p.h
src/citra_qt/main.cpp
src/core/CMakeLists.txt
src/core/loader/3dsx.cpp
src/core/loader/3dsx.h
src/core/loader/elf.h
src/core/loader/loader.cpp
src/core/loader/loader.h
src/core/loader/ncch.cpp
src/core/loader/ncch.h
src/core/loader/smdh.cpp
src/core/loader/smdh.h

This PR should be reviewed commit per commit.
The first four commits are some loader cleanup, so a loader can be created more easily~~, and the final one adds SMDH support to the SDL2 frontend~~ (pushed back to a future PR).

Improve SMDH support in loaders and frontends

---

src/citra_qt/game_list.cpp

AddFstEntriesToGameList - prevent loading a directory as a file

---

src/core/hle/kernel/thread.cpp

Fix #1307 
Here is a [small test](https://github.com/wwylele/ctrhwtest/tree/master/waitsync_timeout_test) for this.

Thread: update timeout when reruning WaitSynch

---

.travis-upload.sh
README.md
appveyor.yml

This is supposed to fix parts of #1925 
I did not test this yet and I'm a little worried that it will break the build upload.
However, without this PR this wouldn't be worked on by anybody probably and I feel like it's too important to let it slide.
Can anybody test this?

Add GPL license.txt and README.md to builds

---

src/core/CMakeLists.txt
src/core/hle/applets/applet.cpp
src/core/hle/applets/erreula.cpp
src/core/hle/applets/erreula.h
src/core/hle/service/apt/apt.h

Fix **Funky Barn 3D - hangs at intro** #1606

HLE/Applets: Implement ErrEula applet

---

src/citra/citra.cpp

#1620 did not deal with command line encode problem on no-qt build. This PR conuinue to fix it.
Another way  is use `wmain` ,but I think `wmain` will cause more portability issues so that I use `CommandLineToArgvW` to convert path to Unicode format.
Thanks @yami-hack 's comment!

Fix boot_filename encode on Windows

---

src/core/arm/dyncom/arm_dyncom_thumb.cpp

dyncom: Fix translation of thumb REVSH

---

src/core/hle/service/apt/apt.cpp
src/core/hle/service/apt/apt.h
src/core/hle/service/apt/apt_a.cpp
src/core/hle/service/apt/apt_s.cpp
src/core/hle/service/apt/apt_u.cpp

Some guy corrected the old and confusing description, so I need to fix my old wrong code :smiley: 
https://www.3dbrew.org/wiki/APT:GetScreencapPostPermission
https://www.3dbrew.org/wiki/APT:SetScreencapPostPermission

Correct APT::0x00550040 and APT::0x00560000 function

---

.github/ISSUE_TEMPLATE.md

Text is a Markdown comment.
Intended to reduce spurious issue reports.

.github: Add ISSUE_TEMPLATE.md

---

CMakeLists.txt

Revert "MSVC: Add RelWithDebInfo and removing debugging from Release."

---

src/citra_qt/configure_dialog.cpp
src/citra_qt/configure_dialog.h
src/citra_qt/configure_system.cpp
src/citra_qt/configure_system.h
src/citra_qt/main.cpp

Clean up some ugly code and replace them with the one introduced in #2032.

Qt: unify running detection of system settings configure

---

src/common/file_util.cpp

Old form is deprecated, this fixes a warning on gcc.

Switch to readdir() from readdir_r()

---

.gitmodules
CMakeLists.txt
src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/config.cpp
src/citra_qt/configure_general.cpp
src/citra_qt/configure_general.ui
src/common/microprofile.h
src/core/CMakeLists.txt
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic.cpp
src/core/arm/dynarmic/arm_dynarmic.h
src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/dyncom/arm_dyncom.h
src/core/core.cpp
src/core/hle/kernel/thread.cpp
src/core/settings.h

Have fun
// Edit by JayFoxRox: Note that dynarmic is a submodule which has other submodules.
Do `git submodule update --init --recursive` after checkout.
// Edit by JayFoxRox: Dear redditors / users, please don't ask random compilation questions here, thanks! - just be patient

Interface ARM CPU JIT (Dynarmic)

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/boss/boss.cpp
src/core/hle/service/boss/boss.h
src/core/hle/service/boss/boss_u.cpp

I redo the #2019 PR and append a lot of stub code and comment which was investigated through reverse engineering the boss module.  But there are many parameter meaning was unknown (>m<), sorry!

Update the stub code of BOSS

---

src/core/hle/service/ac_u.cpp
src/core/hle/service/ac_u.h

This PR stubs functions, which used, if user agreed EULA (with currently closed #1662)

AC_U: Stub functions, used if EULA agreed

---

src/citra_qt/main.cpp
src/citra_qt/main.ui

Resubmission of #2088.
I ran into some errors when I tried to fix that PR.

Minor Menu Fixes

---

src/citra/config.cpp
src/citra/default_ini.h
src/citra/emu_window/emu_window_sdl2.cpp
src/citra_qt/bootmanager.cpp
src/citra_qt/config.cpp
src/citra_qt/configure_dialog.cpp
src/citra_qt/configure_graphics.cpp
src/citra_qt/configure_graphics.ui
src/citra_qt/main.cpp
src/citra_qt/main.h
src/common/CMakeLists.txt
src/common/emu_window.cpp
src/common/emu_window.h
src/common/framebuffer_layout.cpp
src/common/framebuffer_layout.h
src/common/math_util.h
src/core/settings.cpp
src/core/settings.h
src/video_core/renderer_opengl/renderer_opengl.cpp

Allows users to choose to show only one screen or to flip bottom and top screens. Adds a configuration option in QT to change this as well.

Support additional screen layouts.

---

src/video_core/pica.h

Clang format on travis is pestering me to make this change. It doesn't show up in pull requests because clang format only checks changed files on pull request.

Minor formatting change

---

src/core/hle/kernel/event.cpp
src/core/hle/kernel/timer.cpp

Kernel/Events: Log an error when trying to create Pulse events and timers

---

src/core/hle/service/err_f.cpp

http://3dbrew.org/wiki/ERR:Throw
I found the old code is not accurate when I looking at this page!

Rework the code of err:f service!

---

src/core/hle/service/apt/apt.cpp
src/core/hle/service/apt/apt.h
src/core/hle/service/apt/apt_a.cpp
src/core/hle/service/apt/apt_u.cpp

From shrds work:
Fixes #1822 #1910 
CancelLibraryApplet stub.

Bravely Default/Second stuck #1822

---

src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/config.cpp
src/core/hw/gpu.cpp
src/core/hw/gpu.h
src/core/settings.h
src/video_core/command_processor.cpp

Remove the broken frame_skip option

---

src/video_core/rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp

This slipped past my last warnings-fix PR, sorry.

ClangFormat: Fixed the clang-format errors

---

src/video_core/shader/shader_jit_x64.cpp

As noticed by @Subv and pointed out by @yuriks in citra-emu#1629 (comment) , our shader-JIT had some serious issue where the LOOP address register was used directly in offset calculations.
As each addressed vector is 16-bytes in size, this PR changes the JIT registers by keeping their values shifted 4 bits to the left (effectively keeping these regs multiplied by 16 at all times).
The offset used in address calculations is stored in LOOPCOUNT_REG. It's incremented by LOOPINC.
Hence both registers were shifted.
This fixes #1629 and #2226.
Additionally the indexed lookup is performed using MOVAPS which requires the memory address to be 16 byte aligned. As we didn't satisfy that condition with the old code, we probably read garbage. This might have been responsible for #1743 and #2209 …

shader_jit: Load LOOPCOUNT_REG and LOOPINC 4 bit left-shifted

---

src/core/hle/applets/applet.cpp
src/core/hle/applets/applet.h
src/core/hle/applets/erreula.cpp
src/core/hle/applets/erreula.h
src/core/hle/applets/mii_selector.cpp
src/core/hle/applets/mii_selector.h
src/core/hle/applets/swkbd.cpp
src/core/hle/applets/swkbd.h

Each commit should be fairly self-explanatory.

applet: minor interface changes

---

src/core/CMakeLists.txt
src/core/hle/service/nfc/nfc.cpp
src/core/hle/service/nfc/nfc.h
src/core/hle/service/nfc/nfc_m.cpp
src/core/hle/service/nfc/nfc_m.h
src/core/hle/service/nfc/nfc_u.cpp
src/core/hle/service/nfc/nfc_u.h
src/core/hle/service/service.cpp

Adds unimplemented NFC service functions.

service: Add nfc services

---

src/audio_core/audio_core.cpp

audio_core: SelectSink should default to auto if sink_id is invalid

---

src/citra_qt/debugger/graphics_cmdlists.cpp

Each commit should be self-explanatory.

graphics_cmdlist: Minor changes

---

src/core/hle/service/act/act.h

These aren't the AM services. Gotta love evident indications of copy and pasting, haha lol rofl.

act: Fix docstring typo

---

src/video_core/CMakeLists.txt
src/video_core/command_processor.cpp
src/video_core/shader/debug_data.h
src/video_core/shader/shader.cpp
src/video_core/shader/shader.h
src/video_core/shader/shader_interpreter.cpp
src/video_core/shader/shader_interpreter.h
src/video_core/shader/shader_jit_x64.cpp
src/video_core/shader/shader_jit_x64.h

Misc. Shader refactors

---

src/citra_qt/bootmanager.cpp
src/citra_qt/main.cpp
src/common/scm_rev.cpp.in

General code cleanup PR.
1. fixed GPLv2 license text line at the start in  **scm_rev.cpp.in**
2. fixed " **screen swap - Hotkey** " , while using non single window mode.
3. cleaned up unused #define in  **bootmanager.cpp** and fixed lines for **travis ci**

Code cleanup

---

src/video_core/command_processor.cpp
src/video_core/debug_utils/debug_utils.cpp
src/video_core/debug_utils/debug_utils.h

Speeds up ALBW main menu slightly (~3%)

VideoCore: Inline IsPicaTracing

---

src/video_core/command_processor.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp

Commandlist processing now doesn't look so slow anymore. :P

VideoCore: Make profiling scope more representative

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/csnd_snd.cpp
src/core/hle/service/csnd_snd.h

Reformat the source similar other services.

csnd:SND: Reformat source code

---

src/core/arm/dynarmic/arm_dynarmic.cpp

Change of interface in MerryMage/dynarmic@36082087ded632079b16d24137fdd0c450ce82ea.

arm_dynarmic: Provide MemoryReadCode callback

---

src/citra/default_ini.h

config: SDL: Move background color setting to correct section.

---

.travis.yml

Travis is still having issues uploading to bintray. We just got a new reencrypted key from bunnei, so i'm just going to instamerge this to see if this is the key we need.

Try a different travis key

---

src/citra_qt/bootmanager.cpp
src/citra_qt/debugger/callstack.cpp
src/citra_qt/debugger/graphics/graphics_cmdlists.cpp
src/citra_qt/debugger/graphics/graphics_vertex_shader.cpp
src/citra_qt/util/spinbox.cpp
src/core/gdbstub/gdbstub.cpp
src/core/hle/service/boss/boss.cpp
src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/mic_u.cpp
src/core/hle/service/soc_u.cpp
src/core/loader/ncch.cpp
src/core/loader/ncch.h
src/video_core/shader/shader_interpreter.cpp

I fixed some warnings including unused variable, format, override, initialization order.

Fix some warnings

---

src/core/hle/kernel/thread.cpp

After hwtesting and reverse engineering the kernel, it was found that the CTROS scheduler performs no priority boosting for threads like this, although some other forms of scheduling priority-starved threads might take place.
For example, it was found that hardware interrupts might cause low-priority threads to run if the CPU is preempted in the middle of an SVC handler that deschedules the current (high priority) thread before scheduling it again.

Kernel: Removed the priority boost code for starved threads.

---

src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/config.cpp
src/citra_qt/configure_graphics.cpp
src/citra_qt/configure_graphics.ui
src/core/settings.cpp
src/core/settings.h
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/video_core.cpp
src/video_core/video_core.h

For those of us with hardware fast enough to upscale, but not fast enough to upscale to our native resolutions...
Obligatory UI change screenshot:

config: Add option for specifying screen resolution scale factor.

---

src/core/hle/kernel/event.cpp
src/core/hle/kernel/event.h
src/core/hle/kernel/kernel.h
src/core/hle/kernel/timer.cpp
src/core/hle/kernel/timer.h

Finally we can implement these.
Closes #1904

 Kernel: Implemented Pulse event and timers.

---

src/core/hle/kernel/resource_limit.cpp
src/core/hle/kernel/thread.cpp
src/core/hle/service/y2r_u.cpp
src/core/hle/svc.cpp

This PR gets rid of some TODOs.
It is better to review this commit-by-commit.

Implement some TODOs in the code.

---

src/core/loader/3dsx.cpp

fixes citra-emu/citra#2449
As per devkitPro/3dstools@47bea18

loader: Add support for 3DSX special relocation types

---

src/core/hle/service/cfg/cfg.cpp

Previously in #2240 I added a language overriding in `GetConfigInfoBlock`, which happens when the region setting is auto. This causes a small problem because `GetConfigInfoBlock` is also used by the Qt frontend to checkout the current settings. The symptom is that the configuration dialog will always shows "Japanese" as language if the region is auto, in spite of the actual language settings. ~~Now I moved this overriding into the service functions, so that it only happens when the game reads it.~~ Now I moved this overriding to the boot process, so that it won't happens when users edit the system settings. It will still affect if users open the configuration window while a game is running, but it doesn't matter and actually tells users that the language is changed.

CFG: move language override to the boot process

---

src/core/hle/service/gsp_gpu.cpp

This avoid endless spam of "unimplemented StoreDataCache..." in some games

GSP_GPU::StoreDataCache stubbed

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/hle/service/ir/ir_u.cpp
src/core/hle/service/nim/nim.cpp

I added the http svc enum to the correct spot in the log.h file

added http service enum to the log.h file

---

src/core/hle/kernel/timer.cpp

Timer: restore missing signaled=true from #2421

---

README.md

Fixed the broken links that were a result of the updated website.

New website link updates.

---

src/core/hle/service/cfg/cfg.cpp

see [3dbrew](https://www.3dbrew.org/wiki/Cfg:GenHashConsoleUnique) for documentation. Results are verified against real 3DS.

cfg: correctly implement GenHashConsoleUnique

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/nwm_uds.h

Currently it will let games create a network as hosts, but will not broadcast it anywhere and will not allow clients to connect.

Services/UDS: Initial support for hosting local-wlan networks.

---

src/core/hle/service/dsp_dsp.cpp

Confirmed by RE.
Code has been a part of BE for a few months.

dsp_dsp: Messages are modified by service before being sent to DSP

---

src/core/hle/service/ldr_ro/ldr_ro.cpp

My first attempt on using IPC helper. I hope I get it right :smile:

ldr_ro: use IPC helper

---

src/audio_core/audio_core.cpp
src/audio_core/audio_core.h
src/audio_core/hle/dsp.cpp
src/audio_core/hle/dsp.h
src/core/core.cpp
src/core/hle/kernel/memory.cpp
src/core/hle/kernel/memory.h
src/core/hle/kernel/process.cpp
src/core/hle/kernel/process.h
src/core/memory.cpp
src/core/memory.h

cc @Subv
~~Review each commit.~~ (Be mindful of fixups though.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2687)

Kernel: Map special regions according to ExHeader

---

src/core/hle/service/ptm/ptm.cpp
src/core/hle/service/ptm/ptm.h
src/core/hle/service/ptm/ptm_u.cpp

Use IPCHelper for PTM services. Also stubbed GetPedometerState service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2710)

use IPCHelper for PTM services

---

appveyor.yml

More C++14/17 goodness!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2718)

Upgrade AppVeyor to Visual Studio 2017

---

src/common/CMakeLists.txt
src/common/telemetry.cpp
src/common/telemetry.h
src/core/CMakeLists.txt
src/core/core.cpp
src/core/core.h
src/core/loader/ncch.cpp
src/core/telemetry_session.cpp
src/core/telemetry_session.h

This is the first part of a set of changes to add a telemetry framework to Citra. In the near term, this will be used for user-submitted compatibility data to our own custom service endpoint (services.citra-emu.org). My goal, however, is to make this very generic, and allow us to easily log useful/interesting data fields throughout the emulator, and then upload them to our service at a later time. In the long term, we may use this for anonymous telemetry, critical errors and crash reports, measuring how often features are used, etc.
The general design right now is to have essentially a "metadata log", which is just a list of logged data fields. A data field considers of:
* **Name** - String used as a key to access the field, must be unique to a given log (otherwise overwrite previous …

Telemetry framework Part 1

---

src/video_core/renderer_opengl/gl_shader_gen.cpp

It is confirmed that bump map respects to all "special features" of texture units: 
- different texture type for unit 0 ([here is a testing program](https://gist.github.com/wwylele/c939cc90551b0c28f1298bf08a026583) that uses projection texture for bump map)
- different coordinates for unit 2 (tested before, see #2686)
- proctex for unit 3. . (tested when implementing proctex)
So it should use the same sampler function as combiner's
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2725)

gl_shader: refactor texture sampler into its own function

---

src/core/hle/service/cam/cam.cpp
src/core/hle/service/cam/cam.h

Please keep eyes on those numbers to see if I made mistakes, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2722)

CAM: use IPCHelper

---

src/citra_qt/game_list_p.h

Found that this ones aren't needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2746)

Remove unused imports in game_list_p.h

---

README.md

Missed this one in #2728.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2747)

Fix FAQ Link in Readme

---

src/core/hle/service/nwm/nwm_uds.cpp

This function decrypts the encrypted data tags contained in the 802.11 beacon frames.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2737)

Services/UDS: Implement DecryptBeaconData.

---

src/citra_qt/debugger/wait_tree.h
src/core/hle/kernel/client_session.cpp
src/core/hle/kernel/server_session.h

Fixes #2760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2761)

Kernel: Ensure objects are kept alive during ClientSession disconnection

---

src/common/break_points.cpp

Found that this one isn't needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2763)

Remove unused import in break_points.cpp

---

src/video_core/regs_lighting.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_opengl/gl_shader_gen.cpp
src/video_core/renderer_opengl/gl_shader_gen.h

[Here is a testing program](https://gist.github.com/wwylele/3318df2a717d9451722c7a9e5a36b5a8) (adapted from 3ds-examples/fragment-lighting)
Reference: https://www.3dbrew.org/wiki/GPU/Fragment_Lighting (including http://mathb.in/64694)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2727)

Fragment lighting: implement spot light 

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

While debugging the software renderer implementation, it was noticed
that this is actually exactly what the hardware does, upgrading the
status of this "hack" to being a proper implementation. And there was
much rejoicing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2767)

OpenGL: Update comment on AreQuaternionsOpposite with new information

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/nwm_uds.h
src/core/hle/service/nwm/uds_beacon.h

This lets the application know that the host was successfully added to the session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2738)

Services/UDS: Set the proper bit in the ConnectionStatus structure when creating a network.

---

CMakeLists.txt
externals/CMakeLists.txt
src/video_core/shader/shader_jit_x64_compiler.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2785)

CMake: Set MSVC flags for improved C++ standards conformance

---

src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/service/service.cpp
src/tests/CMakeLists.txt
src/tests/core/hle/kernel/hle_ipc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2787)

Kernel/IPC: Add tests for HLERequestContext buffer translation

---

src/core/hle/service/nwm/nwm_uds.cpp

This hook will be called by whoever creates the AssociationResponse frame, which contains the assigned network node id.
So far AssociationResponse is intended to be created inside NWM itself, as a response to an AssociationRequest frame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2779)

UDS: Added a hook for updating the connection status when a client connects to the network.

---

src/core/hle/kernel/process.cpp
src/core/memory.h

Just two small random changes I found in my git stashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2789)

Trivial no-op additions

---

src/core/hle/kernel/hle_ipc.cpp
src/tests/core/hle/kernel/hle_ipc.cpp

Missed this in my first implementation. Thanks to @wwylele for pointing out that this was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2796)

Kernel/IPC: Support translation of null handles

---

src/core/hle/function_wrappers.h
src/core/hle/svc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2798)

Kernel: Implement CreateSession SVC

---

src/core/hle/function_wrappers.h
src/core/hle/kernel/errors.h
src/core/hle/kernel/server_port.cpp
src/core/hle/kernel/server_port.h
src/core/hle/svc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2801)

Implement CreateSessionToPort and AcceptSession; fix CreatePort

---

externals/cryptopp/CMakeLists.txt

Overrides #2758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2805)

externals: silence warning C4390 on MSVC for cryptopp

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2812)

fixing a couple of typos

---

src/core/memory.cpp

Unmapping pages tries to flush any cached GPU surfaces touching that
region. When a cached page is invalidated, GetPointerFromVMA() is used
to restore the original pagetable pointer. However, since that VMA has
already been deleted, this hits an UNREACHABLE case in that function.
Now when this happens, just set the page type to Unmapped and continue,
which arrives at the correct end result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2797)

Memory: Fix crash when unmapping a VMA covering cached surfaces

---

src/core/hle/service/boss/boss_p.cpp

This PR addes 3 functions according to 3dbrew
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2815)

Service/boss:P: Add some functions to FunctionTable

---

src/core/hle/kernel/shared_memory.cpp
src/core/hle/service/apt/apt.cpp
src/core/hle/service/gsp_gpu.cpp
src/core/hle/service/y2r_u.cpp
src/core/memory.cpp
src/core/memory.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2799)

Add address conversion functions returning optional, Add function to flush virtual region from rasterizer cache

---

src/citra_qt/debugger/graphics/graphics_vertex_shader.cpp

All of these are confirmed with 3dbrew and citra interpreter / JIT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2837)

Misc shader debugger fixes

---

src/core/hle/service/apt/apt.cpp
src/core/hle/service/apt/apt.h

And reduced their log level to debug.
This PR is mostly error-handling and returning the correct error codes.
It's better to review it commit by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2840)

Services/APT: Corrected the behavior of the Receive/Send/Glance/CancelParameter functions

---

src/core/hle/service/dlp/dlp_clnt.cpp
src/core/hle/service/dlp/dlp_fkcl.cpp
src/core/hle/service/dlp/dlp_srvr.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2864)

Service/dlp: Update function tables according 3dbrew

---

src/citra/default_ini.h
src/input_common/sdl/sdl.cpp

The code was already looking for `threshold`, not `threshould`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2874)

Fix some spelling mistakes

---

src/input_common/main.h

Discovered by @Dragios in #2878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2879)

Fix Spelling/English mistakes

---

src/video_core/swrasterizer/lighting.cpp

This is the swrasterizer counterpart of #2727. You can use the same program there to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2871)

SwRasterizer/Lighting: implement spot light

---

src/video_core/swrasterizer/lighting.cpp

This is the swrasterizer counterpart of #2776 . Same test program there can be used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2872)

SwRasterizer/Lighting: implement geometric factor

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2901)

Fix info about TODO list

---

src/core/hle/lock.cpp
src/core/hle/lock.h
src/core/hle/svc.cpp
src/core/memory.cpp

As suggested by @wwylele in that thread, this fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2905)

Use recursive_mutex instead of mutex to fix #2902

---

src/citra_qt/citra-qt.rc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2917)

Fix icon for citra qt

---

src/core/hle/applets/mii_selector.cpp
src/core/hle/applets/mii_selector.h

According to https://www.3dbrew.org/wiki/Mii_Selector
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2876)

Mii Selector Applet: update Mii structures

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2928)

Fixed framebuffer warning

---

src/video_core/pica_types.h

Based on https://github.com/citra-emu/citra/issues/2939#issuecomment-330706569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2944)

Optimized Float<M,E> multiplication

---

src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm.h
src/core/hle/service/sm/srv.cpp
src/core/hle/service/sm/srv.h

Now system modules can do more than just crash immediately on startup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2948)

HLE/SRV: Implemented RegisterService.

---

src/core/memory.cpp

Not all physical regions need to be mapped into the address space of every process, for example, system modules do not have a VRAM mapping.
This fixes a crash when loading applets and system modules.
In the future we'll have to figure out a way to update the page tables of other processes when caching / uncaching a region.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2954)

Memory/RasterizerCache: Ignore unmapped memory regions when caching physical regions

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2972)

Add the .vs folder and the CMakeSettings.json file from Visual Studio to gitignore

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/uds_data.cpp
src/core/hle/service/nwm/uds_data.h

Follow up of #2920. This is the last step in the connection sequence. 
Next steps are sending packets, receiving packets, disconnect and destroy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2963)

Services/UDS: Handle the rest of the connection sequence.

---

src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic.cpp
src/core/arm/dynarmic/arm_dynarmic.h
src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/dyncom/arm_dyncom.h
src/core/core_timing.cpp
src/core/core_timing.h
src/core/hle/svc.cpp
src/tests/core/arm/dyncom/arm_dyncom_vfp_tests.cpp

It's needed for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2973)

Moved down_count to CoreTiming

---

src/core/hle/service/nim/nim.cpp
src/core/hle/service/nim/nim.h
src/core/hle/service/nim/nim_u.cpp

Implementation verified by reverse engineering.
This lets the Home Menu boot without crashing on startup.
Closes #2465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2974)

Services/NIM: Implement CheckForSysUpdateEvent.

---

src/core/hle/kernel/shared_memory.cpp

Fixes a potential issue where two shared memories pointing to the same memory address might not have the same backing memory.
Consider the following,
Processes = [A, B, C]
SharedMemories = [S, T] pointing to address K
1. Process A creates SharedMemory S pointing to address K, thus A's memory mapping for K now points to a block owned by S.
2. Process B maps S into its address space.
3. Process C maps S into its address space.
-- At this point all 3 processes have the memory pointed to by S mapped into their address space --
4. Process A creates SharedMemory T pointing to address K, thus A's memory mapping for K now points to a block owned by T, which is different than the one owned by S.
5. A writes some data at address K.
6. Processes B and C do not see the changes in the data because …

SharedMemory: Don't take over and unmap the source memory block when creating a shared memory, just reference it

---

src/video_core/command_processor.cpp

Literally just cut and paste the body of code from the two switch cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2985)

Extracted the attribute setup and draw commands into their own functions

---

src/core/hle/lock.cpp

nt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3024)

hle/lock: Remove #pragma once in cpp file

---

src/core/core.cpp
src/core/gdbstub/gdbstub.cpp
src/core/hle/applets/applet.cpp
src/core/hle/kernel/address_arbiter.cpp
src/core/hle/service/apt/apt.cpp
src/core/hle/service/dsp_dsp.cpp
src/core/hle/service/fs/archive.cpp
src/core/hle/service/fs/fs_user.cpp
src/core/hle/service/ndm/ndm.cpp
src/core/hle/service/sm/srv.cpp
src/core/hle/service/y2r_u.cpp
src/core/hw/aes/ccm.cpp
src/core/hw/gpu.cpp
src/video_core/regs_framebuffer.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_shader_gen.cpp
src/video_core/renderer_opengl/pica_to_gl.h
src/video_core/shader/shader_jit_x64_compiler.cpp
src/video_core/swrasterizer/framebuffer.cpp
src/video_core/swrasterizer/lighting.cpp
src/video_core/swrasterizer/rasterizer.cpp

...except for
- service/am, because it is being developed
- externals/microprofile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3064)

Clean all format warnings

---

src/core/CMakeLists.txt
src/core/file_sys/cia_container.h
src/core/file_sys/title_metadata.h

These were left out of the recent stream of PRs by @shinyquagsire23.
Somehow we didn't catch this during review, the CI should have warned us about this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3093)

Added missing headers to CMakeLists.txt and fixed includes.

---

src/core/hle/svc.cpp

This behavior was reverse engineered from the real kernel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3084)

Kernel/Thread: Use the process' ideal CPU when specifying the Default CPU on CreateThread.

---

src/citra/default_ini.h

fixes #3108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3109)

sdl2 default ini: fix framelimit

---

src/core/hle/service/ptm/ptm.cpp
src/core/hle/service/ptm/ptm.h
src/core/hle/service/ptm/ptm_gets.cpp
src/core/hle/service/ptm/ptm_play.cpp
src/core/hle/service/ptm/ptm_sysm.cpp
src/core/hle/service/ptm/ptm_u.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/2969)

Service/PTM: Stub GetStepHistory function

---

src/core/hle/service/sm/srv.cpp

This was incorrect behavior that somehow found its way to 3dbrew. The correct behavior is to sleep until the port becomes available again and then return a session to it.
This is currently unimplemented due to the inability to put a guest thread to sleep during HLE requests.
The correct behavior was reverse engineered by TuxSH a while ago but we never corrected the code in citra.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3085)

HLE/SRV: Don't return the port handle if it isn't available when calling GetServiceHandle.

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3126)

Added Webhook notifications for Appveyor.

---

src/core/hle/kernel/ipc.cpp

This descriptor requires the target process to set up a "receive buffer" beforehand, where the input data will be written to when the descriptor is processed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3083)

Kernel/IPC: Handle the StaticBuffer descriptor in LLE command requests.

---

src/video_core/command_processor.cpp

This reverts commit b3b34a1e76664c412fd7b37b3529cadd3983acfb. This commit causes a significant performance regression on at least mingw. It is unknown if this impacts other builds right now, as the issue was tracked down by the users who noticed the regression. @yuriks looked a little more into the issue and found the following
> yuriks: hmm, hard to tell what's going on in the asm exactly, but as far as I can tell moving Draw into a function caused WritePicaRegs to become small enough that it was  inlined in ProcessCommandList
and maybe that caused the performance regression? but I don't know why
Since the change was originally meant to be a simple code quality improvement that wouldn't affect anything, and later we noticed that it had a major impact on performance, I feel that we should …

Revert "Extracted the attribute setup and draw commands into their own functions"

---

src/network/room.cpp
src/network/room.h
src/network/room_member.cpp
src/network/room_member.h

This PR adds the possibility the set a password for rooms
It also adds a unique (randomly generated) GUID used to announce rooms to our web-service.
It adds the possibility to set a preferred game for a room.
The default Port is changed to "CITRA" too ;-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3068)

Libnetwork: add password protected rooms, guid, and error fixes

---

src/network/room.cpp
src/network/room_member.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3163)

room/room_member: Silence -Wswitch warnings

---

src/core/hle/service/am/am.cpp
src/core/hle/service/ptm/ptm.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3166)

services: Silence warnings related to logging

---

src/core/hle/service/ptm/ptm.cpp

This is a defect in #3166 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3179)

service/ptm: add missing % in logging

---

src/core/hle/service/err_f.cpp
src/core/hle/service/err_f.h
src/core/hle/service/service.cpp

No functional change, ref #2531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3190)

HLE/Services: Convert err:f to the new ServiceFramework.

---

src/core/hle/service/fs/archive.cpp

fixup for #3138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3191)

fs: correct header code; remove dead code

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/skyeye_common/armstate.h

Same thing, but with less indirection hiding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3223)

dyncom: Convert the SPSR checking define to a function

---

src/core/hle/kernel/address_arbiter.cpp

This may happen when using WaitIfLessThanWithTimeout and DecrementAndWaitIfLessThanWithTimeout in svcArbitrateAddress.
Fixes a regression introduced in #3096
Closes #3164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3226)

HLE/AddressArbiter: Remove threads that were awoken by timeout from an Arbiter's waitlist

---

src/core/arm/dynarmic/arm_dynarmic_cp15.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3230)

arm_dynarmic_cp15: Add missing header guard

---

src/core/hle/service/cfg/cfg.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3236)

cfg: refer to ConsoleModelBlockID by name

---

src/core/hle/kernel/process.cpp
src/core/hle/kernel/process.h
src/core/hle/kernel/thread.cpp
src/core/hle/service/fs/fs_user.cpp

This function is used by the DLP system module during the DLPSRVR initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3234)

HLE/FS: Implemented FS::GetProgramLaunchInfo.

---

src/common/bit_set.h
src/video_core/shader/shader.cpp
src/video_core/shader/shader.h

A few trivial cleanups in GS-related code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3258)

Small GS cleanups

---

src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h

Fairly trivial changes I noticed could be made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3266)

bootmanager: Minor tidiness/correctness changes

---

src/core/loader/ncch.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3271)

ncch: Add missing return statement in ReadUpdateRomFs

---

src/common/telemetry.h
src/core/file_sys/ncch_container.cpp
src/core/hle/kernel/hle_ipc.cpp
src/core/hle/service/fs/archive.cpp
src/core/loader/ncch.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3262)

common/core: Silence initialization order warnings

---

src/core/hle/service/ldr_ro/cro_helper.h
src/core/hle/service/ldr_ro/ldr_ro.cpp
src/core/hle/service/ldr_ro/ldr_ro.h
src/core/hle/service/ldr_ro/memory_synchronizer.cpp
src/core/hle/service/ldr_ro/memory_synchronizer.h
src/core/hle/service/service.cpp
src/core/memory.cpp
src/core/memory.h

Also fixes all `process` usage, and creates storage for each client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3192)

ldr_ro: convert to ServiceFramework

---

src/core/file_sys/ncch_container.cpp

This is "new" behavior as of firmware 5.0.0-11, older titles have the logo offset and size set to 0, indicating that the logo is stored in the ExeFS.
The Home Menu tries to open this file when launching a title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3249)

NCCH: Load the "logo" file from the specified offset if it's present instead of the ExeFS.

---

src/core/file_sys/archive_backend.cpp
src/core/file_sys/archive_backend.h
src/core/file_sys/archive_other_savedata.cpp
src/core/hle/service/fs/fs_user.cpp

Namely:
* OpenFileDirectly
* DeleteFile
* RenameFile
* DeleteDirectory
* DeleteDirectoryRecursively
* CreateFile
There are still many left to convert, and then we'll have to convert the entire service to ServiceFramework, this is not included in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3252)

HLE/FS: Converted some functions to use IPCHelpers

---

src/citra_qt/game_list.cpp
src/citra_qt/game_list.h

Reduces the number of header dependencies propagated by the header file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3305)

game_list: Use forward declarations where applicable

---

src/core/hle/service/mic_u.cpp
src/core/hle/service/mic_u.h
src/core/hle/service/service.cpp

So, this is my first time using the new IPC helpers and the service framework (which is why I didn't pick a relatively important module to migrate), so if I've made any glaringly wrong issues, please feel free to point them out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3253)

mic_u: Migrate to the new service framework

---

src/audio_core/CMakeLists.txt
src/input_common/CMakeLists.txt

Fixes #3320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3326)

cmake: add missing ${...} for variables inside generator expressions

---

src/citra/citra.cpp

+ remove u16 'always false' compare, add const to const strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3335)

citra(SDL) small fixes: fix fall-through

---

src/core/hle/service/y2r_u.cpp

First time using IPC helper (or really anything on here), so let me know if I made any accuracy mistakes. (ref. #2531)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3257)

y2r: convert some functions to use IPC helper

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h
src/core/hle/service/hid/hid_spvr.cpp
src/core/hle/service/hid/hid_spvr.h
src/core/hle/service/hid/hid_user.cpp
src/core/hle/service/hid/hid_user.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3304)

HID: convert to ServiceFramework

---

src/citra/emu_window/emu_window_sdl2.cpp

This makes it a lot easier to figure out which part of the system isn’t working correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3373)

Print the actual error preventing SDL from working

---

src/citra/config.cpp
src/citra_qt/configuration/config.cpp
src/core/settings.h
src/input_common/motion_emu.cpp

Follow up of #3154 .
Allows to set the tilt clamp to a value other than 90 degrees. I'm no good with the UI, so if this gets merged, someone else will have create a UI for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3366)

Variable tilt clamp

---

src/citra_qt/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3422)

correct escape sequence warning

---

src/citra/config.cpp
src/citra/default_ini.h
src/common/CMakeLists.txt
src/common/announce_multiplayer_room.h
src/core/CMakeLists.txt
src/core/announce_multiplayer_session.cpp
src/core/announce_multiplayer_session.h
src/core/settings.h
src/web_service/CMakeLists.txt
src/web_service/announce_room_json.cpp
src/web_service/announce_room_json.h
src/web_service/telemetry_json.cpp
src/web_service/telemetry_json.h
src/web_service/web_backend.cpp
src/web_service/web_backend.h

This will introduce the web-service to announce rooms to our web-service.
It also allows to fetch a list of announce rooms from the web-service.
For that the possibility to send DELETE msg to web-service was introduced, as well as some error handling in web-service backend
This PR requires #3068 to get merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3069)

Announce room webservice

---

src/core/hle/service/nwm/nwm.cpp
src/core/hle/service/nwm/nwm.h
src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/nwm_uds.h
src/core/hle/service/nwm/uds_beacon.cpp
src/core/hle/service/nwm/uds_beacon.h
src/core/hle/service/nwm/uds_data.cpp
src/core/hle/service/service.cpp

This changes uds to a service framework.
Functional changes:
- add NWM_UDS::ConnectToNetwork and NWM_UDS::DisconnectNetwork
- ties UDS to libnetwork
This PR requires #2968 to get merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3070)

NWM_UDS: change to Service Framework

---

src/citra_qt/main.cpp
src/citra_qt/main.h

Lets the user select multiple CIAs to be installed at once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3434)

QT: allow installation of multiple CIAs 

---

src/core/hle/service/cfg/cfg.h

Value was taken from [3dbrew](https://www.3dbrew.org/wiki/Cfg:GetSystemModel#System_Model_Values)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3480)

Service/CFG: add system model value for New 2DS XL

---

src/core/hle/service/news/news.cpp
src/core/hle/service/news/news.h
src/core/hle/service/news/news_s.cpp
src/core/hle/service/news/news_s.h
src/core/hle/service/news/news_u.cpp
src/core/hle/service/news/news_u.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3470)

Service/NEWS: convert to ServiceFramework 

---

src/core/hle/service/nfc/nfc.cpp
src/core/hle/service/nfc/nfc.h
src/core/hle/service/nfc/nfc_m.cpp
src/core/hle/service/nfc/nfc_m.h
src/core/hle/service/nfc/nfc_u.cpp
src/core/hle/service/nfc/nfc_u.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3476)

Service/NFC: convert to ServiceFramework

---

CONTRIBUTING.md

Add Discord in addition to IRC since people nowadays would find it easier to contact through Discord.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3466)

Add link to Discord

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

Fixes #3332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3542)

Service/AM: Fix crash when scanning titles with installed titles with invalid title IDs

---

src/core/tracer/recorder.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3606)

CiTrace: Migrate logging macros

---

src/core/hle/service/am/am.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3605)

Service/AM: Use Pop<u64>() in DeleteUserProgram and DeleteProgram

---

src/video_core/renderer_opengl/pica_to_gl.h

Removes the need to use the ARRAY_SIZE macro
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3600)

pica_to_gl: Use std::array where applicable

---

src/core/file_sys/disk_archive.cpp
src/core/file_sys/disk_archive.h

Each commit should be fairly self-contained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3596)

disk_archive: Minor miscellaneous cleanup

---

src/common/common_funcs.h
src/common/memory_util.cpp
src/common/swap.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3579)

common: Clean up architecture-specific defines

---

appveyor.yml

master:
pr:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3616)

appveyor: set jobs to 4 for mingw

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/dyncom/arm_dyncom_trans.cpp

Use new logging macros
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3621)

arm/dyncom: Migrate logging macros

---

src/citra/default_ini.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3625)

default_ini.h: Update Comment

---

src/citra/default_ini.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3641)

default_ini: remove space in custom_layout

---

src/core/movie.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3614)

movie: migrate logging macros

---

src/core/hle/service/apt/apt.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3587)

Service/APT: Migrate logging macros

---

src/core/hle/service/boss/boss.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3631)

service/boss: Migrate logging macros

---

src/citra/citra.cpp
src/citra/emu_window/emu_window_sdl2.cpp
src/citra/emu_window/emu_window_sdl2.h

Allow fullscreen in SDL2.
I've separated this from #3576 as they are not very closely related, and that PR is blocked due to UI issues.
* "--fullscreen"
* "-f"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3607)

SDL2: Implement fullscreen

---

src/citra_qt/multiplayer/lobby.ui

Fixed a really small error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3683)

multiplayer_ui: Replace "Hide Full Games" with "Hide Full Rooms"

---

src/video_core/renderer_opengl/gl_shader_decompiler.cpp

This is a solution to [my question in #3499](https://github.com/citra-emu/citra/pull/3499#issuecomment-382837814). We need a way to fallback from GPU shader to CPU shader for GS that relies on register preservation, and the detector is much simpler than I originally thought. The shader must use the special uniform b15 in order to correctly use registers across invocation, so we just error out on such case.
Also lowered the log level of decompilation failure from ERROR to INFO, as it would fallback to CPU shader which should be able to handle the cases correctly (or log another error otherwise).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3678)

gl_shader_decompiler: fallback to CPU shader on GS b15 access

---

src/citra_qt/debugger/console.cpp
src/citra_qt/main.cpp

Fixes #3693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3694)

Fix duplicated logs on windows

---

src/citra/emu_window/emu_window_sdl2.cpp
src/citra_qt/main.cpp

Class: Frontend
Level: Info
Format: "Citra Version: (Nightly/Canary) | (branch)-(commit)"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3665)

frontend: Log Citra version.

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3702)

gitignore: ignore CMakeLists.txt.user* instead of CMakeLists.txt.user

---

src/core/gdbstub/gdbstub.cpp

Change to use the new logging macros
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3668)

core/gdbstub: Migrate logging macros

---

.travis/transifex/docker.sh

Fix the mistake in #3734. Tested on a temporary branch in the main repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3735)

travis: fix dependency name for transifex job

---

src/citra_qt/main.cpp

Default hotkeys:
Continue/Pause: F4
Toggle Speed Limit: CTRL+Z
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3594)

citra_qt: Add Continue/Pause & Toggle Speed Limit hotkeys

---

src/core/hle/service/gsp/gsp_gpu.cpp
src/core/hle/service/gsp/gsp_gpu.h
src/core/hle/shared_page.cpp
src/core/hle/shared_page.h

Disregard the branch name
Sadly, the 2D Game I tested (Ultimate NES Remix) never called this Function, so it didnt f.ix* #3632. 
However, I already made it, so eh, would be a waste to throw away
Have Fun! ᶜᵘᶻ ᶦ ˢᵘʳᵉ ᵃᶦᶰᵗ ʰᵃᵛᶦᶰ ᵃᶰʸ
* Damn keywords
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3652)

gsp_gpu, shared_page: Change 3D LED State on SetLedForceOff

---

src/citra/citra.cpp

Just a correction for a possible typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3800)

citra: correct regex for matching nickname

---

src/core/hle/service/ac/ac.cpp

First time contributing. I wanted to help and thought this was a good way to start and learn the flow of things. I have always been interested in emulation and programming, and since the car accident I have had a bit time on my hands trying to recover from a brain injury.
I hope this works and helps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3838)

AC Migrate Logging Macros

---

src/citra/emu_window/emu_window_sdl2.cpp
src/citra_qt/aboutdialog.cpp
src/citra_qt/main.cpp
src/citra_qt/main.h
src/common/CMakeLists.txt
src/common/scm_rev.cpp.in
src/common/scm_rev.h

follow-up of #3783.
Addressed @jroweboy's comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3804)

citra-qt: Improve Title Bar display

---

src/core/hle/service/ac/ac.cpp

PR #3838 caused clang format to fail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3846)

service/ac: fix clang format

---

src/core/hle/service/csnd_snd.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3843)

service/csnd_snd: Migrate logging macros

---

src/core/hle/service/frd/frd.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3844)

service/frd: Migrate logging macros

---

src/core/hle/service/hid/hid.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3845)

service/hid: Migrate logging macros

---

src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/ir/ir_rst.cpp
src/core/hle/service/ir/ir_user.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3847)

service/ir: Migrate logging macros

---

src/core/hle/service/cam/cam.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3848)

service/cam: Migrate logging macros

---

src/core/hle/service/err_f.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3849)

service/err_f: Migrate logging macros

---

src/core/hle/service/gsp/gsp_gpu.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3852)

service/gsp: Migrate logging macros

---

src/core/hle/service/nfc/nfc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3855)

service/nfc: Migrate logging macros

---

src/core/hle/service/nim/nim_u.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3856)

service/nim: Migrate logging macros

---

src/core/hle/service/cfg/cfg.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3853)

service/cfg: Migrate logging macros

---

src/core/hle/service/ns/ns.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3857)

service/ns: Migrate logging macros

---

src/core/hle/service/sm/srv.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3859)

service/sm: Migrate logging macros

---

src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3860)

service/service: Migrate logging macros

---

src/core/hle/service/y2r_u.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3861)

service/y2r: Migrate logging macros

---

src/core/hle/service/am/am.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3864)

service/am: Migrate logging macros

---

src/core/hle/service/apt/applet_manager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3865)

service/apt/applet_manager: Migrate logging macros

---

src/core/hle/service/fs/archive.cpp
src/core/hle/service/fs/fs_user.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3866)

service/fs: Migrate logging macros

---

src/core/hle/service/ptm/ptm.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3868)

service/ptm: Migrate logging macros

---

src/core/hle/service/dlp/dlp_srvr.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3870)

service/dlp: Migrate logging macro

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/uds_data.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3871)

service/nwm: Migrate logging macros

---

src/core/hle/applets/applet.cpp
src/core/hle/applets/erreula.cpp
src/core/hle/applets/mii_selector.cpp
src/core/hle/applets/mint.cpp
src/core/hle/applets/swkbd.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3872)

applets: Migrate logging macros

---

src/common/logging/log.h
src/core/hle/kernel/address_arbiter.cpp
src/core/hle/kernel/handle_table.cpp
src/core/hle/kernel/memory.cpp
src/core/hle/kernel/mutex.cpp
src/core/hle/kernel/process.cpp
src/core/hle/kernel/resource_limit.cpp
src/core/hle/kernel/shared_memory.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/thread.cpp
src/core/hle/kernel/timer.cpp
src/core/hle/kernel/vm_manager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3876)

hle/kernel: Migrate logging macros

---

externals/httplib/README.md
externals/httplib/httplib.h
src/web_service/web_backend.cpp

Temporary fix deployed server-side, no rush.
This updates cpp-httplib to <https://github.com/yhirose/cpp-httplib/commit/d9479bc0b12e8a1e8bce2d34da4feeef488581f3>, which fixes various edge cases of chunked encoding as well as compression, affecting Citra's ability to talk to services.citra-emu.org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3834)

Update cpp-httplib for gzip + chunked encoding fixes

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Also adds two new languages: Danish and Polish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3830)

dist/languages: Update current translations

---

src/core/hle/service/gsp/gsp.cpp
src/core/hle/service/gsp/gsp.h
src/core/hle/service/gsp/gsp_lcd.cpp
src/core/hle/service/gsp/gsp_lcd.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3887)

service/gsp: Migrate gsp_lcd to ServiceFramework

---

src/core/hle/service/fs/archive.cpp

This only broke the debug build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3885)

FS: fix log with incorrect type

---

src/core/hle/service/mvd/mvd.cpp
src/core/hle/service/mvd/mvd.h
src/core/hle/service/mvd/mvd_std.cpp
src/core/hle/service/mvd/mvd_std.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3890)

service/mvd: Migrate to ServiceFramework

---

src/core/hle/service/service.cpp
src/core/hle/service/ssl_c.cpp
src/core/hle/service/ssl_c.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3874)

service/SSL: convert to ServiceFramework

---

src/core/hle/service/dlp/dlp.cpp
src/core/hle/service/dlp/dlp.h
src/core/hle/service/dlp/dlp_clnt.cpp
src/core/hle/service/dlp/dlp_clnt.h
src/core/hle/service/dlp/dlp_fkcl.cpp
src/core/hle/service/dlp/dlp_fkcl.h
src/core/hle/service/dlp/dlp_srvr.cpp
src/core/hle/service/dlp/dlp_srvr.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3893)

service/dlp: Migrate to ServiceFramework

---

src/core/hle/service/dlp/dlp_srvr.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3896)

Service/DLP: Fix IsChild

---

src/video_core/renderer_opengl/gl_shader_manager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3901)

gl_shader_manager: fix macro

---

src/video_core/renderer_opengl/gl_shader_gen.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3904)

gl_shader_gen: remove newline in logging macro

---

src/core/hle/service/cecd/cecd.cpp
src/core/hle/service/cecd/cecd.h
src/core/hle/service/cecd/cecd_ndm.cpp
src/core/hle/service/cecd/cecd_ndm.h
src/core/hle/service/cecd/cecd_s.cpp
src/core/hle/service/cecd/cecd_s.h
src/core/hle/service/cecd/cecd_u.cpp
src/core/hle/service/cecd/cecd_u.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3906)

service/cecd: Migrate to ServiceFramework

---

src/citra_qt/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3905)

citra_qt: Remove return

---

src/core/hle/service/csnd_snd.cpp
src/core/hle/service/csnd_snd.h
src/core/hle/service/service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3908)

service/csnd: Migrate to ServiceFramework

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

The initial test of always calling glTextureBarrier fixes #3731. This version only calls glTextureBarrier on image bound to texture and framebuffer, which should be enough. More test are welcome
The game, Monster Hunter Gen/X/XX binds an image of the entire rendered screen to both texture and framebuffer to do gamma correction and stuff.
`CheckBarrier` is not applied to TextureCube because in the current texture cache module it can never be the same texture as the one attached to the framebuffer.
Thanks @degasus for finding this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3926)

gl_rasterizer: call glTextureBarrier when an image is bound to both texture and framebuffer

---

src/common/telemetry.h

Just a few minor cleanup-related changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3956)

common/telemetry: Minor changes

---

src/citra_qt/configuration/configure_debug.cpp
src/citra_qt/configuration/configure_debug.ui
src/citra_qt/configuration/configure_general.cpp
src/citra_qt/configuration/configure_general.ui

Self-explanatory.
---
Will attach an actual screenshot as soon as AppVeyor gives me the artifact. :P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3971)

citra_qt: Move CPU JIT toggle to Debug tab.

---

src/common/string_util.cpp
src/common/string_util.h

Please refer to yuzu-emu/yuzu#704 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4027)

Port "string_util: Remove AsciiToHex()" from yuzu

---

src/common/file_util.cpp

Please refer to yuzu-emu/yuzu#765 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4026)

Port "file_util: Remove goto usages from Copy()" from yuzu

---

src/common/file_util.cpp
src/common/file_util.h

Please refer to yuzu-emu/yuzu#705 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4036)

Port "file_util: return string by const reference for GetExeDirectory()" from yuzu

---

src/citra_qt/debugger/wait_tree.cpp

This PR is written manually, because my bot failed because of bad Internet :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4034)

Port "wait_tree: Silence warning about all code paths not returning a value" from yuzu

---

src/citra_qt/game_list.cpp
src/common/file_util.cpp
src/common/file_util.h

Please refer to yuzu-emu/yuzu#764 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4033)

Port "file_util: Minor changes to ScanDirectoryTree() and ForeachDirectoryEntry()" from yuzu

---

src/common/logging/backend.cpp
src/common/logging/backend.h
src/common/logging/filter.cpp
src/common/logging/filter.h

Please refer to yuzu-emu/yuzu#743 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4030)

Port "logging: Use std::string_view where applicable" from yuzu

---

src/common/swap.h

Please refer to yuzu-emu/yuzu#711 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4038)

Port "common/swap: Minor changes" from yuzu

---

src/citra_qt/debugger/wait_tree.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/timer.h

Please refer to yuzu-emu/yuzu#837 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4022)

Port yuzu-emu/yuzu#837 from yuzu

---

src/common/param_package.cpp
src/common/param_package.h

Please refer to yuzu-emu/yuzu#745 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4024)

Port yuzu-emu/yuzu#745 from yuzu

---

src/audio_core/dsp_interface.h
src/audio_core/hle/hle.cpp
src/audio_core/hle/hle.h
src/core/hle/service/dsp/dsp_dsp.cpp
src/core/hle/service/dsp/dsp_dsp.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3996)

service/dsp: Clean up global state

---

src/core/gdbstub/gdbstub.cpp

Please refer to yuzu-emu/yuzu#723 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4031)

Port "gdbstub: Get rid of a few signed/unsigned comparisons" from yuzu

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Adds two new languages: Turkish and Vietnamese.
_Also gets the issue / PR counter to 4000._
K-pop for everyone!
f(x) - "Chu~♡": https://www.youtube.com/watch?v=oB9Qs7TIl1w
f(x) - "Rum Pum Pum Pum": https://www.youtube.com/watch?v=LVnV-B3FzB8
4Minute - "Hate": https://www.youtube.com/watch?v=D_F9HUTYnl0
4Minute - "What's your name?": https://www.youtube.com/watch?v=H-IJWqIHioA
Hyuna - "Roll Deep": https://www.youtube.com/watch?v=ib_1ATfr8wM
Hyuna - "How's this?": https://www.youtube.com/watch?v=y882AFjrSOM
Hyuna - "Red": https://www.youtube.com/watch?v=oTXCgR93zC8
Hyuna - "Ice Cream": https://www.youtube.com/watch?v=vTxZx1NBGic
Hyuna - "Lip & Hip": https://www.youtube.com/watch?v=vcqImqOVE2U
Hyuna - "Bubble Pop!": https://www.youtube.com/watch?v=Wcuj2pIIXEQ
Girls' Generation - "Beep Beep": …

dist/languages: Update translations

---

src/common/common_funcs.h
src/common/misc.cpp

See https://github.com/yuzu-emu/yuzu/pull/709 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4021)

Port #709 from yuzu: "common/misc: Deduplicate code in GetLastErrorMsg()

---

src/audio_core/codec.cpp
src/audio_core/hle/filter.cpp
src/audio_core/hle/mixers.cpp
src/audio_core/interpolate.cpp
src/audio_core/time_stretch.cpp
src/citra_qt/camera/camera_util.cpp
src/common/math_util.h
src/core/hw/y2r.cpp
src/core/perf_stats.cpp
src/input_common/motion_emu.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/swrasterizer/framebuffer.cpp
src/video_core/swrasterizer/lighting.cpp
src/video_core/swrasterizer/rasterizer.cpp
src/video_core/swrasterizer/texturing.cpp
src/video_core/texture/etc1.cpp

Just me being a wannabe Lioncash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/3994)

Remove MathUtil::Clamp and replace it with its std:: counterpart

---

src/core/settings.cpp
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/video_core.cpp
src/video_core/video_core.h

Follow up of #4050 
As @jroweboy stated, this is just one more atomic in VideoCore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4052)

video_core: Allow changing background color while emulation is running

---

src/citra_qt/game_list.cpp

Not really a port, as the commit is completely different..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4065)

game_list: Use QString::fromStdString() where applicable instead of c_str()

---

src/core/hle/kernel/thread.h

Please refer to yuzu-emu/yuzu#882 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4085)

Port "kernel/thread: Remove unimplemented function prototype" from yuzu

---

src/core/hle/kernel/thread.cpp

Please refer to yuzu-emu/yuzu#904 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4083)

Port "kernel/thread: Minor changes" from yuzu

---

src/input_common/keyboard.cpp
src/input_common/motion_emu.cpp
src/input_common/sdl/sdl.cpp

Please refer to yuzu-emu/yuzu#906 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4082)

Port "input_common: minor changes" from yuzu

---

src/common/math_util.h

Please refer to yuzu-emu/yuzu#900 for details.
~~**Caution! This PR had cherry-pick conflicts while being generated.**~~ No conflict
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4081)

Port "math_util: Always initialize members of Rectangle" from yuzu

---

src/common/color.h

Please refer to yuzu-emu/yuzu#988 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4073)

Port "common/color: Minor cleanup" from yuzu

---

src/citra/default_ini.h
src/citra_qt/configuration/config.cpp
src/core/settings.h
src/input_common/udp/client.cpp
src/input_common/udp/client.h
src/input_common/udp/udp.cpp

Allows changing the pad index to request data on.
The UI PR will get updated once this is merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4084)

input_common/udp: allow changing pad index

---

src/network/room.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4094)

network: fix 3 typos

---

src/core/hle/service/soc_u.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4112)

fix soc service - Fcntl failed on validate header

---

src/citra_qt/game_list.cpp

See yuzu-emu/yuzu#943 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4131)

Port #943 from yuzu: "game_list: Join declarations and assignments in onTextChanged()"

---

src/citra_qt/debugger/graphics/graphics_breakpoint_observer.h
src/citra_qt/debugger/graphics/graphics_breakpoints.h
src/citra_qt/debugger/graphics/graphics_breakpoints_p.h
src/citra_qt/debugger/graphics/graphics_surface.h

See yuzu-emu/yuzu#907 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4124)

Port #907 from yuzu: "yuzu: Use Qt 5 signal/slots where applicable"

---

src/core/hle/kernel/vm_manager.cpp

See yuzu-emu/yuzu#905 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4122)

Port #905 from yuzu: "kernel/vm_manager: Minor changes"

---

src/audio_core/sink_details.h

See yuzu-emu/yuzu#895 for more datils.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4120)

Port #895 from yuzu: "sink_details: std::move std::function instances "

---

src/video_core/video_core.h

See yuzu-emu/yuzu#911 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4119)

Port #911 from yuzu: "video_core: Remove unimplemented Start() function prototype"

---

src/common/vector_math.h

See yuzu-emu/yuzu#968 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4133)

Port #968 from yuzu: "vector_math: Minor cleanups"

---

CMakeLists.txt
src/citra_qt/configuration/configure_debug.ui
src/core/arm/dynarmic/arm_dynarmic.cpp
src/core/arm/dyncom/arm_dyncom.cpp
src/core/arm/dyncom/arm_dyncom_interpreter.cpp
src/core/arm/skyeye_common/armstate.cpp
src/core/arm/skyeye_common/armstate.h
src/core/core.cpp
src/core/gdbstub/gdbstub.cpp
src/core/gdbstub/gdbstub.h

- Can be used in either DynCom or Dynarmic mode
- Added support for threads
- Proper support for FPU registers
- Fix for NibbleToHex conversion that used to produce false error codes
- Fix for clang-format failing under Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4101)

GDB Modernization

---

src/common/vector_math.h

See yuzu-emu/yuzu#987 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4151)

Port #987 from yuzu: "vector_math: Use variable template version of is_signed in Vec classes"

---

src/common/x64/xbyak_abi.h
src/common/x64/xbyak_util.h

See yuzu-emu/yuzu#1063 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4154)

Port #1063 from yuzu: "common/xbyak_abi: Mark defined functions in header as inline "

---

src/core/memory.h

See yuzu-emu/yuzu#933 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4158)

Port #933 from yuzu: Multiple cleanups in memory

---

src/video_core/renderer_opengl/gl_stream_buffer.h

See yuzu-emu/yuzu#1133 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4160)

Port #1133 from yuzu: "gl_stream_buffer: Add missing header guard"

---

src/core/frontend/emu_window.h

See yuzu-emu/yuzu#1067 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4159)

Port #1067 from yuzu: "emu_window: Ensure WindowConfig members are always initialized"

---

src/video_core/renderer_opengl/renderer_opengl.cpp

See yuzu-emu/yuzu#1097 for more details.
~~Merge it for the sake of consistency.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4163)

Port #1097 from yuzu: "renderer_opengl: Treat OpenGL errors as critical."

---

CMakeLists.txt

See yuzu-emu/yuzu#1030 for more details.
NOTE: Pushing this branch to the main repo was not intended, and I'll delete the branch as soon as the PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4152)

Port #1030 from yuzu: "externals: Update to SDL2-2.0.8"

---

src/audio_core/cubeb_sink.cpp

Same reason as yuzu-emu/yuzu#1038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4168)

cubeb_sink: Protect queue against multithreaded access

---

src/audio_core/hle/source.cpp
src/common/bit_field.h
src/video_core/regs_texturing.h

See yuzu-emu/yuzu#1139 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4161)

Port #1139 from yuzu: "bit_field: Convert ToBool() into explicit operator bool"

---

src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/object.h

See yuzu-emu/yuzu#1048 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4157)

Port #1048 from yuzu: "kernel/object: Tighten object against data races"

---

CMakeLists.txt
src/citra_qt/CMakeLists.txt
src/citra_qt/game_list.cpp
src/citra_qt/game_list_p.h
src/citra_qt/main.cpp
src/citra_qt/util/util.cpp
src/citra_qt/util/util.h

In https://github.com/yuzu-emu/yuzu/pull/1195 @lioncash left that some comments that also need to be addressed for Citra. 
~~Every review comment on this PR delays Pokemon XY to be playable by 10 years.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4170)

citra_qt: Backport some review fixes of Lioncash

---

src/core/hle/service/hid/hid_spvr.cpp
src/core/hle/service/hid/hid_user.cpp

Just a small change. ([taken from 3dbrew](https://www.3dbrew.org/wiki/HID_Services#HID_service_.22hid:USER.22))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4139)

Service/HID: update function table

---

src/common/alignment.h
src/common/bit_field.h
src/common/bit_set.h
src/common/file_util.h
src/common/hash.h
src/common/x64/xbyak_util.h

Please see yuzu-emu/yuzu#966 and yuzu-emu/yuzu#414 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4132)

Port #966 and #414 from yuzu (Cleanups in common and file_util) & Make bitfield assignment operator public

---

src/network/room_member.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4190)

room_member: fix 3 typos

---

src/network/room_member.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4191)

room_member: RakNet -> ENet

---

src/core/hle/kernel/svc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4192)

svc: change unknown to thread in CreateThread

---

src/citra/emu_window/emu_window_sdl2.cpp
src/input_common/sdl/sdl.cpp

See yuzu-emu/yuzu#1275 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4201)

SDLJoystick: Backport review comments from yuzu #1275

---

src/core/hle/ipc.h

Change desciptors to descriptors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4210)

ipc: fix typo

---

src/citra_qt/util/util.cpp

* Antialias game list compatibility pixmaps
for info, see [yuzu-emu/yuzu#1336](https://github.com/yuzu-emu/yuzu/pull/1336)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4231)

Port #1336 from yuzu

---

src/common/logging/filter.h
src/common/logging/log.h
src/common/logging/text_formatter.h

See yuzu-emu/yuzu#1238 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4221)

Port #1238 from yuzu: "common/logging: Minor changes"

---

src/core/hle/service/soc_u.cpp
src/core/hle/service/soc_u.h

~~I'm not really sure about `rp.MakeBuilder(2, 4)` but tested it working.~~
I got it now. Fixed and tested. working with BufferSize = 0x3000
Build failed seem not relate to this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4114)

Implement soc - RecvFromOther

---

CMakeLists.txt
externals/CMakeLists.txt
src/core/CMakeLists.txt
src/core/core.cpp
src/core/core.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4262)

Added CMake option to enable/disable scripting support

---

src/citra_qt/debugger/wait_tree.cpp
src/core/hle/kernel/address_arbiter.cpp
src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/mutex.cpp
src/core/hle/kernel/server_session.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/thread.cpp
src/core/hle/kernel/thread.h
src/core/hle/kernel/wait_object.cpp
src/core/hle/service/fs/archive.cpp
src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/service.cpp
src/core/hle/service/sm/srv.cpp

See yuzu-emu/yuzu#734 and yuzu-emu/yuzu#1310 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4224)

Port #734 and #1310 from yuzu: Changes to Thread-related enums

---

src/citra_qt/game_list.cpp

See yuzu-emu/yuzu#1367 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4241)

Port yuzu/#1367 from yuzu: "game_list: Handle plurals within setFilterResult() better"

---

src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/cfg/cfg.h
src/core/loader/ncch.cpp

Mainly to deal with games like pokemon which is marked "region free"  in the header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4232)

loader, cfg: choose region based on language if multiple regions available

---

src/core/hle/service/http_c.cpp

Similar to #4273.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4274)

http_c: access FS via backend directly

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h
src/core/hle/service/am/am_u.cpp

This function just returns a Mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4288)

Services/AM: Implement the GetSystemUpdaterMutex function.

---

src/citra_qt/configuration/configure_audio.cpp
src/citra_qt/configuration/configure_audio.h
src/citra_qt/configuration/configure_input.cpp

Please see each commit and the PRs yuzu-emu/yuzu#1429 and yuzu-emu/yuzu#1431 for more details on the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4300)

Port yuzu-emu/yuzu#1429 and yuzu-emu/yuzu#1431: Minor configuration changes

---

src/input_common/sdl/sdl_impl.cpp

Any SDL invocation can call the event callback on the same thread, which can call GetSDLJoystickBySDLID and eventually cause double lock on joystick_map_mutex. To avoid this, lock guard should be placed as closer as possible to the object accessing code, so that any SDL invocation is with the mutex unlocked
We previously assumed that the callback is always called by a separate SDL thread. Apparently this is unspecified by SDL, so we need to assume that any SDL call can also step into the callback. An example callstack on crash, provided by @FearlessTobi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4289)

input/sdl: lock map mutex after SDL call

---

src/core/movie.cpp

Fixes invalid movie error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4307)

movie: fix some checks

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/nwm_uds.h

Some cleanups in NWM_UDS:
- Only handle packets if they match the current state
- Fix some issues in Disconnect
- Some code cleanups (e.g. in SendTo)
There are no changes that require a Network Version Bump
I'd like to get a report of most of the multiplayer games to verify that this PR doesn't break anything, before we merge it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4299)

NWM_UDS: Fix some issues, cleanups, better PacketHandling

---

src/core/hle/service/apt/applet_manager.cpp
src/core/hle/service/apt/applet_manager.h
src/core/hle/service/apt/apt.cpp
src/core/hle/service/apt/apt.h
src/core/hle/service/apt/apt_a.cpp
src/core/hle/service/apt/apt_s.cpp
src/core/hle/service/apt/apt_u.cpp

The real console can't launch an Application directly from within another Application so it has to go through the Home Menu. We do not have such limitation and can directly launch the requested title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4306)

Services/APT: Better implementation of PrepareToDoApplicationJump and DoApplicationJump.

---

.travis/clang-format/script.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4327)

travis: Ignore binary files when checking for trailing whitespace

---

src/citra_qt/configuration/configure_input.cpp
src/citra_qt/configuration/configure_input.h
src/core/core.cpp
src/core/file_sys/ticket.cpp
src/core/file_sys/ticket.h
src/core/hle/kernel/shared_memory.cpp
src/core/hle/service/am/am.cpp
src/core/hle/service/apt/applet_manager.cpp
src/core/hle/service/apt/applet_manager.h
src/core/hle/service/apt/apt.cpp
src/core/hle/service/http_c.cpp
src/core/hle/service/http_c.h
src/core/hw/aes/key.cpp
src/core/loader/loader.h
src/core/loader/ncch.cpp
src/core/loader/ncch.h
src/core/memory.cpp
src/core/memory.h
src/input_common/udp/client.h
src/input_common/udp/protocol.cpp
src/input_common/udp/protocol.h
src/input_common/udp/udp.cpp
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/renderer_opengl/gl_shader_decompiler.cpp
src/video_core/renderer_opengl/gl_shader_decompiler.h
src/video_core/renderer_opengl/gl_shader_gen.cpp
src/video_core/renderer_opengl/gl_shader_gen.h
src/video_core/renderer_opengl/gl_shader_manager.cpp
src/video_core/shader/shader_jit_x64_compiler.cpp
src/video_core/shader/shader_jit_x64_compiler.h

There are still some boost::optional left but they require dynarmic to have a similar fix applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4304)

Replace boost::optional with std::optional where possible

---

src/citra/config.cpp

fixes #4144. Updated inih to use the newly added GetString function which returns the default value on empty string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4331)

citra: fix cemuhook module crash

---

CMakeLists.txt
src/common/file_util.cpp

@bakugo could you test to see if this fixes #4332 ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4336)

Only redefine some 64-bit file operation for MSVC

---

src/citra_qt/CMakeLists.txt
src/citra_qt/compatibility_list.cpp
src/citra_qt/compatibility_list.h
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/game_list_p.h
src/citra_qt/game_list_worker.cpp
src/citra_qt/game_list_worker.h
src/citra_qt/main.cpp
src/citra_qt/main.h

See https://github.com/yuzu-emu/yuzu/pull/1259, https://github.com/yuzu-emu/yuzu/pull/1282, https://github.com/yuzu-emu/yuzu/pull/1301 and https://github.com/yuzu-emu/yuzu/pull/1335 for more details.
It is highly advised to review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4235)

Port various game_list changes from yuzu

---

src/common/CMakeLists.txt
src/common/announce_multiplayer_room.h
src/common/web_result.h
src/core/CMakeLists.txt
src/core/telemetry_session.cpp
src/core/telemetry_session.h
src/web_service/telemetry_json.cpp
src/web_service/telemetry_json.h
src/web_service/verify_login.cpp
src/web_service/web_backend.cpp
src/web_service/web_backend.h

See yuzu-emu/yuzu#1465 and yuzu-emu/yuzu#1473 for more details.
It's highly advised to review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4359)

web_service: Port yuzu-emu/yuzu#1465 and Port yuzu-emu/yuzu#1473 (Many self-contained changes)

---

src/citra_qt/bootmanager.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/config.h
src/citra_qt/configuration/configure_system.cpp
src/citra_qt/configuration/configure_system.h
src/citra_qt/game_list.cpp

This PR ports parts of https://github.com/yuzu-emu/yuzu/pull/1558, https://github.com/yuzu-emu/yuzu/pull/1587, https://github.com/yuzu-emu/yuzu/pull/1567 and https://github.com/yuzu-emu/yuzu/pull/1566.
Please see each comment individually to see the reasons behind the change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4374)

Port various frontend cleanups from yuzu

---

src/core/hle/kernel/ipc.cpp
src/core/hle/kernel/vm_manager.h
src/core/memory.cpp
src/core/memory.h

I had to implement a few more cases in the ipc mapped buffer handling to allow the lle cecd module to run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4228)

LLE Mapped Buffer: Add unmapping of write buffer, zero-size, and multiple page handling

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Current translations as of 2018/11/02.
* Adds in Norwegian language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4395)

dist/languages: Updated translations

---

src/core/hle/service/ldr_ro/ldr_ro.cpp

Change `std::tie` to structured binding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4409)

ldr_ro: change std::tie to structured binding

---

src/video_core/CMakeLists.txt
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/renderer_opengl/gl_resource_manager.cpp
src/video_core/renderer_opengl/gl_resource_manager.h
src/video_core/renderer_opengl/gl_shader_manager.h
src/video_core/renderer_opengl/gl_stream_buffer.cpp

Please see https://github.com/yuzu-emu/yuzu/pull/1649 and https://github.com/yuzu-emu/yuzu/pull/1653 for more details.
I recommend reviewing this commit-by-commit. 
You'll find a short description of the changes in each one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4439)

Port yuzu-emu/yuzu#1649 and yuzu-emu/yuzu#1653: Changes to gl_resource_manager and gl_rasterizer

---

src/core/hle/kernel/ipc.cpp
src/core/hle/kernel/ipc.h
src/core/hle/kernel/server_session.h
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/vm_manager.cpp
src/core/hle/kernel/vm_manager.h
src/core/memory.cpp
src/tests/core/hle/kernel/hle_ipc.cpp
src/tests/core/memory/vm_manager.cpp

To make it simpler.
@Subv Request for review on the IPC mapped buffer part (and probably test it with LLE DLP to make sure it still works)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4433)

VMManager: remove shared_ptr<vector> backing type

---

src/common/string_util.cpp
src/common/string_util.h
src/core/hle/service/ir/extra_hid.cpp
src/core/movie.cpp

See yuzu-emu/yuzu#1684 for more details.
Removes some unnecessary/unused functions. Each commit contains the rationale for doing so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4444)

Port yuzu-emu/yuzu#1684: "common/string_util: Minor cleanup"

---

src/core/hle/applets/swkbd.cpp
src/core/hle/kernel/handle_table.cpp
src/core/hle/kernel/handle_table.h
src/core/hle/kernel/shared_memory.cpp
src/core/hle/kernel/shared_memory.h
src/core/hle/kernel/svc.cpp
src/core/hle/service/apt/apt.cpp
src/core/hle/service/http_c.cpp
src/core/hle/service/ir/ir_user.cpp
src/core/hle/service/mic_u.cpp
src/core/hle/service/nwm/nwm_uds.cpp

See yuzu-emu/yuzu#1734 and yuzu-emu/yuzu#1767 for more details.
Please review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4456)

Port yuzu-emu/yuzu#1734 and yuzu-emu/yuzu#1767: Minor changes to "kernel"

---

src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/ir/ir_user.cpp
src/core/movie.cpp

Should hopefully get Bitrise CI passing again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4462)

ir_user: Remove ArrayToString() calls

---

src/common/thread.cpp
src/common/thread.h

See yuzu-emu/yuzu#1773 for more details.
Gets rid of obsolete functions and tidies up the rest of the interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4458)

Port yuzu-emu/yuzu#1773: "common/thread: Minor cleanup"

---

src/dedicated_room/citra-room.cpp

Without this change, it will not accept 254 but it will say that the maximum is 254.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4497)

dedicated_room: allow maximum members = 254

---

src/citra_qt/multiplayer/host_room.ui

the minimum for dedicated_room is 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4498)

host_room: change minimum members to 2

---

src/citra_qt/configuration/configure_audio.h
src/citra_qt/configuration/configure_camera.h
src/citra_qt/configuration/configure_debug.h
src/citra_qt/configuration/configure_dialog.h
src/citra_qt/configuration/configure_general.h
src/citra_qt/configuration/configure_graphics.h
src/citra_qt/configuration/configure_input.cpp
src/citra_qt/configuration/configure_input.h
src/citra_qt/configuration/configure_motion_touch.h
src/citra_qt/configuration/configure_ui.h
src/citra_qt/configuration/configure_web.h
src/citra_qt/game_list.cpp
src/citra_qt/game_list_worker.cpp

This ports https://github.com/yuzu-emu/yuzu/pull/1832, https://github.com/yuzu-emu/yuzu/pull/1837 and https://github.com/yuzu-emu/yuzu/pull/1842.
As always, please review commit-by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4489)

Port QT interface changes from yuzu.

---

README.md

reflect migration to wiki
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4528)

update CONTRIBUTING link

---

src/network/CMakeLists.txt

This is not used anywhere in in the module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4543)

network: remove cpp-jwt library dependency

---

.travis/macos/upload.sh

This works locally, as far as I can see. Testing on CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4517)

[WIP] travis: Simplify macos/upload.sh

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/nwm_uds.h

No functional change. Just moving around variables and function declarations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4614)

NWM_UDS: move states into the class

---

src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/config.h
src/citra_qt/configuration/configure_dialog.cpp
src/citra_qt/configuration/configure_dialog.h
src/video_core/renderer_base.h
src/video_core/video_core.cpp

Link to PR: https://github.com/yuzu-emu/yuzu/pull/2058.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4628)

Backport various minor frontend review changes from yuzu and port minor PR from yuzu

---

src/core/file_sys/archive_ncch.h
src/core/hle/applets/applet.cpp
src/core/hle/applets/applet.h
src/core/hle/applets/erreula.cpp
src/core/hle/applets/erreula.h
src/core/hle/applets/mii_selector.cpp
src/core/hle/applets/mii_selector.h
src/core/hle/applets/mint.cpp
src/core/hle/applets/mint.h
src/core/hle/applets/swkbd.cpp
src/core/hle/applets/swkbd.h
src/core/hw/aes/arithmetic128.cpp
src/core/hw/aes/arithmetic128.h
src/core/hw/aes/ccm.cpp
src/core/hw/aes/ccm.h
src/core/hw/aes/key.cpp
src/core/hw/aes/key.h
src/core/hw/y2r.cpp
src/core/hw/y2r.h

Some files already used nested namespaces, however some didn't. No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4653)

core: use nested namespaces

---

.travis/macos/upload.sh

Should fix #4643 (ffmpeg was updated to 4.1.1).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4650)

travis/macos/upload: Don't hardcode ffmpeg/libvorbis versions

---

src/common/file_util.cpp
src/common/file_util.h

splits the getting and setting into two functions
blocks #4575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4598)

common: decouple getting and setting user paths

---

src/core/frontend/emu_window.cpp

You can now click or drag on either eye's touchscreen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4596)

Fix mouse touchscreen in SBS 3D mode

---

src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/server_session.cpp
src/core/hle/kernel/server_session.h
src/core/hle/service/service.cpp
src/core/hle/service/service.h
src/tests/core/hle/kernel/hle_ipc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4617)

HLE/IPC: clean up System::GetInstance

---

src/input_common/sdl/sdl_impl.cpp

See yuzu-emu/yuzu#2254 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4705)

Port yuzu-emu/yuzu#2254: "input_common/sdl_impl: Minor cleanup in SDLState constructor"

---

src/common/bit_field.h

Taken from yuzu-emu/yuzu#2210.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4694)

Port commit from yuzu-emu/yuzu#2210: "common/bit_field: Make BitField trivially copyable"

---

src/core/core.cpp
src/core/hle/service/apt/apt.cpp
src/core/hle/service/dsp/dsp_dsp.cpp
src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/ir/extra_hid.h
src/core/hle/service/ir/ir_user.cpp
src/core/hle/service/y2r_u.cpp
src/core/hle/service/y2r_u.h
src/core/hw/y2r.cpp
src/core/hw/y2r.h
src/core/memory.cpp
src/core/memory.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4683)

Misc global instance reference cleaup

---

src/citra/config.cpp
src/core/hle/service/service.cpp
src/web_service/verify_login.h

This ports yuzu-emu/yuzu#2189, yuzu-emu/yuzu#2222, yuzu-emu/yuzu#2218 which are all only minor changes. 
Please rview commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4693)

Port yuzu-emu/yuzu#2189, yuzu-emu/yuzu#2222, yuzu-emu/yuzu#2218

---

src/citra/citra.cpp
src/citra_qt/compatdb.cpp
src/citra_qt/main.cpp
src/common/logging/backend.cpp
src/common/logging/backend.h
src/core/core.cpp
src/core/core.h
src/core/loader/ncch.cpp
src/video_core/renderer_opengl/gl_shader_gen.cpp
src/video_core/renderer_opengl/pica_to_gl.h
src/video_core/renderer_opengl/renderer_opengl.cpp

See yuzu-emu/yuzu#2188 and yuzu-emu/yuzu#2190 for more details.
I strongly advise to review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4681)

Port yuzu-emu/yuzu#2188 and yuzu-emu/yuzu#2190: various minor code refactoring changes

---

src/common/scope_exit.h
src/common/swap.h

See yuzu-emu/yuzu#2391 and yuzu-emu/yuzu#2392 for more details.
Please review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4734)

Port yuzu-emu/yuzu#2391 and yuzu-emu/yuzu#2392: Changes to common

---

src/citra_qt/configuration/configure_dialog.cpp
src/citra_qt/configuration/configure_dialog.h
src/citra_qt/configuration/configure_web.cpp
src/citra_qt/configuration/configure_web.h
src/citra_qt/configuration/configure_web.ui
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/main.cpp
src/citra_qt/multiplayer/host_room.cpp
src/citra_qt/multiplayer/host_room.h
src/citra_qt/multiplayer/lobby.cpp
src/citra_qt/multiplayer/lobby.h
src/citra_qt/multiplayer/message.cpp
src/citra_qt/multiplayer/message.h
src/citra_qt/multiplayer/state.cpp
src/citra_qt/multiplayer/state.h
src/common/announce_multiplayer_room.h
src/core/announce_multiplayer_session.cpp
src/core/announce_multiplayer_session.h
src/core/telemetry_session.cpp
src/core/telemetry_session.h
src/web_service/announce_room_json.cpp
src/web_service/announce_room_json.h

Fixes #3339
It's recommended to review commit by commit. More information is available in the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4749)

web_service: Misc fixes

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4762)

Update translations (2019-04-30)

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4765)

Updated Contributing link in README.md

---

src/common/math_util.h
src/input_common/sdl/sdl_impl.cpp

See yuzu-emu/yuzu#2528 and yuzu-emu/yuzu#2530 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4786)

Port yuzu-emu/yuzu#2528 and yuzu-emu/yuzu#2530: Minor changes

---

src/citra_qt/configuration/configure_hotkeys.cpp
src/citra_qt/util/sequence_dialog/sequence_dialog.cpp

See yuzu-emu/yuzu#2517 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4783)

Port yuzu-emu/yuzu#2517: "configure_hotkeys: Minor cleanup"

---

src/CMakeLists.txt

See yuzu-emu/yuzu#2454 and yuzu-emu/yuzu#2460 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4805)

Port yuzu-emu/yuzu#2454 and yuzu-emu/yuzu#2460: Add build flags

---

src/core/file_sys/ncch_container.cpp

This adds support for custom exheaders, which brings feature parity
with Luma3DS's code patching functionality and allows for injecting
new game code.
Also, resize the code buffer according to the exheader to make it possible
to increase code size by combining exheader replacement and
IPS patching.
This also ensures the codeset memory (created in
AppLoader_NCCH::LoadExec) actually is large enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4813)

ncch_container: Add support for exheader replacement 

---

src/common/common_paths.h
src/common/file_util.cpp
src/common/logging/text_formatter.cpp
src/input_common/main.cpp

A few minor improvements so things play nice with other platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4820)

common: Various fixes and minor improvements.

---

src/citra_qt/multiplayer/host_room.h
src/citra_qt/multiplayer/lobby.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4831)

citra_qt/multiplayer: silent Wreorder warnings

---

src/audio_core/cubeb_input.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4834)

audio_core/cubeb: silent signed/unsigned comparison warning

---

src/core/arm/dyncom/arm_dyncom_interpreter.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4837)

interpreter: silent sign warnings

---

src/core/hle/kernel/client_port.cpp
src/core/hle/kernel/process.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4838)

kernel: silence -Wreorder

---

src/core/file_sys/ncch_container.cpp

Require and assume that override exheaders are decrypted for consistency with Luma's loader and to ensure consistent behaviour regardless of whether the NCCH is marked as encrypted or not.
Currently, exheader overriding with an encrypted NCCH would cause the title ID checking heuristic to mistakenly disable encryption, which would then make exefs loading fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4862)

ncch_container: Assume override exheaders are decrypted

---

src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_ui.cpp
src/citra_qt/configuration/configure_ui.ui
src/citra_qt/game_list.cpp
src/citra_qt/game_list_p.h
src/citra_qt/uisettings.h
src/core/loader/smdh.cpp
src/core/loader/smdh.h

Refer to the commit messages for details.
Screenshot of the configuration page:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4896)

citra_qt: Misc game list updates/fixes

---

src/core/file_sys/ncch_container.cpp

Fixes a regression from #4862, which caused the NCCH title ID checking
heuristic to be skipped whenever the exheader is replaced.
I was thinking the heuristic wouldn't be needed in that case, but it
turns out that many users still have pathological NCCHs that indicate
they are encrypted but are actually decrypted...
Now the original exheader is always read and used for the heuristic
to determine whether the NCCH is actually encrypted; only then do we
load a replacement exheader (if it exists) to avoid affecting the
heuristic.
Apologies for the regression :/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4900)

ncch_container: Fix NCCH decryption heuristic when replacing exheader

---

src/citra_qt/main.cpp

Made a minor change to https://github.com/citra-emu/citra/pull/4931 and didn't wanna stall the change any longer than needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4944)

Added Host CPU and OS to log

---

src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_graphics.cpp
src/citra_qt/configuration/configure_graphics.h
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/game_list_p.h
src/citra_qt/game_list_worker.cpp
src/citra_qt/game_list_worker.h
src/citra_qt/main.cpp
src/citra_qt/main.h
src/citra_qt/uisettings.h
src/core/perf_stats.cpp
src/core/perf_stats.h

This backports various changes that were done in yuzu review of Citra port PRs.
Please review commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4952)

Backport various review changes from yuzu

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4945)

Update translations (2019-09-21)

---

src/citra_qt/main.cpp
src/citra_qt/main.h

[![Video](https://cdn-b-east.streamable.com/image/zrlqw_first.jpg)](https://streamable.com/zrlqw)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4948)

citra_qt: add amiibo drag and drop support

---

src/citra_qt/configuration/config.cpp

Fixes #4999
_Here's the obligatory K-pop. Enjoy!_
https://www.youtube.com/watch?v=kOHB85vDuow
https://www.youtube.com/watch?v=deV_DmHKwjc
https://www.youtube.com/watch?v=gqhWHy0rrtM
https://www.youtube.com/watch?v=nKU4OVH18mE
https://www.youtube.com/watch?v=mAKsZ26SabQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5000)

citra_qt/configuration: add missing Read/SaveUtilityValues

---

src/citra_qt/configuration/configure_input.cpp
src/core/settings.cpp

Videos:
[Nightly](https://streamable.com/ltwcx)
[This PR](https://streamable.com/tlew7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4995)

settings, configure_input: fix rename input profile

---

src/dedicated_room/citra-room.cpp
src/network/room.cpp

This allows you to see what happens in your rooms without joining them if you use citra-room.
Requested by `Drgn#6630` in the MHXX Discord server.
Sample logs:
```
[  10.294862] Network <Info> network\room.cpp:Network::Room::RoomImpl::SendStatusMessage:787: Test (vvanelslande) has joined.
[  12.900549] Network <Info> network\room.cpp:Network::Room::RoomImpl::HandleChatPacket:955: Test (vvanelslande): Test …
```

network/room (server): add message/join/leave/kick/ban/unban/game name logging

---

src/audio_core/cubeb_input.cpp
src/audio_core/cubeb_input.h
src/citra/config.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_audio.cpp
src/core/frontend/mic.h
src/core/hle/service/mic_u.cpp

Before this PR it always used the default device.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/4982)

service/mic: actually use the specified device

---

src/citra/citra.cpp
src/citra/config.cpp
src/citra/default_ini.h
src/citra/emu_window/emu_window_sdl2.cpp
src/citra/emu_window/emu_window_sdl2.h
src/citra_qt/bootmanager.cpp
src/citra_qt/bootmanager.h
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_graphics.cpp
src/citra_qt/configuration/configure_graphics.ui
src/citra_qt/configuration/configure_hotkeys.cpp
src/citra_qt/configuration/configure_web.cpp
src/citra_qt/main.cpp
src/citra_qt/main.h
src/core/CMakeLists.txt
src/core/frontend/emu_window.cpp
src/core/frontend/emu_window.h
src/core/frontend/scope_acquire_context.cpp
src/core/frontend/scope_acquire_context.h
src/core/settings.cpp
src/core/settings.h
src/core/telemetry_session.cpp
src/video_core/renderer_base.h
src/video_core/renderer_opengl/gl_resource_manager.cpp
src/video_core/renderer_opengl/gl_resource_manager.h
src/video_core/renderer_opengl/gl_state.cpp
src/video_core/renderer_opengl/gl_state.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_opengl/renderer_opengl.h

Fixes https://github.com/citra-emu/citra/issues/4811 (and maybe https://github.com/citra-emu/citra/issues/4319 https://github.com/citra-emu/citra/issues/3879) superscedes PR https://github.com/citra-emu/citra/pull/4737 as well
Based off the design in https://redream.io/posts/improving-audio-video-synchronization-multi-sync and comments in #4780 this brings shared context support to citra by decoupling guest and host vsync. This does **NOT** include changes to how the framelimiter works, its just changing the vsync situation. Future work can be done to improve audio sync to eliminate popping as well.
Previously, citra's framelimiter relied on host vsync being *disabled* in order to work properly, but this is finicky at best. For people who have force enabled vsync in their drivers, citra …

Split Presentation thread from Render thread

---

src/citra_qt/bootmanager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5029)

Remove accidentally pushed debugging logs

---

src/video_core/renderer_opengl/renderer_opengl.cpp

Previously we would first attempt to use any buffer that was free,
meaning whichever buffer has already been displayed. This has poor
interactions when the operating system throttles the update rate of the
window, so if there isn't any free buffers available, just reuse the
oldest frame instead.
Fixes https://github.com/citra-emu/citra/issues/5026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5030)

Remove wait for free buffer

---

src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h
src/core/telemetry_session.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5021)

 common/cpu_detect: Remove unused functionality

---

src/citra_qt/configuration/config.cpp
src/citra_qt/main.cpp
src/citra_qt/util/spinbox.cpp

Ports https://github.com/yuzu-emu/yuzu/pull/2513.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5010)

yuzu/main: Specify string conversions explicitly

---

src/common/threadsafe_queue.h

See yuzu-emu/yuzu#3173 for more details.
Fixes a race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5062)

Port yuzu-emu/yuzu#3173: "common: SPSCQueue: Notify after incrementing queue size."

---

src/input_common/udp/client.cpp
src/input_common/udp/client.h
src/input_common/udp/protocol.h
src/input_common/udp/udp.cpp
src/input_common/udp/udp.h

See yuzu-emu/yuzu#3374 for more details.
Individual minor changes to the UDP backend that don't really warrant their own PRs by themselves.
Each commit should be fairly self-contained, so they can be reviewed individually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5087)

Port yuzu-emu/yuzu#3374: "input_common/udp: Minor changes"

---

README.md

See yuzu-emu/yuzu#3550 for more details.
I've added a Discord shield to the top of the repo as I know this is something a lot of people look for when browsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5156)

Port yuzu-emu/yuzu#3550: "Minor Readme Changes"

---

CMakeModules/CopyCitraQt5Deps.cmake

Port of https://github.com/yuzu-emu/yuzu/pull/3548/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5148)

Use the correct directory for Qt Plugins

---

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5152)

Don't dump textures that aren't a power of 2

---

.travis.yml
src/citra_qt/debugger/registers.cpp
src/common/ring_buffer.h
src/core/arm/dynarmic/arm_dynarmic.cpp
src/core/arm/dynarmic/arm_dynarmic.h
src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
src/core/arm/dynarmic/arm_dynarmic_cp15.h
src/core/core.cpp

Let's do this.
A lot has changed since the last update, however it was mostly affecting A64 emulation.
There are minor updates to codegen on the A32 side of things (mainly to enable support of ARMv7 to be written) but there should not be a significant increase or decrease in performance.
Follow-up PRs to enable that page_table optimization (i.e. #5145) to follow after this one is merged.
Biggest change from a Citra point of view is stepping is now implemented, so the interpreter is no longer required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5184)

Update dynarmic (Apr 2020)

---

src/network/room.cpp

Logging user IPs (in addition to existing username logging) can help dedicated server hosts manage their servers better.
https://community.citra-emu.org/t/need-ip-log-feature-for-dedicated-server-host/203171
Note that the "unbanned" message already includes the IP, so it was omitted from the change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5162)

Added user IP to log events for join/left/kicked/banned

---

src/video_core/renderer_opengl/gl_shader_decompiler.h
src/video_core/swrasterizer/proctex.h

Ensures errors related to multiple inclusions never happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5245)

video_core: Add missing header guards

---

src/video_core/renderer_opengl/gl_shader_manager.cpp

Prevents unnecessary copies from occurring. In the case of ShaderCache, we can just remove the parameter, given it's unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5244)

gl_shader_manager: std::move std::string where applicable

---

.travis.yml
.travis/linux-frozen/build.sh
.travis/linux-frozen/deps.sh
.travis/linux-frozen/docker.sh

I'm trying to fix travis-ci frozen mingw build
It is just a workaround but for now it at least succedes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5276)

fix travis-ci frozen mingw build

---

src/core/frontend/applets/mii_selector.h
src/core/frontend/applets/swkbd.h

Prevents undefined behavior when destroying derived classes through a base class pointer (which is what occurs within the System class).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5309)

applets: Make destructors virtual where applicable

---

src/core/file_sys/seed_db.h

Prevents any potential inclusion errors from occurring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5307)

file_sys/seed_db: Add missing include guard

---

src/video_core/renderer_opengl/gl_shader_manager.cpp

Prevents the internal buffer in the std::optional from being zeroed out unnecessarily and instead sets the validity byte only in some implementations (see #5293 for a more in depth explanation). While we're at it, we can make use of std::move to eliminate unnecessary heap reallocations from occurring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5335)

gl_shader_manager: Make use of std::nullopt where applicable

---

src/citra_qt/configuration/configure_input.cpp
src/citra_qt/configuration/configure_input.h
src/citra_qt/configuration/configure_input.ui

See yuzu-emu/yuzu#3268 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5174)

Port yuzu-emu/yuzu#3268: "GUI: Deadzone controls for sdl engine at configuration input"

---

src/core/hle/service/ldr_ro/cro_helper.cpp

We can simply initialize the variable in this case with a consistent
value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5394)

cro_helper: Silence -Wuninitialized warning

---

CMakeLists.txt

closes #5234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5424)

Fix using system boost

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fi_FI.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5438)

Update translations (2020-07-01)

---

src/citra_qt/debugger/wait_tree.cpp

See yuzu-emu/yuzu#4376 for more details.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5462)

Port yuzu-emu/yuzu#4376: "frontend: Improve wait tree readability for dark themes"

---

src/citra_qt/camera/camera_util.cpp
src/citra_qt/camera/qt_camera_base.cpp
src/citra_qt/camera/still_image_camera.cpp
src/citra_qt/configuration/configure_camera.cpp
src/citra_qt/configuration/configure_camera.h
src/citra_qt/configuration/configure_motion_touch.cpp
src/citra_qt/debugger/profiler.cpp
src/citra_qt/debugger/profiler.h
src/citra_qt/main.cpp
src/citra_qt/main.h
src/core/CMakeLists.txt
src/core/announce_multiplayer_session.cpp
src/core/frontend/camera/blank_camera.cpp
src/core/frontend/camera/interface.h
src/core/hle/service/cam/cam.h
src/core/hle/service/cam/cam_params.h
src/core/settings.cpp
src/core/settings.h
src/video_core/pica_state.h

Also moves the camera enums to a separate file, as most definitions are not necessary on settings.h
Accepting suggestions for the name of the new file and such
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5512)

Forward declare some classes and remove some unnecessary includes

---

src/common/thread.cpp

See yuzu-emu/yuzu#4461 for more details.
- In `SetCurrentThreadName`, when on Linux, truncate to 15 bytes, as (at least on glibc) `pthread_set_name_np` will otherwise return `ERANGE` and do nothing.
- Also, add logging in case `pthread_set_name_np` returns an error anyway.  This is Linux-specific, as the Apple and BSD versions of `pthread_set_name_np` return `void`.
- To make things slightly more succinct, change `SetCurrentThreadName` to take `const std::string&` rather than `const char *`.
- Change the name for CPU threads in multi-core mode from "yuzu:CoreCPUThread_N" (19 bytes) to "yuzu:CPUCore_N" (14 bytes) so it fits into the Linux limit.  Some other thread names are also cut off, but I didn't bother addressing them as you can guess them from the truncated …

Port yuzu-emu/yuzu#4461: "Fix thread naming on Linux, which limits names to 15 bytes."

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fi_FI.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5541)

Update translations (2020-09-01)

---

src/core/hle/kernel/process.cpp
src/core/hle/kernel/process.h
src/core/loader/3dsx.cpp
src/core/loader/elf.cpp
src/core/loader/loader.cpp
src/core/loader/loader.h

Attempt to fix #5443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5446)

Bump kernel version for 3DSX

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fi_FI.ts
dist/languages/fr.ts
dist/languages/hu_HU.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5596)

Update translations (2020-11-01)

---

.github/workflows/ci.yml

This PR fixes the error during the release stage when the CI is trying to get the name of the tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5613)

CI: fix the tag fetching command

---

bitrise.yml
src/android/build.gradle
src/android/gradle/wrapper/gradle-wrapper.properties

The build was complaining about not finding an NDK directory. Updating Gradle and the Bitrise build steps resolved the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5661)

Fix Bitrise build

---

externals/json/README.md
externals/json/json.hpp

See yuzu-emu/yuzu#4440 for more details.
Updates our tracked libraries to use their latest releases, keeping them up to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5536)

Port yuzu-emu/yuzu#4440: "CMakeLists: Update several libraries"

---

src/citra_qt/compatdb.cpp
src/citra_qt/main.cpp
src/citra_qt/multiplayer/message.cpp
src/common/swap.h
src/core/core_timing.h

See yuzu-emu/yuzu#5277 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5670)

Port yuzu-emu/yuzu#5277: "general: Fix various spelling errors"

---

src/common/x64/xbyak_abi.h
src/video_core/shader/shader_jit_x64_compiler.cpp
src/video_core/shader/shader_jit_x64_compiler.h

See yuzu-emu/yuzu#4086 and yuzu-emu/yuzu#4611 for more details.
The commits should be fairly self-explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5546)

Port yuzu-emu/yuzu#4086 and yuzu-emu/yuzu#4611: Xbyak cleanups

---

src/citra/citra.cpp
src/citra_qt/compatdb.cpp
src/citra_qt/main.cpp
src/common/telemetry.cpp
src/common/telemetry.h
src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h
src/core/core.cpp
src/core/hle/service/apt/apt.cpp
src/core/loader/ncch.cpp
src/core/telemetry_session.cpp
src/core/telemetry_session.h
src/video_core/renderer_opengl/gl_shader_gen.cpp
src/video_core/renderer_opengl/pica_to_gl.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/web_service/telemetry_json.cpp
src/web_service/telemetry_json.h

See yuzu-emu/yuzu#1064 and yuzu-emu/yuzu#3948 for more details.
The two commits are also fairly self-explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5501)

Port yuzu-emu/yuzu#1064 and yuzu-emu/yuzu#3948: Changes to Telemetry and CPU feature detection

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fi_FI.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5730)

Update translations (2021-03-01)

---

src/core/hle/service/nwm/nwm_uds.cpp
src/core/hle/service/nwm/uds_data.cpp

This is an attempt to fix @tywald's problem with MH, reported on Discord a while ago. Apparently it is fixed by the first two commits. The third commit addresses the issue of Citra sometimes crashing when host close the network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5382)

service/nwm_uds: Various improvements/corrections

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fi_FI.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5807)

Update translations (2021-07-01)

---

src/video_core/renderer_opengl/post_processing_opengl.cpp

Those are available in upstream Dolphin, so it will help with keeping things compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5818)

Add Get(Inv)WindowResolution shader functions

---

src/common/linear_disk_cache.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5902)

added std::vector<V> instead of V*

---

src/common/file_util.cpp
src/core/core.cpp
src/core/frontend/emu_window.cpp
src/core/frontend/emu_window.h
src/core/frontend/framebuffer_layout.cpp
src/core/frontend/framebuffer_layout.h
src/core/frontend/input.h
src/core/settings.cpp
src/core/settings.h
src/video_core/renderer_base.cpp
src/video_core/renderer_base.h
src/video_core/renderer_opengl/renderer_opengl.cpp

some more stuff from the android repo, shouldn't have any affect on the desktop side. Hopefully, after this async and disk shader should be one of the last things to merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5906)

Backport some more stuff from android

---

src/video_core/renderer_opengl/gl_format_reinterpreter.cpp

closes #5890 and #5861
The issues have a little more info but the gist of it is - glCopyImageSubData seems to be incorrect behaviour and glTextureView apparently only works on nvidia.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5905)

Remove CopyImageSubData; and enable TextureView reinterpreter only on nvidia

---

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp

**gles before:**
memory -> bgr -> rgb -> texture
memory <- copy <- texture
**gles now:**
memory -> bgr -> rgb -> texture
memory <- bgr <- rgb <- texture
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5924)

fx bgr write back on gles

---

src/citra_qt/camera/qt_multimedia_camera.cpp

qt_multimedia_camera.cpp:
Prefer std::fill over ranged-for loop.
---
Great project btw! :tada:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5995)

citra_qt: Minor refactor to prefer standard algorithms

---

src/core/hle/kernel/svc.cpp

Adds svcGetSystemInfo type 0x20000 to get citra related information from homebrew applications (name, version, build date, build branch and build commit). This way, it is possible for apps to know if they are running on Citra, as well as to get some build information.
The type 0x20000 is not used by any retail application, so it should not cause any compatibility issues. This type has been chosen after seeing [Luma3DS kernel extension uses type 0x1000](https://github.com/LumaTeam/Luma3DS/blob/b83a0abb9d5544549818ed224c155f83c5217546/k11_extension/source/svc/GetSystemInfo.c#L38), however this could be discussed to choose a different value.
Below is an example of how this PR can be used to retrieve information:
```
void printCitraInfo() {
s64 output = 0;
svcGetSystemInfo(&output, 0x20000, …
```

Add svcGetSystemInfo 0x20000 to get citra information

---

src/CMakeLists.txt
src/citra_qt/cheats.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_camera.cpp
src/citra_qt/debugger/ipc/recorder.cpp
src/citra_qt/multiplayer/chat_room.cpp
src/common/alignment.h
src/common/texture.cpp
src/common/texture.h
src/common/timer.cpp
src/common/timer.h
src/common/x64/xbyak_abi.h
src/core/dumping/backend.cpp
src/core/dumping/ffmpeg_backend.cpp
src/core/file_sys/seed_db.cpp
src/core/hle/kernel/ipc.cpp
src/core/hle/kernel/thread.cpp
src/core/hle/service/dsp/dsp_dsp.cpp
src/core/hle/service/nfc/nfc.cpp
src/input_common/sdl/sdl_impl.cpp
src/tests/core/hle/kernel/hle_ipc.cpp
src/tests/core/memory/vm_manager.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/texture_downloader_es.cpp

Treats this warning as a compilation error on MSVC.
This is part of a series of PRs to enforce several compiler warnings on MSVC that we have enforced on [yuzu](https://github.com/yuzu-emu/yuzu/blob/master/src/CMakeLists.txt#L59-L75) where applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6023)

general: Enforce C4267 warning on MSVC

---

dist/languages/da_DK.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es_ES.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/lt_LT.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl_PL.ts
dist/languages/pt_BR.ts
dist/languages/ro_RO.ts
dist/languages/ru_RU.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

This PR is generated by [zhaowenlan1779/txbot](https://github.com/zhaowenlan1779/txbot).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6086)

Update translations (2022-08-01)

---

src/android/app/src/main/jni/CMakeLists.txt
src/android/app/src/main/jni/android_common/android_common.cpp
src/android/app/src/main/jni/android_common/android_common.h
src/android/app/src/main/jni/applets/mii_selector.cpp
src/android/app/src/main/jni/applets/swkbd.cpp
src/android/app/src/main/jni/native.cpp
src/common/string_util.cpp
src/common/string_util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6089)

android: Improve string conversion

---

src/video_core/rasterizer_cache/rasterizer_cache.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6119)

Fix graphical bugs in Yokai 2/3 games

---

src/citra_qt/compatdb.ui
src/citra_qt/game_list.cpp
src/citra_qt/game_list.h
src/citra_qt/game_list_p.h

Please see https://github.com/yuzu-emu/yuzu/pull/8204 and https://github.com/yuzu-emu/yuzu/pull/8797 or the commit descriptions for more info.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6123)

ui: Fixes to compatibility list translations (yuzu port)

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6134)

cmake: Add SDL2 alias when using system library

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6160)

renderer_opengl: Fix flashlight problems in Luigi's Mansion

---

src/citra_qt/bootmanager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6183)

citra_qt: Avoid null reference capture when taking screenshots

---

src/citra_qt/debugger/graphics/graphics_surface.cpp
src/common/color.h
src/core/hw/gpu.cpp
src/core/hw/y2r.cpp
src/video_core/swrasterizer/framebuffer.cpp
src/video_core/texture/etc1.cpp
src/video_core/texture/texture_decode.cpp

See yuzu-emu/yuzu#4535 and yuzu-emu/yuzu#4548 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/5526)

Port yuzu-emu/yuzu#4535 and yuzu-emu/yuzu#4548: Changes to the Common namespace

---

dist/languages/.tx/config

txbot has been failing previously because of this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6275)

dist/languages: Migrate to new tx client

---

src/citra_qt/configuration/configure_general.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6296)

citra_qt: Hide updates on per-game config

---

src/core/hle/service/am/am.cpp

The home menu uses GetNumTickets and GetTicketList to determine installed titles to display. Thus even though we don't actually have tickets installed, we at least need these command stubs to be able to retrieve a list of installed titles so that the home menu can detect and display installed games.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6292)

am: Return installed titles in GetNumTickets and GetTicketList stubs.

---

src/core/hle/service/nim/nim_u.cpp
src/core/hle/service/nim/nim_u.h

Provides full stubs for nim:u based on my own RE work. Most of it has been figured out, although there's a few data gaps and one function I didn't quite figure out yet what it does. Will be updating 3dbrew with the information I've found as well.
This fixes a lot of instability around app icons on the home menu, such as random downloading present icons with garbled titles. It also allows the home menu to launch apps without enabling LLE NIM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6290)

nim: Fully stub nim:u service.

---

src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_opengl/renderer_opengl.h

Attempt to resolve #6278, which is an issue unique to Intel GPUs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6306)

Resolve Black Screen on Intel GPU Regression

---

.ci/transifex/docker.sh

Switches to the new transifex client written in go. Depends on https://github.com/citra-emu/build-environments/pull/38
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6401)

transifex: Remove python client

---

src/citra/emu_window/emu_window_sdl2.cpp
src/citra/emu_window/emu_window_sdl2_gl.cpp
src/citra_qt/bootmanager.cpp
src/core/frontend/emu_window.h
src/video_core/renderer_opengl/gl_shader_manager.cpp
src/video_core/renderer_opengl/gl_shader_manager.h

See https://github.com/yuzu-emu/yuzu/pull/7410 for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6412)

Port yuzu-emu/yuzu#7410: "Wayland fixes"

---

src/android/build.gradle

fixes: https://github.com/citra-emu/citra/issues/6232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6417)

replace jcenter with mavenCentral 

---

src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableButton.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableDpad.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableJoystick.java

InputOverlay is doing too much work for every element in the overlay. This PR addresses that by removing code from the main class and moving it into each individual class.
This also detects when a finger presses a button so it avoid triggering any touch event that might be under the button.
Fixes #6390
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6391)

android: Clean up overlay controls and avoid triggering touch screen when a button is pressed

---

src/android/app/src/main/jni/default_ini.h
src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_graphics.cpp
src/citra_qt/configuration/configure_graphics.h
src/citra_qt/configuration/configure_graphics.ui
src/common/settings.cpp
src/common/settings.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/video_core.cpp
src/video_core/video_core.h

* MacOS opengl has been dropped, no need to keep this around
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6403)

Remove remnants of separable shader setting

---

externals/CMakeLists.txt
src/CMakeLists.txt
src/android/app/src/main/jni/native.cpp
src/common/dynamic_library/ffmpeg.cpp
src/common/dynamic_library/ffmpeg.h
src/common/file_util.cpp
src/common/misc.cpp
src/common/string_util.cpp
src/core/arm/skyeye_common/armstate.cpp
src/core/cheats/cheats.cpp
src/core/dumping/ffmpeg_backend.cpp
src/core/dumping/ffmpeg_backend.h
src/core/file_sys/archive_backend.h
src/core/hle/kernel/kernel.h
src/core/hle/kernel/thread.cpp
src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/nwm/uds_data.cpp
src/core/hle/service/soc_u.cpp
src/core/movie.cpp
src/input_common/sdl/sdl_impl.cpp
src/network/packet.cpp
src/video_core/geometry_pipeline.cpp
src/video_core/pica.cpp
src/video_core/shader/shader.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6602)

Chore: enable `-Werror` on GCC and clang

---

src/citra_qt/configuration/configuration_shared.h
src/citra_qt/main.cpp

Update graphics button indicator while launching or stopping a game
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6625)

update graphics api button indicator

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.java
src/android/app/src/main/res/values/strings.xml

Got requested to adjust the strings throughout the app and make them more consistent. Hopefully this makes things a little better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6613)

citra_android: String adjustments

---

src/core/hle/kernel/ipc_debugger/recorder.cpp

assoicated -> associated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/6686)

kernel: fix typo in recorder.cpp

---

src/audio_core/hle/source.cpp

Fix all compiling issues related with fmt (see #7015)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7024)

audio_core/hle: Fix compile issues

---

src/core/hle/kernel/hle_ipc.h
src/core/hle/service/fs/fs_user.cpp
src/core/hle/service/fs/fs_user.h
src/core/loader/3dsx.cpp
src/core/loader/ncch.cpp

Adds product info and save data secure value related functions.
This PR, #7050 and https://github.com/citra-emu/citra/pull/7035 allow citra to go online using LLE friends module.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7051)

Add missing FS:USER functions

---

src/core/hle/service/ps/ps_ps.cpp
src/core/hle/service/ssl/ssl_c.cpp
src/core/hle/service/ssl/ssl_c.h

Use a proper crypto secure random bytes source for SSL module, also implement the equivalent call in PS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7164)

Implement PS:GetRandomBytes and use openssl for random bytes

---

src/video_core/shader/generator/glsl_shader_gen.cpp

Aimed to fix https://github.com/citra-emu/citra/issues/7352
Part of the sky dome is rendered with depth values a little lower the -1 lower NDC range of the 3DS (The exact depth value generated is -1.00000214061). So it ends up being clipped and the clipped area showed as black.
The solution is to apply an epsilon check for this as well. A larger epsilon was chosen for this case as the depth value generated is a bit further away. I've done some hardware testing and it appears one must multiply r=-1.f by 0.1f about 5 times before a triangle with depth set to -1.f + r becomes visible again, so it seems this change matches hardware behavior.
Also refactored the clipping into a separate function so it's a little cleaner and less duplicated all over the place
- - - …

glsl_shader_gen: Use epsilon for both ends of NDC range

---

src/core/hle/service/http/http_c.cpp
src/core/hle/service/http/http_c.h

This PR implements various HTTP commands that some applications use to connect to their servers. Specifically:
- `GetRequestState`
- `AddPostDataBianry`
- `SetPostDataType`
- All `SendPostData` commands
- `SetPostDataEncoding`
- `GetResponseHeaderTimeout`
- `SetPostDataTypeSize`
This allows games that don't require Nintendo servers to connect online, like Flipnote Studio 3D with the Kaeru World servers patch. It also prepares ground work for those that do, as some games will perform HTTP requests to get and post user generated content.
To be honest I haven't looked much into reverse engineered code of the sysmodule, but I've made lots of tests with various edge cases on the original sysmodule and tried to replicate those as accurately as possible.
Screenshot:
- - - …

http: Implement various missing commands
